<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'lrskills' => 'Especialidades',
	'lrrules' => 'Reglas de visitante',
	'lrgroups' => 'Grupos de visitantes',
	'lrbans' => 'Bloqueos de visitantes',
	'lrmessagerouting' => 'Enrutado de Mensajes',
	'corestaff' => 'Operadores',
	'coreteams' => 'Equipos',
	'admin_tmpcanpersonalize' => 'Puede Acceder a Plantillas > Personalizar',
	'coreloginshare' => 'LoginShare Operadores',
	'coredepartments' => 'Departamentos',
	'coretemplategroups' => 'Grupos de plantillas',
	'coretemplates' => 'Plantillas',
	'coreusergroups' => 'Grupos de usuarios',
	'staff_profile' => 'Puede actualizar el perfil',
	'staff_changepassword' => 'Puede cambiar la contraseña',
	'coretemplateloginshare' => 'LoginShare Usuarios',
	'corecustomfieldgroups' => 'Grupos de campos personalizados',
	'corecustomfields' => 'Campos personalizados',
	'staff_newssubscribers' => 'Suscriptores de noticias',
	'staff_newscategories' => 'Categorías de noticias',
	'staff_newscanpublicinsert' => 'Puede insertar Noticias Públicas',
	'staff_newsitems' => 'Noticias',
	'staff_troubleshootercategories' => 'Categorías',
	'corewidgets' => 'Widgets',
	'corelanguages' => 'Idiomas',
	'staff_comments' => 'Comentarios',
	'corelanguagephrases' => 'Frases de idiomas',
	'livechatcalls' => 'Llamadas',
	'parserqueues' => 'Colas de mail',
	'admin_tcanrunmoveattachments' => 'Puede mover adjuntos',
	'staff_troubleshootersteps' => 'Pasos',
	'parserlogs' => 'Logs de Procesador',
	'parserrules' => 'Reglas de Procesador',
	'parserbreaklines' => 'Líneas de corte',
	'parserbans' => 'Bloqueos',
	'parsercatchall' => 'Reglas Recoge-Todo',
	'admin_canrunimport' => 'Puede ejecutar importaciones',
	'parserblockages' => 'Bloqueo de bucles',
	'parserlooprule' => 'Reglas Bucles',
	'issuestatus' => 'Estados',
	'issuepriorities' => 'Prioridades',
	'issueresolutions' => 'soluciones',
	'issuelinks' => 'Enlaces',
	'issuetypes' => 'Tipos',
	'ticketworkflows' => 'flujos de trabajo de trabajo',
	'ticketstatuses' => 'Estados',
	'ticketpriorities' => 'Prioridades',
	'ticketfiletypes' => 'Tipos de archivo',
	'staff_notifications' => 'Notificaciones',
	'tickettypes' => 'Tipos de ticket',
	'ticketlinks' => 'Enlaces',
	'ticketbayes' => 'Categorías Bayesianas',
	'ticketslaplans' => 'Planes SLA',
    'ticketautocloserules' => 'Reglas de autocierre',
	'ticketslaschedules' => 'Calendarios SLA',
	'staff_ticketbilling' => 'Facturación de tickets',
	'staff_tcanforward' => 'Puede reenviar tickets',
	'staff_tcanreply' => 'Puede responder a tickets',
	'staff_tcanfollowup' => 'Puede crear seguimientos',
	'staff_tcanrelease' => 'Puede liberar tickets',
	'staff_ticketfollowup' => 'Seguimientos',
	'staff_tcanviewauditlog' => 'Puede ver logs de auditoría',
	'staff_ticketnotes' => 'Notas de Ticket',
	'staff_tcanworkflow' => 'Puede ver/actualizar flujos de trabajo',
	'staff_tcansaveasdraft' => 'Puede guardar borradores',
	'staff_tcanbenchmarks' => 'Puede ver valoraciones',
	'ticketslaholidays' => 'Festivos SLA',
	'ticketescalations' => 'Priorizaciones',
	'corebenchmarks' => 'Valoraciones',
	'corescheduledtasks' => 'Tareas Programadas',
	'staff_usernotes' => 'Notas de usuario',
	'livechatnotes' => 'Notas de chat',
	'livechatmessages' => 'Mensajes/Encuestas',
	'livechatcanned' => 'Enlatado',
	'livechathistory' => 'Historial chat',
	'winapplrbans' => 'Winapp: Bloqueos visitantes',
	'staff_kbcategories' => 'Categorías',
	'staff_kbarticles' => 'Artículos',
	'staff_kbcaninsertpublishedarticles' => 'Puede publicar artículos',
	'staff_trcaninsertpublishedsteps' => 'Puede publicar pasos',
	'staff_tags' => 'Etiquetas',
	'staff_tcansearch' => 'Puede buscar tickets',
	'staff_ticketmacros' => 'Macros',
	'staff_ticketfilters' => 'Filtros',
	'staff_ticketviews' => 'Vistas',
	'staff_tickets' => 'Tickets',
	'staff_ticketposts' => 'Mensajes de ticket',
	'staff_tcanmarkasspam' => '¿Puede marcar el ticket como spam?',
	'staff_tcantrashticket' => '¿Puede borrar tickets?',
	'ls_canobserve' => 'Winapp: Puede observar chats',
	'admin_canmanagetaggenerator' => 'Puede administrar el generador de etiquetas',
	'admin_canmanagerestapi' => 'Puede administrar la API REST',
	'admin_canviewloginlog' => 'Puede ver el log de inicio de sesión',
	'admin_canviewactivitylog' => 'Puede ver el log de actividad',
	'admin_canviewerrorlog' => 'Puede ver el log de errores',
	'admin_canviewdatabase' => 'Puede ver los detalles de la base de datos',
	'admin_canrundiagnostics' => 'Puede ejecutar diagnósticos',
	'admin_canviewdepartments' => 'Puede ver departamentos',
	'admin_lrcandeletevisitorgroup' => 'Puede eliminar grupos de visitantes',
	'admin_lrcaninsertvisitorgroup' => 'Puede insertar grupos de visitantes',
	'admin_lrcanupdatevisitorgroup' => 'Puede actualizar grupos de visitantes',
	'admin_lrcanviewvisitorgroups' => 'Puede ver grupos de visitantes',
	'admin_caninsertstaff' => 'Puede insertar operadores',
	'admin_caneditstaff' => 'Puede actualizar operadores',
	'admin_candeletestaff' => 'Puede eliminar operadores',
	'admin_caninsertteams' => 'Puede insertar Equipos',
	'admin_caneditteams' => 'Puede actualizar Equipos',
	'admin_candeleteteams' => 'Puede eliminar Equipos',
	'admin_caninsertdepartment' => 'Puede insertar departamentos',
	'admin_caneditdepartment' => 'Puede editar departamentos',
	'admin_candeletedepartment' => 'Puede eliminar departamentos',
	'admin_canupdatesettings' => 'Puede actualizar la configuración',
	'admin_canrebuildgeoip' => 'Puede reconstruir la base de datos GeoIP',
	'admin_caninsertcfgroup' => 'Puede insertar grupos de campos personalizados',
	'admin_canupdatecfgroup' => 'Puede actualizar grupos de campos personalizados',
	'admin_candeletecfgroup' => 'Puede eliminar grupos de campos personalizados',
	'admin_caninsertcustomfield' => 'Puede insertar campos personalizados',
	'admin_canupdatecustomfield' => 'Puede actualizar campos personalizados',
	'admin_candeletecustomfield' => 'Puede eliminar campos personalizados',
	'admin_canviewlanguages' => 'Puede ver idiomas',
	'admin_caninsertlanguage' => 'Puede insertar idiomas',
	'admin_canupdatelanguage' => 'Puede actualizar idiomas',
	'admin_candeletelanguage' => 'Puede eliminar idiomas',
	'admin_canrestorelanguage' => 'Puede restaurar idiomas',
	'admin_canviewphrases' => 'Puede ver frases',
	'admin_caninsertphrase' => 'Puede insertar frases',
	'admin_canupdatephrase' => 'Puede actualizar frases',
	'admin_candeletephrase' => 'Puede eliminar frases',
	'admin_canimportphrases' => 'Puede importar paquetes de idioma',
	'admin_canexportphrases' => 'Puede exportar paquetes de idioma',
	'admin_canrestorephrases' => 'Puede restaurar frases',
	'admin_canrunlanguagediagnostics' => 'Puede ejecutar diagnósticos de idioma',
	'mod_ringroute' => 'RingRoute',
	'admin_canupdaterrprofiles' => 'Puede actualizar perfiles de RingRoute',
	'admin_lrcanviewonlinestaff' => 'Puede ver operadores conectados',
	'admin_lrcandisconnectstaff' => 'Puede desconectar operadores conectados',
	'admin_lrcanupdaterouting' => 'Puede actualizar reglas de enrutado de mensajes',
	'admin_lrcanviewrouting' => 'Puede ver reglas de enrutado de mensajes',
	'admin_lrcanviewbans' => 'Puede ver bloqueos por IP',
	'admin_lrcaninsertban' => 'Puede insertar bloqueos por IP',
	'admin_lrcanupdateban' => 'Puede actualizar bloqueos por IP',
	'admin_lrcandeleteban' => 'Puede eliminar bloqueos por IP',
	'admin_lrcanviewrules' => 'Puede ver reglas de visitantes',
	'admin_lrcaninsertrule' => 'Puede insertar reglas de visitantes',
	'admin_lrcanupdaterule' => 'Puede actualizar reglas de visitantes',
	'admin_lrcandeleterule' => 'Puede eliminar reglas de visitantes',
	'admin_lrcanviewskills' => 'Puede ver especialidades',
	'admin_lrcaninsertskill' => 'Puede insertar especialidades',
	'admin_lrcanupdateskill' => 'Puede actualizar especialidades',
	'admin_lrcandeleteskill' => 'Puede eliminar especialidades',
	'admin_mpcaninsertqueue' => 'Puede insertar colas de mail',
	'admin_mpcanupdatequeue' => 'Puede actualizar colas de mail',
	'admin_mpcandeletequeue' => 'Pude eliminar colas de mail',
	'admin_mpcanviewqueues' => 'Puede ver colas de mail',
	'admin_mpcanviewparserlogs' => 'Puede ver el log del Procesador',
	'admin_mpcandeleteparserlogs' => 'Puede eliminar los logs del Procesador',
	'mod_parser' => 'Procesador de correo',
	'admin_mpcaninsertrule' => 'Puede insertar reglas',
	'admin_mpcanupdaterule' => 'Puede actualizar reglas',
	'admin_mpcandeleterule' => 'Puede eliminar reglas',
	'admin_mpcanviewrules' => 'Puede ver reglas',
	'admin_mpcaninsertbreakline' => 'Puede insertar líneas de corte',
	'admin_mpcanupdatebreakline' => 'Puede actualizar líneas de corte',
	'admin_mpcandeletebreaklines' => 'Puede eliminar líneas de corte',
	'admin_mpcanviewbreaklines' => 'Puede ver líneas de corte',
	'admin_mpcaninsertban' => 'Puede insertar bloqueo por email',
	'admin_mpcanupdateban' => 'Puede actualizar bloqueo por email',
	'admin_mpcandeletebans' => 'Puede eliminar bloqueo por email',
	'admin_mpcanviewbans' => 'Puede ver bloqueos por email',
	'admin_mpcaninsertcatchall' => 'Puede insertar Reglas Recoge-Todo',
	'admin_mpcanupdatecatchall' => 'Puede actualizar Reglas Recoge-Todo',
	'admin_candeletecatchall' => 'Puede eliminar Reglas Recoge-Todo',
	'admin_canviewcatchall' => 'Puede ver Reglas Recoge-Todo',
	'admin_iscanviewstatus' => 'Puede ver Estados',
	'admin_iscaninsertstatus' => 'Puede insertar Estados',
	'admin_iscanupdatestatus' => 'Puede actualizar Estados',
	'admin_iscandeletestatus' => 'Puede eliminar Estados',
	'admin_iscanviewpriorities' => 'Puede ver Prioridades',
	'admin_iscaninsertpriority' => 'Puede insertar Prioridades',
	'admin_iscanupdatepriority' => 'Puede actualizar Prioridades',
	'admin_iscandeletepriorities' => 'Puede eliminar Prioridades',
	'admin_iscanviewresolutions' => 'Puede ver soluciones',
	'admin_iscaninsertresolution' => 'Puede insertar soluciones',
	'admin_iscanupdateresolution' => 'Puede actualizar soluciones',
	'admin_iscandeleteresolutions' => 'Puede eliminar soluciones',
	'admin_iscanviewlinks' => 'Puede ver Enlaces',
	'admin_iscaninsertlink' => 'Puede insertar Enlaces',
	'admin_iscanupdatelink' => 'Puede actualizar Enlaces',
	'admin_iscandeletelinks' => 'Puede eliminar Enlaces',
	'admin_iscanviewtypes' => 'Puede ver Tipos',
	'admin_iscaninsertype' => 'Puede insertar Tipos',
	'admin_iscanupdatetype' => 'Puede actualizar Tipos',
	'admin_iscandeletetypes' => 'Puede eliminar Tipos',
	'mod_issues' => 'Problemas',
	'mod_tickets' => 'Tickets',
	'admin_tcanviewbayescategories' => 'Puede ver Categorías Bayesianas',
	'admin_tcandeletebayescategories' => 'Puede eliminar Categorías Bayesianas',
	'admin_tcaninsertbayescategory' => 'Puede insertar Categorías Bayesianas',
	'admin_tcanupdatebayescategory' => 'Puede actualizar Categorías Bayesianas',
	'admin_tcanrunbayesdiagnostics' => 'Puede ejecutar Diagnósticos Bayesianos',
	'admin_tcanviewslaplans' => 'Puede ver Planes SLA',
	'admin_tcaninsertslaplan' => 'Puede insertar Planes SLA',
	'admin_tcanupdateslaplan' => 'Puede actualizar Planes SLA',
	'admin_tcandeleteslaplans' => 'Puede eliminar Planes SLA',
	'admin_tcanviewslaschedules' => 'Puede ver Planificaciones SLA',
	'admin_tcaninsertslaschedules' => 'Puede insertar Planificaciones SLA',
	'admin_tcanupdateslaschedules' => 'Puede actualizar Planificaciones SLA',
	'admin_tcandeleteslaschedules' => 'Puede eliminar Planificaciones SLA',
	'admin_tcanviewslaholidays' => 'Puede ver Festivos SLA',
	'admin_tcaninsertslaholidays' => 'Puede insertar Festivos SLA',
	'admin_tcanupdateslaholidays' => 'Puede actualizar Festivos SLA',
	'admin_tcandeleteslaholidays' => 'Puede eliminar Festivos SLA',
	'admin_tcanimpexslaholidays' => 'Puede Importar/Exportar Festivos SLA',
	'admin_tcanviewescalations' => 'Puede ver reglas de priorización',
	'admin_tcaninsertescalations' => 'Puede insertar reglas de priorización',
	'admin_tcanupdateescalations' => 'Puede actualizar reglas de priorización',
	'admin_tcandeleteescalations' => 'Puede eliminar reglas de priorización',
	'admin_canviewcfgroups' => 'Puede ver Campos Personalizados de Grupos',
	'admin_canviewcfields' => 'Puede ver Campos Personalizados',
	'admin_tmpcanviewgroups' => 'Puede ver Grupos de Plantillas',
	'admin_tmpcaninsertgroup' => 'Puede insertar Grupos de Plantillas',
	'admin_tmpcanupdategroup' => 'Puede actualizar Grupos de Plantillas',
	'admin_tmpcandeletegroup' => 'Puede eliminar Grupos de Plantillas',
	'admin_tmpcanviewtemplates' => 'Puede ver Plantillas',
	'admin_tmpcaninserttemplate' => 'Puede insertar Plantillas',
	'admin_tmpcanrestoretemplates' => 'Puede restaurar Plantillas',
	'admin_tmpcanupdatetemplate' => 'Puede actualizar Plantillas',
	'admin_tmpcanrundiagnostics' => 'Puede Ejecutar Diagnósticos de Plantillas',
	'admin_tmpcanrunimportexport' => 'Puede Ejecutar Importar/Exportar',
	'admin_tmpcanimportloginshare' => 'Puede importar Plugins LoginShare',
	'admin_tmpcanupdateloginshare' => 'Puede actualizar Ajustes de LoginShare',
	'admin_tmpcanviewloginshare' => 'Puede ver Plugins LoginShare',
	'admin_tmpcansearchtemplates' => 'Puede Buscar Plantillas',
	'admin_tmpcandeleteloginshare' => 'Puede eliminar Plugins LoginShare',
	'admin_tcanviewworkflows' => 'Puede ver flujos de trabajo',
	'admin_tcaninsertworkflow' => 'Puede insertar flujos de trabajo',
	'admin_tcanupdateworkflow' => 'Puede actualizar flujos de trabajo',
	'admin_tcandeleteworkflows' => 'Puede eliminar flujos de trabajo',
	'admin_tcanviewstatus' => 'Puede ver Estados',
	'admin_tcaninsertstatus' => 'Puede insertar Estados',
	'admin_tcanupdatestatus' => 'Puede actualizar Estados',
	'admin_tcandeletestatus' => 'Puede eliminar Estados',
	'admin_tcanviewpriorities' => 'Puede ver Prioridades',
	'admin_tcaninsertpriority' => 'Puede insertar Prioridades',
	'admin_tcanupdatepriority' => 'Puede actualizar Prioridades',
	'admin_tcandeletepriority' => 'Puede eliminar Prioridades',
	'admin_tcanviewfiletypes' => 'Puede ver Tipos de Archivo',
	'admin_tcaninsertfiletype' => 'Puede insertar Tipos de Archivo',
	'admin_tcanupdatefiletype' => 'Puede actualizar Tipos de Archivo',
	'admin_tcandeletefiletypes' => 'Puede eliminar Tipos de Archivo',
	'admin_tcanviewlinks' => 'Puede ver Enlaces',
	'admin_tcaninsertlink' => 'Puede insertar Enlaces',
	'admin_tcanupdatelink' => 'Puede actualizar Enlaces',
	'admin_tcandeletelinks' => 'Puede eliminar Enlaces',
	'admin_tcanpurgeattachments' => 'Puede purgar adjuntos',
	'admin_tcanrunmaintenance' => 'Puede Ejecutar Mantenimiento de Tickets',
	'admin_mpcanviewloopblockages' => 'Puede ver Bloqueos de Bucle',
	'admin_mpcandeleteloopblockages' => 'Puede eliminar Bloqueos de Bucle',
	'admin_mpcanviewlooprules' => 'Puede ver Reglas de Bucle',
	'admin_mpcaninsertlooprule' => 'Puede insertar Reglas de Bucle',
	'admin_mpcanupdatelooprule' => 'Puede actualizar Reglas de Bucle',
	'admin_mpcandeletelooprule' => 'Puede eliminar Reglas de Bucle',
	'staff_users' => 'Usuarios',
	'staff_usersorganizations' => 'Organizaciones de usuario',
	// ======= END v4 LOCALES =======

	/**
	* ###############################################
	* DEPARTMENT PERMISSIONS
	* ###############################################
	*/
	'd_ls_canhistory' => 'Puede ver las transcripciones del historial de chat',
	'd_ls_canchat' => 'Puede aceptar/rechazar chats',
	'd_t_canreply' => 'Puede responder a tickets',
	'd_t_canforward' => 'Puede Reenviar tickets',
	'd_t_canfollowup' => 'Puede crear seguimientos de ticket',
	'd_t_canbilling' => 'Puede crear entradas de facturación',


	/**
	* ###############################################
	* TEAM PERMISSIONS
	* ###############################################
	*/
	// Troubleshooter Permissions
	'mod_troubleshooter' => 'Asistente',
	'tr_entab' => 'Puede ver la pestaña del asistente',
	'tsmanagecategories' => 'Puede administrar categorías',
	'tsmanagesteps' => 'Puede administrar pasos',
	'tsinsertcategory' => 'Puede insertar categorías',
	'tseditcategory' => 'Puede editar categorías',
	'tsdeletecategory' => 'Puede eliminar categorías',
	'tsaddstep' => 'Puede añadir pasos en asistente',
	'tseditstep' => 'Puede editar un paso existente',
	'tsdeletestep' => 'Puede eliminar paso de asistente',
	'tsexport' => 'Puede exportar datos del asistente',
	'tsimport' => 'Puede importar datos del asistente',

	// Tickets
	'mod_tickets' => 'Tickets',
	't_entab' => 'Puede ver la pestaña de tickets',
	'tmanage' => 'Puede administrar tickets',
	'tdeleteview' => 'Puede eliminar vistas de ticket',
	'teditview' => 'Puede editar vistas de ticket',
	'tnewticket' => 'Puede crear un nuevo ticket',
	'tdeleteticket' => 'Puede eliminar tickets',
	'tdeletepost' => 'Puede eliminar mensajes de ticket',
	'teditpost' => 'Puede editar mensajes de ticket',
	'texport' => 'Puede exportar como PDF/XML',
	'tforward' => 'Puede reenviar tickets',
	'tcrearule' => 'Puede crear reglas de alerta públicas',
	'tbilling' => 'Puede añadir entradas de facturación',
	'tdelrecipients' => 'Puede eliminar destinatarios de ticket',
	'tmerge' => 'Puede fusionar tickets',
	'tdelarule' => 'Puede eliminar reglas de alerta públicas',
	'tupdarule' => 'Puede editar reglas de alerta públicas',
	'tdellabel' => 'Puede eliminar etiquetas de ticket',
	'tcanviewall' => 'Puede ver todos los tickets <i>(Sin Asignar, Asignados a sí mismo y asignados a Otros)</i>',
	'tbanticket' => 'Puede bloquear usuarios',
	'tbandelete' => 'Puede bloquear usuarios y eliminar tickets',

	// Downloads
	'mod_downloads' => 'Descargas',
	'dl_entab' => 'Puede ver la pestaña de descargas',
	'dlcandelcat' => 'Puede eliminar categorías',
	'dlcaneditcat' => 'Puede editar categorías',
	'dlcandelfile' => 'Puede eliminar archivo',
	'dlcaneditfile' => 'Puede editar archivo',
	'dlcaninsertcat' => 'Puede insertar categoría',
	'dlcaninsertfile' => 'Puede insertar archivo',

	// News
	'mod_news' => 'Noticias',
	'nw_entab' => 'Puede ver la pestaña de noticias',

	// Knowledgebase
	'mod_knowledgebase' => 'Biblioteca',
	'kb_entab' => 'Puede ver la pestaña de biblioteca',

	// Teamwork
	'mod_teamwork' => 'Trabajo en equipo',
	'tw_entab' => 'Puede ver la pestaña de trabajo en equipo',

	// Live Chat
	'mod_livesupport' => 'Chat',
	'ls_entab' => 'Puede ver la pestaña de chat',

	// Core
	'mod_core' => 'SWIFT General',
	'cu_entab' => 'Puede ver la pestaña de usuarios',
);

?>