<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'actionvariables' => 'Variables',
	'livechat' => 'Chat',
	'rules' => 'Reglas',
	'insertgroup' => 'Insertar grupo',
	'editgroup' => 'Editar grupo',
	'insertban' => 'Insertar bloqueo',
	'editban' => 'Editar bloqueo',
	'actionvisitorexperience' => 'Experiencia Visitante',
	'actionstaffalerts' => 'Alertas Operadores',
	'hexcode' => 'Código de Color Hex',
	'wineditgroup' => 'Editar Grupo de visitantes: %s',
	'visitorgroups' => 'Grupos de visitantes',
	'titlenorulecriteria' => 'No se especificó criterio',
	'msgnorulecriteria' => SWIFT_PRODUCT . ' no puede insertar una regla de visitante puesto que no se ha especificado un criterio.',
	'titlenoruleactions' => 'No se especificó ninguna acción',
	'msgnoruleactions' => SWIFT_PRODUCT . ' no ha podido insertar la regla de visitante puesto que no se han definido acciones.',
	'invalidgroup' => 'El grupo especificado no es válido. Por favor, asegúrese de que el grupo visitante existe y de que la base de datos no esté corrompida',
	'visitorgrouptitle' => 'Nombre grupo visitantes',
	'desc_visitorgrouptitle' => 'Por favor, indique un nombre para el grupo de visitantes.',
	'groupcolor' => 'Color de grupo',
	'desc_groupcolor' => 'Especifique un color para el nombre del grupo que se mostrará en el listado de visitantes.',
	'lastupdate' => 'Última actualización',
	'titledelvisitorgroup' => 'Eliminados "%d" Grupos de visitantes',
	'msgdelvisitorgroup' => 'Se han eliminado correctamente los siguientes grupos de visitantes de la base de datos:',
	'titleinsertgroup' => 'Insertado grupo de visitantes "%s"',
	'msginsertgroup' => 'Se ha insertado correctamente el grupo de visitantes "<font color="%s">%s</font>" en la base de datos.',
	'titleupdategroup' => 'Actualizado grupo de visitantes "%s"',
	'msgupdategroup' => 'Se ha actualizado correctamente el grupo de visitantes "<font color="%s">%s</font>".',
	'isregex' => 'Es una expresión regular?',
	'desc_isregex' => 'Si se activa,'.SWIFT_PRODUCT.' comparará las IPs de los visitantes usando la expresión regular indicada arriba.',
	'titleinsertban' => 'Insertado bloqueo de visitante',
	'msginsertban' => 'Se ha bloqueado al visitante "%s".',
	'titleupdateban' => 'Actualizado bloqueo al visitante',
	'msgupdateban' => 'Se ha actualizado correctamente el bloqueo al visitante "%s"',
	'wineditban' => 'Editar bloqueo: %s',
	'gridisregex' => 'RegEx?',
	'titledelbans' => 'Eliminado(s) "%d" bloqueos de visitantes',
	'msgdelbans' => 'Se han eliminado los siguientes bloqueos de visitantes de la base de datos:',
	'onlinestatus' => 'Estado Conectado',
	'desc_onlinestatus' => '',
	'disconnect' => 'Desconectar',
	'logintime' => 'Inicio sesión',
	'lastactivity' => 'Última Actividad',
	'username' => 'Usuario',
	'fullname' => 'Nombre',
	'titledcstaff' => 'Se ha desconectado a "%d" operadores',
	'msgdcstaff' => 'Se ha desconectado a los siguientes operadores:',
	'skills' => 'Especialidades',
	'desc_skills' => '',
	'skilltitle' => 'Nombre especialidad',
	'alertemail' => 'Email de Alerta',
	'wineditskill' => 'Editar especialidad: %s',
	'messagerouting' => 'Enrutado de mensajes',
	'desc_messagerouting' => '',
	'mrdepartment' => 'Departamento',
	'mraction' => 'Accción',
	'titleupdmr' => 'Actualizadas reglas de enrutamiento de mensajes',
	'msgupdmr' => 'Se han actualizado correctamente las reglas de enrutado de mensajes. Los detalles se muestran a continuación:',
	'routetotickets' => 'Ruta a los Tickets',
	'mrdepartment' => 'Departamento',
	'routetoemail' => 'Ruta al Email',
	'mremail' => 'Email(s)',
	'insertrule' => 'Insertar Regla',
	'desc_insertrule' => '',
	'insertcriteria' => 'Insertar Criterio',
	'tabactions' => 'Acciones',
	'insertaction' => 'Insertar Acción',
	'ruletitle' => 'Nombre Regla',
	'desc_ruletitle' => 'Introduzca el nombre de la Regla',
	'rulestop' => 'Reglas de Interrupción de Procesado',
	'desc_rulestop' => 'Si se activa, otras reglas no se procesarán si se cumplen los requisitos especificados a continuación.',
	'sortorder' => 'Orden',
	'desc_sortorder' => 'Especifique en qué orden se procesarán las Reglas; siempre en orden Ascendente..',
	'criteria' => 'Criterio',
	'smatchall' => 'Coincidir todos (Y)',
	'smatchany' => 'Coincidir cualquiera (O)',
	'matchtype' => 'Opciones de Criterio',
	'smatchtype' => 'Tipo de Coincidencia',
	'desc_matchtype' => 'Seleccione el método de agrupación para los campos de criterio.',
	'clearall' => 'Limpiar todo',
	'titlevrcoreerror' => 'Error de Núcleo: falló la inserción',
	'msgvrcoreerror' => 'No se pudo insertar la regla de visitantes',
	'invalidvisitorrule' => 'ERROR: Regla de visitantes inválida. Asegúrese de que la regla existe en la base de datos',
	'editrule' => 'Editar Regla',
	'desc_editrule' => '',
	'if' => 'Si',
	'titleinsertrule' => 'Insertada regla de visitantes "%s"',
	'msginsertrule' => 'Se ha insertado correctamente la regla de visitante "%s" en la base de datos.',
	'actaddvariable' => '<b>Variable:</b> %s = %s',
	'actvisitorexperience' => '<b>Experiencia visitante:</b> %s',
	'actstaffalert' => '<b>Alerta Operador:</b> Nombre: %s, Valor: %s',
	'actsetskill' => '<b>Definir especialidad:</b> Nombre especialidad: %s',
	'actsetgroup' => '<b>Definir Grupo:</b> Nombre del grupo de visitantes: %s',
	'actsetdepartment' => '<b>Definir Departamento:</b> Nombre departamento: %s',
	'actsetcolor' => '<b>Definir Color:</b> Código de Color: %s',
	'actbanvisitor' => '<b>Bloquear visitante:</b> Tipo: %s',
	'titleupdaterule' => 'Actualizada regla de visitante "%s"',
	'msgupdaterule' => 'La regla de visitante se actualizó correctamente "%s".',
	'titledelvrules' => 'Eliminadas "%s" Reglas de visitantes',
	'msgdelvrules' => 'Se eliminaron las siguientes reglas de visitantes.<br>%s',
	'settings' => 'Opciones',
	'lssettings' => 'Opciones',
	'desc_lssettings' => '',
	'tabsettings' => 'Opciones',
	'insertskill' => 'Insertar especialidad',
	'desc_insertskill' => '',
	'tabassignments' => 'Asignaciones',
	'skilltitle' => 'Nombre especialidad',
	'desc_skilltitle' => 'Introduzca el nombre de la especialidad',
	'skilldesc' => 'Descripción de la especialidad',
	'desc_skilldesc' => 'Introduzca la descripción de la especialidad. Máximo de 255 caracteres.',
	'skillemail' => 'Email',
	'desc_skillemail' => 'Introduzca la dirección de correo del grupo de especialidades',
	'skillsperm' => 'Asignaciones de operadores',
	'ruletype' => 'Activador de Regla',
	'desc_ruletype' => 'Seleccione las acciones de llevar a cabo cuando la regla se active',
	'ruletype_1' => 'Cuando haya un chat',
	'ruletype_2' => 'Cuando un visitante entre en la página',
	'ruletype_3' => 'Cuando un visitante entre en la web',
	'ruletype_4' => 'Cuando un visitante esté en en espera',
	'actionsetskill' => 'Definir Especialidad',
	'actionsetdepartment' => 'Definir Departamento',
	'actionsetgroup' => 'Definir Grupo',
	'actionsetcolor' => 'Definir Color',
	'actionbanvisitor' => 'Bloquear Visitante',
	'notavailable' => '-- No Disponible --',
	'inlinechat' => 'Chat en línea',
	'engagevisitor' => 'Captación Visitantes',
	'customengagevisitor' => 'Captación Visitantes (Personalizado)',
	'editskill' => 'Editar especialidad',
	'invalidchatskill' => 'Especialidad de chat no válida. Por favor, asegúrese de que la especialidad de chat existe en la base de datos.',
	'titledelchatskills' => 'Eliminadas "%d" especialidades de chat',
	'msgdelchatskills' => 'Se han eliminado las siguientes especialidades de chat de la base de datos:<br />%s',
	'titleinsertskill' => 'Insertada especialidad de chat',
	'msginsertskill' => 'Se han insertado "%s" especialidades de chat en la base de datos.',
	'titleupdateskill' => 'Actualizada especialidad de chat',
	'msgupdateskill' => 'Se han actualizado "%s" especialidades de chat.',
	'preservemessage' => 'Conservar registro de mensajes',
	'seperatevia' => 'separar vía ;',

	// ======= RULE STRINGS =======
	'rule_currentpage' => 'Navegando - Página actual',
	'desc_rule_currentpage' => 'La página que el visitante está viendo actualmente',
	'rule_currentpageurl' => 'Visitante - Página Actual (URL)',
	'desc_rule_currentpageurl' => 'La página que el visitante está viendo actualmente',
	'rule_currentpagetitle' => 'Visitante - Página Actual (Título)',
	'desc_rule_currentpagetitle' => 'La página que el visitante está viendo actualmente',
	'rule_numberofpages' => 'Navegación - Número de Páginas',
	'desc_rule_numberofpages' => 'Número de páginas que el visitante ha abierto en la sesión activa',
	'rule_previouspagetitle' => 'Navegación - Página Anterior (Título)',
	'desc_rule_previouspagetitle' => 'La página activa anterior',
	'rule_previouspageurl' => 'Navegación - Página Anterior (URL)',
	'desc_rule_previouspageurl' => 'La página activa anterior',
	'rule_referringurl' => 'Navegación - URL de origen',
	'desc_rule_referringurl' => 'URL de origen de la página activa',
	'rule_searchenginefound' => 'Navegación - Localización por Motores de Búsqueda',
	'desc_rule_searchenginefound' => 'Propiedades Booleanas basadas en si el origen de un visitante es un motor de búsqueda',
	'rule_searchenginename' => 'Navegación - Nombre de Motor de Búsqueda',
	'desc_rule_searchenginename' => 'El motor de búsqueda origen de la visita',
	'rule_searchenginequery' => 'Navegación - Palabras clave búsqueda',
	'desc_rule_searchenginequery' => 'Las palabras clave usadas en la búsqueda',
	'rule_visitedpagetitle' => 'Navegación - Páginas Visitadas (Título)',
	'desc_rule_visitedpagetitle' => 'Todas las páginas que el visitante ha visitado en la sesión activa',
	'rule_visitedpageurl' => 'Navegación - Páginas Visitadas (URL)',
	'desc_rule_visitedpageurl' => 'Todas las páginas que el visitante ha visitado en la sesión activa',
	'rule_repeatvisit' => 'Visitante - Repetición de la Visita',
	'desc_rule_repeatvisit' => 'Si el visitante es nuevo o ya había visitado la página',
	'rule_browser' => 'Visitante - Navegador',
	'desc_rule_browser' => 'Navegador web usado por el visitante: Safari, Mozilla, Internet Explorer',
	'rule_ipaddress' => 'Visitante - Dirección IP',
	'desc_rule_ipaddress' => 'La dirección IP del visitante',
	'rule_onlinestaff' => 'Operadores - Operadores conectados',
	'desc_rule_onlinestaff' => 'Propiedad basada en el estado de los operadores conectados',
	'rule_onlinestaffskills' => 'Operadores - Operadores especialistas conectados',
	'desc_rule_onlinestaffskills' => 'Propiedad basada en el estado de los operadores conectados que tienen la especialidad especificada',
	'rule_onlinestaffdepartments' => 'Operadores - Operadores conectados de un departamento',
	'desc_rule_onlinestaffdepartments' => 'Propiedad basada en el estado los operadores de un departamento específico',
	'rule_timeinsite' => 'Tiempo - Tiempo en la web',
	'desc_rule_timeinsite' => 'Tiempo Total pasado en la web',
	'rule_timeinchat' => 'Tiempo - Tiempo en el Chat',
	'desc_rule_timeinchat' => 'Tiempo total empleado en un chat activo',
	'rule_timeagententry' => 'Tiempo - Segundos desde la última respuesta del operador',
	'desc_rule_timeagententry' => 'Número de segundos desde el último mensaje del operador',
	'rule_timevisitorentry' => 'Tiempo - Segundos desde el último mensaje de un visitante',
	'desc_rule_timevisitorentry' => 'Número de segundos desde el último mensaje de un visitante',
	'rule_timeagentvisitorentry' => 'Tiempo - Segundos desde el último mensaje del operador o del visitante',
	'desc_timeagentvisitorentry' => 'Número de segundos desde el último mensaje del operador o visitante',
	'rule_chatagentlastmessage' => 'Chat - Último mensaje del operador',
	'desc_rule_chatagentlastmessage' => 'El contenido del último mensaje del operador',
	'rule_chatvisitorlastmessage' => 'Chat - Último mensaje del visitante',
	'desc_rule_chatvisitorlastmessage' => 'El contenido del último mensaje del visitante',
	'rule_chatwithagentmessage' => 'Chat - Chat mensaje del operador',
	'desc_rule_chatwithagentmessage' => 'Booleano basado en si hay mensaje de un operador en el chat',
	'rule_chatwithvisitormessage' => 'Chat - Chat con mensaje de visitante',
	'desc_rule_chatwithvisitormessage' => 'Booleano basado en si hay mensaje de visitante en el chat',
	'rule_chatwithagentvisitormessage' => 'Chat - Chat con operador o mensaje de visitante',
	'desc_rule_chatwithagentvisitormessage' => 'Booleano basado en si hay mensaje del operador o visitante en el char',
	'rule_chatinchat' => 'Chat - En Chat',
	'desc_rule_chatinchat' => 'Booleano basado en si el chat ha sido aceptado por un operador',
	'rule_chatrefusedchat' => 'Chat - Chat Rechazado',
	'desc_rule_chatrefusedchat' => 'Booleano basado en si el chat ha sido rechazado por el operador',
	'rule_geocountry' => 'GeoIP - País',
	'desc_rule_geocountry' => '',
	'rule_geocity' => 'GeoIP - Ciudad',
	'desc_rule_geocity' => '',
	'rule_geoipregion' => 'GeoIP - Región',
	'desc_rule_geoipregion' => '',
	'rule_geoorganization' => 'GeoIP - Organización',
	'desc_rule_geoorganization' => '',
	'rule_geotimezone' => 'GeoIP - Zona Horaria',
	'desc_rule_geotimezone' => '',
	'rule_geoisp' => 'GeoIP - ISP',
	'desc_rule_geoisp' => '',
	'rule_geoconnectiontype' => 'GeoIP - Velocidad de la Red',
	'desc_rule_geoconnectiontype' => '',
	'rule_geoippostalcode' => 'GeoIP - Código Postal',
	'desc_rule_geoippostalcode' => '',
	'rule_geoipmetrocode' => 'GeoIP - Código Metropolitano',
	'desc_rule_geoipmetrocode' => '',
	'rule_geoipareacode' => 'GeoIP - Código Área',
	'desc_rule_geoipareacode' => '',
	'rule_geoiplatitude' => 'GeoIP - Latitud',
	'desc_rule_geoiplatitude' => '',
	'rule_geoiplongitude' => 'GeoIP - Longitud',
	'desc_rule_geoiplongitude' => '',
	// ======= END v4 LOCALES =======


	'livesupport' => 'Live Chat',
	'visitorbans' => 'Bloqueos Visitantes',
	'desc_visitorbans' => 'Visitantes se bloquean por dirección IP. Los bloqueos de Visitante se pueden añadir desde la aplicación de escritorio LiveResponse. Los visitantes bloqueados no aparecerán en el seguimiento de visitantes y no podrán ver el estado del chat en el botón de la interfaz de cliente.',
	'visitorbanlist' => 'Lista de Bloqueos de Visitantes',
	'ipaddress' => 'Dirección IP',
	'desc_ipaddress' => 'Introduce la dirección IP a bloquear.',
	'addedby' => 'Creado por',
	'bandate' => 'Fecha Creación',
	'insertvisitorban' => 'Insertar Bloqueo Visitante',
	'invalidip' => 'ERROR: Dirección IP incorrecta',
	'ipinsertconfirm' => 'El Bloqueo de visitantes por dirección "%s" se ha insertado correctamente',
	'ipupdateconfirm' => 'El bloqueo de IP para la dirección "%s" ha sido actualizado',
	'ipdelconfirm' => 'Bloqueo de visitante eliminado correctamente',
	'invalidban' => 'Entrada de bloqueo de visitante incorrecta',
	'updatevisitorban' => 'Actualizar Bloqueo Visitante',
);
?>