<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
		// ======= BEGIN V4 LOCALES =======
	'insertholiday' => 'Insertar festivo',
	'impex' => 'Importar/Exportar',
	'manageholidays' => 'Festivos',
	'desc_manageholidays' => '',
	'desc_insertholiday' => '',
	'holidaytitle' => 'Nombre festivo',
	'desc_holidaytitle' => 'Introduzca el nombre del festivo',
	'holidaydate' => 'Fecha festivo',
	'desc_holidaydate' => 'Por favor, especifique la fecha del festivo',
	'tabslaplans' => 'Planes SLA',
	'flagicon' => 'Icono de bandera',
	'desc_flagicon' => 'Especifique la URL del icono de bandera. Las banderas por defecto se encuentran en el directorio themes/global/flags. Puede usar las siguientes variables:<br><b>{$themepath}</b> - URL para el directorio de temas<br> - Ejemplo: {$themepath}us.gif',
	'slaplans' => 'Planes SLA disponibles',
	'slaiscustom' => 'Vinculado con Planes SLA personalizados',
	'desc_slaiscustom' => 'Especifique si el festivo está vinculado a planes SLA personalizados',
	'customall' => 'Todo',
	'custom' => 'Personalizado',
	'wineditslaholiday' => 'Editar festivo: %s',
	'editholiday' => 'Editar festivo',
	'desc_editholiday' => '',
	'invalidslaholiday' => 'Festivo no válido. Por favor, asegúrese de que existe en la base de datos.',
	'titleinsertslaholiday' => 'Insertado festivo',
	'msginsertslaholiday' => 'Se ha insertado correctamente el festivo "%s" en la base de datos.',
	'titleupdateslaholiday' => 'Actualizado festivo',
	'msgupdateslaholiday' => 'Se ha actualizado correctamente el festivo "%s".',
	'titledelslaholidays' => 'Eliminados "%d" festivos',
	'msgdelslaholidays' => 'Se han eliminado correctamente los siguientes festivos de la base de datos:',
	'slaimportexport' => 'Importar/Exportar',
	'desc_slaimportexport' => '',
	'tabexport' => 'Exportar',
	'tabimport' => 'Importar',
	'import' => 'Importar',
	'export' => 'Exportar',
	'exporttitle' => 'Nombre',
	'desc_exporttitle' => 'Introduzca el nombre de este paquete de festivos',
	'exportauthor' => 'Autor',
	'desc_exportauthor' => 'Introduzca el autor de este paquete de festivos',
	'exportfilename' => 'Archivo',
	'desc_exportfilename' => 'Especifique el nombre de archivo para este paquete de festivos',
	'slaholidaypack' => 'Paquete de festivos',
	'slaholidayfile' => 'Archivo de paquete de festivos',
	'desc_slaholidayfile' => 'Suba el archivo del paquete de festivos. '.SWIFT_PRODUCT.' importará todos las festivos disponibles en el archivo XML en la base de datos.',
	'titleslaholidayimpex' => 'Pack de festivos importado',
	'msgslaholidayimpex' => 'Se han importado correctamente <b>"%d"</b> festivos en la base de datos.',
	'titleslaholidayimpexfailed' => 'La importación del paquete de festivos ha fallado',
	'msgslaholidayimpexfailed' => 'La importación del paquete de festivos ha fallado. Por favor, compruebe que el contenido del pack contiene un archivo XML válido generado por '.SWIFT_PRODUCT.'.',
	'insertschedule' => 'Insertar planificación',
	'desc_insertschedule' => '',
	'sladayopen24' => 'Abierto (24 Horas)',
	'sladayclosed' => 'Cerrado',
	'sladayopencustom' => 'Abierto (Personalizado)',
	'titleinvalidhrange' => 'Intervalo horario no válido',
	'msginvalidhrange' => 'Por favor, corrija los siguientes intervalos horarios para continuar:',
	'manageschedules' => 'Administrar planificaciones',
	'desc_manageschedules' => '',
	'titleinsertslasched' => 'Planificación insertada',
	'msginsertslasched' => 'Se ha insertado correctamente la planificación "%s" en la base de datos.',
	'titleupdateslasched' => 'Planificación actualizada',
	'msgupdateslasched' => 'Se ha actualizado correctamente la planificación "%s".',
	'creationdate' => 'Fecha creación',
	'invalidslaschedule' => 'Fecha de creación no válida. Por favor, asegúrese de que la planificación existe en la base de datos.',
	'editschedule' => 'Editar planificación',
	'desc_editschedule' => '',
	'titleslaschedulenodel' => 'No se ha podido borrar la planificación',
	'msgslaschedulenodel' => SWIFT_PRODUCT.' no ha podido borrar las siguientes planificaciones puesto que están vinculadas a algunos planes SLA. Por favor, elimine los vínculos para poder eliminar las planificaciones de la base de datos.',
	'titledelslaschedules' => 'Eliminadas "%d" planificaciones',
	'msgdelslaschedules' => 'Se han eliminado correctamente las siguientes planificaciones de la base de datos.',
	'slasettings' => 'Ajustes SLA',
	'tabsettings' => 'Ajustes',
	'sla' => 'SLA',
	'insertplan' => 'Insertar plan',
	'desc_insertplan' => '',
	'tabholidays' => 'Festivos',
	'plantitle' => 'Nombre plan',
	'desc_plantitle' => 'Introduzca el nombre del plan.',
	'resolutionduehrs' => 'Fecha resolución (horas)',
	'desc_resolutionduehrs' => 'Introduzca el número de horas tras las que se espera que el ticket se marque como resuelto.',
	'resolutionduehrs2' => 'Resolución (horas)',
	'overduehrs' => 'Vencimiento (horas)',
	'desc_overduehrs' => 'Introduzca el número de horas tras las que el ticket se marcará como vencido. Puede especificar los minutos como decimales. Ejemplo: 1.20',
	'planschedule' => 'Planificación SLA',
	'desc_planschedule' => 'Especifique la planificación para este Plan SLA. La fecha de vencimiento se calcula automáticamente en función de la planificación de trabajo.',
	'smatchtype' => 'Tipo de coincidencia',
	'matchtype' => 'Opciones de criterio',
	'desc_matchtype' => 'Selecciona los siguientes métodos de agrupación para los campos de criterio.',
	'smatchall' => 'Coincidir todo (Y)',
	'smatchany' => 'Coincidir cualquiera (O)',
	'isenabled' => '¿Activo?',
	'desc_isenabled' => 'Conmute la ejecución de este plan SLA activando/desactivando esta opción.',
	'sortorder' => 'Orden',
	'desc_sortorder' => 'Especifique el orden para esta regla. Las reglas siempre se procesan en orden ascendente.',
	'insertcriteria' => 'Insertar criterio',
	'manageplans' => 'Planes',
	'schedules' => 'Planificaciones',
	'desc_manageplans' => '',
	'scheduletitle' => 'Nombre planificación',
	'desc_scheduletitle' => '',
	'titlenocriteriaadded' => 'No hay criterios disponibles',
	'msgnocriteriaadded' => 'Es necesario añadir al menos un criterio para insertar o editar el plan SLA.',
	'noscheduleavailable' => '-- No hay planificaciones disponibles --',
	'titlenoslasched' => 'Planificación SLA no disponible',
	'msgnoslasched' => 'No se han añadido planificaciones SLA a '. SWIFT_PRODUCT .'. Es necesario añadir una planificación SLA para insertar o actualizar un plan SLA.',
	'nocustomholidays' => 'No hay festivos personalizados disponibles. Puede activar esta propiedad en Administrar festivos &gt; Editar',
	'editplan' => 'Editar plan',
	'desc_editplan' => '',
	'invalidslaplan' => 'Plan SLA no válido. Asegúrese de que el Plan SLA existe en la base de datos.',
	'titleslaplandel' => 'Eliminados "%d" planes SLA',
	'msgslaplandel' => 'Se han eliminado los siguientes planes SLA de la base de datos:',
	'titleslaplanenable' => 'Activados "%d" planes SLA',
	'msgslaplanenable' => 'Se han activado los siguientes planes SLA:',
	'titleslaplandisable' => 'Desactivados "%d" planes SLA',
	'msgslaplandisable' => 'Se han desactivado correctamente los siguientes Planes SLA:',
	'linkedholidays' => 'Festivos vinculados (Personalizado)',
	'titleslaplaninsert' => 'Insertado Plan SLA',
	'msgslaplaninsert' => 'Se ha insertado correctamente el plan SLA "%s" en la base de datos.',
	'titleslaplanupdate' => 'Plan SLA Actualizado',
	'msgslaplanupdate' => 'Se ha actualizado correctamente el plan SLA "%s".',
	'if' => 'If',
	'scheduledesc' => 'Información de planificación',

	// SLA Rules
	'srticketstatus' => 'Estado de ticket',
	'desc_srticketstatus' => '',
	'srticketpriority' => 'Prioridad del ticket',
	'desc_srticketpriority' => '',
	'srdepartmentid' => 'Departamento',
	'desc_srdepartmentid' => '',
	'srownerstaffid' => 'Responsable del ticket',
	'desc_srownerstaffid' => '',
	'sremailqueueid' => 'Cola Email',
	'srusergroupid' => 'Grupo Usuarios',
	'desc_srusergroupid' => '',
	'desc_sremailqueueid' => '',
	'notapplicable' => '-- NA --',
	'srfullname' => 'Nombre',
	'desc_srfullname' => '',
	'sremail' => 'Email',
	'desc_sremail' => '',
	'srlastreplier' => 'Última respuesta por',
	'desc_srlastreplier' => '',
	'srsubject' => 'Asunto',
	'desc_srsubject' => '',
	'srcharset' => 'Juego Caracteres',
	'desc_srcharset' => '',
	'srflagtype' => 'Tipo Marca',
	'desc_srflagtype' => '',
	'srbayescategory' => 'Categoría bayesiana',
	'desc_srbayescategory' => '',
	'purpleflag' => 'Marca violeta',
	'redflag' => 'Marca roja',
	'orangeflag' => 'Marca naranja',
	'yellowflag' => 'Marca amarilla',
	'blueflag' => 'Marca azul',
	'greenflag' => 'Marca verde',
	'srcreator' => 'Creador',
	'desc_srcreator' => '',
	'creatorstaff' => 'Operador',
	'creatorclient' => 'Usuario',
	'srunassigned' => '-- Sin Asignar --',
	'srtemplategroup' => 'Grupo plantillas',
	'desc_srtemplategroup' => '',
	'srisresolved' => '¿Resuelto?',
	'desc_srisresolved' => '',
	'srtickettype' => 'Tipo de ticket',
	'desc_srtickettype' => '',
	'srwasreopened' => '¿Reabierto?',
	'desc_srwasreopened' => '',
	'srtotalreplies' => 'Respuestas Totales',
	'desc_srtotalreplies' => '',


	'slajanuary' => 'Enero (01)',
	'slafebruary' => 'Febrero (02)',
	'slamarch' => 'Marzo (03)',
	'slaapril' => 'Abril (04)',
	'slamay' => 'Mayo (05)',
	'slajune' => 'Junio (06)',
	'slajuly' => 'Julio (07)',
	'slaaugust' => 'Agosto (08)',
	'slaseptember' => 'Septiembre (09)',
	'slaoctober' => 'Octubre (10)',
	'slanovember' => 'Noviembre (11)',
	'sladecember' => 'Diciembre (12)',
	// ======= END V4 LOCALES =======
);
?>