<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN NEW V4 LOCALES =======
	'tabgeneral' => 'General',
	'insertcfgrouptitle' => 'Se ha insertado el grupo de campos personalizados "%s"',
	'insertcfgroupmsg' => 'Se ha insertado correctamente el grupo de campos personalizados "<b>%s</b>" en la base de datos.<br><b>Nombre:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de visualización:</b> %s',
	'updatecfgrouptitle' => 'Se ha actualizado el grupo de campos personalizados "%s"',
	'updatecfgroupmsg' => 'Se ha actualizado correctamente el grupo de campos personalizados "<b>%s</b>".<br><b>Nombre:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de visualización:</b> %s',
	'wineditcfgroup' => 'Editar grupo de campos personalizados: %s',
	'titledelcfgroup' => 'Se ha(n) eliminado "%d" grupo(s) de campos personalizados',
	'msgdelcfgroup' => 'Se han eliminado correctamente los siguientes grupos de campos personalizados de la base de datos:<br>%s',
	'buttonnext' => 'Siguiente',
	'encryptindb' => 'Cifrar el valor en la base de datos',
	'desc_encryptindb' => 'Si está habilitado, el valor guardado en la base de datos será cifrado usando el hash único de instalación. Los valores del campo contraseña se guardan cifrados por defecto.',
	'tabdepartments' => 'Departamentos',
	'assigneddepartments' => 'Departamentos asignados',
	'titleunproc' => 'Imposible continuar',
	'msgunproc' => 'Es necesario crear al menos un grupo de campos personalizados para añadir un campo personalizado.',
	'taboptions' => 'Opciones',
	'tablanguages' => 'Idiomas: traducción',
	'tabpermissions' => 'Permisos',
	'field_date' => 'Fecha',
	'desc_field_date' => 'Este tipo de campo permite crear un desplegable selector de fecha.',
	'field_linkedselect' => 'Selector enlazado',
	'desc_field_linkedselect' => 'Seleccione este tipo de campo para crear un selector enlazado.',
	'cfteampermissions' => 'Permisos: Equipo',
	'cfstaffpermissions' => 'Permisos: Operadores (Anula los permisos de equipo)',
	'notset' => 'No establecido',
	'insertcfieldtitle' => 'Se ha insertado el campo personalizado "%s"',
	'insertcfieldmsg' => 'Se ha insertado correctamente el campo personalizado "<b>%s</b>" en la base de datos.<br>',
	'updatecfieldtitle' => 'Actualizado campo personalizado "%s"',
	'updatecfieldmsg' => 'Se ha actualizado correctamente el campo personalizado "<b>%s</b>".<br>',
	'wineditcfield' => 'Editar campo personalizado: %s',
	'titledelcfields' => 'Se ha(n) eliminado "%d" campo(s) personalizado(s)',
	'msgdelcfields' => 'Se han eliminado los siguientes campos personalizados de la base de datos:<br>%s',
	// ======= END NEW V4 LOCALES =======

	'grouptitle' => 'Nombre del grupo',
	'desc_grouptitle' => '',
	'grouptype' => 'Tipo de grupo',
	'desc_grouptype' => 'Los campos personalizados deben pertenecer a un <b>grupo de campos personalizados</b>, el cual está vinculado a un área del producto como creación de tickets, chat, usuario, grupo de usuarios, etc.',
	'displayorder' => 'Orden de visualización',
	'desc_displayorder' => 'Si hay varios grupos en un área del producto, se ordenarán usando el orden de visualización (ascendente) especificado aquí.',
	'customfields' => 'Campos personalizados',
	'managegroups' => 'Administrar grupos',
	'desc_customfieldgroups' => '',
	'grouplist' => 'Grupos de campos personalizados',
	'insertgroup' => 'Insertar grupo',
	'cfgroupdetails' => 'Detalles del grupo de campos personalizados',
	'grouptypeuser' => 'Usuario',
	'grouptypeknowledgebase' => 'Artículos de base de conocimiento',
	'grouptypenews' => 'Artículos de noticias',
	'grouptypetroubleshooter' => 'Pasos del solucionador',
	'grouptypedownloads' => 'Descarga de archivos',
	'grouptypeuserorganization' => 'Organización de usuario',
	'grouptypestaffticket' => 'Creación de ticket por operador',
	'grouptypeuserticket' => 'Creación de ticket por usuario',
	'grouptypestaffuserticket' => 'Creación de ticket por usuario y operador',//Mahesh Slaria: Staff & user ticket creation
	'grouptypetimetrack' => 'Seguimiento de tiempos de ticket',
	'grouptypecontact' => 'Contacto de trabajo en equipo',
	'grouptypeevent' => 'Evento de trabajo en equipo',
	'grouptypetask' => 'Tarea de trabajo en equipo',
	'grouptypelivesupportpre' => 'Chat - Pre Chat',
	'grouptypelivesupportpost' => 'Chat - Post Chat',
	'insertgroup' => 'Insertar Grupo',
	'updategroup' => 'Actualizar grupo',
	'cfgroupinsertconfirm' => 'Se ha insertado correctamente el grupo de campos personalizados "%s"',
	'addfield' => 'Añadir campo',
	'cfgroupdelconfirm' => 'El/los grupo(s) de campos personalizados ha(n) sido eliminado(s) correctamente',
	'cfgroupactconfirm' => 'Está seguro de que desea eliminar este grupo de campos personalizados? Eliminar un grupo provocará el borrado permanente de todos los campos personalizados, así como sus respectivos valores almacenados. Esta acción es irreversible!',
	'editgroup' => 'Editar grupo',
	'invalidcfgroup' => 'Grupo de campos personalizados no válido',
	'usergroups' => 'Grupos de usuarios',
	'desc_usergroups' => 'Seleccione los grupos de usuarios para los que el grupo de campos personalizados estará disponible. Por ejemplo, puede tener dos grupos de usuarios diferentes y puede querer tener este grupo de campos personalizados disponible sólo para uno de ellos.',
	'cfgroupupdateconfirm' => 'El grupo de campos personalizados "%s" se ha actualizado correctamente',
	'selectoneusergroup' => 'ERROR: es necesario seleccionar al menos un grupo de usuarios',
	'insertfield' => 'Insertar campo',
	'desc_customfields' => '',
	'next' => 'Siguiente &raquo;',
	'selectcftype' => 'Seleccionar tipo de campo personalizado',
	'insertfieldstep1' => 'Insertar campo: Paso 1',
	'insertfieldstep2' => 'Insertar campo: Paso 2',
	'fielddetails' => 'Detalles de campo',
	'customfieldgroup' => 'Grupo de campos personalizados',
	'desc_customfieldgroup' => '',
	'fieldtype' => 'Tipo de campo',
	'erroraddcfgroup' => 'ERROR: Necesita crear al menos un grupo de campos personalizados para añadir un campo',
	'nogroupadded' => '-- No hay grupos de campos disponibles --',
	'fieldtitle' => 'Título del campo',
	'desc_fieldtitle' => 'El título del campo se muestra junto a cada campo en los interfaces de usuario y operador para describir el propósito de cada campo.',
	'fieldname' => 'Nombre del campo',
	'desc_fieldname' => '',
	'isrequired' => 'Es obligatorio?',
	'desc_isrequired' => 'Si está habilitado, se obligará al usuario a rellenar el campo para que los datos se puedan procesar.',
	'usereditable' => 'Editable por usuarios',
	'desc_usereditable' => 'Si los usuarios pueden modificar el contenido del campo',
	'staffeditable' => 'Editable por operadores',
	'desc_staffeditable' => 'Si los operadores pueden modificar el contenido del campo',
	'regexpvalidate' => 'Validación mediante expresiones regulares',
	'desc_regexpvalidate' => 'Aquí puede especificar una expresión regular para validar el contenido del campo.',
	'defaultvalue' => 'Valor por defecto',
	'desc_defaultvalue' => 'si se especifica, el valor por defecto del campo será lo que introduzca aquí.',
	'description' => 'Descripción del campo',
	'desc_description' => 'Una descripción del campo.',
	'fielddisplayorder' => 'Orden de visualizaciónr',
	'desc_fielddisplayorder' => 'Si hay varios campos en un grupo, se ordenan usando el orden de visualización (ascendente) especificado aquí',
	'fieldoptions' => 'Opciones de campo',
	'optionvalues' => 'Opciones de valores',
	'optiondisplayorder' => 'Orden de visualización',
	'optionisselected' => 'Está seleccionado?',
	'cfieldinsertconfirm' => 'Campo personalizado "%s" insertado correctamente',
	'cfdepartments' => 'Departamentos',
	'desc_cfdepartments' => 'Seleccione los departamentos a los que está vinculado el campo personalizado. Puede usar esta característica para mostrar diferentes campos personalizados para diferentes departamentos.',
	'cfgroupd' => 'Grupo de campos personalizados',
	'desc_cfgroupd' => 'Seleccione el grupo de campos personalizados para este campo.',

	// Manage Fields
	'managefields' => 'Administrar campos',
	'desc_customfields' => '',
	'fieldlist' => 'Lista de campos',
	'cfdelconfirm' => 'Campo personalizado eliminado correctamente',
	'cfdelconfirmmsg' => 'Está seguro de que desea eliminar este campo personalizado? Eliminar un campo personalizado borrará permanentemente el campo y todos los valores almacenados. Esta acción es irreversible!',

	// Edit Custom Field
	'invalidcustomfield' => 'Campo personalizado no válido',
	'editcfield' => 'Editar campo personalizado',
	'updatefield' => 'Actualizar campo',
	'cfieldupdateconfirm' => 'Campo personalizado "%s" actualizado correctamente',

	// Field List
	'field_text' => 'Texto',
	'desc_field_text' => 'Seleccione este tipo de campo para crear un campo de introducción de texto.',
	'field_textarea' => 'Área de texto',
	'desc_field_textarea' => 'Seleccione este tipo de campo para crear una caja de texto multilínea.',
	'field_password' => 'Contraseña',
	'desc_field_password' => 'Seleccione este tipo de campo para crear un campo de introducción de contraseñas (sin visualización de caracteres).',
	'field_checkbox' => 'Casilla de verificación',
	'desc_field_checkbox' => 'Seleccione este tipo de campo para crear una lista de casillas de verificación (con posibilidad de selección múltiple).',
	'field_radio' => 'Botones Radio',
	'desc_field_radio' => 'Seleccione este tipo de campo para crear una lista de botones tipo radio (SIN posibilidad de selección múltiple).',
	'field_select' => 'Desplegable',
	'desc_field_select' => 'Seleccione este tipo de campo para crear un selector desplegable (selección única).',
	'field_file' => 'Archivo',
	'desc_field_file' => 'Seleccione este tipo de campo para crear un campo de subida de archivos (sólo se puede subir un archivo).',
	'field_selectmultiple' => 'Desplegable Multiple',
	'desc_field_selectmultiple' => 'Seleccione este tipo de campo para crear una lista con selección múltiple.',
	'field_custom' => 'Personalizado',
	'desc_field_custom' => 'Seleccione este tipo de campo para crear una entrada genérica para campos personalizados en ' . SWIFT_PRODUCT . '. Sin embargo tendrá que añadir el código HTML necesario en las plantillas de envío de tickets. Este tipo de campo personalizado sólo proporciona un encaminamiento y un área de almacenamiento para los datos. Debe escribir el código HTML correspondiente para que el usuario pueda introducir los datos.',
);
?>