<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titlespecifyvalidemail' => 'Dirección email no válida',
	'msgspecifyvalidemail' => 'Por favor introduzca una dirección de email válida. Toda la correspondencia sobre este bug se enviará a esa dirección.',
	'send' => 'Enviar',
	'ddbversion' => 'Versión base de datos: %s',
	'ddbtype' => 'Tipo de base de datos: %s',
	'configurationvariables' => 'Variables de configuración',
	'phpmodule' => 'Módulo: <b>%s</b>',
	'killsessions' => 'Cerrar sesiones',
	'titlekillsession' => 'Cerradas "%d" sesiones',
	'msgkillsession' => 'Se han cerrado las siguientes sesiones:',
	'wineditcache' => 'Editar caché: %s',
	'titlebugreportdispatched' => 'Informe de bug enviado',
	'msgbugreportdispatched' => SWIFT_PRODUCT . ' ha enviado su informe de bug a Kayako. Un representante de Kayako se pondrá en contacto con usted lo antes posible.',
	'rebuildcache' => 'Reconstruír caché',
	'licunlimited' => '- Ilimitado - ',
	'tabrebuildcache' => 'Reconstruír caché',
	'cachename' => 'Nombre caché',
	'result' => 'Resultado',
	'failure' => 'Fallo',
	'success' => 'Éxito',
	'clearedcachedirectory' => 'Directorio caché borrado',
	'licorganization' => 'Organización: ' ,
	'licproductpackage' => 'Paquete: ',
	'licstaffcount' => 'Número de operadores licencia: ',
	'licexpirenever' => '- Nunca -',
	// ======= END v4 LOCALES =======

	// ======= BEGIN v3 IMPORT =======
	'php_ini_memory_limit' => 'Límite de RAM en php.ini: %s',
	'php_uname' => 'Información extendida del SO del servidor: %s',
	'swift_language_base_charset' => 'Juego caracteres base de idioma SWIFT: %s',
	'swift_language_html_charset' => 'Juego caracteres html de idioma SWIFT: %s',
	'swift_language_text_charset' => 'Juego caracteres texto de idioma SWIFT: %s',
	'swift_language_html_encoding' => 'Codificación html de idioma SWIFT: %s',
	'swift_language_text_encoding' => 'Codificación texto idioma SWIFT: %s',
	'php_installed_modules' => 'Módulos PHP instalados: %s',
	'disk_free_space' => 'Espacio libre en disco: %s de %s bytes',
	'php_ini_max_execution_time' => 'Max Execution Time en PHP INI: %s',
	'php_ini_display_errors' => 'PHP Error Display: %s',
	'php_ini_quiet_eval' => 'PHP Quiet Evaluation Mode: %s',
	'php_ini_error_reporting' => 'PHP Error Reporting Level: %s',
	'php_ini_output_buffering' => 'PHP Output Buffering: %s',
	'zend_version' => 'Versión Zend: %s',
	'php_ini_register_globals' => 'Register Globals: %s',
	'php_ini_magic_quotes_gpc' => 'Magic Quotes GPC: %s',
	'php_ini_magic_quotes_runtime' => 'Magic Quotes Runtime: %s',
	'php_ini_post_max_size' => 'Maximum POST size: %s',
	'php_ini_upload_max_size' => 'Maximum upload size: %s',
	'php_ini_allow_calltime_pass_reference' => 'PHP allows call-time reference passage: %s',
	'php_ini_allow_url_fopen' => 'PHP allows URL fopen(): %s',
	'php_ini_always_populate_raw_post_data' => 'Force-populate POST with raw data: %s',
	'php_ini_default_charset' => 'Juego de caracteres por defecto servidor: %s',
	'php_ini_default_mimetype' => 'Tipo MIME por defecto servidor: %s',
	'php_ini_display_startup_errors' => 'PHP muestra errores de inicio: %s',
	'php_ini_expose_php' => 'PHP está expuesto: %s',
	'php_ini_ignore_repeated_errors' => 'PHP ignores repeat errors: %s',
	'php_ini_max_input_time' => 'INI Max output time: %s',
	'php_ini_output_handler' => 'Global output handler: %s',
	'php_ini_report_zend_debug' => 'Report Zend debugging calls: %s',
	'php_ini_safe_mode' => 'PHP is in safe mode: %s',
	'php_ini_bug_compat_42' => 'INI Compatibility mode 42: %s',
	'php_ini_bug_compat_warn' => 'Warn of INI compatibility modes: %s',
	'php_ini_track_errors' => 'PHP tracks errors: %s',
	'php_ini_upload_max_filesize' => 'Maximum file upload size: %s',
	'php_ini_zend_1_compatibility_mode' => 'Zend 1 compatibility mode: %s',
	'php_rusage' => 'RUsage: %s',
	'licfullname' => 'Nombre registrado: ',
	// ======= END v3 IMPORT =======
	'diagnostics' => 'Diagnósticos',
	'phpinfo' => 'PHP Info',
	'desc_phpinfo' => 'La configuración PHP de su servidor se muestra a continuación. Para más información sobre la función phpinfo() visite <a href="http://www.php.net/phpinfo" target="_blank">http://www.php.net/phpinfo</a>.',
	'mysqlinfo' => 'MySQL Info',
	'desc_mysqlinfo' => 'La configuración MySQL de su servidor se muestra a continuación. El valor de estas variables se especifica en el archivo my.cnf que habitualmente se encuentra en el directorio <i>etc</i>.',
	'variable' => 'Variable',
	'value' => 'Valor',
	'cachetitle' => 'Nombre caché',
	'cacheinfo' => 'Info caché',
	'desc_cacheinfo' => 'La información que se genera frecuentemente y los datos se cachean, reduciendo la necesidad de arrancar peticiones repetitivas a la base de datos.',

	// Report Bug
	'reportbug' => 'Informar de bug',
	'desc_reportbug' => 'Puede informar de un bug al equipo de Kayako proporcionando una descripción breve del fallo a continuación. Se recomienda que guarde la información de depuración ya que ayuda a encontrar el problema antes. Por favor, asegúrese de que la dirección de email especificada es correcta.',
	'bugdetails' => 'Informe de bug',
	'submitbug' => 'Enviar bug',
	'bugsubject' => 'Asunto',
	'desc_bugsubject' => 'Introduzca un asunto para el informe de bug.',
	'bugfromname' => 'Nombre',
	'desc_bugfromname' => 'Introduzca su nombre o el nombre de la persona de su organización a la que se debe contactar.',
	'bugfromemail' => 'Dirección email',
	'desc_bugfromemail' => 'Esta es la dirección de email que se usará como remitente para el informe enviado a Kayako. Pör favor, asegúrese de que la dirección es válida.',
	'debuginfo' => '### Info depuración ###',
	'dphpversion' => 'PHP Version: %s',
	'dphpuploadsize' => 'Max Upload Size: %s',
	'dphpsafemode' => 'Safe Mode: %s',
	'dswifturl' => 'Installation URL: %s',
	'dswiftproduct' => 'Product: %s',
	'dswiftversion' => 'Version: %s',
	'dswiftbuilddate' => 'Build Date: %s',
	'dswiftbuildtype' => 'Build Type: %s',
	'dmysqlversion' => 'MySQL Version: %s',
	'duseragent' => 'User Agent: %s',
	'dserversoftware' => 'Server Software: %s',
	'dos' => 'Operating System: %s',
	'specifyvalidemail' => 'ERROR: Por favor especifique una dirección de email válida',
	'bugreportdispatched' => 'Informe de bug enviado a bugs@kayako.com',

	// License Information
	'licenseinfo' => 'Información de licencia',
	'desc_licenseinfo' => '',
	'liccreated' => 'Creada el: ',
	'licnever' => '-- Nunca --',
	'licexpiry' => 'Fecha expiración: ',
	'licuniqueid' => 'ID única: ',
	'licproduct' => 'Producto: ',
	'licdomains' => 'Dominios registrados',
	'licdomform' => 'Dominio #%s',

	// Active Sessions
	'activesessions' => 'Sesiones activas',
	'desc_activesessions' => '',
	'sess' . SWIFT_Interface::INTERFACE_API => 'API',
	'sess' . SWIFT_Interface::INTERFACE_STAFF => 'Operador',
	'sess' . SWIFT_Interface::INTERFACE_ADMIN => 'Administrador',
	'sess' . SWIFT_Interface::INTERFACE_CLIENT => 'Usuario',
	'sess' . SWIFT_Interface::INTERFACE_WINAPP => 'Winapp',
	'sess' . SWIFT_Interface::INTERFACE_CONSOLE => 'Consola',
	'sess' . SWIFT_Interface::INTERFACE_VISITOR => 'Visitante',
	'sess' . SWIFT_Interface::INTERFACE_CHAT => 'Chat',
	'sess' . SWIFT_Interface::INTERFACE_ARCHIVE => 'Archivo',
	'sess' . SWIFT_Interface::INTERFACE_PDA => 'PDA',
	'sess' . SWIFT_Interface::INTERFACE_RSS => 'RSS',
	'sess' . SWIFT_Interface::INTERFACE_SYNCWORKS => 'SyncWorks',
	'sessionlist' => 'Lista de sesiones',
	'ipaddress' => 'Dirección IP',
	'lastactivity' => 'Última vez activo',
	'sessiontype' => 'Tipo sesión',
	'useragent' => 'User Agent',
	'killsession' => 'Cerrar sesión',
	'sessiondelconfirm' => 'Sesión cerrada correctamente',
	'sess' . SWIFT_Interface::INTERFACE_INSTAALERT => 'InstaAlert',
);

?>