<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'insertbreakline' => 'Insertar línea de corte',
	'editbreakline' => 'Editar línea de corte',
	'emailqueues' => 'Colas de email',
	'winviewparserlog' => 'Ver log de procesador de correo',
	'close' => 'Cerrar',
	'titleparserlogdel' => 'Eliminados "%d" logs del procesador',
	'msgparserlogdel' => 'Se han eliminado correctamente las siguientes entradas del log del procesador:',
	'breaklines' => 'Líneas de corte',
	'desc_breaklines' => '',
	'isregexp' => 'Espresión regular?',
	'sortorder' => 'Orden',
	'wineditbreakline' => 'Editar línea de corte',
	'breaklinetitle' => 'Texto de línea de corte',
	'desc_breaklinetitle' => 'Introduzca el texto de línea de corte, todos los emails entrantes se cortarán desde la línea que contiene la línea de corte.',
	'desc_sortorder' => 'Introduzca el orden de las líneas de corte.',
	'isregexp' => 'Es regex?',
	'desc_isregexp' => 'Si está activado el texto de línea de corte de arriba se tratará como una expresión regular.',
	'titleinsertbreakline' => 'Línea de corte insertada',
	'msginsertbreakline' => 'Se ha insertado la línea de corte del procesador en la base de datos.',
	'titleupdatebreakline' => 'Actualizada línea de corte',
	'msgupdatebreakline' => 'Se ha actualizaco correctamente la línea de corte del procesador.',
	'titledelbreakline' => 'Eliminada(s) "%d" Línea(s) de corte',
	'msgdelbreakline' => 'Se han eliminado correctamente las siguientes líneas de corte:',
	'invalidbreakline' => 'Se ha especificado una línea de corte no válida. Por favor, asegúrese de que la línea de corte existe en la base de datos.',
	'tabsettings' => 'Configuración',
	'forcequeue' => 'Forzar encolado en emails entrantes',
	'desc_forcequeue' => 'Si se activa el sistema forzará a todos los emails en la bandeja de entrada a usar la misma cola de la que se estña bajando el correo. Si quiere usar esta cola como repositorio de emails reenviados se recomienda que desactive esta opción.',
	'leavecopyonserver' => 'Dejar copia en el servidor?',
	'desc_leavecopyonserver' => 'Si se activa, el sistema dejará una copia del mensaje en el servidor. Por defecto el sistema vacía la bandeja de entrada una vez que termina el proceso de descarga.<br /><b><font color="red">NOTA:</font></b> Esta opción sólo funciona con cuentas IMAP.',
	'nonssl' => 'No SSL',
	'tls' => 'TLS',
	'ssl' => 'SSL',
	'sslv2' => 'SSL v2',
	'sslv3' => 'SSL v3',
	'usequeuesmtp' => 'Usar servidor SMTP de cola',
	'desc_usequeuesmtp' => 'Si se activa, el servidor mencionado antes se usará para enviar todos los emails relacionados con esta cola. Esto evita que el email se marque como spam.',
	'smtptype' => 'Tipo de SMTP',
	'desc_smtptype' => 'Seleccione el tipo de servidor SMTP.',
	'next' => 'Siguiente',
	'titleinvalidqueueprefix' => 'Prefijo de cola no válido',
	'msginvalidqueueprefix' => 'Por favor, especifique un prefijo de cola válido. Sólo se permiten caracteres alfanuméricos.',
	'titlefailedtocreatequeue' => 'No se ha podido crear la cola',
	'msgfailedtocreatequeue' => 'Imposible crear la cola. Por favor revise la configuración de la base de datos y las opciones de conectividad.',
	'back' => 'Atrás',
	'wineditemailqueue' => 'Editar cola de email',
	'tabticketsettings' => 'Opciones de ticket',
	'tabpop3imap' => 'POP3/IMAP',
	'queueisenabled' => 'Habilitada?',
	'desc_queueisenabled' => 'si está habilitada la cola procesará todos los emails entrantes enviados a la dirección de correo especificada. Deshabilitad la cola rechazará silenciosamente todos los emails entrantes.',
	'titlequeueinsert' => 'Insertada cola de email',
	'msgqueueinsert' => 'Se ha insertado correctamente la cola de email "%s".',
	'titlequeueupdate' => 'Actualizada cola de email',
	'msgqueueupdate' => 'Se ha actualizado correctamente la cola de email "%s".',
	'titledelqueues' => 'Eliminada(s) "%d" cola(s) de email',
	'msgdelqueues' => 'Se ha(n) eliminado la(s) siguiente(s) cola(s) de email:',
	'titlestaffemail' => 'Dirección email no válida',
	'msgstaffemail' => SWIFT_PRODUCT . ' no puede insertar/actualizar la dirección de email de la cola ya que está asignada al operador "%s". Especifique otra dirección para evitar bucles de correo.',
	'verifyconnection' => 'Comprobar conexión',
	'vcvariablesanity' => 'Comprobando información de servidor de cola.',
	'vcimapnotcompiled' => 'PHP no ha sido compilado con soporte IMAP. Los usuarios de *nix deben recompilar PHP con el flag \'--with-imap\' flag; Los usuarios de windows descomentar la línea extension=\'php_imap.dll\' en el archivo php.ini',
	'vcimapcompiled' => 'PHP ha sido compilado con soporte IMAP',
	'vcattemptconnection' => 'Intentando conectar al servidor POP3/IMAP',
	'vcconnectionsuccess' => 'Conexión correcta',
	'vctotalmessages' => 'Mensajes en bandeja de entrada: %d',
	'vcconnectionfailed' => 'Error de conexión con cuenta de correo:<BR />%s',
	'erremailqueuesame' => 'Se ha rechazado el correo ya que la dirección de origen se ha añadido como cola de email',
	// ======= END v4 LOCALES =======

	// ======= BEGIN v3 CVS UPDATE IMPORT =======
	'queue_id_label' => 'ID',
	'managemailqueue' => 'Administrar colas de email',
	'invalidqueueaddress' => 'Debe introducir una dirección de email válida para la cola.',
	'fetchpop3tls' => 'POP3 TLS',
	'fetchimaptls' => 'IMAP TLS',
	'errloopcontrol' => 'Mensaje bloqueado debido a la activación de una regla de control de bucles.',
	'errorlockfilefound' => '[ERROR]: Encontrado archivo de bloqueo! (./files/parser.lockfile). Se ha encontrado un archivo de bloqueo, que impide la ejecución. Si es una instancia de cron inactiva por favor elimine el archivo para continuar. Para eliminar el archivo manualmente por favor <a href="%s">haga click aquí</a>',
	'lockfileexpired' => '[AVISO]: Se ha encontrado un archivo de bloqueo caducado (./files/parser.lockfile) de una sesión previa de cron. Eliminando automáticamente...',
	'errtoobig' => 'Tamaño máximo de mensaje %s excedido; tamaño de mensaje: %s',
	'autorespondernotsent' => ' (Autorrespuesta no enviada debido a configuración actual)',
	// ======= END v3 CVS UPDATE IMPORT =======

	'mailparser' => 'Procesador de correo',
	'desc_mailparser' => '',
	'queuelist' => 'Lista de colas de email',

	'insertemailqueue' => 'Insertar cola de email',
	'queuedetails' => 'Detalles de cola',
	'insertqueue' => 'Insertar cola',
	'queuenextstep' => 'Siguiente &raquo;',
	'emailgeneralfields' => 'Campos de email',
	'emailimapfields' => 'Información de cuenta (necesaria solo si se selecciona POP3/IMAP)',
	'emailaddress' => 'Dirección de email de cola',
	'desc_emailaddress' => 'Introduzca una dirección de email válida para la cola Ejemplo: soporte@dominio.com',
	'emailtype' => 'Tipo de cola',
	'desc_emailtype' => '',
	'emailfetchtype' => 'Tipo de recuperación',
	'desc_emailfetchtype' => 'Especifique como recuperará el correo el procesador de email. Cualquier opción que no sea <i>Pipe</i> requiere servidor, usuario y contraseña.',
	'fetchpipe' => 'Pipe',
	'fetchpop3' => 'POP3',
	'fetchpop3ssl' => 'POP3 SSL',
	'fetchimap' => 'IMAP',
	'fetchimapssl' => 'IMAP SSL',
	'emailhost' => 'Servidor',
	'desc_emailhost' => 'Introduzca el nombre o IP del servidor de correo. Por ejemplo <i>mail.dominio.com</i>.',
	'emailport' => 'Puerto',
	'desc_emailport' => 'Especifique el puerto del servidor de correo. Se recomienda que este valor no se cambie a no ser que el servidor esté funcionando en un puerto diferente del puerto por defecto.',
	'emailusername' => 'Usuario',
	'desc_emailusername' => 'Introduzca el usuario del servidor de correo.',
	'emailpassword' => 'Contraseña',
	'desc_emailpassword' => 'Introduzca la contraseña del servidor de correo.',

	'queueoverrides' => 'Anulaciones de cola (Opcional)',
	'queuefromname' => 'Nombre remitente',
	'desc_queuefromname' => 'Si se especifica, todos los emails salientes de esta cola tendrán este nombre como <i>nombre del remitente</i>.',
	'queuefromemail' => 'Email remitente',
	'desc_queuefromemail' => 'Si se especifica, todos los emails salientes de esta cola tendrán este email como <i>email remitente</i>.',

	'queuesettings' => 'Configuración de cola',
	'templategroup' => 'Grupo de plantillas de cola',
	'desc_templategroup' => 'Seleccione el grupo de plantillas de la cola. La configuración y plantillas de este crupo de plantillas se usarán para la nueva cola.',
	'queuesignature' => 'Firma de cola (Opcional)',
	'desc_queuesignature' => 'Introduzca la firma de la cola. Esta firma se añadirá a todos los emails salientes en esta cola.',
	'registrationrequired' => 'Necesario registro?',
	'desc_registrationrequired' => 'Si se activa, solo usuarios <b>registrados</b> podrán crear nuevos tickets enviando un mensaje a esta dirección de email de cola. Los usuarios no registrados podrán enviar tickets a través del Centro de Soporte.',
	'issueautoresponder' => 'Enable New Issue Autoresponder?',
	'desc_issueautoresponder' => 'If enabled, the system will send an Autoresponder message confirming the receipt of a new issue.',
	'replyautoresponder' => 'Enable New Reply Autoresponder?',
	'desc_replyautoresponder' => 'If enabled, the system will send an Autoresponder message confirming the receipt of a new reply under an already existing issue.',

	'ticketfields' => 'Ticket Fields',
	'queuedepartment' => 'Department',
	'desc_queuedepartment' => 'Specify the department under which new tickets will be created.',
	'queuetickettype' => 'Ticket Type',
	'desc_queuetickettype' => 'Select the ticket type for this queue. Any new tickets created under this queue will be set to the specified ticket type.',
	'queueticketstatus' => 'Ticket Status',
	'desc_queueticketstatus' => 'Select the ticket status for this queue. Any new tickets under this queue will be created using this status',
	'queuepriority' => 'Ticket Priority',
	'desc_queuepriority' => 'Select the ticket priority for this queue. This is not related to the "Priority" of an incoming email. Any new tickets created under this queue will be assigned the selected priority.',
	'failedtocreatequeue' => 'ERROR: Failed to create email queue',
	'redirect_queueinsert' => 'Email queue inserted successfully.',
	'queueinsertconfirm' => 'Email queue "%s" inserted successfully',
	'depdeleteconfirm' => 'Email queue "%s" deleted successfully',
	'invalidemailqueue' => 'Invalid email queue specified',
	'editemailqueue' => 'Edit Email Queue',
	'emailqueues' => 'Email Queues',
	'queueupdconfirm' => 'Email queue "%s" updated successfully',
	'invalidparserlog' => 'Invalid parser log entry. Make sure that the parser log entry exists in the database and has not been deleted.',
	'desc_parserlog' => 'The mail parser logs all incoming email under the log with useful information to help debug any problems. To disable the logging of email or change other settings, navigate to <i>Settings > Mail Parser</i>.',
	'desc_mailparser' => 'The mail parser is a crucial component of '. SWIFT_PRODUCT .'. It includes some powerful features like parser rules, catch-all rules, breaklines, and banning to simplify your workflow. The mail parser uses email queues to associate different information with a department and to find out which department an incoming email should be routed to. For more information, please refer to the Mail Parser section of the user manual.',
	'queueprefix' => 'Queue Subject Prefix (Optional)',
	'desc_queueprefix' => 'If specified, all mail subjects under this queue will be prefixed with the specified value. For example, if you specify the queue prefix as <i>SUPPORT</i> the outgoing email subject for staff replies will be: <i>[SUPPORT #ABC-12345]: Actual Subject</i>',
	'invalidqueueprefix' => 'Invalid queue prefix; only alphanumeric characters (e.g. A-Z, 0-9) and spaces are allowed.',

	'titleenablequeues' => 'Enabled "%d" Email Queue(s)',
	'msgenablequeues' => SWIFT_PRODUCT . ' has successfully enabled the following email queue(s):',
	'titledisablequeues' => 'Disabled "%d" Email Queue(s)',
	'msgdisablequeues' => SWIFT_PRODUCT . ' has successfully disabled the following email queue(s):',

	// View Parser Log
	'viewparserlog' => 'View Parser Log',
	'parserlogentry' => 'Parser Log #%s',
	'generalinformation' => 'General Information',
	'mimedata' => 'MIME Data',
	'ppticketid' => 'Ticket ID: ',
	'ppticketmaskid' => 'Ticket Mask ID: ',
	'ppdate' => 'Date: ',
	'pptimeline' => 'Timeline: ',
	'ppemailqueue' => 'Email Queue: ',
	'ppstatus' => 'Process Status: ',
	'ppsubject' => 'Subject: ',
	'ppfromemail' => 'From Email: ',
	'pptoemail' => 'Destination Email: ',
	'ppsize' => 'Size: ',
	'pptimetaken' => 'Time Taken: ',
	'ppdesc' => 'Description: ',
	'ppresult' => 'Result',
	'pparserlogid' => 'Parser Log ID: ',

	// Parser Log
	'parserlog' => 'Parser Log',
	'parserlogs' => 'Parser Logs',
	'emailsubject' => 'Email Subject',
	'emailsubjectresult' => 'Email Subject & Result',
	'emailstatus' => 'Status',
	'emailsubresultformat' => '%s<BR /><B>Result:</B> %s',
	'emailparsetime' => 'Parse Time',
	'emailfrom' => '"From:" Email',
	'emailto' => '"To:" Email',
	'emaildescription' => 'Description',
	'emailticketid' => 'Ticket/Bug ID',
	'emailticketmaskid' => 'Ticket Mask ID',
	'emailcontents' => 'Email Contents',

	'nosubject' => '(No Subject)',


	// Breaklines
	'breaklines' => 'Breaklines',
	'desc_breaklines' => 'The Breakline feature in '. SWIFT_PRODUCT .' prevents the addition of previously quoted content in an email. '. SWIFT_PRODUCT .' will strip the entire text that follows the breakline. This helps keep the content of the incoming email "clean." If the Reply Content is ever empty, the entire message is stored in the database. Example:<BR /><BR /><b>Original Email:</b><BR />Reply Content<BR />-----Original Message-----<BR />Quoted Message<BR /><BR /><b>Result:</b><BR />Reply Content<BR /><BR />',
	'breaklinelist' => 'Breakline List',
	'breakline' => 'Breakline',
	'insertbreakline' => 'Insert Breakline',
	'desc_breakline' => 'Enter the contents of the breakline you wish to insert.<BR /><BR />Note: To use regular expressions, prepend your breakline with "regex:"<BR />Example: <i>"regex:@[-=]{4,}[^-=]+[-=]{4,}@"</i>',
	'breaklinedelconfirm' => 'Breakline deleted successfully',
	'breaklineinsertconfirm' => 'Breakline inserted successfully',

	// Parser Errors
	'errnorecipients' => 'No recipients found',
	'errnofromemail' => 'No from email specified',
	'errnoqueues' => 'No assigned queues found for mail recipients',
	'errfloodprotection' => 'Flood Protection Triggered',
	'scccreatedticket' => 'Created ticket #%s',
	'scccreatedreply' => 'Created reply #%s to ticket #%s',
	'sctcreatedreply' => 'Created reply from third party #%s to ticket #%s',
	'scccreatedstaffreply' => 'Created staff reply #%s to ticket #%s',
	'clearedduelimit' => '-- MIME data cleared due to the size limit under Settings > Parser --',
	'errusernotreg' => 'User %s is not registered. The queue settings require that the user be registered.',
	'erremailbanned' => 'User email address is banned',
	'actionrepprefix' => 'Re: ',

	// Misc
	'reprocessemail' => 'Reprocess Email',

	// Loop Cutter
	'pr_loopcutter_prevents_autoresponder_desc' => ' (Autoresponder not sent due to loop control)',
	'pr_mangelooprules' => 'Loop Rules',
	'pr_loopcontrolrules' => 'Loop Control Rules',
	'pr_manageloopblockages' => 'Loop Blockages',
	'pr_loopblockages' => 'Loop Blockages',
	'pr_insert_new_loopcutter_rule_title' => 'Insert Loop Control Rule',
	'pr_edit_new_loopcutter_rule_title' => 'Edit Loop Control Rule',
	'pr_threshhold_grid_timeframe_title' => 'Timeframe',
	'pr_threshhold_grid_maxhits_title' => 'Max Hits',
	'pr_threshhold_grid_restoreafter_title' => 'Restore After',
	'pr_threshhold_grid_address_title' => 'Address',
	'pr_new_loop_control_header_text' => 'New Loop Control',
	'pr_newloopcontrolwatchlength_title' => 'Watching Timeframe',
	'pr_newloopcontrolwatchlength_desc' => 'This is the length of the timeframe that the loop blocker considers, measured in seconds.',
	'pr_newloopcontrolmaxcontacts_title' => 'Maximum Contacts',
	'pr_newloopcontrolmaxcontacts_desc' => 'This is the number of emails sent which will trigger a loop block.',
	'pr_newloopcontrolrestoreafter_title' => 'Restore After',
	'pr_newloopcontrolrestoreafter_desc' => 'This is the amount of time after which a loop block will be automatically removed, measured in seconds.',
	'pr_new_loop_control_rule_added_desc' => 'New loop control rule added.',
	'pr_desc_loopblockages_filler' => 'Below is a list of active loop blockages.  The addresses listed here triggered one or more loop control rules (<i>Mail Parser >> Manage Loop Rules</i>).  Depending on the active settings (<i>Settings >> Mail Parser >> Loop Control Settings</i>), incoming email from these addresses may be completely ignored by ' . SWIFT_PRODUCT . ' and an autoresponder message may not be sent.  These settings will be in effect for each blockage until it expires.',
	'pr_desc_looprules_filler' => 'Below is a list of loop control rules.  These rules prevent autoresponder loops or other email flood situations and all incoming email messages are subjected to them.  If a rule is triggered, the settings (<i>Settings >> Mail Parser >> Loop Control Settings</i>) are applied.  This allows ' . SWIFT_PRODUCT . ' to completely ignore the message and/or not reply with an autoresponder message.  Blockages created by these rules are automatically removed after the specified timeframe.',
	'pr_loop_rule_deleted' => 'Rule deleted.',
	'pr_loop_block_deleted' => 'Blockage deleted.',
	'invalidlooprule' => 'Invalid Loop Cutter Rule. Please make sure the record exists in the database.',
	'wineditloopcutterrule' => 'Edit Loop Cutter Rule',
	'pr_threshhold_grid_title' => 'Threshold Rule Title',
	'thresholdruletitle' => 'Loop Rule Title',
	'desc_thresholdruletitle' => 'Enter your Loop Rule title',
	'titledelloopblock' => 'Deleted "%d" Loop Blockage(s)',
	'msgdelloopblock' => 'Successfully deleted the following Loop Blockage(s) from the database:',
	'titledellooprule' => 'Deleted "%d" Loop Rule(s)',
	'msgdellooprule' => 'Successfully deleted the following Loop Rule(s) from the database:',
	'titleinsertlooprule' => 'Inserted Loop Rule',
	'msginsertlooprule' => 'Successfully inserted the Loop Rule into the database:',
	'titleupdatelooprule' => 'Updated Loop Rule',
	'msgupdatelooprule' => 'Successfully updated the Loop Rule:',
	'titlelooprulemasterdel' => 'Unable to delete master loop rule(s)',
	'msglooprulemasterdel' => SWIFT_PRODUCT . ' is unable to delete the following master loop rule(s):',
);
?>