<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'insertbreakline' => 'Insertar línea de corte',
	'editbreakline' => 'Editar línea de corte',
	'emailqueues' => 'Colas de email',
	'winviewparserlog' => 'Ver log de Procesador de correo',
	'close' => 'Cerrar',
	'titleparserlogdel' => 'Eliminados "%d" logs del Procesador',
	'msgparserlogdel' => 'Se han eliminado correctamente las siguientes entradas del log del Procesador:',
	'breaklines' => 'Líneas de corte',
	'desc_breaklines' => '',
	'isregexp' => 'Espresión regular?',
	'sortorder' => 'Orden',
	'wineditbreakline' => 'Editar línea de corte',
	'breaklinetitle' => 'Texto de línea de corte',
	'desc_breaklinetitle' => 'Introduzca el texto de línea de corte, todos los emails entrantes se cortarán desde la línea que contiene la línea de corte.',
	'desc_sortorder' => 'Introduzca el orden de las líneas de corte.',
	'isregexp' => 'Es regex?',
	'desc_isregexp' => 'Si está activado el texto de línea de corte de arriba se tratará como una expresión regular.',
	'titleinsertbreakline' => 'Línea de corte insertada',
	'msginsertbreakline' => 'Se ha insertado la línea de corte del Procesador en la base de datos.',
	'titleupdatebreakline' => 'Actualizada línea de corte',
	'msgupdatebreakline' => 'Se ha actualizaco correctamente la línea de corte del Procesador.',
	'titledelbreakline' => 'Eliminada(s) "%d" Línea(s) de corte',
	'msgdelbreakline' => 'Se han eliminado correctamente las siguientes líneas de corte:',
	'invalidbreakline' => 'Se ha especificado una línea de corte no válida. Por favor, asegúrese de que la línea de corte existe en la base de datos.',
	'tabsettings' => 'Configuración',
	'forcequeue' => 'Forzar encolado en emails entrantes',
	'desc_forcequeue' => 'Si se activa el sistema forzará a todos los emails en la bandeja de entrada a usar la misma cola de la que se estña bajando el correo. Si quiere usar esta cola como repositorio de emails reenviados se recomienda que desactive esta opción.',
	'leavecopyonserver' => 'Dejar copia en el servidor?',
	'desc_leavecopyonserver' => 'Si se activa, el sistema dejará una copia del mensaje en el servidor. Por defecto el sistema vacía la bandeja de entrada una vez que termina el proceso de descarga.<br /><b><font color="red">NOTA:</font></b> Esta opción sólo funciona con cuentas IMAP.',
	'nonssl' => 'No SSL',
	'tls' => 'TLS',
	'ssl' => 'SSL',
	'sslv2' => 'SSL v2',
	'sslv3' => 'SSL v3',
	'usequeuesmtp' => 'Usar servidor SMTP de cola',
	'desc_usequeuesmtp' => 'Si se activa, el servidor mencionado antes se usará para enviar todos los emails relacionados con esta cola. Esto evita que el email se marque como spam.',
	'smtptype' => 'Tipo de SMTP',
	'desc_smtptype' => 'Seleccione el tipo de servidor SMTP.',
	'next' => 'Siguiente',
	'titleinvalidqueueprefix' => 'Prefijo de cola no válido',
	'msginvalidqueueprefix' => 'Por favor, especifique un prefijo de cola válido. Sólo se permiten caracteres alfanuméricos.',
	'titlefailedtocreatequeue' => 'No se ha podido crear la cola',
	'msgfailedtocreatequeue' => 'Imposible crear la cola. Por favor revise la configuración de la base de datos y las opciones de conectividad.',
	'back' => 'Atrás',
	'wineditemailqueue' => 'Editar cola de email',
	'tabticketsettings' => 'Opciones de ticket',
	'tabpop3imap' => 'POP3/IMAP',
	'queueisenabled' => 'Habilitada?',
	'desc_queueisenabled' => 'si está habilitada la cola procesará todos los emails entrantes enviados a la dirección de correo especificada. Deshabilitad la cola rechazará silenciosamente todos los emails entrantes.',
	'titlequeueinsert' => 'Insertada cola de email',
	'msgqueueinsert' => 'Se ha insertado correctamente la cola de email "%s".',
	'titlequeueupdate' => 'Actualizada cola de email',
	'msgqueueupdate' => 'Se ha actualizado correctamente la cola de email "%s".',
	'titledelqueues' => 'Eliminada(s) "%d" cola(s) de email',
	'msgdelqueues' => 'Se ha(n) eliminado la(s) siguiente(s) cola(s) de email:',
	'titlestaffemail' => 'Dirección email no válida',
	'msgstaffemail' => SWIFT_PRODUCT . ' no puede insertar/actualizar la dirección de email de la cola ya que está asignada al operador "%s". Especifique otra dirección para evitar bucles de correo.',
	'verifyconnection' => 'Comprobar conexión',
	'vcvariablesanity' => 'Comprobando información de servidor de cola.',
	'vcimapnotcompiled' => 'PHP no ha sido compilado con soporte IMAP. Los usuarios de *nix deben recompilar PHP con el flag \'--with-imap\' flag; Los usuarios de windows descomentar la línea extension=\'php_imap.dll\' en el archivo php.ini',
	'vcimapcompiled' => 'PHP ha sido compilado con soporte IMAP',
	'vcattemptconnection' => 'Intentando conectar al servidor POP3/IMAP',
	'vcconnectionsuccess' => 'Conexión correcta',
	'vctotalmessages' => 'Mensajes en bandeja de entrada: %d',
	'vcconnectionfailed' => 'Error de conexión con cuenta de correo:<BR />%s',
	'erremailqueuesame' => 'Se ha rechazado el correo ya que la dirección de origen se ha añadido como cola de email',
	// ======= END v4 LOCALES =======

	// ======= BEGIN v3 CVS UPDATE IMPORT =======
	'queue_id_label' => 'ID',
	'managemailqueue' => 'Administrar colas de email',
	'invalidqueueaddress' => 'Debe introducir una dirección de email válida para la cola.',
	'fetchpop3tls' => 'POP3 TLS',
	'fetchimaptls' => 'IMAP TLS',
	'errloopcontrol' => 'Mensaje bloqueado debido a la activación de una regla de control de bucles.',
	'errorlockfilefound' => '[ERROR]: Encontrado archivo de bloqueo! (./files/parser.lockfile). Se ha encontrado un archivo de bloqueo, que impide la ejecución. Si es una instancia de cron inactiva por favor elimine el archivo para continuar. Para eliminar el archivo manualmente por favor <a href="%s">haga click aquí</a>',
	'lockfileexpired' => '[AVISO]: Se ha encontrado un archivo de bloqueo caducado (./files/parser.lockfile) de una sesión previa de cron. Eliminando automáticamente...',
	'errtoobig' => 'Tamaño máximo de mensaje %s excedido; tamaño de mensaje: %s',
	'autorespondernotsent' => ' (Autorrespuesta no enviada debido a configuración actual)',
	// ======= END v3 CVS UPDATE IMPORT =======

	'mailparser' => 'Procesador de correo',
	'desc_mailparser' => '',
	'queuelist' => 'Lista de colas de email',

	'insertemailqueue' => 'Insertar cola de email',
	'queuedetails' => 'Detalles de cola',
	'insertqueue' => 'Insertar cola',
	'queuenextstep' => 'Siguiente &raquo;',
	'emailgeneralfields' => 'Campos de email',
	'emailimapfields' => 'Información de cuenta (necesaria solo si se selecciona POP3/IMAP)',
	'emailaddress' => 'Dirección de email de cola',
	'desc_emailaddress' => 'Introduzca una dirección de email válida para la cola Ejemplo: soporte@dominio.com',
	'emailtype' => 'Tipo de cola',
	'desc_emailtype' => '',
	'emailfetchtype' => 'Tipo de recuperación',
	'desc_emailfetchtype' => 'Especifique como recuperará el correo el Procesador de email. Cualquier opción que no sea <i>Pipe</i> requiere servidor, usuario y contraseña.',
	'fetchpipe' => 'Pipe',
	'fetchpop3' => 'POP3',
	'fetchpop3ssl' => 'POP3 SSL',
	'fetchimap' => 'IMAP',
	'fetchimapssl' => 'IMAP SSL',
	'emailhost' => 'Servidor',
	'desc_emailhost' => 'Introduzca el nombre o IP del servidor de correo. Por ejemplo <i>mail.dominio.com</i>.',
	'emailport' => 'Puerto',
	'desc_emailport' => 'Especifique el puerto del servidor de correo. Se recomienda que este valor no se cambie a no ser que el servidor esté funcionando en un puerto diferente del puerto por defecto.',
	'emailusername' => 'Usuario',
	'desc_emailusername' => 'Introduzca el usuario del servidor de correo.',
	'emailpassword' => 'Contraseña',
	'desc_emailpassword' => 'Introduzca la contraseña del servidor de correo.',

	'queueoverrides' => 'Anulaciones de cola (Opcional)',
	'queuefromname' => 'Nombre remitente',
	'desc_queuefromname' => 'Si se especifica, todos los emails salientes de esta cola tendrán este nombre como <i>nombre del remitente</i>.',
	'queuefromemail' => 'Email remitente',
	'desc_queuefromemail' => 'Si se especifica, todos los emails salientes de esta cola tendrán este email como <i>email remitente</i>.',

	'queuesettings' => 'Configuración de cola',
	'templategroup' => 'Grupo de plantillas de cola',
	'desc_templategroup' => 'Seleccione el grupo de plantillas de la cola. La configuración y plantillas de este crupo de plantillas se usarán para la nueva cola.',
	'queuesignature' => 'Firma de cola (Opcional)',
	'desc_queuesignature' => 'Introduzca la firma de la cola. Esta firma se añadirá a todos los emails salientes en esta cola.',
	'registrationrequired' => 'Necesario registro?',
	'desc_registrationrequired' => 'Si se activa, solo usuarios <b>registrados</b> podrán crear nuevos tickets enviando un mensaje a esta dirección de email de cola. Los usuarios no registrados podrán enviar tickets a través del Centro de Soporte.',
	'issueautoresponder' => 'Activar autorrespuesta nuevo ticket?',
	'desc_issueautoresponder' => 'Si está activado, el sistema enviará un mensaje confirmando la recepción de un nuevo ticket.',
	'replyautoresponder' => 'Activar autorrespuesta nueva respuesta?',
	'desc_replyautoresponder' => 'Si está activado, el sistema enviará un mensaje confirmando la recepción de una nueva respuesta a un ticket existente.',

	'ticketfields' => 'Campos de ticket',
	'queuedepartment' => 'Departamento',
	'desc_queuedepartment' => 'Especifique el departamento en el que se crearán los nuevos tickets.',
	'queuetickettype' => 'Tipo de tickets',
	'desc_queuetickettype' => 'Seleccione el tipo de ticket para esta cola. Este será el tipo de los nuevos tickets creados en esta cola.',
	'queueticketstatus' => 'Estado de tickets',
	'desc_queueticketstatus' => 'Seleccione el estado de ticket para esta cola. Este será el estado de los nuevos tickets creados en esta cola',
	'queuepriority' => 'Prioridad de tickets',
	'desc_queuepriority' => 'Seleccione la prioridad de ticket para esta cola. Esta será la prioridad de los nuevos tickets creados en esta cola.',
	'failedtocreatequeue' => 'ERROR: No se ha podido crear la cola de email',
	'redirect_queueinsert' => 'Cola de email insertada correctamente.',
	'queueinsertconfirm' => 'Cola de email "%s" insertada correctamente',
	'depdeleteconfirm' => 'Cola de email "%s" eliminada correctamente',
	'invalidemailqueue' => 'Se ha especificado una cola de email no válida',
	'editemailqueue' => 'Editar cola de email',
	'emailqueues' => 'Colas de email',
	'queueupdconfirm' => 'Cola de email "%s" actualizada correctamente',
	'invalidparserlog' => 'Entrada de log de Procesador no válida. Asegúrese de que la entrada de log existe en la base de datos y no ha sido eliminada.',
	'desc_parserlog' => 'El Procesador registra todo el mail entrante con información útil para ayudar a depurar problemas. Para deshabilitar el log de email o cambiar la configuración vaya a <i>Configuración > Procesador de correo</i>.',
	'desc_mailparser' => 'El Procesador de correo es un componente crucial de '. SWIFT_PRODUCT .'. Incluye características muy potentes como reglas de procesamiento, reglas Recoge-Todo, líneas de corte y bloqueos para simplificar su trabajo. El Procesador de correo usa colas de correo para asociar diferente información con un departamento y determinar a qué departamento debería enrutarse el email entrante. Para más información consulte a la sección de Procesador de Correo en el manual del usuario.',
	'queueprefix' => 'Prefijo de asunto de cola (Opcional)',
	'desc_queueprefix' => 'Si se especifica, se añadirá este prefijo a todos los asuntos de correos en esta cola. Por ejemplo, si se especifica <i>SOPORTE</i>, el asunto de emails salientes de respuestas de operadores será: <i>[SOPORTE #ABC-12345]: Asunto actual</i>',
	'invalidqueueprefix' => 'Prefijo de cola no válido; sólo se permiten caracteres alfanuméricos (p.ej. A-Z, 0-9) y espacios.',

	'titleenablequeues' => 'Activada(s) "%d" cola(s) de email',
	'msgenablequeues' => SWIFT_PRODUCT . ' ha activado correctamente la(s) siguiente(s) cola(s) de email:',
	'titledisablequeues' => 'Desactivada(s) "%d" cola(s) de email',
	'msgdisablequeues' => SWIFT_PRODUCT . ' ha desactivado correctamente la(s) siguiente(s) cola(s) de email',

	// View Parser Log
	'viewparserlog' => 'Ver log del Procesador',
	'parserlogentry' => 'Log de Procesador #%s',
	'generalinformation' => 'Información general',
	'mimedata' => 'Datos MIME',
	'ppticketid' => 'ID Ticket: ',
	'ppticketmaskid' => 'ID Máscara ticket: ',
	'ppdate' => 'Fecha: ',
	'pptimeline' => 'Línea tiempo: ',
	'ppemailqueue' => 'Cola Email: ',
	'ppstatus' => 'Estado Proceso: ',
	'ppsubject' => 'Asunto: ',
	'ppfromemail' => 'Email remitente: ',
	'pptoemail' => 'Email destinatario: ',
	'ppsize' => 'Tamaño: ',
	'pptimetaken' => 'Tiempo proceso: ',
	'ppdesc' => 'Descripción: ',
	'ppresult' => 'Resultado',
	'pparserlogid' => 'ID log Procesador: ',

	// Parser Log
	'parserlog' => 'Log de Procesador',
	'parserlogs' => 'Logs del Procesador',
	'emailsubject' => 'Asunto del email',
	'emailsubjectresult' => 'Asunto email y resultado',
	'emailstatus' => 'Estado',
	'emailsubresultformat' => '%s<BR /><B>Resultado:</B> %s',
	'emailparsetime' => 'Tiempo de proceso',
	'emailfrom' => '"De:" Email',
	'emailto' => '"Para:" Email',
	'emaildescription' => 'Descripción',
	'emailticketid' => 'ID Ticket/Bug',
	'emailticketmaskid' => 'ID Máscara Ticket',
	'emailcontents' => 'Contenido Email',

	'nosubject' => '(Sin asunto)',


	// Breaklines
	'breaklines' => 'Líneas de corte',
	'desc_breaklines' => 'La función de línea de corte de '. SWIFT_PRODUCT .' evita la adición de contenido previamente citado en un email. '. SWIFT_PRODUCT .' eliminará todo el texto que haya detrás de la línea de corte. Esto ayuda a mantener limpio el contenido del correo entrante. Ejemplo:<BR /><BR /><b>Email original:</b><BR />Contenido de la respuesta<BR />-----Mensaje Original-----<BR />Mensaje citado<BR /><BR /><b>Resultado:</b><BR />Contenido de la respuesta<BR /><BR />',
	'breaklinelist' => 'Lista de líneas de corte',
	'breakline' => 'Línea de corte',
	'insertbreakline' => 'Insertar línea de corte',
	'desc_breakline' => 'Introduzca la línea de corte que desea insertar.<BR /><BR />Nota: Para usar expresiones escriba "regex:" antes de la línea de corte<BR />Ejemplo: <i>"regex:@[-=]{4,}[^-=]+[-=]{4,}@"</i>',
	'breaklinedelconfirm' => 'Línea de corte eliminada correctamente',
	'breaklineinsertconfirm' => 'Línea de corte insertada correctamente',

	// Parser Errors
	'errnorecipients' => 'No se han encontrado destinatarios',
	'errnofromemail' => 'No se ha especificado email remitente',
	'errnoqueues' => 'No se han encontrado colas asignadas para los destinatarios',
	'errfloodprotection' => 'Protección contra flood activada',
	'scccreatedticket' => 'Creado ticket #%s',
	'scccreatedreply' => 'Creada respuesta #%s al ticket #%s',
	'sctcreatedreply' => 'Creada respuesta de tercero #%s al ticket #%s',
	'scccreatedstaffreply' => 'Creada respuesta de operador #%s al ticket #%s',
	'clearedduelimit' => '-- datos MIME borrados debido al límite de tamaño establecido en Configuración > Procesador --',
	'errusernotreg' => 'El usuario %s no está registrado. La configuración de la cola exige que lo esté.',
	'erremailbanned' => 'Dirección de email bloqueada',
	'actionrepprefix' => 'Re: ',

	// Misc
	'reprocessemail' => 'Reprocesar email',

	// Loop Cutter
	'pr_loopcutter_prevents_autoresponder_desc' => ' (Autorrespuesta no enviada debido a control de bucles)',
	'pr_mangelooprules' => 'Reglas de bucles',
	'pr_loopcontrolrules' => 'Reglas de control de bucles',
	'pr_manageloopblockages' => 'Bloqueos de bucles',
	'pr_loopblockages' => 'Bloqueos de bucles',
	'pr_insert_new_loopcutter_rule_title' => 'Insertar regla de control de bucles',
	'pr_edit_new_loopcutter_rule_title' => 'Editar regla de control de bucles',
	'pr_threshhold_grid_timeframe_title' => 'Marco de tiempo',
	'pr_threshhold_grid_maxhits_title' => 'Max impactos',
	'pr_threshhold_grid_restoreafter_title' => 'Restaurar tras',
	'pr_threshhold_grid_address_title' => 'Dirección',
	'pr_new_loop_control_header_text' => 'Nuevo control de bucles',
	'pr_newloopcontrolwatchlength_title' => 'Tiempo de observación',
	'pr_newloopcontrolwatchlength_desc' => 'Esta es la longitud del marco de tiempo que el bloqueador de bucles tiene en cuenta, medido en segundos.',
	'pr_newloopcontrolmaxcontacts_title' => 'Máximos contactos',
	'pr_newloopcontrolmaxcontacts_desc' => 'Este es el número de emails enviados que activará el bloqueo.',
	'pr_newloopcontrolrestoreafter_title' => 'Restaurar tras',
	'pr_newloopcontrolrestoreafter_desc' => 'Es el tiempo tras el que se eliminará el bloqueo, en segundos.',
	'pr_new_loop_control_rule_added_desc' => 'Añadida nueva regla de control de bucles.',
	'pr_desc_loopblockages_filler' => 'A continuación hay una lista de bloqueos activos. Las direcciones de la lista activaron una o más reglas de control de bucles (<i>Procesador de correo >> Administrar reglas de bucles</i>).  Dependiendo de la configuración activa (<i>Configuración >> Procesador de correo >> Configuración de control de bucles</i>), el correo entrante desde estas direcciones será ignorado por ' . SWIFT_PRODUCT . ' y no se les enviarán mensajes de autorrespuesta.  Esta configuración será efectiva para cada bloqueo hasta que caduque.',
	'pr_desc_looprules_filler' => 'A continuación hay una lista de reglas de control de bucles. Estas reglas impiden que se produzcan bucles de autorrespuesta u otras situaciones de flood de correo y todos los emails entrantes están sujetos a ellas. Si se activa una regla, la configuración (<i>Configuración >> Procesador de correo >> Configuración de control de bucles</i>) se aplicará. Esto permite que ' . SWIFT_PRODUCT . ' ignore los mensajes y/o no responda con una autorrespuesta. Los bloqueos creados por estas reglas se eliminan automáticamente tras un tiempo especificado.',
	'pr_loop_rule_deleted' => 'Regla eliminada.',
	'pr_loop_block_deleted' => 'Bloqueo eliminado.',
	'invalidlooprule' => 'Regla de corte de bucles no válida. Asegúrese de que el registro existe en la base de datos.',
	'wineditloopcutterrule' => 'Editar regla de corte de bucles',
	'pr_threshhold_grid_title' => 'Nombre de umbral de regla',
	'thresholdruletitle' => 'Nombre de regla de bucles',
	'desc_thresholdruletitle' => 'Introduzca el nombre de la regla de bucles',
	'titledelloopblock' => 'Eliminado(s) "%d" bloqueo(s) de bucle',
	'msgdelloopblock' => 'Se han eliminado correctamente los siguientes bloqueos de bucle:',
	'titledellooprule' => 'Eliminada(s) "%d" regla(s) de bucle',
	'msgdellooprule' => 'Se han eliminado correctamente las siguientes reglas de bucle:',
	'titleinsertlooprule' => 'Insertada regla de bucle',
	'msginsertlooprule' => 'Se ha insertado correctamente la regla de bucle:',
	'titleupdatelooprule' => 'Regla de bucle actualizada',
	'msgupdatelooprule' => 'Se ha actualizado correctamente la regla de bucle:',
	'titlelooprulemasterdel' => 'Imposible eliminar regla(s) de bucle maestra(s)',
	'msglooprulemasterdel' => SWIFT_PRODUCT . ' no puede eliminar la(s) siguiente(s) regla(s) maestra(s):',
);
?>