<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

/**
* ###############################################
* Setting Groups, Items and other text.
* Descript Text Example: d_startofweek or d_general
* ###############################################
*/

$__LANG = array (
	'settings' => 'Configuración',
	'desc_settings' => 'Desde aquí puede administrar toda la configuración de funcionamiento y los ajustes generales del sistema.',
	'systemsettings' => 'Configuración del sistema',
	'loginsharesettings' => 'Configuración LoginShare',
	'staff' => 'Operadores',
	'users' => 'Usuarios',
	'restapi' => 'API REST',
	'reports' => 'Informes',
	'groups' => 'Grupos',
	'settingsfor' => 'Configuración de: %s',
	'updatesettings' => 'Actualizar configuración',
	'settingsupdatedfor' => 'Actualizada configuración del grupo "%s"',
	'titleurlinvaliddata' => 'Datos no válidos',
	'desc_titleurlinvaliddata' => SWIFT_PRODUCT . ' no puede actualizar el campo de URL ya que contiene datos con formato incorrecto.',

	// ======= SETTING GROUPS =======
	'settings_general' => 'General',
	'settings_cpu' => 'Servidor y Optimización CPU',
	'settings_security' => 'Seguridad',
	'settings_datetime' => 'Fecha y hora',
	'settings_livesupport' => 'Chat',
	'settings_tickets' => 'Tickets',
	'settings_parser' => 'Procesador de correo',
	'settings_tr' => 'Asistente',
	'settings_users' => 'Usuarios y Organizaciones',
	'settings_nw' => 'Noticias',
	'settings_dl' => 'Descargas',
	'settings_kb' => 'Biblioteca',
	'settings_tw' => 'Trabajo en equipo',
	'settings_ringroute' => 'RingRoute',
	'settings_mail' => 'Configuración email',
	'settings_livechat' => 'Chat',
	'settings_loginshare' => 'LoginShare',
	'settings_onsite' => 'OnSite',
	'settings_reports' => 'Informes',

	// ======= IMPORT FROM v3 CVS =======
	'g_whmcstgroup' => 'Grupo de plantillas WHMCS',
	'd_g_whmcstgroup' => 'Seleccione el grupo de plantillas por defecto para la integración con WHMCS. Este grupo invalidará el grupo de plantillas por defecto. Podrá mostrar un grupo de plantillas diferente cuando ' . SWIFT_PRODUCT . ' se use vía WHMCS y otro cuando se acceda normalmente.',
	'g_supportcenter' => 'Configuración Centro de Soporte',
	'g_returnlogout' => 'Al cerrar sesión volver al grupo de plantillas por defecto',
	'd_g_returnlogout' => 'Redirige al usuario al grupo de plantillas por defecto tras cerrar la sesión.',
	'g_overrideswiftpath' => 'Anular las variables $swiftpath y $themepath automáticamente',
	'd_g_overrideswiftpath' => 'Si se activa, el sistema intentará determinar las variables de plantilla $swiftpath y $themepath por la URL. Esto le permite crear instalaciones de helpdesk multipunto usando una sola base de datos.',
	'dt_timezonephp' => 'Zona horaria',
	'd_dt_timezonephp' => 'La zona horaria por defecto del sistema. Los operadores tienen la opción de anular esta zona horaria para reflejar la suya propia (a travñes de las Preferencias de Operadores en el Panel de Control de Operadores).',
	'livesupport_usehttps' => 'Usar siempre conexión segura (https) para los chats',
	'd_livesupport_usehttps' => 'Si está activado, todas las sesiones de chat se transportarán por https.',
	'pr_loopoptions' => 'Configuración de control de bucles',
	'pr_loopcut_prevents_autoresponder' => 'No enviar autorrespuesta',
	'd_pr_loopcut_prevents_autoresponder' => 'Si se activa, ' . SWIFT_PRODUCT . ' no enviará la confirmación de recepción para el mensaje que hizo saltar la regla de control de bucles.  <em>Se recomienda encarecidamente que esta opción este siempre activada.</em>',
	'pr_loopcut_ignores_cut_mail' => 'Ignorar mensaje de email',
	'd_pr_loopcut_ignores_cut_mail' => 'Si se activa, los mensajes que hagan saltar las reglas de control de bucles no serán procesados.',
	't_autorespondercc' => 'Despachar autorrespuesta para usuarios CC?',
	'd_t_autorespondercc' => 'Si se activa, ' . SWIFT_PRODUCT . ' enviará automáticamente un mensaje de autorrespuesta a los usuarios CC. El mensaje de autorrespuesta se enviará sin la contraseña del creador incluso si esta opción está activada.',
	't_ochtml' => 'Conversión de HTML (Respuestas operadores)',
	'd_t_ochtml' => 'Elija como tratar el contenido HTML en las respuestas de email enviadas por los oepradores. Esta opción afectará al contenido que llega al usuario.<br><dl><dt><b>Entidades HTML</b></dt><dd>Convierte el HTML a texto normal de manera que se puede ver el código.</dd><dt><b>Eliminar etiquetas</b></dt><dd>Elimina el formato HTML completamente; (p.ej "<b>foo</b>" = "foo").</dd><dt><b>No procesar</b></dt><dd>Permitir código HTML (p.ej "<b>foo</b>" = "<b>foo</b>").  Esta opción <b>no</b> se recomienda ya que puede permitir la ejecución de código malicioso en las aplicaciones de correo electrónico.</dd></dl><i>Nota: Esta opción no afecta al contenido final almacenado en la base de datos!</i>',
	't_allowhtml' => 'Permitir etiquetas HTML',
	'd_t_allowhtml' => 'Si se activa, algunas etiquetas HTML (opción siguiente) se permitirán, incluso si se establece la conversión HTML en <i>Eliminar Etiquetas</i>.',
	't_allowableadvtags' => 'Etiquetas HTML permitidas',
	'd_t_allowableadvtags' => 'Si la opción anterior está activada, se permitirán las siguientes etiquetas HTML.',
	't_searchticketidinbody' => 'Buscar ID de ticket en el cuerpo del email?',
	'd_t_searchticketidinbody' => 'Si se activa, ' . SWIFT_PRODUCT . ' intentará buscar el ID de ticket en el cuerpo del email si no lo encuentra en el asunto.',
	'tr_captcha' => 'Activar CAPTCHA para comentarios',
	'd_tr_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'nw_captcha' => 'Activar CAPTCHA para comentarios',
	'd_nw_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'dl_captcha' => 'Activar CAPTCHA para comentarios',
	'd_dl_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'kb_captcha' => 'Activar CAPTCHA para comentarios',
	'd_kb_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',

	// ======= GENERAL SETTINGS =======
	'general_companyname' => 'Nombre de la empresa',
	'd_general_companyname' => 'El nombre que se usará como marca en el Centro de Soporte y en los emails salientes.',
	'general_producturl' => 'URL del producto',
	'd_general_producturl' => 'Introduzca la ruta completa a la URL donde está instalado el producto. Este valor DEBE incluir una barra al final. ' . SWIFT_PRODUCT . ' no funcionará correctamente si este valor es erróneo.',
	'general_returnemail' => 'Dirección email de retorno por defecto',
	'd_general_returnemail' => 'Esta dirección se usará como dirección remitente por defecto en el correo saliente. Esta dirección debe corresponder con una cola de email activa para poder aceptar respuestas de usuarios.',
	'general_redirecttype' => 'Tipo de redirección',
	'd_general_redirecttype' => 'Seleccionar <i>Recarga de HTML Meta</i> para presentar una confirmación de acción antes de redigirir a la siguiente página.',
	'refreshunix' => 'Recarga cabeceras',
	'refreshwindows' => 'Recarga de HTML Meta',
	'general_defaultlanguage' => 'Idioma por defecto',
	'general_themeoptions' => 'Opciones de tema por defecto',
	'g_displaytopheader' => 'Mostrar logotipo en cabecera',
	'd_g_displaytopheader' => 'Activa o desactiva el mostrado del logotipo de la cabecera en el el panel de control de operadores y administradores.<br /><br /><i>NOTA: Necesitará forzar la recarga de la página (Ctrl+F5 o Comando+R) para que esta opción tenga efecto.</i>',
	'g_cpmenu' => 'Estilo de navegación por el menú',
	'd_g_cpmenu' => 'Seleccione el estilo de navegación <i>Pasar por encima</i> para activar una pestaña simplemente pasando el ratón sobre ella.',
	'navleft' => 'Izquierda',
	'navright' => 'Derecha',
	'g_commentsapproval' => 'Moderar comentarios',
	'd_g_commentsapproval' => 'Requiere aprobación manual de los comentarios introducidos por los usuarios.',
	'menuhover' => 'Pasar por encima',
	'menuclick' => 'Pulsar',
	'g_jscache' => 'Caché Javascript para elementos del tema',
	'd_g_jscache' => 'Guarda en caché elementos muy descargados como el menú y la barra de navegación para que las páginas carguen más rápido. Esto deshabilita la vista de comentarios en tiempo real y el contador de mensajes privados en el menú.',
	'g_onlusr' => 'Mostrar operadores conectados en el panel de operadores',
	'd_g_onlusr' => 'Muestra una lista de los operadores conectados y las acciones que están realizando.',
	'g_api' => 'Configuración API',
	'g_enableapiinterface' => 'Activar API',
	'd_g_enableapiinterface' => 'Si se activa, el interfaz API aceptará todas las peticiones debidamente autenticadas.',
	'g_cpdefaultskin' => 'Tema por defecto',
	'd_g_cpdefaultskin' => 'Seleccione el tema por defecto para el panel de control de administración y operadores. Cambiar el tema por defecto requerirá forzar la recarga de la página (Ctrl+F5 o Ctrl+Mayus+R) para poder ver los cambios.',
	'defaultskin' => 'Tema por defecto',
	'skin_modernblue' => 'Azul Moderno',
	'skin_lite' => 'Lite',
	'g_generalsettings' => 'Configuración general',
	'g_maxtagcloud' => 'Máximo número de elementos en nube de etiquetas',
	'd_g_maxtagcloud' => 'Introduzca el número máximo de elementos a mostrar en la nube de etiquetas.',
	'g_maxsearchresults' => 'Máximos resultados búsquedas',
	'd_g_maxsearchresults' => 'Introduzca el número máximo de resultados a mostrar en el Centro de Soporte de usuarios.',

	// ======= CPU SAVING & OPTIMIZATION =======
	'cpu_attachments' => 'Configuración de adjuntos',
	'cpu_attachtype' => 'Lugar de almacenamiento de adjuntos',
	'd_cpu_attachtype' => 'Especifique el lugar en que se almacenarán los adjuntos. Si se selecciona la opción "archivos, todos los adjuntos se almacenarán en el sistema de archivos como archivos individuales (con nombres cifrados). Si se selecciona la opción de base de datos, se almacenarán los adjuntos en la base de datos.',
	'database' => 'Base de datos',
	'files' => 'Sistema de archivos (Directorio "files")',
	'cpu_attachchunksize' => 'Tamaño de parte de archivo en base de datos',
	'd_cpu_attachchunksize' => 'Cada adjunto guardado en la base de datos se divide en un número de partes con el tamaño en bytes especificado aquí. Este número no debería ser mayor que el especificado en la opción<b>maximum packet size</b> del archivo <i>my.cnf</i> (Archivo de configuración de MySQL).',
	'cpu_optimization' => 'Ajustes de optimizacióbn',
	'cpu_winappcompresslevel' => 'Nivel de compresión GZIP',
	'd_cpu_winappcompresslevel' => 'Seleccione el nivel de compresión de las páginas. Valores mayores ocuparán mayor potencia de proceso pero descargarán menos datos. Si se especifica un nivel demasiado alto, los tiempos de carga de página podrían subir. el valor recomendado es <i>1 - Recomendado</i>.',
	'nocompression' => 'No comprimir',
	'reccompression' => 'Recomendado',
	'highestcompression' => 'Alto',
	'cpu_compresswinappdata' => 'Comprimir salida de aplicación de escritorio',
	'cpu_logcleardays' => 'Tiempo de borrado de logs (en días)',
	'd_cpu_logcleardays' => 'Especifique el número de días tras los que se borrarán los logs del sistema.',
	'cpu_smsgateway' => 'Pasarela SMS',
	'gateway_enable' => 'Activar pasarela SMS',
	'd_gateway_enable' => 'La pasarela SMS de Kayako puede enviar alertas directas a teléfonos móviles. Para más información visite el <a target="_blank" href="http://my.kayako.com">Portal de clientes de Kayako</a>.',
	'gateway_username' => 'Usuario pasarela',
	'd_gateway_username' => 'El usuario de la pasarela SMS. Es la misma dirección de email usada para iniciar sesión en el <a target="_blank" href="https://my.kayako.com">Portal de clientes de Kayako</a>.',
	'gateway_password' => 'Contraseña pasarela',
	'd_gateway_password' => 'La contraseña de la pasarela SMS. Es la misma contraseña usada para iniciar sesión en el <a target="_blank" href="https://my.kayako.com">Portal de clientes de Kayako</a>.',
	'cpu_mailsettings' => 'Configuración email saliente',
	'cpu_enablehtmlmails' => 'Correo HTML',
	'd_cpu_enablehtmlmails' => 'Envía el correo saliente en formato HTML. ' . SWIFT_PRODUCT . ' enviará también una versión de texto plano para que el contenido pueda ser visualizado en clientes de email sencillos. El aspecto y contenido de los mensajes se puede cambiar editando las plantillas en <i>Plantillas > Administrar plantillas</i>.',
	'd_tickets_resattachments' => 'Si se activa, solo se procesarán los adjuntos que aparezcan en la lista de tipos de adjunto personalizados en <i>Tickets > Tipos de adjunto</i>. Se ignorará cualquier otro tipo de adjunto.',
	'cpu_enablemailqueue' => 'Cola de envío',
	'd_cpu_enablemailqueue' => 'Usa un sistema de cola para el email saliente. ' . SWIFT_PRODUCT . ' realizará los envíos masivos de email en varias pasadas. Esto puede prevenir la ralentización del servidor.',
	'cpu_mailqueuebatch' => 'Emails enviados por pasada',
	'd_cpu_mailqueuebatch' => 'El número de emails a enviar en cada pasada. Cuanto más alto sea este valor más recursos del sistema consumirá cada pasada.',
	'cpu_smtp' => 'Configuración SMTP',
	'cpu_enablesmtp' => 'Activar SMTP',
	'd_cpu_enablesmtp' => 'Seleccione si se debe usar un servidor SMTP para enviar el email. Por defecto, ' . SWIFT_PRODUCT . ' usará la función mail() interna de PHP para enviar el email.',
	'cpu_smtphost' => 'Servidor SMTP',
	'd_cpu_smtphost' => 'El nombre o la dirección IP del servidor SMTP.',
	'cpu_smtpport' => 'Puerto SMTP',
	'd_cpu_smtpport' => 'El número de puerto del servidor SMTP, <i>normalmente el puerto 25</i>.',
	'cpu_smtpportssl' => 'Puerto SMTP (TLS/SSL)',
	'd_cpu_smtpportssl' => 'Especifique el puerto de su servidor SMTP. No se debe cambiar este valor si no es necesario, ya que la mayoría de servidores SMTP (TLS/SSL) funcionan sobre el puerto 465',
	'cpu_smtpuseauth' => 'Usar autenticación SMTP',
	'd_cpu_smtpuseauth' => 'Usar la información siguiente para autenticarse en el servidor SMTP.',
	'cpu_smtpuser' => 'Usuario SMTP',
	'd_cpu_smtpuser' => 'El usuario que ' . SWIFT_PRODUCT . ' usará para autenticar con el servidor SMTP.',
	'cpu_smtppass' => 'Contraseña SMTP',
	'd_cpu_smtppass' => 'La contraseña que ' . SWIFT_PRODUCT . ' usará para autenticar con el servidor SMTP.',
	'gat_emailfailure' => 'Informes de fallos de envío',
	'd_gat_emailfailure' => 'Enviar informes de fallo de envío al correo electrónico del administrador principal.',
	'cpu_smtptype' => 'Tipo de SMTP',
	'd_cpu_smtptype' => 'Seleccione el tipo de servidor SMTP.',
	'smtpssl' => 'SSL',
	'smtptls' => 'TLS',
	'smtpnonssl' => 'Non SSL',
	'smtpssl2' => 'SSL v2',
	'smtpssl3' => 'SSL v3',
	'encqp' => 'quoted-printable',
	'encbase64' => 'base64',
	'encbinary' => 'binary',
	'enc7bit' => '7bit',
	'enc8bit' => '8bit',
	'cpu_headerencoding' => 'Juego caracteres cabecera',
	'd_cpu_headerencoding' => 'Especifique el juego de caracteres para las variables de cabecera (De, Asunto, Para)',
	'cpu_messageencoding' => 'Juego caracteres mensaje',
	'd_cpu_messageencoding' => 'Especifique el juego de caracteres por defecto para los datos del mensaje (Texto y HTML)',
	'cpu_maildefaultpriority' => 'Prioridad por defecto',
	'd_cpu_maildefaultpriority' => 'Especifique la prioridad por defecto para los emails salientes',
	'mailprioritylow' => 'Baja (5)',
	'mailprioritynormal' => 'Normal (3)',
	'mailpriorityhigh' => 'Alta (1)',

	// ======= SECURITY =======
	'security_autoapprovecomments' => 'Aprobar comentarios automáticamente',
	'd_security_autoapprovecomments' => 'Si se activa, todos los comentarios serán aprobados automáticamente tras pasar los filtros de spam (si están activados).',
	'security_enableakismet' => 'Activar filtro de spam Akismet',
	'd_security_enableakismet' => 'Si se activa ' . SWIFT_PRODUCT . ' revisará todos los comentarios enviados con el filtro Akismet. Para usar Akismet es necesaria una "API key". Para más información visite <a href="http://akismet.com" target="_blank">http://akismet.com</a>.',
	'security_akismetkey' => 'API Key de Akismet',
	'd_security_akismetkey' => 'Introduzca aquí su API key de Akismet.',
	'security_commentscaptcha' => 'Activar captcha para los comentarios',
	'd_security_commentscaptcha' => 'Solicita a los usuarios que quieran publicar comentarios en el Centro de Soporte que introduzcan el texto mostrado en una imagen especial para verificar que son humanos.',
	'security_rememberme' => 'Recuerdame: Almacenar contraseña',
	'd_security_rememberme' => 'Si se activa, cuando un operador seleccione la opción "recuérdame" al iniciar sesión, el sistema guardará la contraseña y el nombre de usuario en una cookie.<br/><br/><i>NOTA: Esto puede producir riesgos de seguridad si se descuber una vulnerabilidad XSS.</i>',
	'security_sessioninactivity' => 'Final sesión por inactividad',
	'd_security_sessioninactivity' => 'El tiempo en segundos tras el cual se finalizará una sesión inactiva.',
	'security_sessionvar' => 'Tipo de variable de sesión',
	'security_visitorinactivity' => 'Expiración de sesión de visitantes',
	'd_security_visitorinactivity' => 'El tiempo en segundos tras el cual los visitantes (seguidos a través de la aplicación de escritorio de ' . SWIFT_PRODUCT . ') serán marcados como inactivos y se borrarán sus sesiones. Incrementar este valor consumirá más recursos del sistema.',
	'security_cookiedomain' => 'Dominio de cookies',
	'd_security_cookiedomain' => 'El dominio de las cookies. Cambie este valor únicamente si hay varias instalaciones de ' . SWIFT_PRODUCT . ' en el mismo dominio.',
	'security_cookiepath' => 'Ruta de cookies',
	'd_security_cookiepath' => 'La ruta de las cookies. Cambie este valor únicamente si hay varias instalaciones de ' . SWIFT_PRODUCT . ' en el mismo dominio.',
	'cookie' => 'Cookie',
	'url' => 'URL',
	'urlcookie' => 'URL y cookie',
	'security_staffpasswordpolicy' => 'Política de contraseñas de operador',
	'security_sppminchars' => 'Longitud mínima',
	'd_security_sppminchars' => 'Especifique el número mínimo de caracteres que debe tener la contraseña de operador.',
	'security_sppminnumbers' => 'Mínimos dígitos',
	'd_security_sppminnumbers' => 'Especifique el número mínimo de dígitos numéricos que debe contener la contraseña de operador.',
	'security_sppminsymbols' => 'Mínimos símbolos',
	'd_security_sppminsymbols' => 'Especifique el número mínimo de símbolos que debe contener la contraseña de operador.',
	'security_sppmincapitalchars' => 'Mínimas mayúsculas',
	'd_security_sppmincapitalchars' => 'Especifique el número mínimo de letras mayúsculas que debe contener la contraseña de operador.',
	'security_sppexpiredays' => 'Caducidad de contraseña (días)',
	'd_security_sppexpiredays' => 'Especifique el número de días tras los que caducará la contraseña de operador. Introduzca "0" si no desea usar esta característica.',
	'security_captcha' => 'Configuración de CAPTCHA',
	'security_captchatype' => 'Tipo de CAPTCHA',
	'captchalocal' => 'Local (PHP GD)',
	'captcharecaptcha' => 'ReCAPTCHA',
	'd_security_captchatype' => 'Seleccione el tipo de CAPTCHA. ' . SWIFT_PRODUCT . ' usará por defecto las funciones GD de PHP para generar la imagen CAPTCHA. ReCaptcha es más eficiente y además ayuda a digitalizar libros. Para más información visite <b><a href="http://www.recaptcha.net" target="_blank">recaptcha.net</a></b>, Para usar ReCAPTCHA, necesitará dar de alta una cuenta en el sitio web de ReCAPTCHA e introducir las credenciales necesarias aquí.',
	'security_recpublickey' => 'ReCAPTCHA Public Key',
	'd_security_recpublickey' => 'Introduzca la Public Key de ReCAPTCHA. (Necesaria únicamente si ha seleccionado ReCAPTCHA)',
	'security_recprivatekey' => 'ReCAPTCHA Private Key',
	'd_security_recprivatekey' => 'Introduzca la Private Key de ReCAPTCHA. (Necesaria únicamente si ha seleccionado ReCAPTCHA)',


	// ======= LOGINSHARE =======
	'loginshare_staff' => 'Configuración LoginShare Operadores',
	'loginshare_staffenable' => 'Activar LoginShare operadores',
	'd_loginshare_staffenable' => 'Si se activa, todas las peticiones de autenticación de operadores se probarán primero en la URL siguiente basándose en las especificaciones de la API de LoginShare.',
	'loginshare_stafftitle' => 'Nombre de LoginShare Operadores',
	'd_loginshare_stafftitle' => 'Introduzca el nombre de este LoginShare',
	'loginshare_staffurl' => 'URL de LoginShare de operadores',
	'd_loginshare_staffurl' => 'Introduzca la URL de la API. <b><a href="http://www.kayako.com" target="_blank">Pulse aquí</a></b> para más información sobre la API LoginShare.',

	'loginshare_user' => 'Configuración LoginShare Usuarios',
	'loginshare_userenable' => 'Activar LoginShare usuarios',
	'd_loginshare_userenable' => 'Si se activa, todas las peticiones de autenticación de usuarios se probarán primero en la URL siguiente basándose en las especificaciones de la API de LoginShare.',
	'loginshare_usertitle' => 'Nombre de LoginShare usuarios',
	'd_loginshare_usertitle' => 'Introduzca el nombre de este LoginShare',
	'loginshare_userurl' => 'URL de LoginShare de usuarios',
	'd_loginshare_userurl' => 'Introduzca la URL de la API. <b><a href="http://www.kayako.com" target="_blank">Pulse aquí</a></b> para más información sobre la API LoginShare.',

	// ======= DATE & TIME =======
	'dtcalus' => 'USA (mm/dd/yy + 12hr)',
	'dtcaleu' => 'EUR (dd/mm/yy + 24hr)',
	'dt_caltype' => 'Tipo de fecha de calendario',
	'd_dt_caltype' => 'Cambia el tipo de fecha usado para la fecha del calendario. Nota: Este ajuste sólo afecta a los valores de fecha del selector de fecha.',
	'dt_dateformat' => 'Formato de fecha',
	'd_dt_dateformat' => 'Especifique el formato por defecto de todas las fechas mostradas en el sistema. ' . SWIFT_PRODUCT . ' usa la función PHP strftime(). Para más información sobre esta función, consulte <a href="http://www.php.net/strftime" target="_blank">strftime()</a>.',
	'dt_timeformat' => 'Formato de hora',
	'd_dt_timeformat' => 'Muestra la hora usando el formato especificado.',
	'dt_datetimeformat' => 'Formato de fecha y hora',
	'd_dt_datetimeformat' => 'Mostrar fechas y horas en el formato especificado.',
	'dt_timezone' => 'Zona horaria',
	'd_dt_timezone' => 'Seleccione la zona horaria por defecto. Los operadores tienen la opción de anular la zona horaria y poner la suya en las preferencias.',
	'dt_daylightsavings' => 'Activar Horario de Verano',
	'd_dt_daylightsavings' => 'Seleccione si quiere activar el Horario de Verano.',

	// ======= LIVE CHAT =======
	'livesupport_clientchatsettings' => 'Configuración visitantes y chat',
	'livesupport_chatwidth' => 'Anchura ventana de chat',
	'd_livesupport_chatwidth' => 'La anchura de la ventana de chat de visitantes (en píxeles).',
	'livesupport_chatheight' => 'Altura ventana de chat',
	'd_livesupport_chatheight' => 'La altura de la ventana de chat de visitantes (en píxeles).',
	'livesupport_clientchatrefresh' => 'Intervalo de recarga de chat',
	'd_livesupport_clientchatrefresh' => 'El intervalo en segundos en el que los datos del chat de sincronizarán durante una sesión de chat. Valores menores incrementarán la carga del servidor.',
	'livesupport_clientpagerefresh' => 'Intervalo de recarga de página de visitantes',
	'd_livesupport_clientpagerefresh' => 'El intervalo en segundos en el que los datos de visitantes se recargarán y se enviarán al servidor. Valores menores incrementarán mucho la carga del servidor.',
	'livesupport_roundrobinretries' => 'Número de intentos de encontrar operador',
	'd_livesupport_roundrobinretries' => 'El número de veces que ' . SWIFT_PRODUCT . ' intentará buscar operadores disponibles cuando se reciba una nueva solicitud de chat. Si no se encuentran operadores disponibles tras este número de intentos, se pedirá al visitante que <i>deje un mensaje</i>.',
	'livesupport_roundrobintimetry' => 'Intervalo de tiempo entre intentos',
	'd_livesupport_roundrobintimetry' => 'El tiempo en segundos que ' . SWIFT_PRODUCT . ' esperará entre cada reintento de encontrar un operador disponible. El tiempo total que un visitante esperará si no hay operadores disponibles es (<i>número de intentos * intervalo entre intentos</i>).  Tras este número de intentos con el intervalo especificado, se pedirá al visitante que <i>deje un mensaje</i>',
	'livesupport_displayclientchatqueue' => 'Comunicar al visitante el número de chats en cola',
	'd_livesupport_displayclientchatqueue' => 'Si se activa, los visitantes verán un mensaje comunicándoles el número de usuarios esperando a comenzar un chat antes que ellos.',
	'livesupport_cachehtmljscode' => 'Guardar Javascript en caché',
	'd_livesupport_cachehtmljscode' => 'Especifique si ' . SWIFT_PRODUCT . ' debe enviar cabeceras de caché al navegador del usuario. Se recomienda no modificar este valor.',
	'livesupport_enableuseristyping' => 'Mostrar "Escribiendo..."',
	'd_livesupport_enableuseristyping' => 'Si se activa, los visitantes y los operadores podrán ver cuándo el otro está escribiendo. Desactive esta opción para reducir la carga del servidor.',

	'livesupport_messagesettings' => 'Configuración de mensajes offline',
	'livesupport_enablemessagefw' => 'Activar reenvío',
	'd_livesupport_enablemessagefw' => 'Reenviar los mensajes offline recibidos por ' . SWIFT_PRODUCT . ' a la siguiente dirección de email.',
	'livesupport_deletemessageafterfw' => 'Eliminar tras reenvío',
	'd_livesupport_deletemessageafterfw' => 'Eliminar automáticamente el mensaje reenviado.',
	'livesupport_fwmessageemail' => 'Direcciones email de reenvío',
	'd_livesupport_fwmessageemail' => 'Reenviar mensajes offline a las siguientes direcciones de email separadas por punto y coma(;). Esta opción solo tendrá efecto si se ha activado la opción anterior, <i>Activar reenvío</i>.<br/><br/>Ejemplo: <i>pepe.perez@empresa.com;fulano.detal@empresa.com</i>',

	'livesupport_winappsettings' => 'Configuración Aplicación de Escritorio',
	'livesupport_searchbgcolor' => 'Color de fondo de visitantes de buscadores',
	'd_livesupport_searchbgcolor' => 'El color de fondo de los visitantes que provengan de un buscador.',
	'livesupport_searchfrcolor' => 'Color de letra de visitantes de buscadores',
	'd_livesupport_searchfrcolor' => 'El color de letra de los visitantes que provengan de un buscador.',
	'ls_adbgcolor' => 'Color de fondo de visitantes de campaña',
	'd_ls_adbgcolor' => 'El color de fondo para los visitantes procedentes de una <b>Campaña de anuncios</b> (configuradas en el panel de control de operadores).',
	'ls_adfrcolor' => 'vColor de fondo de visitantes de campaña',
	'd_ls_adfrcolor' => 'El color de letra para los visitantes procedentes de una <b>Campaña de anuncios</b> (configuradas en el panel de control de operadores).',

	'ls_clientarea' => 'Configuración del Centro de Soporte',
	'ls_displaystatus' => 'Mostrar icono se estado de soporte por chat',
	'd_ls_displaystatus' => 'Muestra el botón de soporte por chat en el Centro de Soporte (mostrando Conectado, Desconectado, Ocupado o Vuelvo enseguida).',
	'ls_staffcp' => 'Configuración panel control operadores de chat',
	'ls_entab' => 'Mostrar pestaña Chat en el panel de control de operadores',
	'd_ls_entab' => 'Mostrar pestaña Chat en el panel de control de operadores.',
	'ls_depname' => 'Usar el nombre del departamento en los chats',
	'd_ls_depname' => 'Use el nombre del departamento en lugar del nombre del operador en los chats. Esto ocultará al usuario el nombre del operador.',
	'livesupport_alertttl' => 'Tiempo de mostrado de alertas',
	'd_livesupport_alertttl' => 'Especifique el tiempo que se mostrarán las alertas (en segundos). Esta opción se usa para las alertas personalizadas en las reglas de visitantes. Introduzca 0 para mostrar las alertas indefinidamente.',
	'livesupport_clicktocallsettings' => 'Configuración de Click to Call',
	'ls_activecountrycode' => 'Código ITU-T de país activo',
	'd_ls_activecountrycode' => 'Introduzca su código de país actual, que se usará para distinguir las llamadas nacionales e internacionales.',
	'ls_ignoreactivecountrycode' => 'Ignorar código de país activo',
	'd_ls_ignoreactivecountrycode' => 'Si se activa, ' . SWIFT_PRODUCT . ' no añadirá el prefijo de país activo en las peticiones de llamada.',
	'ls_internationalcallprefix' => 'Prefijo de llamada internacional',
	'd_ls_internationalcallprefix' => 'Introduzca el prefijo para llamadas internacionales.',
	'ls_enableinternationalcalls' => 'Activar llamadas internacionales',
	'd_ls_enableinternationalcalls' => 'Esta opción le permite activar/desactivar la posibilidad de que los visitantes de otros países soliciten llamadas.',
	'livechat_ignorerange' => 'IPs ignoradas',
	'd_livechat_ignorerange' => SWIFT_PRODUCT . ' ignorará a los visitantes de las direcciones IP o subredes sumunistradas. Esto puede usarse para filtrar los visitantes de la propia empresa. Para bloquear una IP, use el panel de administración &gt; Chat &gt; Bloqueos. Separe múltiples valores con una coma \',\'. Ejemplos de uso:<BR /><i> * <b>202.1.192.0-202.1.192.255</b>: Un rango de IPs<BR /> * <b>200.36.161.0/24</b>: Un rango de Ips usando enmascaramiento<BR /> * <b>200.36.161/24</b>: Sintaxis abreviada igual a la anterior.</i>',

	'livechat_proactivescroll' => 'Activar animación de chat proactivo',
	'd_livechat_proactivescroll' => 'Si se activa, aparecerá una animación flotante solicitando un chat para implicar al visitante.',
	'livechat_timestamps' => 'Activar sellos de tiempo',
	'd_livechat_timestamps' => 'Si se activa, ' . SWIFT_PRODUCT . ' mostrará sellos de tiempo junto a cada mensaje de chat',
	'livechat_timestampformat' => 'Formato de sello de tiempo',
	'd_livechat_timestampformat' => 'Especifique el formato por defecto para los sellos de tiempo mostrados en el historial de chat (no se aplica a sellos de tiempo mostrados en ventanas de chat). ' . SWIFT_PRODUCT . ' usa la función PHP strftime(). Para más información sobre esta función, consulte <a href="http://www.php.net/strftime" target="_blank">strftime()</a>.',
	'ls_forcerandomnumber' => 'Forzar recarga de la URL para cada petición de etiqueta',
	'd_ls_forcerandomnumber' => 'Si se activa, ' . SWIFT_PRODUCT . ' forzará la recarga de la URL de la etiqueta con cada petición a la página. Esto permite una mejor actualización de las imágenes de chat pero puede incrementar la carga del servidor.',

	// ======= MAIL PARSER =======
	'pr_allowmultiplecreation' => 'Crear ticket en todas las colas de destino?',
	'd_pr_allowmultiplecreation' => 'Si se activa, ' . SWIFT_PRODUCT . ' creará múltiples tickets si un email tiene varias direcciones de colas en los campos \'Para:\' o \'CC:\'',
	'pr_generalparser' => 'Configuración de procesador',
	'pr_contentpriority' => 'Prioridad formato contenido email',
	'd_pr_contentpriority' => 'Cada email que llega al sistema puede tener dos tipos de contenido (HTML y texto plano). Esta opción especifica qué versión debe usar ' . SWIFT_PRODUCT . ' para procesar el correo. Es recomendable que este valor sea <i>Texto</i>.',
	'text' => 'Texto',
	'html' => 'HTML',
	'pr_stripscript' => 'Quitar etiquetas &lt;SCRIPT&gt;',
	'd_pr_stripscript' => 'Quita todas las etiquetas script del email entrante. Se recomienda <b>encarecidamente</b> que se deje esta opción activada. Si se deshabilita, los usuarios podrían ejecutar código en el navegador de los operadores.',
	'pr_allowhtml' => 'Permitir etiquetas HTML',
	'd_pr_allowhtml' => 'Si el procesador de correo debería permitir etiquetas HTML en el contenido.',
	'pr_allowabletags' => 'Etiquetas HTML válidas',
	'd_pr_allowabletags' => 'Especifique las etiquetas HTML que el procesador de correo no eliminará del correo entrante.',
	'pr_logoptions' => 'Opciones de log de procesador',
	'pr_enablelog' => 'Activar log',
	'd_pr_enablelog' => 'Guarda en un log toda la actividad del procesador de correo. Se recomienda que esta opción esté siempre activada para ayudar a resolver problemas relacionados con el procesado de email entrante.',
	'pr_logchurndays' => 'Tiempo de guardado de logs',
	'd_pr_logchurndays' => 'El tiempo en días durante el que se guardarán los logs.',
	'pr_maxlogsize' => 'Tamaño máximo de elemento de log',
	'd_pr_maxlogsize' => 'El tamaño máximo permitido en kbs para los elementos del log del procesador. Cualquier elemento mayor de ese tamaño no se guardará. Esto se puede usar para reducir el tamaño de la base de datos del log.',
	'pr_pop3' => 'Configuración de extracción POP3/IMAP',
	'pr_procno' => 'Número máximo de mensajes a procesar en una pasada',
	'd_pr_procno' => 'Una vez que el procesador de correo alcance este límite, terminará el procesado y los mensajes que hayan quedado en la bandeja de entrada se procesarán en la siguiente pasada.',
	'pr_sizelimit' => 'Límite de tamaño de mensaje',
	'd_pr_sizelimit' => 'Rechaza cualquier mensaje de tamaño mayor que el especificado (en KBs). Este tamaño debe ser menor que el de la variable PHP <b>php_memory_limit</b> que se encuentra en el archivo <i>php.ini</i>. De lo contrario los mensajes podrían quedarse en la cola.',
	'pr_parsereplyto' => 'Anular cabecera "Responder a"',
	'd_pr_parsereplyto' => 'Usar la cabecera <i>Responder a</i> como dirección de email primaria del creador del ticket. <b>¡Cuidado!</b> Esto podría ocasionar abusos, ya que las cabeceras Responder a se pueden falsificar fácilmente.',
	'pr_conversion' => 'Convertir automáticamente el juego de caracteres del correo entrante',
	'desc_pr_conversion' => 'Si se activa, ' . SWIFT_PRODUCT . ' intentará convertir automáticamente el correo entrante al juego de caracteres por defecto del helpdesk (<i>p.ej. si el helpdesk usa UTF-8 y se recibe un email que usa ISO-8859-1, se convertirá a UTF-8 antes de añadirse al sistema</i>).',

	// ======= TICKETS =======
	't_spamhandling' => 'Configuración de control de Spam',
	't_spammovetotrash' => '¿Mover el spam a la basura?',
	'd_t_spammovetotrash' => 'Si se activa, todos los tickets marcados como spam se moverán automáticamente a la basura.',
	't_spamban' => '¿Bloquear direcciones de email de Spam?',
	'd_t_spamban' => 'Si se activa, las direcciones de email que enviaron cualquier ticket marcado como spam serán bloqueadas automáticamente.',
	't_restrictnewticket' => 'Restringir la creación de nuevos tickers a los departamentos asignados',
	'd_t_restrictnewticket' => 'Solo permite a los operadores crear tickets en departamentos a los que estén asignados.',
	't_rvalemail' => 'Solicitar direcciones de email válidas',
	'd_t_rvalemail' => 'Hace que los usuarios faciliten una dirección de email válida al enviar un ticket.',
	'tickets_search' => 'Opciones de búsqueda',
	't_searchsortdate' => 'Ordenar resultados por última actividad (descendente)',
	'd_t_searchsortdate' => 'Ordena los resultados de búsqueda por última actividad (descendente). De lo contrario, se usará el orden de visualización por defecto.',
	't_cntrelevance' => 'Búsqueda avanzada de tickets',
	'd_t_cntrelevance' => 'Usar un algoritmo avanzado para buscar y determinar la relevancia de los resultados. Esta opción incrementará los tiempos de búsqueda en un 40%, pero la relevancia de los resultados será mucho mayor.',
	'tickets_searchtype' => 'Tipo de índice de búsqueda',
	'postindex' => 'Índice de mensaje de foro',
	'fulltext' => 'Texto completo MySQL',
	't_autorecip' => 'Añadir a usuarios CC como destinatarios',
	'd_t_autorecip' => 'Añade automáticamente las direcciones de email en CC en los emails entrantes como destinatarios en el ticket que se cree.',
	'tickets_minwordlength' => 'Tamaño mínimo de palabra',
	'd_tickets_minwordlength' => 'Especifique el tamaño mínimo de palabra para los índices de búsqueda. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar. Las palabras cortas tienden a aparecer más frecuentemente, luego permitir su indexación provocará que el índice sea mayor y más lento, y por tanto también lo serán las búsquedas.',
	'tickets_maxwordlength' => 'Tamaño máximo de palabra',
	'd_tickets_maxwordlength' => 'Especifique el tamaño máximo de las palabras indexables para las búsquedas. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar.',
	'tickets_indexnumbers' => 'Indexar números',
	'd_tickets_indexnumbers' => 'Si se activa, los números serán indexables y se podrán buscar.',
	'tickets_minnumberlength' => 'Tamaño mínimo de número',
	'd_tickets_minnumberlength' => 'Especifique el tamaño mínimo de número (en caracteres) para los índices de búsqueda. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar..',
	'tickets_faulttolerance' => 'Tolerancia a fallos de palabra',
	'd_tickets_faulttolerance' => 'Si una palabra aparece en un mensaje de ticket más de las veces especificadas aquí, se ignorará y no se indexará.',
	't_floodprotection' => 'Protección de flood',
	't_fresponder' => 'No enviar mensaje de autorrespuesta',
	'd_t_fresponder' => 'Si se activa, no se enviarán mensajes de autorrespuesta cuando se active la protección de flood.',
	't_fnoadd' => 'No añadir el ticket/respuesta',
	'd_t_fnoadd' => 'Si se activa, el correo entrante será ignorado si se activa la protección contra flood. No se recomienda activar esta opción ya que deshabilitar el mensaje de autorrespuesta debería desactivar cualquier bucle potencial de correo.',
	't_fthreshold' => 'Umbral de tiempo (en segundos)',
	'd_t_fthreshold' => 'Umbral de tiempo en el que se activará la protección contra flood.<BR /><BR /><span class="tabletitle"><i>Como funciona la protección contra flood?</i></span><BR />Cuando se recibe un email entrante, '.SWIFT_PRODUCT. ' revisa la tabla de tickets para comprobar si el usuario ha creado un ticket con el mismo asunto en el umbral de tiempo especificado. Si es así, la protección contra flood se activa y se realizan las acciones especificadas.',
	't_parser' => 'Configuración procesador de correo',
	't_pstaffreply' => 'Permitir a los operadores responder por email',
	'd_t_pstaffreply' => 'Permite a los operadores responder a los tickets directamente desde su email.',
	't_enfp' => 'Activar/desactivar protección contra flood',
	'd_t_enfp' => 'Cambia el estado de la protección contra flood. Se recomienda que nunca desactive esta opción, ya que previene bucles de correo electrónico que pueden producirse si su cliente tiene activada la autorrespuesta.',
	't_sla' => 'Configuración SLA',
	't_encustomoverdue' => 'Usar tiempo de resolución y vencimiento por defecto',
	'd_t_encustomoverdue' => 'Usa el valor (de <i>Tiempo de vencimiento por defecto</i> y <i>Tiempo de resolución por defecto</i>) para calcular los tiempos de vencimiento de un ticket cuando no se ha aplicado un plan SLA al departamento, usuario, grupo de usuarios o al mismo ticket.',
	't_overduehrs' => 'Tiempo de vencimiento por defecto',
	'd_t_overduehrs' => 'Marca un ticket como vencido tras este número de horas. (<i>Vea la opción anterior, <i>Usar tiempo de vencimiento por defecto</i>, para una explicación</i>).',
	't_resolutionduehrs' => 'Tiempo de resolución por defecto',
	'd_t_resolutionduehrs' => 'Marca un ticket como vendido si no se recuelve tras este número de horas. (<i>Vea la opción anterior, <i>Usar tiempo de vencimiento por defecto</i>, para una explicación</i>).',
	'tickets_resattachments' => 'Restringir adjuntos entrantes a los tipos de adjuntos personalizados',
	'd_tickets_resattachments' => 'Si se activa, sólo será procesados los adjuntos que aparezcan en la lista de tipos de adjunto personalizados en  <i>Tickets > Tipos de adjunto</i>. Cualquier adjunto de otro tipo será ignorado.',
	't_rss' => 'Sindicación RSS',
	't_enrss' => 'Activar RSS para vistas de ticket',
	'd_t_enrss' => 'Permite la consulta de las vistas de tickets (del panel de control de operadores) a través de RSS.',
	't_general' => 'Configuración general de tickets',
	't_tpreview' => 'Activar previsualización de mensajes en el listado de tickets',
	'd_t_tpreview' => 'Muestra una previsualización de mensajes al pasar el ratón por encima de un ticket en el panel de control de operadores. Si su helpdesk tiene mucho tráfico se recomienda no activar esta opción.',
	't_postlimit' => 'Mensajes de ticket por página',
	'd_t_postlimit' => 'Si está activada la opción <i>"Dividir mensajes de ticket en páginas"</i> esta opción determina cuantos mensajes se mostrarán en cada página.',
	't_chtml' => 'Conversión HTML (Visualización y alertas de operador)',
	'd_t_chtml' => 'Choose how HTML content should be treated when displaying tickets in the web interface and when sending staff alerts.<br><dl><dt><b>HTML Entities</b></dt><dd>Converts HTML to normal text so that you can see the code.</dd><dt><b>Strip Tags</b></dt><dd>Removes HTML formatting completely; (e.g. "<b>foo</b>" = "foo").</dd><dt><b>No Processing</b></dt><dd>Allow HTML code (e.g. "<b>foo</b>" = "<b>foo</b>").  This setting is <b>not</b> recommended as it can allow malicious code to be executed in staff users\' web browsers and/or email client applications.</dd></dl><i>Note: This setting does not affect the final content stored in the database!</i>',
	't_postorder' => 'Display Order for Ticket Posts',
	'tcentities' => 'HTML Entities',
	'tchtml' => 'No Processing',
	'tchtmlpurifier' => 'HTML Purifier',
	'tcstrip' => 'Strip Tags',
	'd_t_postorder' => 'Specify whether to display the oldest or newest ticket posts first.',
	't_enpagin' => 'Dividir mensajes de ticket en páginas',
	'd_t_enpagin' => 'Display ticket posts for a ticket on separate pages instead of all on a single page. Choose how many ticket posts to display per page below.',
	'newestfirst' => 'Newest First',
	'oldestfirst' => 'Oldest First',
	't_overduecolor' => 'Overdue Tickets Background Color',
	'd_t_overduecolor' => 'The background color of tickets that have been marked as overdue.',
	't_resultlimit' => 'Search Results Limit',
	'd_t_resultlimit' => 'The limit of results that are returned following a search. Setting this value too high can cause searches to become more resource intensive and take longer to execute.',
	't_tidinsub' => 'Set Ticket ID in Subject for Outgoing Email',
	'd_t_tidinsub' => 'Insert a ticket ID into the subject of emails sent when staff create new tickets. Although it is highly recommended that this option be enabled, ' . SWIFT_PRODUCT . ' can still check which ticket a message belongs to by searching for the ticket ID within the email body, by comparing the subject or by checking the Message-ID email header.',
	't_mailset' => 'Mail Settings',
	't_stmsgid' => 'Check the Message-ID for Staff Replies',
	'd_t_stmsgid' => SWIFT_PRODUCT . ' can check the Message-ID header to confirm the identity of a staff user replying to a ticket alert. This adds an extra layer of security and makes sure the replier is a valid staff user. However, it requires that the end mailing client sends the In-Reply-To header, which is not supported by all email clients (in particular, wireless email clients).',
	't_entab' => 'Display Tickets Tab',
	'd_t_entab' => 'Display the Tickets tab within the staff control panel.',
	't_clientarea' => 'Client Support Interface Settings',
	't_cperpage' => 'Tickets to Display Per Page',
	'd_t_cperpage' => 'The number of tickets that will be listed to users when viewing their ticket list.',
	't_eticketid' => 'Ticket ID Type',
	'd_t_eticketid' => 'Choose how ' . SWIFT_PRODUCT . ' should generate new ticket identifiers. It is recommended that this is set to <i>Random</i> to increase security against spoofing attacks.<br /><br />Examples:<br /><i>Sequential:</i> "[#194]: <subject here>"<br /><i>Random:</i> "[ABC-123-4567]:<subject here>"',
	'tsequential' => 'Sequential',
	'trandom' => 'Random',
	't_maxattach' => 'Maximum Number of Attachments When Replying',
	'd_t_maxattach' => 'The maximum number of files that can be attached to a ticket reply. If particularly large files are allowed, it is recommended that the <i>upload_max_filesize</i> setting in your php.ini (PHP configuration file) be edited to reflect the size.',
	't_slaresets' => 'Clear Overdue Time for Tickets After Staff Reply',
	'd_t_slaresets' => 'Si se activa, the SLA overdue time will be automatically cleared whenever a staff user replies to a ticket. A new overdue time will be calculated when the client replies back to the ticket.',
	't_cthirdparty' => 'Users Can View Third-Party Replies',
	'd_t_cthirdparty' => 'Si se activa, users will be able to view third-party replies made to their tickets from within the client support interface.',
	't_cenattach' => 'Users Can Upload Attachments',
	'd_t_cenattach' => 'Si se activa, users will be able to upload file attachments when they create or reply to a ticket.',
	't_cmaxattach' => 'Maximum Number of Attachments',
	'd_t_cmaxattach' => 'The number of attachments a user can add to a new ticket or ticket reply.',
	't_cpostorder' => 'Display Order for Ticket Posts',
	'd_t_cpostorder' => 'Choose whether to display the oldest or newest ticket posts first to users in the client support interface.',
	't_pdainterf' => 'PDA Staff Control Panel Interface',
	't_pdenpagin' => 'Split Ticket Posts by Page',
	'd_t_pdenpagin' => 'Display ticket posts for a ticket will be displayed on separate pages instead of a single page. You may choose how many ticket posts to display per page below.',
	't_pdpostlimit' => 'Number of Tickets Posts Per Page',
	'd_t_pdpostlimit' => 'If you have enabled the <i>"Split Ticket Posts By Page"</i> option, this specifies how many ticket posts to display on a single page. This applies only to the PDA staff control panel interface.',
	't_pdpostorder' => 'Display Order For Ticket Posts',
	'd_t_pdpostorder' => 'Whether to display the oldest or newest ticket posts first.',
	't_signores' => 'Ignore Words Containing Symbols',
	'd_t_signores' => 'Si se activa, words containing any of the following symbols will be ignored:<br /><br /><i>- ~ ` @ # $ ^ & * ( ) _ = + [ ] { } | / < > , . ; \' " \</i>',
	't_ccaptcha' => 'Enable CAPTCHA for Ticket Submission',
	'd_t_ccaptcha' => 'Require users who submit ticket via the client support interface to enter text displayed in a special image to attempt to verify whether they are human.',
	't_autoclose' => 'Ticket Automatic Close Settings',
	't_enautoclose' => 'Enable Auto Closure System',
	'd_t_enautoclose' => 'Automatically change the status of tickets that have lingered in the system for the specified amount of time.',
	't_acstatus' => 'Affected Ticket Statuses',
	'd_t_acstatus' => 'Select the ticket statuses the automatic close system will affect.  Select multiple statuses by holding the CTRL key and selecting multiple entries.',
	't_acdep' => 'Affected Departments',
	'd_t_acdep' => 'Select the departments that the automatic close system will affect. Select multiple departments by holding the CTRL key and selecting multiple entries.',
	't_acstatusch' => 'Target Status',
	'd_t_acstatusch' => 'Select the status to which tickets will be changed automatically once they have lingered for the specified time.',
	't_acinactive' => 'Automatic Closure Inactivity Threshold',
	'd_t_acinactive' => 'After a ticket has remained inactive for this amount of time (in hours), the system will send a notice to the user created the ticket, warning the user of the pending automatic status change.',
	't_acnoticeclose' => 'Final Automatic Close Threshold',
	'd_t_acnoticeclose' => 'After this amount of time (in hours) has elapsed (this starts after the "Automatic Closure Inactivity Threshold" has been reached), the target tickets\' status will automatically be changed.',
	't_arnews' => 'Send Latest News In Auto Responder Message',
	'd_t_arnews' => 'If enabled and if the News module is active, the five most recent news items will be sent inside of the ticket autoresponder (ticket receipt).',
	't_ticketlock' => 'Ticket Lock Settings',
	't_entlock' => 'Enable/Disable Ticket Locking',
	't_entplock' => 'Enable Reply Ticket Locking',
	'd_t_entplock' => 'Allow staff users to see other staff user\'s replies in real-time (as they draft their reply) when viewing the same ticket.',
	't_plockthreshold' => 'Threshold for Post Ticket Locking',
	'd_t_plockthreshold' => 'Any update to the reply made after this threshold (in seconds) will not be displayed to other staff users.',
	'd_t_entlock' => 'The ticket locking feature in ' . SWIFT_PRODUCT . ' will lock a ticket when a staff user opens the ticket. Other staff users will still be able to access the ticket, but a lock icon will be displayed letting other staff users know that the ticket is being viewed.',
	't_locktimeout' => 'Ticket Lock Timeout',
	'd_t_locktimeout' => 'Once this amount of time (in seconds) has elapsed (i.e. if the staff user causing the lock has been idle for this amount of time) the lock icon will not be displayed.',
	't_canirs' => 'Enable the Instant Response System (IRS)',
	'd_t_canirs' => 'Si se activa, when users draft their initial ticket submissions, ' . SWIFT_PRODUCT . ' will search the knowledgebase for relevant articles in real-time.  This feature cuts down on the amount of new tickets submitted, as users may frequently find the answers they are looking for before submitting their tickets.',
	't_maxwcnt' => 'Maximum Word Count for IRS',
	'd_t_maxwcnt' => 'After the amount of words specified here have been entered by the user, the IRS system will no longer continue looking up knowledgebase articles for suggestion.',
	't_reciplist' => 'List Recipients Before Replying',
	'd_t_reciplist' => 'Display the list of added recipients in a ticket. This adds an overhead of additional database queries in the ticket listing page.',
	't_staffcp' => 'Staff Control Panel Settings',
	't_scanirs' => 'Enable Instant Response System (IRS)',
	'd_t_scanirs' => 'Like the IRS in the client support interface, ' . SWIFT_PRODUCT . ' will suggest knowledgebase articles as staff users draft their replies.',
	't_advanced' => 'Advanced Ticket Settings',
	't_postlist' => 'Assign Post List Variable to Staff Replies',
	'd_t_postlist' => 'Include the entire history of the ticket to date in replies sent by staff members.  This does add overhead and could potentially slow down replies.',
	't_reciplimit' => 'Limit Recipients in Incoming Email',
	'd_t_reciplimit' => 'You can use this setting to limit the number of recipients from an incoming email, increasing this setting can cause issues whenver spam emails with high number of recipients are processed by the system.',
	't_mergrecip' => 'Add Users As Recipients When Merging',
	'd_t_mergrecip' => 'When two tickets are merged, add users whose email addresses are associated with either ticket as recipients in the ticket that results from the merge.  This ensures that all users will receive future correspondence associated with the tickets.',
	'tickets_bayesian' => 'Bayesian Filtering Settings',
	'tb_minwordlength' => 'Minimum Word Length',
	'd_tb_minwordlength' => 'Specify the Minimum Length of a Word for the Bayesian Indexing Engine. Any Word that does not meet this criteria will be ignored by the system.',
	'tb_maxwordlength' => 'Maximum Word Length',
	'd_tb_maxwordlength' => 'Specify the Maximum Length of a Word for the Bayesian Indexing Engine. Any Word which is bigger than the specified length will be ignored.',
	'tb_indexnumbers' => 'Index Numbers',
	'd_tb_indexnumbers' => 'Toggle the Indexing of Numbers',
	'tb_minnumberlength' => 'Minimum Number Length',
	'd_tb_minnumberlength' => 'Minimum Length for a Number to Qualify for Bayesian Indexing',
	'tb_signores' => 'Ignore Words with Symbols',
	'd_tb_signores' => 'Si se activa, Any word with a symbol in it will be ignored. This includes URLs, Phone Numbers (With - in them), Ticket IDs etc.',
	'tb_enablespam' => 'Enable Spam Filtering?',
	'd_tb_enablespam' => 'Si se activa, You can train the naive bayesian filter to filter out spam and non spam messages. Even with spam filtering disabled, you can still use the bayesian filtering engine to route tickets based on specified categories.',

	// ======= TROUBLESHOOTER =======
	'tr_staffcp' => 'Troubleshooter Staff Control Panel Settings',
	'tr_general' => 'Client Support Interface Troubleshooter Settings',
	'tr_staffwysiwyg' => 'Enable WYSIWYG Editor',
	'd_tr_staffwysiwyg' => 'Use the advanced WYSIWYG editor (rich text) for creating troubleshooter articles.',
	'tr_enableclient' => 'Display Troubleshooter Widget',
	'd_tr_enableclient' => 'Show the troubleshooter icon and link on the index.php page of the client support interface.',
	'tr_enablepopularcat' => 'Enable Popular Troubleshooters Box',
	'd_tr_enablepopularcat' => 'Show a list of the most popular troubleshooters on the index.php page of the client support interface.',
	'tr_maxpopularcat' => 'Maximum Number Of Troubleshooters To Display',
	'd_tr_maxpopularcat' => 'The maximum number of troubleshooters to display in the popular troubleshooters box.',
	'tr_displayviews' => 'Display Number Of Views',
	'd_tr_displayviews' => 'Display the number of views each troubleshooter category has received besides the category title.',
	'tr_displaynavbar' => 'Display Troubleshooters in Navigation Bar',
	'd_tr_displaynavbar' => 'Display troubleshooters at every step in the navigation bar.',
	'tr_entab' => 'Display Troubleshooter Tab',
	'd_tr_entab' => 'Show the Troubleshooter tab within the Staff Control Panel.',
	't_cstatusupd' => 'Default Ticket Status for Client Reply',
	'd_t_cstatusupd' => 'Automatically set tickets to this status when a client has replied.',
	'tsnochange' => '-- Do Not Change --',
	't_canrecip' => 'Users Can Specify Custom Recipients',
	'd_t_canrecip' => 'Allow users to specify custom "CC Recipients" to tickets that they create.',
	't_enhistory' => 'Send Complete History in Staff Replies?',
	'd_t_enhistory' => 'Include the entire history of the ticket to date in replies sent by staff members.  This does add overhead and could potentially slow down replies.',

	// ======= USER REGISTRATION =======
	'user_enableemailverification' => 'User Email Verification',
	'd_user_enableemailverification' => 'Si se activa, ' . SWIFT_PRODUCT . ' will verify the email address of the user when they register via the client support interface. Verification involves sending an email to the user containing an activation link which they must click to activate the account.',
	'user_enablecaptcha' => 'Enable CAPTCHA for New User Registration',
	'd_user_enablecaptcha' => 'Require users that register via the client support interface to enter text displayed in a special image to verify that they are human.',
	'user_autodelete' => 'Auto Clear',
	'user_adelunveri' => 'Automatically Clear Unverified Users',
	'd_user_adelunveri' => 'Purge unverified user accounts after a given amount of time (set below).',
	'user_delcleardays' => 'Auto Clear Timeline',
	'd_user_delcleardays' => 'The time (in days) after which unverified user accounts will be automatically purged from the system (if the above option is enabled).',
	'u_sendpw' => 'Send Password in Auto Responder (Ticket Receipt)',
	'd_u_sendpw' => 'Send the user\'s password to them whenever they create a new ticket.',
	'user_organizations' => 'User Organization Settings (Support Center)',
	'user_orgrestrictautoadd' => 'Allow Auto-Addition to Shared Organizations',
	'd_user_orgrestrictautoadd' => 'Si se activa, the user will be allowed to be a part of a shared organization through his profile. This setting only applies to organization names entered through the support center.<br/><br /><i>NOTE: This can cause a security risk allowing anyone to specify an organization name and access all tickets under it</i>',
	'user_orgselection' => 'User Organization Selection',
	'd_user_orgselection' => 'Select whether the user is allowed to be a part of an organization or how the system should behave when the user enters an organization name.<br/><br/><i>Do not allow:</i> The user will not be allowed to enter an organization name<br /><i>Create New Record:</i> A new organization will be created whenever a user enters an organization name<br /><i>Create/Auto Merge:</i> A new organization will be created or the user will be merged into one if it exists.',
	'uodontallow' => 'Do not allow',
	'uocreatenew' => 'Create New',
	'uocreatemerge' => 'Create/Auto Merge',
	'user_orgprofileupdate' => 'Organization Profile Update',
	'd_user_orgprofileupdate' => 'Select who can update the organization profile.',
	'uoallusers' => 'All Users',
	'uomanagersonly' => 'Managers Only',
	'user_orgdefaultclassification' => 'Default User Classification',
	'd_user_orgdefaultclassification' => 'Select how a new user is to be classified as.<br /><br/><i>User:</i> All new users are classified as \'normal users\'<br/><i>Manager:</i> A user is classified as a manager if none exists for that organization.',
	'uouser' => 'User',
	'uomanager' => 'Manager',
	'user_dispatchregemail' => 'Dispatch Registration Email',
	'd_user_dispatchregemail' => 'Si se activa, the user will receive an email with his profile details (including his password) after registration.',

	// ======= NEWS =======
	'nw_general' => 'News Settings',
	'nw_sendstaffemail' => 'Send Email Updates to Staff',
	'd_nw_sendstaffemail' => 'Si se activa, the staff users will receive email updates whenever a news article is created or updated. This setting is restricted to news article with type of Global and Private.',
	'nw_sync' => 'Synchronization Settings',
	'nw_globalsync' => 'Global News RSS URL',
	'd_nw_globalsync' => 'Specify the URL to the RSS feed from which the global news will be synchronized.',
	'nw_publicsync' => 'Public News RSS URL',
	'd_nw_publicsync' => 'Specify the URL to the RSS feed from which the public news will be synchronized.',
	'nw_privatesync' => 'Private News RSS URL',
	'd_nw_privatesync' => 'Specify the URL to the RSS feed from which the private news will be synchronized.',
	'nw_wysiwyg' => 'Enable WYSIWYG Editor',
	'd_nw_wysiwyg' => 'Use the advanced WYSIWYG editor (rich text) for creating news articles.',
	'nw_newsstaffcp' => 'Staff Control Panel News Settings',
	'nw_newsclient' => 'Client Support Interface News Settings',
	'nw_enableclient' => 'Display News Widget',
	'd_nw_enableclient' => 'Display the news icon and link on the index.php page of the client support interface.',
	'nw_enablestaffdashboard' => 'Display Latest News on Dashboard',
	'd_nw_enablestaffdashboard' => 'Display the latest news articles in the welcome tab of staff dashboard.',
	'nw_maxdashboardnewslist' => 'Maximum Number of Dashboard News Articles',
	'd_nw_maxdashboardnewslist' => 'The maximum number of most recent news articles that will be displayed on the staff dashboard.',
	'nw_enablenewsnav' => 'Display Latest News on Index Page',
	'd_nw_enablenewsnav' => 'Display the latest news articles at the bottom of the index page.',
	'nw_maxnewslist' => 'Maximum Number of Recent News Articles',
	'd_nw_maxnewslist' => 'The maximum number of most recent news articles that will be displayed on the index page.',
	'nw_navdisplaydate' => 'Display Date Beside News Items',
	'd_nw_navdisplaydate' => 'Display the date a news posting was made alongside the title of the posting.',
	'nw_navdateformat' => 'Navigation News Date Format',
	'd_nw_navdateformat' => 'The format in which the posting date of news items is displayed. For more information, see the documentation for the PHP <a href="http://www.php.net/date" target="_blank">date()</a> function.',
	'nw_rss' => 'RSS Syndication Settings',
	'nw_enablerss' => 'Enable RSS Content Syndication',
	'd_nw_enablerss' => 'Allow users to subscribe to RSS feeds of posted news items.',
	'nw_maxrss' => 'Maximum Limit of Latest News Items for RSS Feed',
	'd_nw_maxrss' => 'The maximum number of news articles that will be syndicated into an RSS feed at any one time.',
	'nw_entab' => 'Display News Tab',
	'd_nw_entab' => 'Display the News tab within the Staff Control Panel.',
	'nw_svalidate' => 'Validate Subscriber Email Address',
	'd_nw_svalidate' => 'Specify whether ' . SWIFT_PRODUCT . ' should verify the email address of the user when they subscribe to news postings through the client support interface. Verification involves sending an email to the user containing an activation link which they must click to activate the account.',
	'nw_pageno' => 'Number of News Items Per Page',
	'd_nw_pageno' => 'The number of news items shown on one page.',
	'nw_staffpageno' => 'Number of News Items Per Page',
	'd_nw_staffpageno' => 'The number of news items shown on one page.',

	// ======= DOWNLOADS =======
	'dl_clientarea' => 'Downloads Settings',
	'dl_enableclient' => 'Display Downloads Widget',
	'd_dl_enableclient' => 'Show the Downloads icon and link on the index.php page of the client support interface.',
	'dl_enpopularfiles' => 'Display Popular Downloads Box',
	'd_dl_enpopularfiles' => 'Show a list of the most popular downloads on the index.php page of the client support interface.',
	'dl_maxpopularfiles' => 'Maximum Number Of Popular Downloads',
	'dl_dispdownloadcnt' => 'Display Download Count In Popular Downloads Box',
	'dl_enlatestfiles' => 'Display Latest Downloads Box',
	'd_dl_enlatestfiles' => 'Show a list of the most recently uploaded downloads on the index.php page of the client support interface.',
	'dl_maxlatestfiles' => 'Maximum Number Of Latest Downloads To Display',
	'dl_displaydldate' => 'Display Posting Date Of Latest Downloads',
	'dl_dispdateformat' => 'Posting Date Format',
	'd_dl_dispdateformat' => 'Specify the format used to display dates in download items. For more information, see the documentation for the PHP <a href="http://www.php.net/date" target="_blank">date()</a> function.',
	'dl_staffcp' => 'Downloads Staff Control Panel Settings',
	'dl_entab' => 'Display Downloads Tab',
	'd_dl_entab' => 'Show the Downloads tab within the staff control panel.',
	'dl_rss' => 'RSS Syndication Settings',
	'dl_enrss' => 'Enable RSS Content Syndication',
	'd_dl_enrss' => 'Allow users to subscribe to RSS feeds for new download item postings.',
	'dl_rsslinkfile' => 'Link Directly To Download',
	'd_dl_rsslinkfile' => 'Show a link directly to the download in the RSS feed for each download item. If disabled, a link to the download page will be included.',
	'dl_catindex' => 'Client Support Interface Category Index Settings',
	'dl_defaultdisp' => '-- Default Display Order --',
	'dl_alphabetical' => 'Alphabetical',
	'dl_chrono' => 'Chronological',
	'dl_totalitems' => 'Total Items',
	'dl_datemodified' => 'Date Modified',
	'dl_totaldownloads' => 'Total Downloads',
	'dl_asc' => 'Ascending',
	'dl_desc' => 'Descending',
	'dl_catdisplayorder' => 'Category Display Order Override',
	'd_dl_catdisplayorder' => 'Use this display order instead of the display order chosen when the categories were created. Select <i>Default Display Order</i> to use the display order specified when creating the categories.',
	'dl_catorder' => 'Category Display Order',
	'd_dl_catorder' => 'Select the default category display order.',
	'dl_itdisplayorder' => 'Download Items Display Order Override',
	'd_dl_itdisplayorder' => 'Use this display order instead of the display order chosen when the download items were created. Select <i>Default Display Order</i> to use the display order specified when creating the download items.',
	'dl_itorder' => 'Download Items Order Of Display',
	'd_dl_itorder' => 'The way the downloads will be ordered.',
	'dl_maxcatarticles' => 'Item Limit Under Subcategories',
	'd_dl_maxcatarticles' => 'The maximum number of downloads displayed under download subcategories.',
	'dl_displaymore' => 'Display More Download Link',
	'd_dl_displaymore' => 'Show a "Display More" link under download subcategories, showing users more downloads are available within a category.',
	'dl_catarticledetails' => 'Display Item Description In List',
	'd_dl_catarticledetails' => 'Show the description for a download item when listing items in a category.',
	'dl_climit' => 'Download Description Character Limit',
	'd_dl_climit' => 'The maximum number of characters shown for the download description (see the setting above).',

	// ======= KNOWLEDGEBASE =======
	'kb_clientarea' => 'General Knowledgebase Settings',
	'kb_clientareaindex' => 'Client Support Interface Index Page Settings',
	'kb_categoryindex' => 'Category Index Settings',
	'kb_enableclient' => 'Display Knowledgebase Widget',
	'd_kb_enableclient' => 'Show the knowledgebase icon and link on the index.php page of the client support interface.',
	'kb_enpopulararticles' => 'Display Popular Articles Box',
	'd_kb_enpopulararticles' => 'Show a list of the most popular knowledgebase articles on the index.php page of the client support interface.',
	'kb_maxpopulararticles' => 'Maximum Number Of Popular Articles',
	'kb_dispviews' => 'Display View Count Next To Popular Articles',
	'kb_enlatestarticles' => 'Display Latest Articles Box',
	'd_kb_enlatestarticles' => 'Show a list of the most recent knowledgebase articles on the <i>index.php</i> page of the client support interface.',
	'kb_maxlatestarticles' => 'Maximum Number Of Latest Articles',
	'kb_displayarticledate' => 'Display Creation Date Next To Latest Articles',
	'kb_dateformat' => 'Creation Date Format',
	'd_kb_dateformat' => 'Specify the format used to display creation dates in articles. For more information, see the documentation for the PHP <a href="http://www.php.net/date" target="_blank">date()</a> function.',
	'kb_maxcatarticles' => 'Maximum Number of Articles to Display under Category List',
	'kb_displaymore' => 'Display "More Topics" Link Under Category List',
	'kb_catarticledetails' => 'Display Article Details Under Category List',
	'kb_alphabetical' => 'Alphabetical',
	'kb_chrono' => 'Chronological',
	'kb_totalarticles' => 'Total Articles',
	'kb_catdisplayorder' => 'Override Category Display Order Field',
	'd_kb_catdisplayorder' => 'Specify the display order to be used when sorting categories. Select <i>Default Display Order</i> to use the display order specified when creating article categories.',
	'kb_catorder' => 'Category Order Of Display',
	'kb_asc' => 'Ascending',
	'kb_desc' => 'Descending',
	'kb_arorder' => 'Article Order Of Display',
	'd_kb_ardisplayorder' => 'Use the specified display order to sort articles. Select <i>Default Display Order</i> to use the display order specified when creating articles.',
	'kb_ardisplayorder' => 'Override Article Display Order Field',
	'kb_datemodified' => 'Date Modified',
	'kb_views' => 'Total Views',
	'kb_rating' => 'Article Rating',
	'kb_defaultdisp' => '-- Default Display Order --',
	'kb_enrss' => 'Enable RSS Content Syndication',
	'kb_rss' => 'RSS Syndication Settings',
	'd_kb_enrss' => 'Enable users to subscribe to new article postings.',
	'kb_climit' => 'Article Preview Character Limit',
	'd_kb_climit' => 'The maximum number of characters that will be displayed for an article preview under a category index. To disable article previews, set this value to "0".',
	'kb_rssclimit' => 'RSS Feed Character Limit',
	'd_kb_rssclimit' => 'The maximum number of characters of an article that will be syndicated into an RSS feed.',
	'kb_enrating' => 'Enable Article Rating',
	'd_kb_enrating' => '',
	'kb_categorycolumns' => 'Number of Category Columns',
	'd_kb_categorycolumns' => 'Specify the number of columns to group the categories into.',
	'kb_staffcp' => 'Knowledgebase Staff Control Panel Settings',
	'kb_staffwysiwyg' => 'Enable WYSIWYG Editor',
	'd_kb_staffwysiwyg' => 'Use the advanced WYSIWYG editor (rich text) for creating new articles.',
	'kb_entab' => 'Display Knowledgebase Tab',
	'd_kb_entab' => 'Enable the Knowledgebase tab within the Staff Control Panel.',
	'kb_parcount' => 'Count Articles In Subcategories',
	'd_kb_parcount' => 'Si se activa, ' . SWIFT_PRODUCT . ' will include articles stored in subcategories when counting articles in a category. Deeply nested knowledgebase structures can be very resource intensive.',

	// ======= TEAMWORK =======
	'tw_syncworks' => 'There are no settings available for this module.',

	//======== PURCHASER ======
	'settings_purchase' => 'Ticket Purchaser',
	'purchase_admin_email' => 'Billing Email',
	'purchase_money_format' => 'Currency Symbol Position',
	'purchase_number_format_style' => 'Number Format',
	'purchase_money_sign' => 'Currency Symbol',
	'purchase_bluepay_account' => 'Bluepay Account Number',
	'purchase_bluepay_key' => 'Bluepay Secret Key',
	'purchase_bluepay_mode' => 'Bluepay Transaction Mode',
	'purchase_bluepay_mode_test' => 'Test',
	'purchase_bluepay_mode_live' => 'Live',
	'purchase_invoice_address' => 'Billing address to display on invoices',

	// ======= RINGROUTE =======
	'rr_general' => 'General RingRoute Settings',
	'ringrouteenable' => 'Enable RingRoute',
	'd_ringrouteenable' => 'Use this option to enable/disable the RingRoute VoIP system',
	'ringrouteusername' => 'RingRoute Email',
	'd_ringrouteusername' => 'Please enter your registered RingRoute email address. The access credentials should match the one you use to login into the RingRoute control panel.',
	'ringroutepassword' => 'RingRoute Password',
	'd_ringroutepassword' => 'Enter the RingRoute password.',

	// ======= ONSITE =======
	'ons_general' => 'General OnSite Settings',
	'ons_primaryserver' => 'Primary Server',
	'd_ons_primaryserver' => 'The host name or IP address of the OnSite server that should be used to negotiate a P2P NAT traversal session.',
	'ons_secondaryserver' => 'Secondary Server',
	'd_ons_secondaryserver' => 'The host name or IP address of the OnSite server that should be used when the primary server is unavailable due to technical difficulties.',
	'ons_portrange' => 'Port Range',
	'd_ons_portrange' => 'The number of sequential ports that should be tried during the P2P negotiation. The default value is 3.',
	'ons_retrytolerance' => 'Retry Tolerance',
	'd_ons_retrytolerance' => 'The number of times the P2P pairing operation will be attempted (endpoint exchange). This is used for cases where the other endpoint hasn\'t regsitered with the server yet. The default value is 3.',
	'ons_retrywait' => 'Retry Wait',
	'd_ons_retrywait' => 'The number of seconds to wait in between attempts at the P2P pairing operation (endpoint exchange) The default value is 5.',
	'ons_pairingtimeout' => 'Pairing Timeout',
	'd_ons_pairingtimeout' => 'The number of seconds to wait after making all outgoing P2P connection attempts before completely giving up. The default value is 30.',

	// ======= REPORT =======
	'rep_general' => 'Reports Settings',
	'rep_maxrows' => 'Max Rows',
	'd_rep_maxrows' => 'The maximum number of rows to display in a page for tabular/summary reports',
);

?>