<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

/**
* ###############################################
* Setting Groups, Items and other text.
* Descript Text Example: d_startofweek or d_general
* ###############################################
*/

$__LANG = array (
	'settings' => 'Configuración',
	'desc_settings' => 'Desde aquí puede administrar toda la configuración de funcionamiento y los ajustes generales del sistema.',
	'systemsettings' => 'Configuración del sistema',
	'loginsharesettings' => 'Configuración LoginShare',
	'staff' => 'Operadores',
	'users' => 'Usuarios',
	'restapi' => 'API REST',
	'reports' => 'Informes',
	'groups' => 'Grupos',
	'settingsfor' => 'Configuración de: %s',
	'updatesettings' => 'Actualizar configuración',
	'settingsupdatedfor' => 'Actualizada configuración del grupo "%s"',
	'titleurlinvaliddata' => 'Datos no válidos',
	'desc_titleurlinvaliddata' => SWIFT_PRODUCT . ' no puede actualizar el campo de URL ya que contiene datos con formato incorrecto.',

	// ======= SETTING GROUPS =======
	'settings_general' => 'General',
	'settings_cpu' => 'Servidor y Optimización CPU',
	'settings_security' => 'Seguridad',
	'settings_datetime' => 'Fecha y hora',
	'settings_livesupport' => 'Chat',
	'settings_tickets' => 'Tickets',
	'settings_parser' => 'Procesador de correo',
	'settings_tr' => 'Asistente',
	'settings_users' => 'Usuarios y Organizaciones',
	'settings_nw' => 'Noticias',
	'settings_dl' => 'Descargas',
	'settings_kb' => 'Biblioteca',
	'settings_tw' => 'Trabajo en equipo',
	'settings_ringroute' => 'RingRoute',
	'settings_mail' => 'Configuración email',
	'settings_livechat' => 'Chat',
	'settings_loginshare' => 'LoginShare',
	'settings_onsite' => 'OnSite',
	'settings_reports' => 'Informes',

	// ======= IMPORT FROM v3 CVS =======
	'g_whmcstgroup' => 'Grupo de plantillas WHMCS',
	'd_g_whmcstgroup' => 'Seleccione el grupo de plantillas por defecto para la integración con WHMCS. Este grupo invalidará el grupo de plantillas por defecto. Podrá mostrar un grupo de plantillas diferente cuando ' . SWIFT_PRODUCT . ' se use vía WHMCS y otro cuando se acceda normalmente.',
	'g_supportcenter' => 'Configuración Centro de Soporte',
	'g_returnlogout' => 'Al cerrar sesión volver al grupo de plantillas por defecto',
	'd_g_returnlogout' => 'Redirige al usuario al grupo de plantillas por defecto tras cerrar la sesión.',
	'g_overrideswiftpath' => 'Anular las variables $swiftpath y $themepath automáticamente',
	'd_g_overrideswiftpath' => 'Si se activa, el sistema intentará determinar las variables de plantilla $swiftpath y $themepath por la URL. Esto le permite crear instalaciones de helpdesk multipunto usando una sola base de datos.',
	'dt_timezonephp' => 'Zona horaria',
	'd_dt_timezonephp' => 'La zona horaria por defecto del sistema. Los operadores tienen la opción de anular esta zona horaria para reflejar la suya propia (a travñes de las Preferencias de Operadores en el Panel de Control de Operadores).',
	'livesupport_usehttps' => 'Usar siempre conexión segura (https) para los chats',
	'd_livesupport_usehttps' => 'Si está activado, todas las sesiones de chat se transportarán por https.',
	'pr_loopoptions' => 'Configuración de control de bucles',
	'pr_loopcut_prevents_autoresponder' => 'No enviar autorrespuesta',
	'd_pr_loopcut_prevents_autoresponder' => 'Si se activa, ' . SWIFT_PRODUCT . ' no enviará la confirmación de recepción para el mensaje que hizo saltar la regla de control de bucles.  <em>Se recomienda encarecidamente que esta opción este siempre activada.</em>',
	'pr_loopcut_ignores_cut_mail' => 'Ignorar mensaje de email',
	'd_pr_loopcut_ignores_cut_mail' => 'Si se activa, los mensajes que hagan saltar las reglas de control de bucles no serán procesados.',
	't_autorespondercc' => 'Despachar autorrespuesta para usuarios CC?',
	'd_t_autorespondercc' => 'Si se activa, ' . SWIFT_PRODUCT . ' enviará automáticamente un mensaje de autorrespuesta a los usuarios CC. El mensaje de autorrespuesta se enviará sin la contraseña del creador incluso si esta opción está activada.',
	't_ochtml' => 'Conversión de HTML (Respuestas operadores)',
	'd_t_ochtml' => 'Elija como tratar el contenido HTML en las respuestas de email enviadas por los oepradores. Esta opción afectará al contenido que llega al usuario.<br><dl><dt><b>Entidades HTML</b></dt><dd>Convierte el HTML a texto normal de manera que se puede ver el código.</dd><dt><b>Eliminar etiquetas</b></dt><dd>Elimina el formato HTML completamente; (p.ej "<b>foo</b>" = "foo").</dd><dt><b>No procesar</b></dt><dd>Permitir código HTML (p.ej "<b>foo</b>" = "<b>foo</b>").  Esta opción <b>no</b> se recomienda ya que puede permitir la ejecución de código malicioso en las aplicaciones de correo electrónico.</dd></dl><i>Nota: Esta opción no afecta al contenido final almacenado en la base de datos!</i>',
	't_allowhtml' => 'Permitir etiquetas HTML',
	'd_t_allowhtml' => 'Si se activa, algunas etiquetas HTML (opción siguiente) se permitirán, incluso si se establece la conversión HTML en <i>Eliminar Etiquetas</i>.',
	't_allowableadvtags' => 'Etiquetas HTML permitidas',
	'd_t_allowableadvtags' => 'Si la opción anterior está activada, se permitirán las siguientes etiquetas HTML.',
	't_searchticketidinbody' => 'Buscar ID de ticket en el cuerpo del email?',
	'd_t_searchticketidinbody' => 'Si se activa, ' . SWIFT_PRODUCT . ' intentará buscar el ID de ticket en el cuerpo del email si no lo encuentra en el asunto.',
	'tr_captcha' => 'Activar CAPTCHA para comentarios',
	'd_tr_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'nw_captcha' => 'Activar CAPTCHA para comentarios',
	'd_nw_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'dl_captcha' => 'Activar CAPTCHA para comentarios',
	'd_dl_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',
	'kb_captcha' => 'Activar CAPTCHA para comentarios',
	'd_kb_captcha' => 'Si se activa, los usuarios tendrán que comprobar una imagen CAPTCHA antes de enviar un comentario.',

	// ======= GENERAL SETTINGS =======
	'general_companyname' => 'Nombre de la empresa',
	'd_general_companyname' => 'El nombre que se usará como marca en el Centro de Soporte y en los emails salientes.',
	'general_producturl' => 'URL del producto',
	'd_general_producturl' => 'Introduzca la ruta completa a la URL donde está instalado el producto. Este valor DEBE incluir una barra al final. ' . SWIFT_PRODUCT . ' no funcionará correctamente si este valor es erróneo.',
	'general_returnemail' => 'Dirección email de retorno por defecto',
	'd_general_returnemail' => 'Esta dirección se usará como dirección remitente por defecto en el correo saliente. Esta dirección debe corresponder con una cola de email activa para poder aceptar respuestas de usuarios.',
	'general_redirecttype' => 'Tipo de redirección',
	'd_general_redirecttype' => 'Seleccionar <i>Recarga de HTML Meta</i> para presentar una confirmación de acción antes de redigirir a la siguiente página.',
	'refreshunix' => 'Recarga cabeceras',
	'refreshwindows' => 'Recarga de HTML Meta',
	'general_defaultlanguage' => 'Idioma por defecto',
	'general_themeoptions' => 'Opciones de tema por defecto',
	'g_displaytopheader' => 'Mostrar logotipo en cabecera',
	'd_g_displaytopheader' => 'Activa o desactiva el mostrado del logotipo de la cabecera en el el panel de control de operadores y administradores.<br /><br /><i>NOTA: Necesitará forzar la recarga de la página (Ctrl+F5 o Comando+R) para que esta opción tenga efecto.</i>',
	'g_cpmenu' => 'Estilo de navegación por el menú',
	'd_g_cpmenu' => 'Seleccione el estilo de navegación <i>Pasar por encima</i> para activar una pestaña simplemente pasando el ratón sobre ella.',
	'navleft' => 'Izquierda',
	'navright' => 'Derecha',
	'g_commentsapproval' => 'Moderar comentarios',
	'd_g_commentsapproval' => 'Requiere aprobación manual de los comentarios introducidos por los usuarios.',
	'menuhover' => 'Pasar por encima',
	'menuclick' => 'Pulsar',
	'g_jscache' => 'Caché Javascript para elementos del tema',
	'd_g_jscache' => 'Guarda en caché elementos muy descargados como el menú y la barra de navegación para que las páginas carguen más rápido. Esto deshabilita la vista de comentarios en tiempo real y el contador de mensajes privados en el menú.',
	'g_onlusr' => 'Mostrar operadores conectados en el panel de operadores',
	'd_g_onlusr' => 'Muestra una lista de los operadores conectados y las acciones que están realizando.',
	'g_api' => 'Configuración API',
	'g_enableapiinterface' => 'Activar API',
	'd_g_enableapiinterface' => 'Si se activa, el interfaz API aceptará todas las peticiones debidamente autenticadas.',
	'g_cpdefaultskin' => 'Tema por defecto',
	'd_g_cpdefaultskin' => 'Seleccione el tema por defecto para el panel de control de administración y operadores. Cambiar el tema por defecto requerirá forzar la recarga de la página (Ctrl+F5 o Ctrl+Mayus+R) para poder ver los cambios.',
	'defaultskin' => 'Tema por defecto',
	'skin_modernblue' => 'Azul Moderno',
	'skin_lite' => 'Lite',
	'g_generalsettings' => 'Configuración general',
	'g_maxtagcloud' => 'Máximo número de elementos en nube de etiquetas',
	'd_g_maxtagcloud' => 'Introduzca el número máximo de elementos a mostrar en la nube de etiquetas.',
	'g_maxsearchresults' => 'Máximos resultados búsquedas',
	'd_g_maxsearchresults' => 'Introduzca el número máximo de resultados a mostrar en el Centro de Soporte de usuarios.',

	// ======= CPU SAVING & OPTIMIZATION =======
	'cpu_attachments' => 'Configuración de adjuntos',
	'cpu_attachtype' => 'Lugar de almacenamiento de adjuntos',
	'd_cpu_attachtype' => 'Especifique el lugar en que se almacenarán los adjuntos. Si se selecciona la opción "archivos, todos los adjuntos se almacenarán en el sistema de archivos como archivos individuales (con nombres cifrados). Si se selecciona la opción de base de datos, se almacenarán los adjuntos en la base de datos.',
	'database' => 'Base de datos',
	'files' => 'Sistema de archivos (Directorio "files")',
	'cpu_attachchunksize' => 'Tamaño de parte de archivo en base de datos',
	'd_cpu_attachchunksize' => 'Cada adjunto guardado en la base de datos se divide en un número de partes con el tamaño en bytes especificado aquí. Este número no debería ser mayor que el especificado en la opción<b>maximum packet size</b> del archivo <i>my.cnf</i> (Archivo de configuración de MySQL).',
	'cpu_optimization' => 'Ajustes de optimizacióbn',
	'cpu_winappcompresslevel' => 'Nivel de compresión GZIP',
	'd_cpu_winappcompresslevel' => 'Seleccione el nivel de compresión de las páginas. Valores mayores ocuparán mayor potencia de proceso pero descargarán menos datos. Si se especifica un nivel demasiado alto, los tiempos de carga de página podrían subir. el valor recomendado es <i>1 - Recomendado</i>.',
	'nocompression' => 'No comprimir',
	'reccompression' => 'Recomendado',
	'highestcompression' => 'Alto',
	'cpu_compresswinappdata' => 'Comprimir salida de aplicación de escritorio',
	'cpu_logcleardays' => 'Tiempo de borrado de logs (en días)',
	'd_cpu_logcleardays' => 'Especifique el número de días tras los que se borrarán los logs del sistema.',
	'cpu_smsgateway' => 'Pasarela SMS',
	'gateway_enable' => 'Activar pasarela SMS',
	'd_gateway_enable' => 'La pasarela SMS de Kayako puede enviar alertas directas a teléfonos móviles. Para más información visite el <a target="_blank" href="http://my.kayako.com">Portal de clientes de Kayako</a>.',
	'gateway_username' => 'Usuario pasarela',
	'd_gateway_username' => 'El usuario de la pasarela SMS. Es la misma dirección de email usada para iniciar sesión en el <a target="_blank" href="https://my.kayako.com">Portal de clientes de Kayako</a>.',
	'gateway_password' => 'Contraseña pasarela',
	'd_gateway_password' => 'La contraseña de la pasarela SMS. Es la misma contraseña usada para iniciar sesión en el <a target="_blank" href="https://my.kayako.com">Portal de clientes de Kayako</a>.',
	'cpu_mailsettings' => 'Configuración email saliente',
	'cpu_enablehtmlmails' => 'Correo HTML',
	'd_cpu_enablehtmlmails' => 'Envía el correo saliente en formato HTML. ' . SWIFT_PRODUCT . ' enviará también una versión de texto plano para que el contenido pueda ser visualizado en clientes de email sencillos. El aspecto y contenido de los mensajes se puede cambiar editando las plantillas en <i>Plantillas > Administrar plantillas</i>.',
	'd_tickets_resattachments' => 'Si se activa, solo se procesarán los adjuntos que aparezcan en la lista de tipos de adjunto personalizados en <i>Tickets > Tipos de adjunto</i>. Se ignorará cualquier otro tipo de adjunto.',
	'cpu_enablemailqueue' => 'Cola de envío',
	'd_cpu_enablemailqueue' => 'Usa un sistema de cola para el email saliente. ' . SWIFT_PRODUCT . ' realizará los envíos masivos de email en varias pasadas. Esto puede prevenir la ralentización del servidor.',
	'cpu_mailqueuebatch' => 'Emails enviados por pasada',
	'd_cpu_mailqueuebatch' => 'El número de emails a enviar en cada pasada. Cuanto más alto sea este valor más recursos del sistema consumirá cada pasada.',
	'cpu_smtp' => 'Configuración SMTP',
	'cpu_enablesmtp' => 'Activar SMTP',
	'd_cpu_enablesmtp' => 'Seleccione si se debe usar un servidor SMTP para enviar el email. Por defecto, ' . SWIFT_PRODUCT . ' usará la función mail() interna de PHP para enviar el email.',
	'cpu_smtphost' => 'Servidor SMTP',
	'd_cpu_smtphost' => 'El nombre o la dirección IP del servidor SMTP.',
	'cpu_smtpport' => 'Puerto SMTP',
	'd_cpu_smtpport' => 'El número de puerto del servidor SMTP, <i>normalmente el puerto 25</i>.',
	'cpu_smtpportssl' => 'Puerto SMTP (TLS/SSL)',
	'd_cpu_smtpportssl' => 'Especifique el puerto de su servidor SMTP. No se debe cambiar este valor si no es necesario, ya que la mayoría de servidores SMTP (TLS/SSL) funcionan sobre el puerto 465',
	'cpu_smtpuseauth' => 'Usar autenticación SMTP',
	'd_cpu_smtpuseauth' => 'Usar la información siguiente para autenticarse en el servidor SMTP.',
	'cpu_smtpuser' => 'Usuario SMTP',
	'd_cpu_smtpuser' => 'El usuario que ' . SWIFT_PRODUCT . ' usará para autenticar con el servidor SMTP.',
	'cpu_smtppass' => 'Contraseña SMTP',
	'd_cpu_smtppass' => 'La contraseña que ' . SWIFT_PRODUCT . ' usará para autenticar con el servidor SMTP.',
	'gat_emailfailure' => 'Informes de fallos de envío',
	'd_gat_emailfailure' => 'Enviar informes de fallo de envío al correo electrónico del administrador principal.',
	'cpu_smtptype' => 'Tipo de SMTP',
	'd_cpu_smtptype' => 'Seleccione el tipo de servidor SMTP.',
	'smtpssl' => 'SSL',
	'smtptls' => 'TLS',
	'smtpnonssl' => 'Non SSL',
	'smtpssl2' => 'SSL v2',
	'smtpssl3' => 'SSL v3',
	'encqp' => 'quoted-printable',
	'encbase64' => 'base64',
	'encbinary' => 'binary',
	'enc7bit' => '7bit',
	'enc8bit' => '8bit',
	'cpu_headerencoding' => 'Juego caracteres cabecera',
	'd_cpu_headerencoding' => 'Especifique el juego de caracteres para las variables de cabecera (De, Asunto, Para)',
	'cpu_messageencoding' => 'Juego caracteres mensaje',
	'd_cpu_messageencoding' => 'Especifique el juego de caracteres por defecto para los datos del mensaje (Texto y HTML)',
	'cpu_maildefaultpriority' => 'Prioridad por defecto',
	'd_cpu_maildefaultpriority' => 'Especifique la prioridad por defecto para los emails salientes',
	'mailprioritylow' => 'Baja (5)',
	'mailprioritynormal' => 'Normal (3)',
	'mailpriorityhigh' => 'Alta (1)',

	// ======= SECURITY =======
	'security_autoapprovecomments' => 'Aprobar comentarios automáticamente',
	'd_security_autoapprovecomments' => 'Si se activa, todos los comentarios serán aprobados automáticamente tras pasar los filtros de spam (si están activados).',
	'security_enableakismet' => 'Activar filtro de spam Akismet',
	'd_security_enableakismet' => 'Si se activa ' . SWIFT_PRODUCT . ' revisará todos los comentarios enviados con el filtro Akismet. Para usar Akismet es necesaria una "API key". Para más información visite <a href="http://akismet.com" target="_blank">http://akismet.com</a>.',
	'security_akismetkey' => 'API Key de Akismet',
	'd_security_akismetkey' => 'Introduzca aquí su API key de Akismet.',
	'security_commentscaptcha' => 'Activar captcha para los comentarios',
	'd_security_commentscaptcha' => 'Solicita a los usuarios que quieran publicar comentarios en el Centro de Soporte que introduzcan el texto mostrado en una imagen especial para verificar que son humanos.',
	'security_rememberme' => 'Recuerdame: Almacenar contraseña',
	'd_security_rememberme' => 'Si se activa, cuando un operador seleccione la opción "recuérdame" al iniciar sesión, el sistema guardará la contraseña y el nombre de usuario en una cookie.<br/><br/><i>NOTA: Esto puede producir riesgos de seguridad si se descuber una vulnerabilidad XSS.</i>',
	'security_sessioninactivity' => 'Final sesión por inactividad',
	'd_security_sessioninactivity' => 'El tiempo en segundos tras el cual se finalizará una sesión inactiva.',
	'security_sessionvar' => 'Tipo de variable de sesión',
	'security_visitorinactivity' => 'Expiración de sesión de visitantes',
	'd_security_visitorinactivity' => 'El tiempo en segundos tras el cual los visitantes (seguidos a través de la aplicación de escritorio de ' . SWIFT_PRODUCT . ') serán marcados como inactivos y se borrarán sus sesiones. Incrementar este valor consumirá más recursos del sistema.',
	'security_cookiedomain' => 'Dominio de cookies',
	'd_security_cookiedomain' => 'El dominio de las cookies. Cambie este valor únicamente si hay varias instalaciones de ' . SWIFT_PRODUCT . ' en el mismo dominio.',
	'security_cookiepath' => 'Ruta de cookies',
	'd_security_cookiepath' => 'La ruta de las cookies. Cambie este valor únicamente si hay varias instalaciones de ' . SWIFT_PRODUCT . ' en el mismo dominio.',
	'cookie' => 'Cookie',
	'url' => 'URL',
	'urlcookie' => 'URL y cookie',
	'security_staffpasswordpolicy' => 'Política de contraseñas de operador',
	'security_sppminchars' => 'Longitud mínima',
	'd_security_sppminchars' => 'Especifique el número mínimo de caracteres que debe tener la contraseña de operador.',
	'security_sppminnumbers' => 'Mínimos dígitos',
	'd_security_sppminnumbers' => 'Especifique el número mínimo de dígitos numéricos que debe contener la contraseña de operador.',
	'security_sppminsymbols' => 'Mínimos símbolos',
	'd_security_sppminsymbols' => 'Especifique el número mínimo de símbolos que debe contener la contraseña de operador.',
	'security_sppmincapitalchars' => 'Mínimas mayúsculas',
	'd_security_sppmincapitalchars' => 'Especifique el número mínimo de letras mayúsculas que debe contener la contraseña de operador.',
	'security_sppexpiredays' => 'Caducidad de contraseña (días)',
	'd_security_sppexpiredays' => 'Especifique el número de días tras los que caducará la contraseña de operador. Introduzca "0" si no desea usar esta característica.',
	'security_captcha' => 'Configuración de CAPTCHA',
	'security_captchatype' => 'Tipo de CAPTCHA',
	'captchalocal' => 'Local (PHP GD)',
	'captcharecaptcha' => 'ReCAPTCHA',
	'd_security_captchatype' => 'Seleccione el tipo de CAPTCHA. ' . SWIFT_PRODUCT . ' usará por defecto las funciones GD de PHP para generar la imagen CAPTCHA. ReCaptcha es más eficiente y además ayuda a digitalizar libros. Para más información visite <b><a href="http://www.recaptcha.net" target="_blank">recaptcha.net</a></b>, Para usar ReCAPTCHA, necesitará dar de alta una cuenta en el sitio web de ReCAPTCHA e introducir las credenciales necesarias aquí.',
	'security_recpublickey' => 'ReCAPTCHA Public Key',
	'd_security_recpublickey' => 'Introduzca la Public Key de ReCAPTCHA. (Necesaria únicamente si ha seleccionado ReCAPTCHA)',
	'security_recprivatekey' => 'ReCAPTCHA Private Key',
	'd_security_recprivatekey' => 'Introduzca la Private Key de ReCAPTCHA. (Necesaria únicamente si ha seleccionado ReCAPTCHA)',


	// ======= LOGINSHARE =======
	'loginshare_staff' => 'Configuración LoginShare Operadores',
	'loginshare_staffenable' => 'Activar LoginShare operadores',
	'd_loginshare_staffenable' => 'Si se activa, todas las peticiones de autenticación de operadores se probarán primero en la URL siguiente basándose en las especificaciones de la API de LoginShare.',
	'loginshare_stafftitle' => 'Nombre de LoginShare Operadores',
	'd_loginshare_stafftitle' => 'Introduzca el nombre de este LoginShare',
	'loginshare_staffurl' => 'URL de LoginShare de operadores',
	'd_loginshare_staffurl' => 'Introduzca la URL de la API. <b><a href="http://www.kayako.com" target="_blank">Pulse aquí</a></b> para más información sobre la API LoginShare.',

	'loginshare_user' => 'Configuración LoginShare Usuarios',
	'loginshare_userenable' => 'Activar LoginShare usuarios',
	'd_loginshare_userenable' => 'Si se activa, todas las peticiones de autenticación de usuarios se probarán primero en la URL siguiente basándose en las especificaciones de la API de LoginShare.',
	'loginshare_usertitle' => 'Nombre de LoginShare usuarios',
	'd_loginshare_usertitle' => 'Introduzca el nombre de este LoginShare',
	'loginshare_userurl' => 'URL de LoginShare de usuarios',
	'd_loginshare_userurl' => 'Introduzca la URL de la API. <b><a href="http://www.kayako.com" target="_blank">Pulse aquí</a></b> para más información sobre la API LoginShare.',

	// ======= DATE & TIME =======
	'dtcalus' => 'USA (mm/dd/yy + 12hr)',
	'dtcaleu' => 'EUR (dd/mm/yy + 24hr)',
	'dt_caltype' => 'Tipo de fecha de calendario',
	'd_dt_caltype' => 'Cambia el tipo de fecha usado para la fecha del calendario. Nota: Este ajuste sólo afecta a los valores de fecha del selector de fecha.',
	'dt_dateformat' => 'Formato de fecha',
	'd_dt_dateformat' => 'Especifique el formato por defecto de todas las fechas mostradas en el sistema. ' . SWIFT_PRODUCT . ' usa la función PHP strftime(). Para más información sobre esta función, consulte <a href="http://www.php.net/strftime" target="_blank">strftime()</a>.',
	'dt_timeformat' => 'Formato de hora',
	'd_dt_timeformat' => 'Muestra la hora usando el formato especificado.',
	'dt_datetimeformat' => 'Formato de fecha y hora',
	'd_dt_datetimeformat' => 'Mostrar fechas y horas en el formato especificado.',
	'dt_timezone' => 'Zona horaria',
	'd_dt_timezone' => 'Seleccione la zona horaria por defecto. Los operadores tienen la opción de anular la zona horaria y poner la suya en las preferencias.',
	'dt_daylightsavings' => 'Activar Horario de Verano',
	'd_dt_daylightsavings' => 'Seleccione si quiere activar el Horario de Verano.',

	// ======= LIVE CHAT =======
	'livesupport_clientchatsettings' => 'Configuración visitantes y chat',
	'livesupport_chatwidth' => 'Anchura ventana de chat',
	'd_livesupport_chatwidth' => 'La anchura de la ventana de chat de visitantes (en píxeles).',
	'livesupport_chatheight' => 'Altura ventana de chat',
	'd_livesupport_chatheight' => 'La altura de la ventana de chat de visitantes (en píxeles).',
	'livesupport_clientchatrefresh' => 'Intervalo de recarga de chat',
	'd_livesupport_clientchatrefresh' => 'El intervalo en segundos en el que los datos del chat de sincronizarán durante una sesión de chat. Valores menores incrementarán la carga del servidor.',
	'livesupport_clientpagerefresh' => 'Intervalo de recarga de página de visitantes',
	'd_livesupport_clientpagerefresh' => 'El intervalo en segundos en el que los datos de visitantes se recargarán y se enviarán al servidor. Valores menores incrementarán mucho la carga del servidor.',
	'livesupport_roundrobinretries' => 'Número de intentos de encontrar operador',
	'd_livesupport_roundrobinretries' => 'El número de veces que ' . SWIFT_PRODUCT . ' intentará buscar operadores disponibles cuando se reciba una nueva solicitud de chat. Si no se encuentran operadores disponibles tras este número de intentos, se pedirá al visitante que <i>deje un mensaje</i>.',
	'livesupport_roundrobintimetry' => 'Intervalo de tiempo entre intentos',
	'd_livesupport_roundrobintimetry' => 'El tiempo en segundos que ' . SWIFT_PRODUCT . ' esperará entre cada reintento de encontrar un operador disponible. El tiempo total que un visitante esperará si no hay operadores disponibles es (<i>número de intentos * intervalo entre intentos</i>).  Tras este número de intentos con el intervalo especificado, se pedirá al visitante que <i>deje un mensaje</i>',
	'livesupport_displayclientchatqueue' => 'Comunicar al visitante el número de chats en cola',
	'd_livesupport_displayclientchatqueue' => 'Si se activa, los visitantes verán un mensaje comunicándoles el número de usuarios esperando a comenzar un chat antes que ellos.',
	'livesupport_cachehtmljscode' => 'Guardar Javascript en caché',
	'd_livesupport_cachehtmljscode' => 'Especifique si ' . SWIFT_PRODUCT . ' debe enviar cabeceras de caché al navegador del usuario. Se recomienda no modificar este valor.',
	'livesupport_enableuseristyping' => 'Mostrar "Escribiendo..."',
	'd_livesupport_enableuseristyping' => 'Si se activa, los visitantes y los operadores podrán ver cuándo el otro está escribiendo. Desactive esta opción para reducir la carga del servidor.',

	'livesupport_messagesettings' => 'Configuración de mensajes offline',
	'livesupport_enablemessagefw' => 'Activar reenvío',
	'd_livesupport_enablemessagefw' => 'Reenviar los mensajes offline recibidos por ' . SWIFT_PRODUCT . ' a la siguiente dirección de email.',
	'livesupport_deletemessageafterfw' => 'Eliminar tras reenvío',
	'd_livesupport_deletemessageafterfw' => 'Eliminar automáticamente el mensaje reenviado.',
	'livesupport_fwmessageemail' => 'Direcciones email de reenvío',
	'd_livesupport_fwmessageemail' => 'Reenviar mensajes offline a las siguientes direcciones de email separadas por punto y coma(;). Esta opción solo tendrá efecto si se ha activado la opción anterior, <i>Activar reenvío</i>.<br/><br/>Ejemplo: <i>pepe.perez@empresa.com;fulano.detal@empresa.com</i>',

	'livesupport_winappsettings' => 'Configuración Aplicación de Escritorio',
	'livesupport_searchbgcolor' => 'Color de fondo de visitantes de buscadores',
	'd_livesupport_searchbgcolor' => 'El color de fondo de los visitantes que provengan de un buscador.',
	'livesupport_searchfrcolor' => 'Color de letra de visitantes de buscadores',
	'd_livesupport_searchfrcolor' => 'El color de letra de los visitantes que provengan de un buscador.',
	'ls_adbgcolor' => 'Color de fondo de visitantes de campaña',
	'd_ls_adbgcolor' => 'El color de fondo para los visitantes procedentes de una <b>Campaña de anuncios</b> (configuradas en el panel de control de operadores).',
	'ls_adfrcolor' => 'vColor de fondo de visitantes de campaña',
	'd_ls_adfrcolor' => 'El color de letra para los visitantes procedentes de una <b>Campaña de anuncios</b> (configuradas en el panel de control de operadores).',

	'ls_clientarea' => 'Configuración del Centro de Soporte',
	'ls_displaystatus' => 'Mostrar icono se estado de soporte por chat',
	'd_ls_displaystatus' => 'Muestra el botón de soporte por chat en el Centro de Soporte (mostrando Conectado, Desconectado, Ocupado o Vuelvo enseguida).',
	'ls_staffcp' => 'Configuración panel control operadores de chat',
	'ls_entab' => 'Mostrar pestaña Chat en el panel de control de operadores',
	'd_ls_entab' => 'Mostrar pestaña Chat en el panel de control de operadores.',
	'ls_depname' => 'Usar el nombre del departamento en los chats',
	'd_ls_depname' => 'Use el nombre del departamento en lugar del nombre del operador en los chats. Esto ocultará al usuario el nombre del operador.',
	'livesupport_alertttl' => 'Tiempo de mostrado de alertas',
	'd_livesupport_alertttl' => 'Especifique el tiempo que se mostrarán las alertas (en segundos). Esta opción se usa para las alertas personalizadas en las reglas de visitantes. Introduzca 0 para mostrar las alertas indefinidamente.',
	'livesupport_clicktocallsettings' => 'Configuración de Click to Call',
	'ls_activecountrycode' => 'Código ITU-T de país activo',
	'd_ls_activecountrycode' => 'Introduzca su código de país actual, que se usará para distinguir las llamadas nacionales e internacionales.',
	'ls_ignoreactivecountrycode' => 'Ignorar código de país activo',
	'd_ls_ignoreactivecountrycode' => 'Si se activa, ' . SWIFT_PRODUCT . ' no añadirá el prefijo de país activo en las peticiones de llamada.',
	'ls_internationalcallprefix' => 'Prefijo de llamada internacional',
	'd_ls_internationalcallprefix' => 'Introduzca el prefijo para llamadas internacionales.',
	'ls_enableinternationalcalls' => 'Activar llamadas internacionales',
	'd_ls_enableinternationalcalls' => 'Esta opción le permite activar/desactivar la posibilidad de que los visitantes de otros países soliciten llamadas.',
	'livechat_ignorerange' => 'IPs ignoradas',
	'd_livechat_ignorerange' => SWIFT_PRODUCT . ' ignorará a los visitantes de las direcciones IP o subredes sumunistradas. Esto puede usarse para filtrar los visitantes de la propia empresa. Para bloquear una IP, use el panel de administración &gt; Chat &gt; Bloqueos. Separe múltiples valores con una coma \',\'. Ejemplos de uso:<BR /><i> * <b>202.1.192.0-202.1.192.255</b>: Un rango de IPs<BR /> * <b>200.36.161.0/24</b>: Un rango de Ips usando enmascaramiento<BR /> * <b>200.36.161/24</b>: Sintaxis abreviada igual a la anterior.</i>',

	'livechat_proactivescroll' => 'Activar animación de chat proactivo',
	'd_livechat_proactivescroll' => 'Si se activa, aparecerá una animación flotante solicitando un chat para implicar al visitante.',
	'livechat_timestamps' => 'Activar sellos de tiempo',
	'd_livechat_timestamps' => 'Si se activa, ' . SWIFT_PRODUCT . ' mostrará sellos de tiempo junto a cada mensaje de chat',
	'livechat_timestampformat' => 'Formato de sello de tiempo',
	'd_livechat_timestampformat' => 'Especifique el formato por defecto para los sellos de tiempo mostrados en el historial de chat (no se aplica a sellos de tiempo mostrados en ventanas de chat). ' . SWIFT_PRODUCT . ' usa la función PHP strftime(). Para más información sobre esta función, consulte <a href="http://www.php.net/strftime" target="_blank">strftime()</a>.',
	'ls_forcerandomnumber' => 'Forzar recarga de la URL para cada petición de etiqueta',
	'd_ls_forcerandomnumber' => 'Si se activa, ' . SWIFT_PRODUCT . ' forzará la recarga de la URL de la etiqueta con cada petición a la página. Esto permite una mejor actualización de las imágenes de chat pero puede incrementar la carga del servidor.',

	// ======= MAIL PARSER =======
	'pr_allowmultiplecreation' => 'Crear ticket en todas las colas de destino?',
	'd_pr_allowmultiplecreation' => 'Si se activa, ' . SWIFT_PRODUCT . ' creará múltiples tickets si un email tiene varias direcciones de colas en los campos \'Para:\' o \'CC:\'',
	'pr_generalparser' => 'Configuración de procesador',
	'pr_contentpriority' => 'Prioridad formato contenido email',
	'd_pr_contentpriority' => 'Cada email que llega al sistema puede tener dos tipos de contenido (HTML y texto plano). Esta opción especifica qué versión debe usar ' . SWIFT_PRODUCT . ' para procesar el correo. Es recomendable que este valor sea <i>Texto</i>.',
	'text' => 'Texto',
	'html' => 'HTML',
	'pr_stripscript' => 'Quitar etiquetas &lt;SCRIPT&gt;',
	'd_pr_stripscript' => 'Quita todas las etiquetas script del email entrante. Se recomienda <b>encarecidamente</b> que se deje esta opción activada. Si se deshabilita, los usuarios podrían ejecutar código en el navegador de los operadores.',
	'pr_allowhtml' => 'Permitir etiquetas HTML',
	'd_pr_allowhtml' => 'Si el procesador de correo debería permitir etiquetas HTML en el contenido.',
	'pr_allowabletags' => 'Etiquetas HTML válidas',
	'd_pr_allowabletags' => 'Especifique las etiquetas HTML que el procesador de correo no eliminará del correo entrante.',
	'pr_logoptions' => 'Opciones de log de procesador',
	'pr_enablelog' => 'Activar log',
	'd_pr_enablelog' => 'Guarda en un log toda la actividad del procesador de correo. Se recomienda que esta opción esté siempre activada para ayudar a resolver problemas relacionados con el procesado de email entrante.',
	'pr_logchurndays' => 'Tiempo de guardado de logs',
	'd_pr_logchurndays' => 'El tiempo en días durante el que se guardarán los logs.',
	'pr_maxlogsize' => 'Tamaño máximo de elemento de log',
	'd_pr_maxlogsize' => 'El tamaño máximo permitido en kbs para los elementos del log del procesador. Cualquier elemento mayor de ese tamaño no se guardará. Esto se puede usar para reducir el tamaño de la base de datos del log.',
	'pr_pop3' => 'Configuración de extracción POP3/IMAP',
	'pr_procno' => 'Número máximo de mensajes a procesar en una pasada',
	'd_pr_procno' => 'Una vez que el procesador de correo alcance este límite, terminará el procesado y los mensajes que hayan quedado en la bandeja de entrada se procesarán en la siguiente pasada.',
	'pr_sizelimit' => 'Límite de tamaño de mensaje',
	'd_pr_sizelimit' => 'Rechaza cualquier mensaje de tamaño mayor que el especificado (en KBs). Este tamaño debe ser menor que el de la variable PHP <b>php_memory_limit</b> que se encuentra en el archivo <i>php.ini</i>. De lo contrario los mensajes podrían quedarse en la cola.',
	'pr_parsereplyto' => 'Anular cabecera "Responder a"',
	'd_pr_parsereplyto' => 'Usar la cabecera <i>Responder a</i> como dirección de email primaria del creador del ticket. <b>¡Cuidado!</b> Esto podría ocasionar abusos, ya que las cabeceras Responder a se pueden falsificar fácilmente.',
	'pr_conversion' => 'Convertir automáticamente el juego de caracteres del correo entrante',
	'desc_pr_conversion' => 'Si se activa, ' . SWIFT_PRODUCT . ' intentará convertir automáticamente el correo entrante al juego de caracteres por defecto del helpdesk (<i>p.ej. si el helpdesk usa UTF-8 y se recibe un email que usa ISO-8859-1, se convertirá a UTF-8 antes de añadirse al sistema</i>).',

	// ======= TICKETS =======
	't_spamhandling' => 'Configuración de control de Spam',
	't_spammovetotrash' => '¿Mover el spam a la basura?',
	'd_t_spammovetotrash' => 'Si se activa, todos los tickets marcados como spam se moverán automáticamente a la basura.',
	't_spamban' => '¿Bloquear direcciones de email de Spam?',
	'd_t_spamban' => 'Si se activa, las direcciones de email que enviaron cualquier ticket marcado como spam serán bloqueadas automáticamente.',
	't_restrictnewticket' => 'Restringir la creación de nuevos tickers a los departamentos asignados',
	'd_t_restrictnewticket' => 'Solo permite a los operadores crear tickets en departamentos a los que estén asignados.',
	't_rvalemail' => 'Solicitar direcciones de email válidas',
	'd_t_rvalemail' => 'Hace que los usuarios faciliten una dirección de email válida al enviar un ticket.',
	'tickets_search' => 'Opciones de búsqueda',
	't_searchsortdate' => 'Ordenar resultados por última actividad (descendente)',
	'd_t_searchsortdate' => 'Ordena los resultados de búsqueda por última actividad (descendente). De lo contrario, se usará el orden de visualización por defecto.',
	't_cntrelevance' => 'Búsqueda avanzada de tickets',
	'd_t_cntrelevance' => 'Usar un algoritmo avanzado para buscar y determinar la relevancia de los resultados. Esta opción incrementará los tiempos de búsqueda en un 40%, pero la relevancia de los resultados será mucho mayor.',
	'tickets_searchtype' => 'Tipo de índice de búsqueda',
	'postindex' => 'Índice de mensaje de foro',
	'fulltext' => 'Texto completo MySQL',
	't_autorecip' => 'Añadir a usuarios CC como destinatarios',
	'd_t_autorecip' => 'Añade automáticamente las direcciones de email en CC en los emails entrantes como destinatarios en el ticket que se cree.',
	'tickets_minwordlength' => 'Tamaño mínimo de palabra',
	'd_tickets_minwordlength' => 'Especifique el tamaño mínimo de palabra para los índices de búsqueda. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar. Las palabras cortas tienden a aparecer más frecuentemente, luego permitir su indexación provocará que el índice sea mayor y más lento, y por tanto también lo serán las búsquedas.',
	'tickets_maxwordlength' => 'Tamaño máximo de palabra',
	'd_tickets_maxwordlength' => 'Especifique el tamaño máximo de las palabras indexables para las búsquedas. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar.',
	'tickets_indexnumbers' => 'Indexar números',
	'd_tickets_indexnumbers' => 'Si se activa, los números serán indexables y se podrán buscar.',
	'tickets_minnumberlength' => 'Tamaño mínimo de número',
	'd_tickets_minnumberlength' => 'Especifique el tamaño mínimo de número (en caracteres) para los índices de búsqueda. Cualquier palabra que no cumpla con este criterio será ignorada por el indexador y no se podrá buscar..',
	'tickets_faulttolerance' => 'Tolerancia a fallos de palabra',
	'd_tickets_faulttolerance' => 'Si una palabra aparece en un mensaje de ticket más de las veces especificadas aquí, se ignorará y no se indexará.',
	't_floodprotection' => 'Protección de flood',
	't_fresponder' => 'No enviar mensaje de autorrespuesta',
	'd_t_fresponder' => 'Si se activa, no se enviarán mensajes de autorrespuesta cuando se active la protección de flood.',
	't_fnoadd' => 'No añadir el ticket/respuesta',
	'd_t_fnoadd' => 'Si se activa, el correo entrante será ignorado si se activa la protección contra flood. No se recomienda activar esta opción ya que deshabilitar el mensaje de autorrespuesta debería desactivar cualquier bucle potencial de correo.',
	't_fthreshold' => 'Umbral de tiempo (en segundos)',
	'd_t_fthreshold' => 'Umbral de tiempo en el que se activará la protección contra flood.<BR /><BR /><span class="tabletitle"><i>Como funciona la protección contra flood?</i></span><BR />Cuando se recibe un email entrante, '.SWIFT_PRODUCT. ' revisa la tabla de tickets para comprobar si el usuario ha creado un ticket con el mismo asunto en el umbral de tiempo especificado. Si es así, la protección contra flood se activa y se realizan las acciones especificadas.',
	't_parser' => 'Configuración procesador de correo',
	't_pstaffreply' => 'Permitir a los operadores responder por email',
	'd_t_pstaffreply' => 'Permite a los operadores responder a los tickets directamente desde su email.',
	't_enfp' => 'Activar/desactivar protección contra flood',
	'd_t_enfp' => 'Cambia el estado de la protección contra flood. Se recomienda que nunca desactive esta opción, ya que previene bucles de correo electrónico que pueden producirse si su cliente tiene activada la autorrespuesta.',
	't_sla' => 'Configuración SLA',
	't_encustomoverdue' => 'Usar tiempo de resolución y vencimiento por defecto',
	'd_t_encustomoverdue' => 'Usa el valor (de <i>Tiempo de vencimiento por defecto</i> y <i>Tiempo de resolución por defecto</i>) para calcular los tiempos de vencimiento de un ticket cuando no se ha aplicado un plan SLA al departamento, usuario, grupo de usuarios o al mismo ticket.',
	't_overduehrs' => 'Tiempo de vencimiento por defecto',
	'd_t_overduehrs' => 'Marca un ticket como vencido tras este número de horas. (<i>Vea la opción anterior, <i>Usar tiempo de vencimiento por defecto</i>, para una explicación</i>).',
	't_resolutionduehrs' => 'Tiempo de resolución por defecto',
	'd_t_resolutionduehrs' => 'Marca un ticket como vendido si no se recuelve tras este número de horas. (<i>Vea la opción anterior, <i>Usar tiempo de vencimiento por defecto</i>, para una explicación</i>).',
	'tickets_resattachments' => 'Restringir adjuntos entrantes a los tipos de adjuntos personalizados',
	'd_tickets_resattachments' => 'Si se activa, sólo será procesados los adjuntos que aparezcan en la lista de tipos de adjunto personalizados en  <i>Tickets > Tipos de adjunto</i>. Cualquier adjunto de otro tipo será ignorado.',
	't_rss' => 'Sindicación RSS',
	't_enrss' => 'Activar RSS para vistas de ticket',
	'd_t_enrss' => 'Permite la consulta de las vistas de tickets (del panel de control de operadores) a través de RSS.',
	't_general' => 'Configuración general de tickets',
	't_tpreview' => 'Activar previsualización de mensajes en el listado de tickets',
	'd_t_tpreview' => 'Muestra una previsualización de mensajes al pasar el ratón por encima de un ticket en el panel de control de operadores. Si su helpdesk tiene mucho tráfico se recomienda no activar esta opción.',
	't_postlimit' => 'Mensajes de ticket por página',
	'd_t_postlimit' => 'Si está activada la opción <i>"Dividir mensajes de ticket en páginas"</i> esta opción determina cuantos mensajes se mostrarán en cada página.',
	't_chtml' => 'Conversión HTML (Visualización y alertas de operador)',
	'd_t_chtml' => 'Elija cómo se tratará el contenido en formato HTML cuando se muestren los tickets en la web y cuando se envíen alertas de operador.<br><dl><dt><b>Entidades HTML</b></dt><dd>Convierte el HTML a texto normal de manera que se vea el código.</dd><dt><b>Quitar etiquetas</b></dt><dd>Elimina completamente el formato HTML; (p.ej. "<b>foo</b>" = "foo").</dd><dt><b>No Procesar</b></dt><dd>Permite código HTML (p.ej. "<b>foo</b>" = "<b>foo</b>"). Esta última opción <b>no</b> se recmoienda ya que podría permitir la ejecución de código malicioso en los navegadores y en las aplicaciones de correo electrónico de los operadores.</dd></dl><i>Nota: Esta opción no afecta al contenido almacenado en la base de datos!</i>',
	't_postorder' => 'Orden de visualización de mensajes de ticket',
	'tcentities' => 'Entidades HTML',
	'tchtml' => 'No Procesar',
	'tchtmlpurifier' => 'Purificador HTML',
	'tcstrip' => 'Quitar etiquetas',
	'd_t_postorder' => 'Especifique si desea mostrar primero los mensajes más antiguos o los más nuevos.',
	't_enpagin' => 'Dividir mensajes de ticket en páginas',
	'd_t_enpagin' => 'Muestra los mensajes de ticket en páginas en lugar de en una sola página. Seleccione más adelante el número de mensajes a mostrar en cada página.',
	'newestfirst' => 'Nuevos primero',
	'oldestfirst' => 'Antiguos primero',
	't_overduecolor' => 'Color de fondo de tickets vencidos',
	'd_t_overduecolor' => 'El color de fondo de los tickets marcados como vencidos.',
	't_resultlimit' => 'Límite de resultados de búsqueda',
	'd_t_resultlimit' => 'La cantidad máxima de resultados que se devolverán en una búsqueda. Si se especifica un valor muy alto, las búsquedas utilizarán más recursos del sistema y tardarán más en ejecutarse.',
	't_tidinsub' => 'Poner ID en el asunto de los emails salientes',
	'd_t_tidinsub' => 'Inserta el ID de ticket en el asunto de los emails enviados cuando los oepradores crean nuevos tickets. Aunque se recomienda que esta opción esté activada, ' . SWIFT_PRODUCT . ' puede comprobar cuándo un mensaje pertenece a un ticket buscando el ID del ticket en el cuerpo del mensaje, comparando el asunto o comprobando la cabecera Message-ID del email.',
	't_mailset' => 'Configuración de correo',
	't_stmsgid' => 'Comprobar Message-ID en respuestas de operador',
	'd_t_stmsgid' => SWIFT_PRODUCT . ' puede comprobar la cabecera Message-ID para confirmar la identidad de un operador que responde a una alerta de ticket. Esto es una capa de seguridad adicional y asegura que quien responde es un operador válido. Sin embargo, requiere que el cliente de correo envíe la cabecera In-Reply-To, la cual no está soportada por todos los clientes de email (sobre todo clientes de correo inalámbricos).',
	't_entab' => 'Mostrar pestaña Tickets',
	'd_t_entab' => 'Muestra la pestaña Tickets en el panel de control de operadores.',
	't_clientarea' => 'Configuración del Centro de Soporte',
	't_cperpage' => 'Tickets a mostrar por página',
	'd_t_cperpage' => 'El número de tickets que se mostrarán al usuario en su lista de tickets.',
	't_eticketid' => 'Tipo de ID de ticket',
	'd_t_eticketid' => 'Elija cómo ' . SWIFT_PRODUCT . ' generará los nuevos identificadores de ticket. Se recomienda establecerlo en <i>Aleatorio</i> para incrementar la seguridad contra ataques de spoofing.<br /><br />Ejemplos:<br /><i>Secuencial:</i> "[#194]: <asunto aquí>"<br /><i>Aleatorio:</i> "[ABC-123-4567]:<asunto aquí>"',
	'tsequential' => 'Secuencial',
	'trandom' => 'Aleatorio',
	't_maxattach' => 'Número máximo de adjuntos al responder',
	'd_t_maxattach' => 'El número máximo de archivos que se pueden adjuntar a una respuesta de ticket. Si se permiten archivos particularmente grandes, se recomienda que se edite la opción <i>upload_max_filesize</i> del archivo php.ini (Archivo de configuración PHP) para reflejar este tamaño.',
	't_slaresets' => 'Reiniciar contador de vencimiento tras respuesta de operador',
	'd_t_slaresets' => 'Si se activa, el contador de tiempo de vencimiento de SLA se reiniciará automáticamente cuando un operador responda a un ticket. Se recalculará el tiempo de vencimiento cuando el usuario responda de nuevo al ticket.',
	't_cthirdparty' => 'Los usuarios pueden ver respuestas de terceros',
	'd_t_cthirdparty' => 'Si se activa, los usuarios podrán ver respuestas de terceros en el Centro de Soporte.',
	't_cenattach' => 'Usuarios pueden subir adjuntos',
	'd_t_cenattach' => 'Si se activa, los usuarios podrán subir adjuntos cuando creen o respondan a un ticket.',
	't_cmaxattach' => 'Número máximo de adjuntos',
	'd_t_cmaxattach' => 'El número de adjuntos que un usuario puede añadir a un ticket o respuesta de ticket.',
	't_cpostorder' => 'Orden de visualización para mensajes de ticket',
	'd_t_cpostorder' => 'Seleccione si se mostrarán en primer lugar los mensajes de ticket nuevos o los más antiguos en el Centro de Soporte.',
	't_pdainterf' => 'Interfaz PDA de Panel Control Operadores',
	't_pdenpagin' => 'Dividir mensajes en páginas',
	'd_t_pdenpagin' => 'Muestra los mensajes de ticket en páginas separadas en lugar de en una sola página.',
	't_pdpostlimit' => 'Número de mensajes de ticket por página',
	'd_t_pdpostlimit' => 'si ha activado la opción <i>"Dividir mensajes en páginas"</i> esto especifica cuántos mensajes se mostraran en cada página. Esta opción se aplica solo al interfaz PDA del panel de control de operadores.',
	't_pdpostorder' => 'Orden de visualización para mensajes de ticket',
	'd_t_pdpostorder' => 'Si se mostrarán primero los mensajes más antiguos o los más nuevos.',
	't_signores' => 'Ignorar palabras que contengan símbolos',
	'd_t_signores' => 'Si se activa, se ignorarán las palabras que contengan alguno de los siguientes símbolos:<br /><br /><i>- ~ ` @ # $ ^ & * ( ) _ = + [ ] { } | / < > , . ; \' " \</i>',
	't_ccaptcha' => 'Activar CAPTCHA para el envío de tickets',
	'd_t_ccaptcha' => 'Solicitar a los usuarios que envíen un ticket a través del Centro de Soporte que introduzcan un texto mostrado en una imagen especial para intentar verificar si son humanos.',
	't_autoclose' => 'Configuración cerrado automático de tickets',
	't_enautoclose' => 'Activar sistema de cerrado automático',
	'd_t_enautoclose' => 'Cambia automáticamente el estado de los tickets que lleven cierto tiempo en el sistema.',
	't_acstatus' => 'Estados de ticket afectados',
	'd_t_acstatus' => 'Seleccione los estados de ticket a los que afectará el sistema de cerrado automático. Seleccione múltiples estados manteniendo pulsada la tecla CTRL mientras selecciona con el ratón.',
	't_acdep' => 'Departamentos afectados',
	'd_t_acdep' => 'Seleccione los departamentos a los que afectará el sistema de cerrado automático. Seleccione múltiples departamentos manteniendo pulsada la tecla CTRL mientras selecciona con el ratón.',
	't_acstatusch' => 'Estado objetivo',
	'd_t_acstatusch' => 'Seleccione el estado al que se cambiarán los tickets cuando estén en el sistema durante un cierto tiempo.',
	't_acinactive' => 'Umbral de aviso para cerrado automático',
	'd_t_acinactive' => 'Después de que un ticket haya permanecido inactivo durante el tiempo especificado aquí (en horas), el sistema enviará un aviso a la persona que creó el ticket, avisándole del inminente cerrado automático del mismo.',
	't_acnoticeclose' => 'Umbral de cierre para cerrado automático',
	'd_t_acnoticeclose' => 'Después de que haya transcurrido este período de tiempo (en horas), (que comienza tras haber pasado el "Umbral de aviso para cerrado automático"), el estado de los tickets objetivo será cambiado.',
	't_arnews' => 'Enviar últimas noticias en autorrespuesta',
	'd_t_arnews' => 'Si está activado y lo está también el módulo de noticias, las cinco noticias más recientes se enviarán en la autorrespuesta del ticket (recibo del ticket).',
	't_ticketlock' => 'Configuración bloqueo de tickets',
	't_entlock' => 'Activar/Desactivar bloqueo de tickets',
	't_entplock' => 'Activar bloqueo de ticket por respuesta',
	'd_t_entplock' => 'Permite a los operadores ver las respuestas de los demás en tiempo real (según escriben el borrador de respuesta) cuando están viendo el mismo ticket.',
	't_plockthreshold' => 'Umbral de bloqueo de mensaje de ticket',
	'd_t_plockthreshold' => 'Cualquier actualización de una respuesta realizada tras este umbral de tiempo (en segundos) no se mostrará a los demás operadores.',
	'd_t_entlock' => 'El bloqueo de tickets ' . SWIFT_PRODUCT . ' bloqueará un ticket cuando un operador lo abra. Los demás operadores podrán acceder al ticket pero se mostrará un icono de candado para que el resto de operadores sepa que otros están viendo el ticket.',
	't_locktimeout' => 'Tiempo de espera de bloqueo de ticket',
	'd_t_locktimeout' => 'Una vez que ha transcurrido este tiempo (en segundos) (p.ej. si el operador que ha bloqueado el ticket ha estado inactivo durante este período de tiempo) dejará de mostrarse el icono del candado.',
	't_canirs' => 'Activar el Sistema de Respuesta Instantánea (IRS)',
	'd_t_canirs' => 'Si se activa, cuando los usuarios escriban el borrador de una solicitud de ticket, ' . SWIFT_PRODUCT . ' buscará en la biblioteca artículos relevantes en tiempo real. Esta característica reduce mucho el número de tickets recibidos, ya que los usuarios podrán encontrar las respuestas a sus dudas antes de enviar los tickets.',
	't_maxwcnt' => 'Número máximo de palabras para IRS',
	'd_t_maxwcnt' => 'Después de que el usuario haya introducido este número de palabras, el sistema IRS dejará de sugerir artículos de la biblioteca.',
	't_reciplist' => 'Listar destinatarios antes de responder',
	'd_t_reciplist' => 'Muestra la lista de destinatarios añadidos a un ticket. Esto añade peticiones a la base de datos a la página de lista de tickets.',
	't_staffcp' => 'Configuración de panel de control de operadores',
	't_scanirs' => 'Activar Sistema de Respuesta Instantánea (IRS)',
	'd_t_scanirs' => 'Igual que el sistema IRS en el Centro de Soporte, ' . SWIFT_PRODUCT . ' sugerirá artículos de la biblioteca según los operadores vayan redactando sus respuestas.',
	't_advanced' => 'Configuración avanzada de ticket',
	't_postlist' => 'Asigna variable de listado de mensajes a respuestas de operadores',
	'd_t_postlist' => 'Incluye el historial completo del ticket hasta la fecha en las respuestas enviadas por operadores. Esto añade carga y podría ralentizar las respuestas.',
	't_reciplimit' => 'Limitar destinatarios en correo entrante',
	'd_t_reciplimit' => 'Puede usar esta opción para limitar el número de destinatarios de un email entrante. Aumentar esta opción puede causar problemas cuando correos de spam con gran número de destinatarios sean procesados por el sistema.',
	't_mergrecip' => 'Añadir usuarios como destinatarios al fusionar',
	'd_t_mergrecip' => 'Cuando se fusionan dos tickets, añade a los usuarios cuyas direcciones de email estén asociadas con alguno de los tickets como destinatarios en el ticket resultante. Esto asegura que todos los usuarios recibirán la futura correspondencia asociada a los tickets.',
	'tickets_bayesian' => 'Configuración Filtrado Bayesiano',
	'tb_minwordlength' => 'Tamaño mínimo de palabra',
	'd_tb_minwordlength' => 'Especifique el tamaño mínimo de palabra para el motor de indexado del filtro bayesiano. Cualquier palabra que no cumpla estos criterios será ignorada por el sistema.',
	'tb_maxwordlength' => 'Tamaño máximo de palabra',
	'd_tb_maxwordlength' => 'Especifique el tamaño máximo de palabra para el motor de indexado del filtro bayesiano. Cualquier palabra que no cumpla este criterios será ignorada por el sistema.',
	'tb_indexnumbers' => 'Indexar números',
	'd_tb_indexnumbers' => 'Activa la indexación de números',
	'tb_minnumberlength' => 'Tamaño mínimo de número',
	'd_tb_minnumberlength' => 'Tamaño mínimo de un número para que el filtro bayesiano lo indexe',
	'tb_signores' => 'Ignorar palabras con símbolos',
	'd_tb_signores' => 'Si se activa, las palabras que contengan símbolos serán ignoradas. Esto incluye URLs, números de teléfonos (con guiones), IDs de ticket, etc.',
	'tb_enablespam' => 'Activar filtro de SPAM?',
	'd_tb_enablespam' => 'Si se activa, puede entrenar el filtro bayesiano para que distinga entre mensajes de spam y no spam. Incluso con el filtrado deshabilitado puede usar el motor de filtrado bayesiano para enrutar tickets según categorías específicas.',

	// ======= TROUBLESHOOTER =======
	'tr_staffcp' => 'Configuración Asistente en panel de control de operadores',
	'tr_general' => 'Configuración Asistente en Centro de Soporte',
	'tr_staffwysiwyg' => 'Activar editor WYSIWYG',
	'd_tr_staffwysiwyg' => 'Usar el editor avanzado WYSIWYG (texto enriquecido) para crear los artículos de Asistente.',
	'tr_enableclient' => 'Mostrar widget de Asistente',
	'd_tr_enableclient' => 'Muestra el icono y enlace de Asistente en la página index.php del Centro de Soporte.',
	'tr_enablepopularcat' => 'Activar lista de Asistentes populares',
	'd_tr_enablepopularcat' => 'Muestra una lista de los asistentes más populares en la página index.php del Centro de Soporte.',
	'tr_maxpopularcat' => 'Número máximo de Asistentes a mostrar',
	'd_tr_maxpopularcat' => 'El número máximo de asistentes que se mostrarán en el listado de asistentes populares.',
	'tr_displayviews' => 'Mostrar número de vistas',
	'd_tr_displayviews' => 'Mostrar el número de veces que se ha visitado cada categoría de asistentes junto al nombre de la categoría.',
	'tr_displaynavbar' => 'Mostrar asistentes en la barra de navegación',
	'd_tr_displaynavbar' => 'Mostrar asistentes en cada paso en la barra de navegación.',
	'tr_entab' => 'Mostrar pestaña Asistente',
	'd_tr_entab' => 'Muestra la pestaña de Asistente en el panel de control de operadores.',
	't_cstatusupd' => 'Estado de ticket por defecto para respuestas de usuarios',
	'd_t_cstatusupd' => 'Cambia los tickets a este estado automáticamente al responder el usuario.',
	'tsnochange' => '-- Sin cambios --',
	't_canrecip' => 'Los usuarios pueden especificar destinatarios personalizados',
	'd_t_canrecip' => 'Permite a los usuarios especificar "Destinatarios CC" personalizados en los tickets que creen.',
	't_enhistory' => 'Enviar historial completo en respuestas de operadores?',
	'd_t_enhistory' => 'Incluye el historial completo de un ticket hasta la fecha en las respuestas enviadas por operadores. Esto añade carga y podría ralentizar las respuestas.',

	// ======= USER REGISTRATION =======
	'user_enableemailverification' => 'Verificación de usuario por email',
	'd_user_enableemailverification' => 'Si se activa, ' . SWIFT_PRODUCT . ' verificará la dirección de correo del usuario cuando este se registre en el Centro de Soporte. La verificación consiste en el envío de un email a los usuarios con un enlace de activación que deberán usar para activar la cuenta.',
	'user_enablecaptcha' => 'Activar CAPTCHA para registro de usuarios',
	'd_user_enablecaptcha' => 'Solicita a los usuarios que se registren a través del Centro de Soporte la introducción del texto mostrado en una imagen para verificar que son humanos.',
	'user_autodelete' => 'Eliminación automática',
	'user_adelunveri' => 'Eliminar automáticamente usuarios no verificados',
	'd_user_adelunveri' => 'Elimina cuentas de usuario no verificadas tras un tiempo establecido (establecido abajo).',
	'user_delcleardays' => 'Tiempo eliminación automática',
	'd_user_delcleardays' => 'El tiempo (en días) tras el que las cuentas de usuario no verificadas se eliminarán automáticamente del sistema (si la opción anterior está activada).',
	'u_sendpw' => 'Enviar contraseña en autorrespuesta (Recibo de ticket)',
	'd_u_sendpw' => 'Envía la contraseña a los usuarios al crear un nuevo ticket.',
	'user_organizations' => 'Configuración de organización de usuarios (Centro de Soporte)',
	'user_orgrestrictautoadd' => 'Permitir adición automática a Organizaciones compartidas',
	'd_user_orgrestrictautoadd' => 'Si se activa, los usuarios podrán formar parte de organizaciones comparticas a través de su perfil. Esta opción sólo se aplica a nombres de organizaciones introducidos en el Centro de Soporte.<br/><br /><i>NOTA: Esto puede ser un riesgo de seguridad, al permitir que cualquiera especifique un nombre de organización y pueda acceder a los tickets de la misma</i>',
	'user_orgselection' => 'Selección de organización de usuario',
	'd_user_orgselection' => 'Seleccione si se permitirá a los usuarios formar parte de una organización o cómo debería comportarse el sistema cuando los usuarios introduzcan un nombre de organización. <br/><br/><i>No permitir:</i> No se permitirá a los usuarios introducir un nombre de organización<br /><i>Crear nueva:</i> Se creará una nueva organización cada vez que un usuario introduzca un nombre de organización<br /><i>Crear/Fusionar:</i> Se creará una nueva organización o el usuario será integrado en una si ya existe una con el mismo nombre.',
	'uodontallow' => 'No permitir',
	'uocreatenew' => 'Crear nueva',
	'uocreatemerge' => 'Crear/Fusionar',
	'user_orgprofileupdate' => 'Actualización de perfil de organización',
	'd_user_orgprofileupdate' => 'Seleccione quién puede actualizar el perfil de organización.',
	'uoallusers' => 'Todos los usuarios',
	'uomanagersonly' => 'Sólo administradores',
	'user_orgdefaultclassification' => 'Clasificación de usuarios por defecto',
	'd_user_orgdefaultclassification' => 'Seleccione cómo se clasificarán los nuevos usuarios.<br /><br/><i>Usuario:</i> Todos los nuevos usuarios son clasificados como \'usuarios normales\'<br/><i>Administrador:</i> Un usuario se clasificará como administrador si no existe ninguno para su organización.',
	'uouser' => 'Usuario',
	'uomanager' => 'Administrador',
	'user_dispatchregemail' => 'Enviar email de registro',
	'd_user_dispatchregemail' => 'Si se activa, el usuario recibirá un email con los detalles del perfil (incluyendo su contraseña) tras el registro.',

	// ======= NEWS =======
	'nw_general' => 'Configuración de noticias',
	'nw_sendstaffemail' => 'Enviar actualizaciones por email a operadores',
	'd_nw_sendstaffemail' => 'Si se activa, los operadores recibirán actualizaciones por email cuando un artículo de noticias sea creado o actualizado. Esta opción está restringida a noticias de tipo Global y Privada.',
	'nw_sync' => 'Configuración de sincronización',
	'nw_globalsync' => 'URL RSS de noticias Globales',
	'd_nw_globalsync' => 'Especifique la URL del feed RSS desde el que se sincronizarán las noticias globales.',
	'nw_publicsync' => 'URL RSS de noticias Públicas',
	'd_nw_publicsync' => 'Especifique la URL del feed RSS desde el que se sincronizarán las noticias públicas.',
	'nw_privatesync' => 'URL RSS de noticias Privadas',
	'd_nw_privatesync' => 'Especifique la URL del feed RSS desde el que se sincronizarán las noticias privadas.',
	'nw_wysiwyg' => 'Activar editor WYSIWYG',
	'd_nw_wysiwyg' => 'Usar el editor avanzado WYSIWYG (texto enriquecido) para crear noticias.',
	'nw_newsstaffcp' => 'Configuración de noticias en panel de operadores',
	'nw_newsclient' => 'Configuración de noticias en panel de usuarios',
	'nw_enableclient' => 'Mostrar widget de noticias',
	'd_nw_enableclient' => 'Mostrar el icono y el enlace a noticias en la página index.php del Centro de Soporte.',
	'nw_enablestaffdashboard' => 'Mostrar últimas noticias en el panel de control',
	'd_nw_enablestaffdashboard' => 'Mostrar las últimas noticias en la pestaña de bienvenida del panel de control de operadores.',
	'nw_maxdashboardnewslist' => 'Número máximo de noticias en panel de control',
	'd_nw_maxdashboardnewslist' => 'El número máximo de noticias recientes que se mostrarán en el panel de control de operadores.',
	'nw_enablenewsnav' => 'Mostrar últimas noticias en la página de inicio',
	'd_nw_enablenewsnav' => 'Mostrar las últimas noticias al final de la página de inicio.',
	'nw_maxnewslist' => 'Número máximo de noticias recientes',
	'd_nw_maxnewslist' => 'El número máximo de noticias recientes que se mostrarán en la página de inicio.',
	'nw_navdisplaydate' => 'Mostrar fecha de las noticias',
	'd_nw_navdisplaydate' => 'Muestra la fecha de realización de la noticia junto al título de la noticia.',
	'nw_navdateformat' => 'Formato de fecha de noticias',
	'd_nw_navdateformat' => 'El formato en el que se mostrará la fecha de las noticias. Para más información consulte la documentación para la función PHP <a href="http://www.php.net/date" target="_blank">date()</a>.',
	'nw_rss' => 'Configuración RSS',
	'nw_enablerss' => 'Activar sindicación RSS',
	'd_nw_enablerss' => 'Permitir a los usuarios suscribirse a los feeds RSS de noticias.',
	'nw_maxrss' => 'Límite máximo de últimas noticias para el feed RSS',
	'd_nw_maxrss' => 'El número máximo de noticias que aparecerán en el feed RSS.',
	'nw_entab' => 'Mostrar pestaña noticias',
	'd_nw_entab' => 'Muestra la pestaña noticias en el panel de control de operadores.',
	'nw_svalidate' => 'Validar dirección email suscriptores',
	'd_nw_svalidate' => 'Especifique si ' . SWIFT_PRODUCT . ' debe verificar la dirección de email de los usuarios cuando se suscriban a las noticias a través del Centro de Soporte. La verificación implica el envío de un email al usuario con un enlace de activación que debe usar para activar su cuenta.',
	'nw_pageno' => 'Número de noticias por página',
	'd_nw_pageno' => 'El número de noticias que se mostrarán en cada página.',
	'nw_staffpageno' => 'Número de noticias por página',
	'd_nw_staffpageno' => 'El número de noticias que se mostrarán en cada página.',

	// ======= DOWNLOADS =======
	'dl_clientarea' => 'Configuración de descargas',
	'dl_enableclient' => 'Mostrar widget de descargas',
	'd_dl_enableclient' => 'Muestra el icono y el enlace a descargas en la página index.php del Centro de Soporte.',
	'dl_enpopularfiles' => 'Mostrar listado de descargas populares',
	'd_dl_enpopularfiles' => 'Muestra una lista de las descargas más populares en la página index.php del Centro de Soporte.',
	'dl_maxpopularfiles' => 'Número máximo de descargas populares',
	'dl_dispdownloadcnt' => 'Muestra el número de descargas en la lista de descargas populares',
	'dl_enlatestfiles' => 'Mostrar listado de últimas descargas',
	'd_dl_enlatestfiles' => 'Muestra una lista de las descargas más recientes en la página index.php del Centro de Soporte.',
	'dl_maxlatestfiles' => 'Número máximo de últimas descargas a mostrar',
	'dl_displaydldate' => 'Mostrar fecha de publicación de últimas noticias',
	'dl_dispdateformat' => 'Formato de fecha de publicación',
	'd_dl_dispdateformat' => 'El formato en el que se mostrará la fecha de las descargas. Para más información consulte la documentación para la función PHP <a href="http://www.php.net/date" target="_blank">date()</a>.',
	'dl_staffcp' => 'Configuración descargas panel de control de operadores',
	'dl_entab' => 'Mostrar pestaña descargas',
	'd_dl_entab' => 'Muestra la pestaña descargas en el panel de control de operadores.',
	'dl_rss' => 'Configuración RSS',
	'dl_enrss' => 'Activar sindicación RSS',
	'd_dl_enrss' => 'Permite a los usuarios suscribirse a los feeds RSS de las nuevas descargas.',
	'dl_rsslinkfile' => 'Enlazar directamente a descarga',
	'd_dl_rsslinkfile' => 'Muestra un enlace directo a la descarga en el feed RSS de cada elemento. Si se deshabilita se incluirá un enlace a la página de descarga.',
	'dl_catindex' => 'Configuración de índice de categorías del Centro de Soporte',
	'dl_defaultdisp' => '-- Orden de visualización por defecto --',
	'dl_alphabetical' => 'Alfabético',
	'dl_chrono' => 'Cronológico',
	'dl_totalitems' => 'Elementos totales',
	'dl_datemodified' => 'Fecha de modificación',
	'dl_totaldownloads' => 'Descargas totales',
	'dl_asc' => 'Ascendente',
	'dl_desc' => 'Descendente',
	'dl_catdisplayorder' => 'Anular orden de visualización de categorías',
	'd_dl_catdisplayorder' => 'Usar este orden de visualización en lugar del orden de visualización seleccionado cuando se crearon las categorías. Seleccione <i>Orden de visualización por defecto</i> para usar el orden de visualización especificado cuando se crearon las categorías.',
	'dl_catorder' => 'Orden de visualización de categorías',
	'd_dl_catorder' => 'Seleccione el orden de visualización de categorías por defecto.',
	'dl_itdisplayorder' => 'Anular orden de visualización de descargas',
	'd_dl_itdisplayorder' => 'Usar este orden de visualización en lugar del orden de visualización seleccionado cuando se crearon las descargas. Seleccione <i>Orden de visualización por defecto</i> para usar el orden de visualización especificado cuando se crearon las descargas.',
	'dl_itorder' => 'Orden de visualización de descargas',
	'd_dl_itorder' => 'La manera en que se ordenarán las descargas.',
	'dl_maxcatarticles' => 'Límite de elementos en subcategorías',
	'd_dl_maxcatarticles' => 'El número máximo de descargas mostrado en las subcategorías de descargas.',
	'dl_displaymore' => 'Mostrar enlace "mostrar más" descargas',
	'd_dl_displaymore' => 'Mostrar un enlace "Mostrar más" en las subcategorías de descargas mostrando más descargas disponibles en una categoría.',
	'dl_catarticledetails' => 'Mostrar descripción de las descargas en la lista',
	'd_dl_catarticledetails' => 'Muestra la descripción de las descargas al ver la lista de descargas en una categoría.',
	'dl_climit' => 'Límite de caracteres de descripción',
	'd_dl_climit' => 'El número mácimo de caracteres de la descripción de las descargas que se mostrarán en el listado (ver opción anterior).',

	// ======= KNOWLEDGEBASE =======
	'kb_clientarea' => 'Configuración general de Biblioteca',
	'kb_clientareaindex' => 'Configuración de índice del Centro de Soporte',
	'kb_categoryindex' => 'Configuración índice de categorías',
	'kb_enableclient' => 'Mostrar widget de Biblioteca',
	'd_kb_enableclient' => 'Muestra el icono y el enlace de Biblioteca en la página index.php del Centro de Soporte.',
	'kb_enpopulararticles' => 'Mostrar listado de artículos populares',
	'd_kb_enpopulararticles' => 'Muestra un listado de los artículos más populares de la biblioteca en la página index.php del Centro de Soporte.',
	'kb_maxpopulararticles' => 'Número máximo de artículos populares',
	'kb_dispviews' => 'Mostrar número de visitas junto a artículos populares',
	'kb_enlatestarticles' => 'Mostrar listado de últimos artículos',
	'd_kb_enlatestarticles' => 'Muestra un listado de los artículos más recientes de la biblioteca en la página <i>index.php</i> del Centro de Soporte.',
	'kb_maxlatestarticles' => 'Número máximo de artículos recientes',
	'kb_displayarticledate' => 'Mostrar fecha de creación junto a artículos recientes',
	'kb_dateformat' => 'Formato de fecha de creación',
	'd_kb_dateformat' => 'El formato en el que se mostrará la fecha de creación de los artículos. Para más información consulte la documentación para la función PHP <a href="http://www.php.net/date" target="_blank">date()</a>.',
	'kb_maxcatarticles' => 'Número máximo de artículos a mostrar en la lista de categorías',
	'kb_displaymore' => 'Mostrar enlace "Más artículos" bajo el listado de categorías',
	'kb_catarticledetails' => 'Mostrar detalles del artículo bajo el listado de categorías',
	'kb_alphabetical' => 'Alfabético',
	'kb_chrono' => 'Cronológico',
	'kb_totalarticles' => 'Artículos totales',
	'kb_catdisplayorder' => 'Anular campo de orden de visualización de categorías',
	'd_kb_catdisplayorder' => 'Especifique el orden de visualización que se usará al ordenar las categorías. Seleccione <i>Orden de visualización por defecto</i> para usar el orden especificado al crear las categorías.',
	'kb_catorder' => 'Orden de visualización de categorías',
	'kb_asc' => 'Ascendente',
	'kb_desc' => 'Descendente',
	'kb_arorder' => 'Orden de visualización de artículos',
	'd_kb_ardisplayorder' => 'Usar el orden de visualización especificado para ordenar los artículos. Seleccione <i>Orden de visualización por defecto</i> para usar el orden de visualización especificado al crear los artículos.',
	'kb_ardisplayorder' => 'Anular campo de orden de visualización de artículos',
	'kb_datemodified' => 'Fecha de modificación',
	'kb_views' => 'Visitas totales',
	'kb_rating' => 'Valoración de artículo',
	'kb_defaultdisp' => '-- Orden por defecto --',
	'kb_enrss' => 'Activar RSS',
	'kb_rss' => 'Configuración RSS',
	'd_kb_enrss' => 'Activar la suscripción de usuarios a artículos.',
	'kb_climit' => 'Límite de caracteres de previsualización de artículos',
	'd_kb_climit' => 'El número máximo de caracteres que se mostrarán en una previsualización de artículo en el índice de una categoría. Para deshabilitar la previsualización ponga este valor a "0".',
	'kb_rssclimit' => 'Límite de caracteres de feed RSS',
	'd_kb_rssclimit' => 'El número máximo de caracteres de un artículo que aparecerán en el feed RSS.',
	'kb_enrating' => 'Activar valoración de artículos',
	'd_kb_enrating' => '',
	'kb_categorycolumns' => 'Número de columnas de categoría',
	'd_kb_categorycolumns' => 'Especifique el número de columnas en las que se agruparán las categorías.',
	'kb_staffcp' => 'Configuración de biblioteca en panel de control de operadores',
	'kb_staffwysiwyg' => 'Activar editor WYSIWYG',
	'd_kb_staffwysiwyg' => 'Usar el editor avanzado WYSIWYG (texto enriquecido) al crear artículos.',
	'kb_entab' => 'Mostrar pestaña Biblioteca',
	'd_kb_entab' => 'Activar la pestaña Biblioteca en el panel de control de operadores.',
	'kb_parcount' => 'Número de artículos en subcategorías',
	'd_kb_parcount' => 'Si se activa, ' . SWIFT_PRODUCT . ' incluirá artículos almacenados en subcategorías al contar los artículos de la categoría. Las bibliotecas con muchas subcategorías pueden consumir muchos recursos.',

	// ======= TEAMWORK =======
	'tw_syncworks' => 'No hay configuración disponible para este módulo.',

	//======== PURCHASER ======
	'settings_purchase' => 'Compra de tickets',
	'purchase_admin_email' => 'Email de facturación',
	'purchase_money_format' => 'Posición del símbolo de moneda',
	'purchase_number_format_style' => 'Formato de número',
	'purchase_money_sign' => 'Símbolo de moneda',
	'purchase_bluepay_account' => 'Número de cuenta Bluepay',
	'purchase_bluepay_key' => 'Secret Key de Bluepay',
	'purchase_bluepay_mode' => 'Modo de transacción Bluepay',
	'purchase_bluepay_mode_test' => 'Prueba',
	'purchase_bluepay_mode_live' => 'Producción',
	'purchase_invoice_address' => 'Dirección de facturación a mostrar en facturas',

	// ======= RINGROUTE =======
	'rr_general' => 'Configuración general RingRoute',
	'ringrouteenable' => 'Activar RingRoute',
	'd_ringrouteenable' => 'Use esta opción para activar/desactivar el sistema VoIP RingRoute',
	'ringrouteusername' => 'Email RingRoute',
	'd_ringrouteusername' => 'Por favor introduzca la dirección de correo registrada RingRoute. Las credenciales de acceso deben coincidir con las que usa para iniciar sesión en el panel de control de RingRoute.',
	'ringroutepassword' => 'Contraseña de RingRoute',
	'd_ringroutepassword' => 'Introduzca la contraseña RingRoute.',

	// ======= ONSITE =======
	'ons_general' => 'Configuración general OnSite',
	'ons_primaryserver' => 'Servidor principal',
	'd_ons_primaryserver' => 'El nombre o dirección IP del servidor OnSite que se usará para negociar una sesión P2P NAT traversal.',
	'ons_secondaryserver' => 'Servidor secundario',
	'd_ons_secondaryserver' => 'El nombre o dirección IP del servidor OnSite que se usará cuando el principal no esté disponible por dificultades técnicas.',
	'ons_portrange' => 'Rango de puertos',
	'd_ons_portrange' => 'El número de puertos consecutivos que se intentarán usar durante la sesión de negociación P2P. el valor por defecto es 3.',
	'ons_retrytolerance' => 'Tolerancia de reintentos',
	'd_ons_retrytolerance' => 'El número de veces que se intentará la operación de enlazado  P2P (intercambio de puntos de acceso). Esto se usa para los casos en que el otro punto de acceso aún no ha registrado con el servidor. El valor por defecto es 3.',
	'ons_retrywait' => 'Espera entre reintentos',
	'd_ons_retrywait' => 'El número de segundos entre intentos de enlazado P2P. El valor por defecto es 5.',
	'ons_pairingtimeout' => 'Tiempo de espera de enlazado',
	'd_ons_pairingtimeout' => 'El número de segundos que se esperará tras hacer los intentos de conexión P2P antes de desistir completamente. El valor por defecto es 30.',

	// ======= REPORT =======
	'rep_general' => 'Configuración de informes',
	'rep_maxrows' => 'Max filas',
	'd_rep_maxrows' => 'El número máximo de filas a mostrar en cada página para informes tabulares/resumen.',
);

?>