<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN V4 LOCALES =======
	'myopentickets' => 'Mis tickets abiertos',
	'mypendingtickets' => 'Mis tickets pendientes',
	'defaultescalationrule' => 'Regla de priorización por defecto',
	'overallsatisfaction' => 'Satisfacción general',
	'writtencommunication' => 'Comunicación escrita',
	'writtenexplanations' => 'Explicación escrita',
	'responsespeeds' => 'Velocidades de respuesta',
	'lc_searchenginevisitors' => 'Visitantes desde buscador',
	'lc_skillsales' => 'Comercial',
	'lc_skillsupport' => 'Soporte',
	'lc_skillaccounts' => 'Cuentas',
	'lc_searchenginerule' => 'Visitantes desde buscador',
	'workflowcloseticket' => 'Cerrar ticket',
	'scconfirmcleardb' => '¿Está seguro de que desea resetear la base de datos?\nSi continúa se eliminarán todas las tablas de la base de datos.',
	'tickettypeissue' => 'Problema',
	'tickettypetask' => 'Tarea',
	'tickettypebug' => 'Fallo',
	'tickettypelead' => 'Posible cliente',
	'tickettypefeedback' => 'Comentarios',
	'sladefaultschedule' => 'Programación por defecto',
	'sladefaultplan' => 'Plan 12 horas por defecto',
	'defaultrule' => 'Regla por defecto',
	'spam' => 'Spam',
	'nospam' => 'No Spam',
	'setup' => 'Instalación',
	'upgrade' => 'Actualización',
	'upgautosetup' => 'Actualización automática',
	'modify' => 'Modificar',
	'diagnostics' => 'Diagnósticos',
	'setlicenseagreement' => 'Contrato de licencia',
	'setsysreq' => 'Requisitos del sistema',
	'setcollectinfo' => 'Recoger información',
	'setautosetup' => 'Instalación automática',
	'setsettings' => 'Configuración',
	'settemplates' => 'Plantillas',
	'setlocalization' => 'Localización',
	'setdone' => 'Hecho',
	'eula' => 'Contrato de licencia de usuario final',
	'iagree' => 'Estoy de acuerdo',
	'setupnext' => 'Siguiente &raquo;',
	'setupdroptable' => 'Eliminando tabla %s',
	'coreadministrator' => 'Administrador',
	'corestaff' => 'Operador',
	'coregeneral' => 'General',
	'coreguest' => 'Visitante',
	'coreregistered' => 'Registrado',
	'coredeftgroup' => 'Grupo de plantillas por defecto',
	'issuefixed' => 'Solucionado',
	'issueimplemented' => 'Implementado',
	'issuewontfix' => 'No se solucionará',
	'issuewontimplement' => 'No se implementará',
	'issueduplicate' => 'Duplicado',
	'issueincomplete' => 'Incompleto',
	'issuecannotrep' => 'No reproducible',
	'issuetimedout' => 'Caducado',
	'issueobsolete' => 'Obsoleto',
	'issuenotbug' => 'No es un fallo',
	'issuedeferred' => 'Retrasado',
	'issueblocks' => 'Bloquea',
	'issueisblockedby' => 'es bloqueado por',
	'issuerelatesto' => 'relativo a',
	'issueisrelatedto' => 'es relativo a',
	'issueinc' => 'incorpora',
	'issueincby' => 'es incorporado por',
	'issueduplicates' => 'duplica',
	'issueduplicatedby' => 'es duplicado por',
	'issueclonedas' => 'fue clonado como',
	'issueisderived' => 'deriva de',
	'issuebug' => 'Fallo',
	'issuefeaturerequest' => 'Petición de función',
	'issueimprovement' => 'Mejora',
	'issuetask' => 'Tarea',
	'issueopen' => 'Abierto',
	'issueinprogress' => 'En curso',
	'issuereopened' => 'Reabierto',
	'issueclosed' => 'Cerrado',
	'issueresolved' => 'Resuelto',
	'issuecritical' => 'Crítico',
	'issueurgent' => 'Urgente',
	'issuehigh' => 'Alto',
	'issuemedium' => 'Medio',
	'issuelow' => 'Bajo',
	'tcrelatesto' => 'relativo a',
	'tcisrelatedto' => 'es relativo a',
	'tcduplicates' => 'duplica',
	'tcisduplicatedby' => 'es duplicado por',
	'tcwasclonedas' => 'fue clonado como',
	'tcisderivedfrom' => 'se deriva de',
	'errorprefix' => 'Error: ',

	'sccachedir' => 'Comprobando si se puede escribir en el directorio cache',
	'sccachedirerror' => 'No se puede escribir en el directorio cache; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scfilesdir' => 'Comprobando si se puede escribir en el directorio files',
	'scfilesdirerror' => 'No se puede escribir en el directorio files; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scgeoipdir' => 'Comprobando si se puede escribir en el directorio geoip',
	'scgeoipdirerror' => 'No se puede escribir en el directorio geoip; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scminphpversion' => 'Comprobando la versión de PHP (versión mínima: %s)',
	'scminphpversionerror' => 'La versión de PHP instalada es anterior a la %s ' . SWIFT_PRODUCT .' no se puede instalar hasta que PHP se haya actualizaco al menos a la mínima versión aceptable.',
	'scfileup' => 'Comprobando si la subida de archivos está activada',
	'scfileuperror' => 'Se ha desactivado la subida de archivos en php.ini; Por favor cambie la variable file_uploads a \'On\' en php.ini antes de instalar ' . SWIFT_PRODUCT . '.',
	'scmaxupsize' => 'Comprobando el tamaño máximo de archivos en subidas',
	'scmaxupnotspec' => 'No especificado',
	'scmaxupsizeerror' => 'Cambie la variable upload_max_filesize en php.ini para incrementar el tamaño máximo permitido para subida de archivos si fuera necesario.',
	'scsafemodecheck' => 'Comprobando el estado de PHP safe mode',
	'scdisabled' => 'Desactivado',
	'scenabled' => 'Activado',
	'scenabled' => 'Activado',
	'scstrictmode' => 'Comprobando el Strict Mode de la base de datos (debe estar desactivado)',
	'scstrictmodeerror' => 'Strict Mode está activado en MySQL, Elimine STRICT_ALL_TABLES y/o STRICT_TRANS_TABLES del archivo de configuración (habitualmente my.cnf)',
	'scmagicquotesgpc' => 'Comprobando si magic quotes GPC está desactivado',
	'scmoduleerror' => '<span style="color: red; font-size: 11px; font-weight: bold;">El módulo <i>%1$s</i> no está configurado para cargarse con PHP. Por favor revise las <u><a style="color: red; font-size: 9pt;" target="_blank" href="%2$s">instrucciones</a></u> para habilitar %1$s en el manual de PHP.</span>',
	'scmodulecheck' => 'Comprobando si el módulo PHP %s está instalado',
	'scinstalled' => 'INSTALADO',
	'scmissing' => 'FALTA',
	'scdbnotempty' => 'La base de datos no está vacía. Por favor pulse "Resetear base de datos" para eliminar todas las tablas que contenga o Continuar para seguir con la instalación. Se recomienda que vacíe la base de datos o el proceso de instalación podría fallar.',
	'sccleardb' => 'Resetear base de datos',
	'sccontinue' => 'Continuar',
	'scnext' => 'Siguiente &raquo;',
	'scsyscheckfailed' => 'Lo sentimos, '. SWIFT_PRODUCT .' no se puede instalar. Ha ocurrido un error o su servidor web no cumple los requisitos mínimos del sistema. Por favor compruebe si aparecen errores en la parte superior y reintente el proceso de instalación tras resolverlos.',
	'scstartsetup' => 'Iniciar instalación',
	'scpassnomatch' => 'Las contraseñas no coinciden',
	'scfieldempty' => 'Uno de los campos requeridos está vacío',
	'scinvalidemail' => 'Se ha especificado una dirección de correo electrónico no válida',
	'scusernamelong' => 'El nombre de usuario especificado excede el tamaño máximo del campo',
	'scfieldlong' => 'Uno de los campos excede el tamaño máximo',
	'scsettingsbut' => 'Configuración &raquo;',
	'scmodsetfailed' => 'La instalación no ha podido ejecutar %s. Por favor contacte con el Soporte de Kayako.',
	'setupexecsql' => 'Ejecutando: %s',
	'setupexecinsert' => 'Insertando datos en: %s',
	'setupexecindex' => 'Creando índice: %s for Table: %s',
	'setupexectable' => 'Creando tabla: %s',
	'scinsertsettings' => 'Insertando ajustes para: %s',
	'scinsertsettingsgroup' => 'Creando grupo de ajustes: %s',
	'sctemplates' => 'Plantillas &raquo;',
	'sctemplatecategory' => 'Creando categoría de plantillas: %s',
	'sctemplate' => 'Creando plantilla: %s',
	'sclanguages' => 'Idioma &raquo;',
	'scpleasewait' => 'Por favor espere...',
	'sclanguage' => 'Creando idioma: %s',
	'sclanguagesection' => 'Creando sección de idioma: %s',
	'scsetupconfirmation' => '<b>'. SWIFT_PRODUCT .' ya está instalado en su servidor web!</b> Visite el Panel de Control de Administración para seguir configurando su instalación.<br/><br/><font color="red"><b>Nota importante:</b> No podrá usar '. SWIFT_PRODUCT .' hasta que no elimine el directorio \'setup\' en el directorio raíz de la instalación.</font><br/><br/><font color="darkblue"><b>Importación de datos:</b></font> Puede importar los datos desde la versión 3 de ' . SWIFT_PRODUCT . ' o desde otras soluciones de la competencia ejecutando el motor de importación desde el Panel de Control de Administración &gt; Importar.',
	'scupgradeconfirmation' => '<div class="smalltext">La actualización ha terminado satisfactoriamente. Su producto está ahora actualizado.</div><br/><br/><font color="red"><b>Nota importante:</b> Debe eliminar inmediatamente el directorio \'setup\' que se encuentra en el directorio raíz de la instalación. Si no lo hace se podría borrar completamente la base de datos si alguien ejecuta la instalación.',
	'scadmincp' => 'CP Admin (Panel de Control)',
	'scstaffcp' => 'CP Operadores (Panel de Control)',
	'scclientsc' => 'Centro de Soporte de usuarios',
	'scpdaint' => 'Interfaz PDA',
	'scfinish' => '&raquo; Terminar &laquo;',
	'diagnostics' => 'Diagnósticos',
	'diagresult' => 'Resultado de los diagnósticos',
	'stproduct' => 'Producto:',
	'stversion' => 'Versión:',
	'stbuilddate' => 'Fecha de Build:',
	'stbuildtype' => 'Tipo de Build:',
	'stsourcetype' => 'Tipo de Source:',
	'stverifyingconnection' => 'Verificando conexión con la base de datos',
	'stcurrentversion' => 'Versión actual:',
	'scaction' => 'Acción',
	'sccheckdbstruct' => 'Comprobar estructura de la base de datos',
	'diagmissingtables' => 'Tablas inexistentes',
	'diagmissingcolumns' => 'Columnas inexistentes',
	'diagcolumnmismatch' => 'MetaType Mismatch Columns',
	'diagcolumnlengthmismatch' => 'Length Mismatch Columns',
	'diagresultok' => 'La estructura de la base de datos está actualizada',
	'diagmissingindexes' => 'Índices inexistentes',
	'diagindexmismatch' => 'MetaType Mismatch Indexes',
	'sticketassigned' => 'Ticket asignado',
	'snewuser' => 'Registro de usuarios',
	// ======= END V4 LOCALES =======

	// ======= IMPORT FROM v3 =======
	'statusonhold' => 'En espera',
	'prlow' => 'Bajo',
	// ======= IMPORT FROM v3 =======

	'statusopen' => 'Abierto',
	'statusinprogress' => 'En curso',
	'statusclosed' => 'Cerrado',
	'prnormal' => 'Normal',
	'prmedium' => 'Media',
	'prhigh' => 'Alta',
	'prurgent' => 'Urgente',
	'premergency' => 'Emergencia',
	'prcritical' => 'Crítica',

	'defaultview' => 'Vista por defecto',
	'alltickets' => 'Todos los tickets',
	'impex' => 'Importar',
	'setupwelcome' => 'Bienvenido al asistente de instalación de Kayako ' . SWIFT_PRODUCT . '. Por favor seleccione una acción de la lista siguiente para continuar.',
);
?>