<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	/**
	 * ---------------------------------------------
	 * Report Locales
	 * ---------------------------------------------
	 */
	'r_tickets' => 'Tickets',
	'r_numunresolvticketsgbdepartment' => 'Matriz de número de tickets sin resolver, agrupada por departamento y responsable',
	'r_totalticketcountgbdepstatus' => 'Total de tickets, agrupados por departamento y estado',
	'r_numescalatedthismongbdep' => 'Número de tickets escalados este mes, agrupados por departamento',
	'r_numescalatedthismongbstatus' => 'Número de tickets escalados este mes, agrupados por estado',
	'r_numescalatedthismongbpriority' => 'Número de tickets escalados este mes, agrupados por prioridad',
	'r_numautoclosedthismongbdepartment' => 'Número de tickets cerrados automáticamente este mes, agrupados por departamento',
	'r_numautoclosedthismongbowner' => 'Número de tickets cerrados automáticamente este mes, agrupados por responsable',
	'r_listautoclosedthismongbdep' => 'Lista de tickets que se cerraron automáticamente este mes, agrupados por departamento',
	'r_listautoclosedthismongbowner' => 'Lista de tickets que se cerraron automáticamente este mes, agrupados por responsable',
	'r_numticketsgbcreationchannelanddepforthismo' => 'Número de tickets generados este mes, agrupados por canal de creación y departamento',
	'r_avgrepliesgbdepthismonth' => 'Media de respuestas a tickets en este mes, agrupadas por departamento',
	'r_avgrepliesgbownerthismonth' => 'Media de respuestas a tickets en este mes, agrupadas por responsable',
	'r_totalescthismonthgbweekday' => 'Número total de tickets escalados este mes, agrupados por semana y día',
	'r_numreopenthismonthgbdep' => 'Número de tickets reabiertos este mes, agrupados por departamento',
	'r_numreopenthismonthgbowner' => 'Número de tickets reabiertos este mes, agrupados por responsable',
	'r_numresolvedthismonthgbdep' => 'Número de tickets resueltos este mes, agrupados por departamento',
	'r_numresolvedthismonthgbowner' => 'Número de tickets resueltos este mes, agrupados por responsable',
	'r_avgescresolvedthismonthgbdep' => 'Media de escalados necesarios para resolver tickets este mes, agrupados por departamento',
	'r_avgescresolvedthismonthgbowner' => 'Media de escalados necesarios para resolver tickets este mes, agrupados por responsable',
	'r_avgtimetoresolvethismonthgbdep' => 'Media de tiempo de resolución de tickets este mes, agrupados por departamento',
	'r_avgtimetoresolvethismonthgbowner' => 'Media de tiempo de resolución de tickets este mes, agrupados por responsable',
	'r_avgrepliestoresolvethismonthgbdep' => 'Media de respuestas necesarias para resolver tickets este mes, agrupadas por departamento',
	'r_avgrepliestoresolvethismonthgbowner' => 'Media de respuestas necesarias para resolver tickets este mes, agrupadas por responsable',
	'r_avgrespthismonthgbdep' => 'Media de tiempo de respuesta de tickets este mes, agrupado por departamento',
	'r_avgrespthismonthgbowner' => 'Media de tiempo de respuesta de tickets este mes, agrupado por responsable',
	'r_avgowntoresolvethismonthgbdep' => 'Media de cambios de responsable necesarios para resolver tickets este mes, agrupados por departamento',
	'r_avgresponsetpgbstaffthismonth' => 'Media de tiempo de respuesta a mensajes de ticket este mes, agrupados por operador',
	'r_avgresponsetpgbdepthismonth' => 'Media de tiempo de respuesta a mensajes de ticket este mes, agrupados por departamento',
	'r_avgresponseclienttpgbdepthismonth' => 'Media de tiempo de respuesta para mensajes de ticket de usuario este mes, agrupado por departamento',
	'r_avgfirstresptimeticketsgbowner' => 'Media de tiempo de primera respuesta para tickets este mes, agrupado por responsable',
	'r_avgfirstresptimeticketsgbdep' => 'Media de tiempo de primera respuesta para tickets este mes, agrupado por departamento',
	'r_avgfirstresptimetpgbstaff' => 'Media de tiempo de primera respuesta para tickets este mes, agrupado por operador',
	'r_listticketsduetoday' => 'Listado de tickets que vencen hoy',
	'r_listoverduetickets' => 'Listado de tickets vencidos',
	'r_totaltimeworkbilledgbdep' => 'Tiempo total trabajado y facturado en tickets este mes, agrupado por departamento',
	'r_totaltimeworkbilledgbowner' => 'Tiempo total trabajado y facturado en tickets este mes, agrupado por responsable',
	'r_distbslaplansgbdepthismo' => 'Distribución de planes SLA para tickets este mes, agrupado por departamento',
	'r_avgresptimegbslathismo' => 'Tiempo medio de respuesta de tickets este mes, agrupado por plan SLA',
	'r_avgrepliesresgbslathismo' => 'Número medio de respuestas necesarias para resolver tickets este mes, agrupado por plan SLA',
	'r_avgrepliesgbslathismo' => 'Número medio de respuestas a tickets este mes, agrupado por plan SLA',
	'r_avgttresolvegbslathismo' => 'Tiempo medio de resolución de tickets este mes, agrupado por plan SLA',
	'r_perctickfcrthismonthgbdep' => 'Porcentaje de tickets resueltos en primer contacto este mes, agrupados por departamento',
	'r_perctickfcrthismonthgbowner' => 'Porcentaje de tickets resueltos en primer contacto este mes, agrupados por responsable',
	'r_perctickreopthismonthgbdep' => 'Porcentaje de tickets reabiertos este mes, agrupado por departamento',
	'r_perctickescthismonthgbdep' => 'Porcentaje de tickets escalados este mes, agrupados por departamento',
	'r_ratings' => 'Puntuación',
	'r_avgratticketsgbstaffthismonth' => 'Media de puntuaciones de tickets este mes, agrupado por operador',
	'r_avgpratticketsgbstaffthismonth' => 'Media de puntuaciones privadas de tickets este mes, agrupado por operador',
	'r_avgratticketsgbdepthismonth' => 'Media de puntuaciones de tickets este mes, agrupado por departamento',
	'r_avgpratticketsgbdepthismonth' => 'Media de puntuaciones privadas de tickets este mes, agrupado por departamento',
	'r_avgratticketpostsgbdepthismonth' => 'Media de puntuaciones de mensajes de ticket este mes, agrupado por operador',
	'r_avgpratticketpostsgbdepthismonth' => 'Media de puntuaciones privadas de mensajes de ticket este mes, agrupado por operador',
	'r_avgratlssurveygbstaffthismonth' => 'Media de puntuaciones por encuestas de chat este mes, agrupado por operador',
	'r_avgratlssurveygbdepthismonth' => 'Media de puntuaciones por encuestas de chat este mes, agrupado por departamento',
	'r_avgratchathistgbstaffthismonth' => 'Media de puntuaciones por historial de chat este mes, agrupado por operador',
	'r_avgratchathistgbdepthismonth' => 'Media de puntuaciones por historial de chat este mes, agrupado por departamento',
	'r_listofticketsratinglsthreethismonth' => 'Lista de tickets con puntuación menor de 3 este mes, agrupado por responsable',
	'r_listofticketpostsratinglsthreethismonth' => 'Lista de tickets con puntuación menor de 3 este mes, agrupado por creador',
	'r_listoflssurveylsthreethismonth' => 'Lista de encuestas de chat con puntuación menor de 3 este mes, agrupado por operador',
	'r_listofchathistorylsthreethismonth' => 'Lista de historial de chat con puntuación menor de 3 este mes, agrupado por operador',
	'r_ticketbilling' => 'Facturación',
	'r_totaltimebilledgbstaffthisweek' => 'Tiempo total facturado esta semana, agrupado por operador',
	'r_totaltimebilledgbstaffthismonth' => 'Tiempo total facturado este mes, agrupado por operador',
	'r_totaltimebilledgbdepartmentthisweek' => 'Tiempo total facturado esta semana, agrupado por departamento',
	'r_totaltimebilledgbdepartmentthismonth' => 'Tiempo total facturado este mes, agrupado por departamento',
	'r_totaltimebilledgbuserthisweek' => 'Tiempo total facturado esta semana, agrupado por usuario',
	'r_totaltimebilledgbuserthismonth' => 'Tiempo total facturado este mes, agrupado por usuario',
	'r_listticketsbilledgbstaffthisweek' => 'Lista de tickets facturados esta semana, agrupados por operador',
	'r_listticketsbilledgbstaffthismonth' => 'Lista de tickets facturados este mes, agrupados por operador',
	'r_listticketsbilledgbuserthisweek' => 'Lista de tickets facturados esta semana, agrupados por usuario',
	'r_listticketsbilledgbuserthismonth' => 'Lista de tickets facturados este mes, agrupados por usuario',
	'r_listticketsbilledgbuserorgthisweek' => 'Lista de tickets facturados esta semana, agrupados por organización de usuarios',
	'r_listticketsbilledgbuserorgthismonth' => 'Lista de tickets facturados este mes, agrupados por organización de usuarios',
	'r_listticketsbilledgbtypeuserthisweek' => 'Lista de tickets facturados esta semana, agrupados por tipo y usuario',
	'r_listticketsbilledgbtypeuserthismonth' => 'Lista de tickets facturados este mes, agrupados por tipo y usuario',
	'r_listticketsbilledgbdepuserthisweek' => 'Lista de tickets facturados esta semana, agrupados por departamento y usuario',
	'r_listticketsbilledgbdepuserthismonth' => 'Lista de tickets facturados este mes, agrupados por departamento y usuario',
	'r_ticketescalations' => 'Escalados',
	'r_ticketauditlogs' => 'Logs de auditoría',
	'r_workdonethisweek' => 'Trabajo realizado esta semana',
	'r_workdonethismonth' => 'Trabajo realizado este mes',
	'r_ticketsdeletedthismonth' => 'Tickets eliminados este mes',
	'r_completelogforthisweek' => 'Log completo de la semana',
	'r_completelogforthismonth' => 'Log completo del mes',
	'r_escalationsforthisweek' => 'Escalados esta semana',
	'r_escalationsforthismonth' => 'Escalados este mes',
	'r_escalationmatrixownerweek' => 'Matriz de escalados de la semana, agrupado por responsable',
	'r_escalationmatrixownermonth' => 'Matriz de escalados del mes, agrupados por responsable',
	'r_escalationmatrixdepartmentweek' => 'Matriz de escalados de la semana, agrupado por departamento',
	'r_escalationmatrixdepartmentmonth' => 'Matriz de escalados del mes, agrupado por departamento',
	'r_escalationmatrixtypeweek' => 'Matriz de escalados de la semana, agrupado por tipo',
	'r_escalationmatrixtypemonth' => 'Matriz de escalados del mes, agrupado por tipo',
	'r_calls' => 'Llamadas',
	'r_unansweredcallsthisweek' => 'Llamadas no respondidas esta semana',
	'r_unansweredcallsthismonth' => 'Llamadas no respondidas este mes',
	'r_callmatrixgbstaffforthisweek' => 'Matriz de llamadas de la semana, agrupado por responsable',
	'r_callmatrixgbstaffforthismonth' => 'Matriz de llamadas del mes, agrupado por responsable',
	'r_avgdurationcallsgbstaffforthisweek' => 'Duración media de llamadas esta semana, agrupado por operador',
	'r_avgdurationcallsgbstaffforthismonth' => 'Duración media de llamadas este mes, agrupado por operador',
	'r_totaldurationcallsgbstaffforthisweek' => 'Duración total de llamadas esta semana, agrupado por operador',
	'r_totaldurationcallsgbstaffforthismonth' => 'Duración total de llamadas este mes, agrupado por operador',
	'r_totalincomingcallsgbdepartmentforthisweek' => 'Llamadas entrantes totales de la semana, agrupadas por departamento',
	'r_totalincomingcallsgbdepartmentforthismonth' => 'Llamadas entrantes totales del mes, agrupadas por departamento',
	'r_callcountgbdayforthisweek' => 'Recuento de llamadas de la semana, agrupado por día',
	'r_callcountgbweekforthismonth' => 'Recuento de llamadas del mes, agrupado por semana',
	'r_callcountmatrixgbdayforthisweek' => 'Matriz de recuento de llamadas de la semana, agrupado por día y estado',
	'r_callcountmatrixgbweekforthismonth' => 'Matriz de recuento de llamadas del mes, agrupado por semana y estado',
	'r_chatrouting' => 'Enrutado de chat',
	'r_unansweredchatsgbstaffforthisweek' => 'Chats no respondidos esta semana, agrupados por operador',
	'r_unansweredchatsgbstaffforthismonth' => 'Chats no respondidos este mes, agrupados por operador',
	'r_unansweredchatcountmatrixgbstaffforthisweek' => 'Matriz de recuento de chats no respondidos de la semana, agrupado por operador',
	'r_unansweredchatcountmatrixgbstaffforthismonth' => 'Matriz de recuento de chats no respondidos del mes, agrupados por operador',
	'r_chats' => 'Chats',
	'r_avgroundrobinhitsgbdepartmentthisweek' => 'Media de rondas necesarias para atender chats esta semana, agrupado por departamento',
	'r_avgroundrobinhitsgbdepartmentthismonth' => 'Media de rondas necesarias para atender chats este mes, agrupado por departamento',
	'r_avgwaittimegbdepartmentthisweek' => 'Tiempo medio de espera para chats esta semana, agrupado por departamento',
	'r_avgwaittimegbdepartmentthismonth' => 'Tiempo medio de espera para chats este mes, agrupado por departamento',
	'r_chatstatusmatrixthisweek' => 'Matriz de estado de chats para esta semana',
	'r_chatstatusmatrixthismonth' => 'Matriz de estado de chats para este mes',
	'r_transfermatrixgbdepartmentthisweek' => 'Matriz de transferencias de chat de esta semana, agrupado por departamento',
	'r_transfermatrixgbdepartmentthismonth' => 'Matriz de transferencias de chat de este mes, agrupado por departamento',
	'r_unansweredchatgbdepartmentthisweek' => 'Matriz de recuento de chats no respondidos esta semana, agrupado por departamento',
	'r_unansweredchatgbdepartmentthismonth' => 'Matriz de recuento de chats no respondidos este mes, agrupado por departamento',
	'r_unansweredchatgbhourdepartmentthisweek' => 'Matriz de recuento de chats no respondidos, agrupado por hora y departamento',
	'r_listunansweredchatgbdepartmentthisweek' => 'Lista de chats no respondidos esta semana, agrupada por departamento',
	'r_listunansweredchatgbdepartmentthismonth' => 'Lista de chats no respondidos este mes, agrupada por departamento',
	'r_proactivechatgbdepartmentthisweek' => 'Matriz de recuento de chat proactivos esta semana, agrupado por departamento',
	'r_proactivechatgbdepartmentthismonth' => 'Matriz de recuento de chat proactivos este mes, agrupado por departamento',
	'r_answeredchatgbstaffthisweek' => 'Matriz de recuento de chats respondidos esta semana, agrupado por operador',
	'r_answeredchatgbstaffthismonth' => 'Matriz de recuento de chats respondidos este mes, agrupado por operador',
	'r_totalchatgbdepartmentthisweek' => 'Matriz de recuento del total de chats de la semana, agrupado por departamento',
	'r_totalchatgbdepartmentthismonth' => 'Matriz de recuento del total de chats del mes, agrupado por departamento',
	'r_totalchatthisweek' => 'Recuento total de chats de la semana',
	'r_totalchatthismonth' => 'Recuento total de chats del mes',
	'r_totalchatgbcountry' => 'Recuento total de chats, agrupado por país',
	'r_totalchatgbcountrycity' => 'Recuento total de chars, agrupado por país y localidad',

	// ======= BEGIN V4 LOCALES =======
	'myopentickets' => 'Mis tickets abiertos',
	'mypendingtickets' => 'Mis tickets pendientes',
	'defaultescalationrule' => 'Regla de priorización por defecto',
	'overallsatisfaction' => 'Satisfacción general',
	'writtencommunication' => 'Comunicación escrita',
	'writtenexplanations' => 'Explicación escrita',
	'responsespeeds' => 'Velocidades de respuesta',
	'lc_searchenginevisitors' => 'Visitantes desde buscador',
	'lc_skillsales' => 'Comercial',
	'lc_skillsupport' => 'Soporte',
	'lc_skillaccounts' => 'Cuentas',
	'lc_searchenginerule' => 'Visitantes desde buscador',
	'workflowcloseticket' => 'Cerrar ticket',
	'scconfirmcleardb' => '¿Está seguro de que desea resetear la base de datos?\nSi continúa se eliminarán todas las tablas de la base de datos.',
	'tickettypeissue' => 'Problema',
	'tickettypetask' => 'Tarea',
	'tickettypebug' => 'Fallo',
	'tickettypelead' => 'Posible cliente',
	'tickettypefeedback' => 'Comentarios',
	'sladefaultschedule' => 'Programación por defecto',
	'sladefaultplan' => 'Plan 12 horas por defecto',
	'sautocloserule' => 'Regla de autocierre por defecto',
	'defaultrule' => 'Regla por defecto',
	'spam' => 'Spam',
	'nospam' => 'No Spam',
	'setup' => 'Instalación',
	'upgrade' => 'Actualización',
	'upgautosetup' => 'Actualización automática',
	'modify' => 'Modificar',
	'diagnostics' => 'Diagnósticos',
	'setlicenseagreement' => 'Contrato de licencia',
	'setsysreq' => 'Requisitos del sistema',
	'setcollectinfo' => 'Recoger información',
	'setautosetup' => 'Instalación automática',
	'setsettings' => 'Configuración',
	'settemplates' => 'Plantillas',
	'setlocalization' => 'Localización',
	'setdone' => 'Hecho',
	'eula' => 'Contrato de licencia de usuario final',
	'iagree' => 'Estoy de acuerdo',
	'setupnext' => 'Siguiente &raquo;',
	'setupdroptable' => 'Eliminando tabla %s',
	'coreadministrator' => 'Administrador',
	'corestaff' => 'Operador',
	'coregeneral' => 'General',
	'coreguest' => 'Visitante',
	'coreregistered' => 'Registrado',
	'coredeftgroup' => 'Grupo de plantillas por defecto',
	'issuefixed' => 'Solucionado',
	'issueimplemented' => 'Implementado',
	'issuewontfix' => 'No se solucionará',
	'issuewontimplement' => 'No se implementará',
	'issueduplicate' => 'Duplicado',
	'issueincomplete' => 'Incompleto',
	'issuecannotrep' => 'No reproducible',
	'issuetimedout' => 'Caducado',
	'issueobsolete' => 'Obsoleto',
	'issuenotbug' => 'No es un fallo',
	'issuedeferred' => 'Retrasado',
	'issueblocks' => 'Bloquea',
	'issueisblockedby' => 'es bloqueado por',
	'issuerelatesto' => 'relativo a',
	'issueisrelatedto' => 'es relativo a',
	'issueinc' => 'incorpora',
	'issueincby' => 'es incorporado por',
	'issueduplicates' => 'duplica',
	'issueduplicatedby' => 'es duplicado por',
	'issueclonedas' => 'fue clonado como',
	'issueisderived' => 'deriva de',
	'issuebug' => 'Fallo',
	'issuefeaturerequest' => 'Petición de función',
	'issueimprovement' => 'Mejora',
	'issuetask' => 'Tarea',
	'issueopen' => 'Abierto',
	'issueinprogress' => 'En curso',
	'issuereopened' => 'Reabierto',
	'issueclosed' => 'Cerrado',
	'issueresolved' => 'Resuelto',
	'issuecritical' => 'Crítico',
	'issueurgent' => 'Urgente',
	'issuehigh' => 'Alto',
	'issuemedium' => 'Medio',
	'issuelow' => 'Bajo',
	'tcrelatesto' => 'relativo a',
	'tcisrelatedto' => 'es relativo a',
	'tcduplicates' => 'duplica',
	'tcisduplicatedby' => 'es duplicado por',
	'tcwasclonedas' => 'fue clonado como',
	'tcisderivedfrom' => 'se deriva de',
	'errorprefix' => 'Error: ',

	'sccachedir' => 'Comprobando si se puede escribir en el directorio cache',
	'sccachedirerror' => 'No se puede escribir en el directorio cache; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scfilesdir' => 'Comprobando si se puede escribir en el directorio files',
	'scfilesdirerror' => 'No se puede escribir en el directorio files; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scgeoipdir' => 'Comprobando si se puede escribir en el directorio geoip',
	'scgeoipdirerror' => 'No se puede escribir en el directorio geoip; cambie los permisos de acceso como se describe en el manual de ' . SWIFT_PRODUCT . '.',
	'scminphpversion' => 'Comprobando la versión de PHP (versión mínima: %s)',
	'scminphpversionerror' => 'La versión de PHP instalada es anterior a la %s ' . SWIFT_PRODUCT .' no se puede instalar hasta que PHP se haya actualizaco al menos a la mínima versión aceptable.',
	'scfileup' => 'Comprobando si la subida de archivos está activada',
	'scfileuperror' => 'Se ha desactivado la subida de archivos en php.ini; Por favor cambie la variable file_uploads a \'On\' en php.ini antes de instalar ' . SWIFT_PRODUCT . '.',
	'scmaxupsize' => 'Comprobando el tamaño máximo de archivos en subidas',
	'scmaxupnotspec' => 'No especificado',
	'scmaxupsizeerror' => 'Cambie la variable upload_max_filesize en php.ini para incrementar el tamaño máximo permitido para subida de archivos si fuera necesario.',
	'scsafemodecheck' => 'Comprobando el estado de PHP safe mode',
	'scdisabled' => 'Desactivado',
	'scenabled' => 'Activado',
	'scenabled' => 'Activado',
	'scstrictmode' => 'Comprobando el Strict Mode de la base de datos (debe estar desactivado)',
	'scstrictmodeerror' => 'Strict Mode está activado en MySQL, Elimine STRICT_ALL_TABLES y/o STRICT_TRANS_TABLES del archivo de configuración (habitualmente my.cnf)',
	'scmagicquotesgpc' => 'Comprobando si magic quotes GPC está desactivado',
	'scmoduleerror' => '<span style="color: red; font-size: 11px; font-weight: bold;">El módulo <i>%1$s</i> no está configurado para cargarse con PHP. Por favor revise las <u><a style="color: red; font-size: 9pt;" target="_blank" href="%2$s">instrucciones</a></u> para habilitar %1$s en el manual de PHP.</span>',
	'scmodulecheck' => 'Comprobando si el módulo PHP %s está instalado',
	'scinstalled' => 'INSTALADO',
	'scmissing' => 'FALTA',
	'scdbnotempty' => 'La base de datos no está vacía. Por favor pulse "Resetear base de datos" para eliminar todas las tablas que contenga o "Continuar" para seguir con la instalación. Se recomienda que vacíe la base de datos o el proceso de instalación podría fallar.',
	'sccleardb' => 'Resetear base de datos',
	'sccontinue' => 'Continuar',
	'scnext' => 'Siguiente &raquo;',
	'scsyscheckfailed' => 'Lo sentimos, '. SWIFT_PRODUCT .' no se puede instalar. Ha ocurrido un error o su servidor web no cumple los requisitos mínimos del sistema. Por favor compruebe si aparecen errores en la parte superior y reintente el proceso de instalación tras resolverlos.',
	'scstartsetup' => 'Iniciar instalación',
	'scpassnomatch' => 'Las contraseñas no coinciden',
	'scfieldempty' => 'Uno de los campos requeridos está vacío',
	'scinvalidemail' => 'Se ha especificado una dirección de correo electrónico no válida',
	'scusernamelong' => 'El nombre de usuario especificado excede el tamaño máximo del campo',
	'scfieldlong' => 'Uno de los campos excede el tamaño máximo',
	'scsettingsbut' => 'Configuración &raquo;',
	'scmodsetfailed' => 'La instalación no ha podido ejecutar %s. Por favor contacte con el Soporte de Kayako.',
	'setupexecsql' => 'Ejecutando: %s',
	'setupexecinsert' => 'Insertando datos en: %s',
	'setupexecindex' => 'Creando índice: %s for Table: %s',
	'setupexectable' => 'Creando tabla: %s',
	'scinsertsettings' => 'Insertando ajustes para: %s',
	'scinsertsettingsgroup' => 'Creando grupo de ajustes: %s',
	'sctemplates' => 'Plantillas &raquo;',
	'sctemplatecategory' => 'Creando categoría de plantillas: %s',
	'sctemplate' => 'Creando plantilla: %s',
	'sclanguages' => 'Idioma &raquo;',
	'scpleasewait' => 'Por favor espere...',
	'sclanguage' => 'Creando idioma: %s',
	'sclanguagesection' => 'Creando sección de idioma: %s',
	'scsetupconfirmation' => '<b>'. SWIFT_PRODUCT .' ya está instalado en su servidor web!</b> Visite el Panel de Control de Administración para seguir configurando su instalación.<br/><br/><font color="red"><b>Nota importante:</b> No podrá usar '. SWIFT_PRODUCT .' hasta que no elimine el directorio \'setup\' en el directorio raíz de la instalación.</font><br/><br/><font color="darkblue"><b>Importación de datos:</b></font> Puede importar los datos desde versiones anteriores de productos Kayako o desde productos de terceros mediante el motor de importación del Panel de Control de Administración.',
	'scupgradeconfirmation' => '<div class="smalltext">La actualización ha terminado satisfactoriamente. Su producto está ahora actualizado.</div><br/><br/><font color="red"><b>Nota importante:</b> Debe eliminar inmediatamente el directorio \'setup\' que se encuentra en el directorio raíz de la instalación. Si no lo hace se podría borrar completamente la base de datos si alguien ejecuta la instalación.',
	'scadmincp' => 'CP Admin (Panel de Control)',
	'scstaffcp' => 'CP Operadores (Panel de Control)',
	'scclientsc' => 'Centro de Soporte de usuarios',
	'scpdaint' => 'Interfaz PDA',
	'scfinish' => '&raquo; Terminar &laquo;',
	'diagnostics' => 'Diagnósticos',
	'diagresult' => 'Resultado de los diagnósticos',
	'stproduct' => 'Producto:',
	'stversion' => 'Versión:',
	'stbuilddate' => 'Fecha de Build:',
	'stbuildtype' => 'Tipo de Build:',
	'stsourcetype' => 'Tipo de Source:',
	'stverifyingconnection' => 'Verificando conexión con la base de datos',
	'stcurrentversion' => 'Versión actual:',
	'scaction' => 'Acción',
	'sccheckdbstruct' => 'Comprobar estructura de la base de datos',
	'diagmissingtables' => 'Tablas inexistentes',
	'diagmissingcolumns' => 'Columnas inexistentes',
	'diagcolumnmismatch' => 'MetaType Mismatch Columns',
	'diagcolumnlengthmismatch' => 'Length Mismatch Columns',
	'diagresultok' => 'La estructura de la base de datos está actualizada',
	'diagmissingindexes' => 'Índices inexistentes',
	'diagindexmismatch' => 'MetaType Mismatch Indexes',
	'sticketassigned' => 'Ticket asignado',
	'snewuser' => 'Registro de usuarios',
	// ======= END V4 LOCALES =======

	// ======= IMPORT FROM v3 =======
	'statusonhold' => 'En espera',
	'prlow' => 'Bajo',
	// ======= IMPORT FROM v3 =======

	'statusopen' => 'Abierto',
	'statusinprogress' => 'En curso',
	'statusclosed' => 'Cerrado',
	'prnormal' => 'Normal',
	'prmedium' => 'Media',
	'prhigh' => 'Alta',
	'prurgent' => 'Urgente',
	'premergency' => 'Emergencia',
	'prcritical' => 'Crítica',

	'defaultview' => 'Vista por defecto',
	'alltickets' => 'Todos los tickets',
	'impex' => 'Importar',
	'setupwelcome' => 'Bienvenido al asistente de instalación de Kayako ' . SWIFT_PRODUCT . '. Por favor seleccione una acción de la lista siguiente para continuar.',
);
?>