<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array(
	'manage' => 'Administrar',

	'tabgeneral' => 'General',
	'tabmassaction' => 'Acción masiva',
	'tabreply' => 'Responder',
	'tabforward' => 'Reenviar',

	'manochange' => '-- Sin cambios --',
	'maticketstatus' => 'Estado de ticket',
	'maticketpriority' => 'Prioridad de ticket',
	'matickettype' => 'Tipo de ticket',
	'madepartment' => 'Departamento',
	'maowner' => 'Responsable',
	'maticketlink' => 'Enlazar',
	'maaddtags' => 'Añadir etiquetas',
	'maremovetags' => 'Eliminar etiquetas',
	'maticketflag' => 'Marca',
	'manoflag' => '-- Sin marca --',
	'mabayescategory' => 'Entrenar bayesiano',
	'sactivestaff' => '-- Operador activo --',
	'tnavnextticket' => 'Siguiente ticket &raquo;',
	'tnavprevticket' => '&laquo; Ticket anterior',

	/**
	 * ---------------------------------------------
	 * Viewing a Ticket
	 * ---------------------------------------------
	 */
	'mergeoptions' => 'Opciones de fusion',
	'mergeparentticket' => 'Id de ticket principal',
	'desc_mergeparentticket' => 'si se especifica, el ticket actual se fusionará con el ticket especificado.',
	'titleeditmergefailed' => 'La fusión de los tickets ha fallado',
	'msgeditmergefailed' => SWIFT_PRODUCT . ' no ha podido fusionar los tickets porque el ticket principal no se ha podido localizar en la base de datos. Por favor, asegúrese de que el identificador (ID) que ha introducido es válido.',
	'titleeditmergesuccess' => 'Los tickets se han fusionado correctamente',
	'msgeditmergesuccess' => SWIFT_PRODUCT . ' ha fusionado correctamente el ticket.',
	'putback' => 'Retrasado',
	'tabcalls' => 'Llamadas',
	'dispatchasuser' => 'Como usuario',
	'viewticket' => 'Ver ticket',
	'viewticketext' => '[#%s]: %s',
	'proptitleticketid' => 'ID DE TICKET',
	'proptitledepartment' => 'DEPARTAMENTO',
	'proptitleowner' => 'RESPONSABLE',
	'proptitlestatus' => 'ESTADO',
	'proptitlepriority' => 'PRIORIDAD',
	'proptitletype' => 'TIPO',
	'tinforesolutiondue' => 'Vencimiento resolución: ',
	'tinfosla' => 'SLA: ',
	'tinfoticketid' => 'ID: ',
	'tinfodue' => 'Vencimiento: ',
	'tinfocreated' => 'Creado: ',
	'tinfoupdated' => 'Actualizado: ',
	'ticketlinkinfo' => 'Departamento: %s, Estado: %s',
	'tppostedon' => 'Publicado el %s',
	'tppostedonsurvey' => 'Comentario de encuesta publicado el %s',
	'tpemail' => 'Email: %s',
	'tpipaddress' => 'Dirección IP: %s',
	'participantbox' => 'Participantes',
	'badgethirdparty' => 'Tercero',
	'badgeuser' => 'Usuario',
	'badgestaff' => 'Operador',
	'badgecc' => 'CC',
	'badgebcc' => 'BCC',
	'wineditticketpost' => 'Editar mensaje ticket',
	'editpost' => 'Editar mensaje',
	'lastedited' => 'Editado por última vez por %s el %s',
	'wineditdue' => 'Editar vencimiento y línea de tiempo de vencimiento de resolución',
	'dialogduetimeline' => 'Vencimiento',
	'dialogresolutionduetimeline' => 'Vencimiento de resolución',
	'stopwatching' => 'Dejar de vigilar',
	'surrender' => 'Rendirse',
	'print' => 'Imprimir',
	'take' => 'Asignármelo a mí',
	'tabauditlog' => 'Log de auditoría',
	'aldescription' => 'Descripción',
	'aldate' => 'Fecha',
	'altimeline' => 'Línea de tiempo',
	'alentrytype' => 'Tipo de entrada',
	'alstaff' => ' (Operador)',
	'aluser' => ' (Usuario)',
	'alsystem' => ' (Sistema)',
	'alparser' => ' (Parser)',
	'editnote' => 'editar nota',
	'notetitle' => '%s el %s',
	'noteeditedtitle' => ' <i>(Editado por %s el %s)</i>',
	'ticketnotedelconfirm' => 'Está seguro  de que desea eliminar esta nota?',
	'tabaddnote' => 'Añadir nota',
	'tabeditnote' => 'Editar nota',
	'addnotes' => 'Notas',
	'notetype' => 'Tipo de nota',
	'addnote' => 'Añadir nota',
	'notes_ticket' => 'Ticket',
	'notes_user' => 'Usuario',
	'notes_userorganization' => 'Organización de usuario',
	'tabrelease' => 'Lanzamiento',
	'tabedit' => 'Editar',
	'tabhistory' => 'Historial',
	'tabchats' => 'Chats',
	'tabuser' => 'Usuarios',
	'notesvisibleall' => '-- Todos --',
	'notevisibleto' => 'Visibilidad',
	'desc_notevisibleto' => 'Puede usar esta opción para restringir la visibilidad de la nota a un operador concreto.',
	'edit_subject' => 'Asunto',
	'edit_fullname' => 'Nombre',
	'edit_email' => 'Email',
	'edit_overridesla' => 'Anular SLA',
	'desc_edit_overridesla' => 'Si está activado, este ticket seguirá usando el plan SLA seleccionado independientemente de las reglas de SLA existentes.',
	'editslausedef' => '-- Usar SLA por defecto --',
	'edittproperties' => 'Propiedades de ticket',
	'edittrecipients' => 'Destinatarios de ticket',
	'editrecipientsdesc' => 'Puede añadir un nuevo destinatario abajo introduciendo una dirección de email en el tipo de destinatario seleccionado. El destinatario seleccionado recibirá las respuestas de los operadores automáticamente, pero no tendrá acceso al ticket en el centro de soporte.<br /><br />Los destinatarios del ticket reciben todos los emails enviados por los operadores. La opción de añadir destinatarios al ticket está disponible cuando se envía un CC, BCC o se reenvía un ticket. Hay tres tipos de destinatario:<br><br><i>Tercero:</i> Un tercero al que se añade a un ticket recibe un CC de todas las respuestas enviadas por el operador. Además, un tercero puede enviar respuestas por email y éstas se añadirán al ticket, aunque el ticket no fuera creado por él.<br><br><i>Usuarios CC:</i> Un usuario CC que se añade a un ticket recibe una copia de todas las respuestas enviadas por un operador.<br><br><i>Usuarios BCC:</i> Un usuario BCC añadido a un ticket recibe una copia oculta de todas las respuestas enviadas por un operador.',
	'editthirdparty' => 'Tercero',
	'editcc' => 'CC',
	'editbcc' => 'BCC',
	'history_ticketid' => 'ID de ticket',
	'history_subject' => 'Asunto',
	'history_date' => 'Fecha',
	'history_department' => 'Departamento',
	'history_type' => 'Tipo',
	'history_status' => 'Estado',
	'history_priority' => 'Prioridad',
	'workflowbox' => 'Flujo de trabajo',
	'informationbox' => 'Información',
	'tinfobticketid' => 'ID DE TICKET',
	'tinfobuser' => 'USUARIO',
	'tinfobuserorganization' => 'ORGANIZACION',
	'tinfobusergroup' => 'GRUPO',
	'dispatchfrom' => 'De',
	'dispatchto' => 'Para',
	'dispatchcc' => 'CC',
	'dispatchbcc' => 'BCC',
	'dispatchcontents' => 'Contenido de la respuesta',
	'dispatchaddmacro' => 'Macro',
	'dispatchaddkb' => 'Base de conocimiento',
	'dispatchsendmail' => 'Enviar email',
	'dispatchwatch' => 'Vigilar',
	'dispatchaddfile' => 'Añadir archivo',
	'dispatchsend' => 'Enviar',
	'dispatchattachfile' => 'Adjuntar',
	'dispatchsaveasdraft' => 'Guardar como borrador',
	'dispatchto' => 'Para',
	'dispatchsubject' => 'Asunto',
	'dispatchsend' => 'Enviar',
	'dispatchsendar' => 'Enviar autorrespuesta',
	'dispatchuser' => 'Usuario',
	'dispatchnewuser' => 'Nuevo usuario',
	'dispatchisphone' => 'Ticket telefónico',
	'winuserquickinsert' => 'Nuevo usuario',
	'dispatch' => 'Despachar',
	'tabdispatch' => 'Despachar',
	'dispatchticket' => 'Despachar ticket',
	'assign' => 'Asignar',
	'newticket' => 'Nuevo ticket',
	'newticket_department' => 'Departamento',
	'desc_newticketdepartment' => 'Seleccione el departamento en el que desea crear el ticket.',
	'nt_sendmail' => 'Enviar email',
	'nt_asuser' => 'Como usuario/telefónico',
	'newticket_type' => 'Tipo',
	'desc_newticket_type' => 'Seleccione el tipo de ticket que desea crear.<br /><br /><i>Enviar email:</i> Envía un email a una dirección de email (funciona como un cliente de correo electrónico)<br /><i>Como usuario/telefónico:</i> Crear un ticket o registrar una llamada telefónica entrante en la cuenta de un usuario.',
	'nt_next' => 'Siguiente',
	'tabnewticket' => 'Nuevo ticket',
	'dispatchcreate' => 'Crear',
	'tabnewticket2' => 'Nuevo ticket: %s',
	'tpemailto' => 'Email enviado a: %s',
	'tpemailforwardedto' => 'Reenviado a: %s',
	'tlockinfo' => '%s está viendo el ticket (última actualización: %s)',
	'tpostlockinfo' => '%s está respondiendo al ticket (última actualización: %s)',
	'tabbilling' => 'Facturación',
	'tabfollowup' => 'Revisión',
	'notes' => 'Notas',
	'billworker' => 'Trabajador',
	'billdate' => 'Fecha de factura',
	'billworkdate' => 'Fecha de trabajo',
	'billtimespent' => 'Tiempo invertido (hh:mm)',
	'billworked' => 'Trabajado:',
	'billtotalworked' => 'Tiempo total trabajado:',
	'billbillable' => 'Facturable:',
	'billtotalbillable' => 'Tiempo total facturable:',
	'editbilling' => 'Editar facturación',
	'tabeditbilling' => 'Editar facturación',
	'billingtitle' => 'Facturación de: %s el %s',
	'billingtitlework' => ' (trabajado en: %s)',
	'billingeditedtitle' => ' <i>(Editado por %s el %s)</i>',
	'billingeditedtitle2' => ' <i>(editado el %s)</i>',
	'editbilling' => 'Editar registro de facturación',
	'ticketbillingdelconfirm' => 'Está seguro de que desea eliminar este registro de facturación de ticket?',
	'titleinvalidbilldate' => 'Valor de tiempo invertido no válido',
	'msginvalidbilldate' => 'Por favor, especifique un valor válido para la fecha y la hora de los campos "facturable" y "trabajable".',
	'fugeneral' => 'General',
	'fuaddnote' => 'Añadir nota',
	'fupostreply' => 'Responder',
	'fuforward' => 'Reenviar',
	'followupmins' => 'En n minutos',
	'followuphours' => 'En n horas',
	'followupdays' => 'En n días',
	'followupweeks' => 'En n semanas',
	'followupmonths' => 'En n meses',
	'followupcustom' => 'Personalizado',
	'followup' => 'Revisión',
	'currentfollowups' => 'Current follow-ups for this ticket:',
	'followup_willrunattime' => 'Will run follow-up at %s created by %s (%s)',
	'followup_willchangeownerto' => 'Will change ticket owner to %s',
	'followup_willchangedepartmentto' => 'Will change department to %s',
	'followup_willchangestatusto' => 'Will change status to %s',
	'followup_willchangepriorityto' => 'Will change priority to %s',
	'followup_willchangetypeto' => 'Will change type to %s',
	'followup_willaddstaffnotes' => 'Will add a ticket note',
	'followup_willaddusernotes' => 'Will add a user note',
	'followup_willaddareply' => 'Will add a pre-written reply to this ticket',
	'followup_willforwardto' => 'Will forward this ticket to %s',
	'followup_removeowner' => 'Will remove this ticket\'s owner',
	'flag' => 'Flag',
	'tescalationhistory' => 'View Escalation History (%d)',
	'tepdate' => 'Escalation Date: ',
	'tepslaplan' => 'SLA Plan: ',
	'tepescalationrule' => 'Escalation Rule: ',
	'ntchatid' => 'Chat ID: ',
	'ntchatuserfullname' => 'User: ',
	'ntchatuseremail' => 'Email: ',
	'ntchatstafffullname' => 'Staff: ',
	'ntchatdepartment' => 'Department: ',
	'titleticketdeleted' => 'Ticket Deleted',
	'msgticketdeleted' => 'Unable to load ticket, ticket has been deleted',

	/**
	 * ---------------------------------------------
	 * MACRO
	 * ---------------------------------------------
	 */
	'macro' => 'Macro',
	'macros' => 'Macros',
	'insertmacro' => 'Insert Macro',
	'editmacro' => 'Edit Macro',
	'tabcategories' => 'Categories',
	'tabreplies' => 'Replies',
	'replytitle' => 'Reply Title',
	'macrotitle' => 'Macro Title',
	'insertcategory' => 'Insert Category',
	'insertreply' => 'Insert Reply',
	'wininsertmacrocat' => 'Insert Macro Category',
	'parentcategoryitem' => '- Parent Category -',
	'macrocategorytitle' => 'Category Title',
	'desc_macrocategorytitle' => 'Enter a title for the category.',
	'parentcategory' => 'Parent Category',
	'desc_parentcategory' => 'The category under which the new category will be added. You can organize categories in a heirarchy to an unlimited level.',
	'categorytype' => 'Category Type',
	'desc_categorytype' => '<i>Public:</i> Visible to all staff users.<BR /><BR /><i>Private:</i> Visible only to the staff user who created the category.',
	'titlemacrocategoryinsert' => 'Inserted Macro Category "%s"',
	'msgmacrocategoryinsert' => SWIFT_PRODUCT . ' has successfully inserted the macro category "%s".',
	'titlemacrocategoryupdate' => 'Updated Macro Category "%s"',
	'msgmacrocategoryupdate' => SWIFT_PRODUCT . ' has successfully updated the macro category "%s".',
	'titleinvalidparentcat' => 'Invalid Parent Category',
	'msginvalidparentcat' => 'The parent category specified is invalid. Please check that the category tree to make sure that the category selected is not a child category.',
	'titledelmacrocat' => 'Deleted "%d" Macro Categories',
	'msgdelmacrocat' => SWIFT_PRODUCT . ' has successfully deleted the following macro categories from the database:',
	'filterreplies' => 'Filter Replies',
	'rootcategory' => 'Root Category',
	'macroreplytitle' => 'Macro Title',
	'desc_macroreplytitle' => 'Enter a title for the macro reply.',
	'parentcategoryreply' => 'Parent Category',
	'desc_parentcategoryreply' => 'The category under which the new reply will be added.',
	'reststaffgroupall' => '-- All Staff Teams --',
	'restrictstaffgroup' => 'Visible to',
	'desc_restrictstaffgroup' => 'You can restrict the visibility of this category to a specified team by selecting one from the available options.',
	'macroreplycontents' => 'Reply Contents',
	'tabproperties' => 'Properties',
	'ticketfields' => 'Ticket Properties',
	'macrodepartment' => 'Department',
	'desc_macrodepartment' => '',
	'macroticketstatus' => 'Ticket Status',
	'desc_macroticketstatus' => '',
	'macrotickettype' => 'Ticket Type',
	'desc_macrotickettype' => '',
	'macroticketpriority' => 'Ticket Priority',
	'desc_macroticketpriority' => '',
	'desc_macroaddtags' => '',
	'macroaddtags' => 'Add Tags',
	'macroownerstaff' => 'Ticket Owner',
	'desc_macroownerstaff' => '',
	'insertmacro' => 'Insert Macro',
	'editmacro' => 'Edit Macro',
	'titlemacroreplyinsert' => 'Inserted Macro "%s"',
	'msgmacroreplyinsert' => SWIFT_PRODUCT . ' has successfully inserted the macro "%s".',
	'titlemacroreplyupdate' => 'Updated Macro "%s"',
	'msgmacroreplyupdate' => SWIFT_PRODUCT . ' has successfully updated the macro "%s".',
	'titledelmacroreply' => 'Deleted "%d" Macro Replies',
	'msgdelmacroreply' => SWIFT_PRODUCT . ' has successfully deleted the following macro relpies from the database:',
	'quickinsert' => 'Quick Insert',
	'qimacro' => 'Macro',
	'qiknowledgebase' => 'Knowledgebase',
	'qidownloads' => 'Downloads',
	'replytotalhits' => 'Hits',
	'replylastused' => 'Last Used',


	/**
	 * ---------------------------------------------
	 * SEARCH
	 * ---------------------------------------------
	 */
	'search' => 'Search',
	'tabsearch' => 'Advanced Search',
	'matchtype' => 'Search Criteria Options',
	'desc_matchtype' => 'Select the grouping method for the search criteria fields.',
	'smatchall' => 'Match All (AND)',
	'smatchany' => 'Match Any (OR)',
	'insertcriteria' => 'Insert Criteria',

	/**
	 * ---------------------------------------------
	 * NEW TICKET
	 * ---------------------------------------------
	 */
	'tabrecurrence' => 'Recurrence',
	'recurrence_none' => 'None',
	'recurrence_daily' => 'Daily',
	'recurrence_weekly' => 'Weekly',
	'recurrence_monthly' => 'Monthly',
	'recurrence_yearly' => 'Yearly',
	'rec_every' => 'Every',
	'rec_days' => 'day(s)',
	'rec_everyweekday' => 'Every weekday',
	'rec_weeks' => 'week(s) on',
	'rec_monday' => 'Monday',
	'rec_tuesday' => 'Tuesday',
	'rec_wednesday' => 'Wednesday',
	'rec_thursday' => 'Thursday',
	'rec_friday' => 'Friday',
	'rec_saturday' => 'Saturday',
	'rec_sunday' => 'Sunday',
	'rec_day' => 'Day',
	'rec_ofevery' => 'of every',
	'rec_months' => 'month(s)',
	'rec_the' => 'The',
	'rec_first' => 'First',
	'rec_second' => 'Second',
	'rec_third' => 'Third',
	'rec_fourth' => 'Fourth',
	'rec_fifth' => 'Fifth',
	'rec_of' => 'of',
	'recurnotactivated' => 'Recurrence not enabled',
	'recurrencerange' => 'Range of recurrence',
	'recur_starts' => 'Starts',
	'recur_ends' => 'Ends',
	'rec_noeenddate' => 'No end date',
	'rec_endafter' => 'End after:',
	'rec_endby' => 'End by:',
	'rec_occurrences' => 'occurrences',
);

?>
