<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titleduplicatesgroup' => 'Nombre de equipo duplicado',
	'msgduplicatesgroup' => SWIFT_PRODUCT . ' no puede insertar el equipo, ya que existe otro con el mismo nombre.',
	'depnotassigned' => '(No asignado)',
	'tabskills' => 'Habilidades',
	'noskillstodisplay' => 'No hay habilidades disponibles. Vaya a Chat &gt; Insertar habilidad para añadir habilidades.',
	'titleextinvalid' => 'Extensión no válida',
	'msgextinvalid' => 'Ha introducido una extensión no válida. Por favor, asegúrese de que la extensión especificada es numérica y de que no contiene ningún carácter especial.',
	'livechatoptions' => 'Configuración de Chat',
	'lcgreeting' => 'Saludo automático',
	'desc_lcgreeting' => 'Introduzca el saludo que recibirá automáticamente el usuario cuando un operador acepte un chat de un cliente.',
	'titleinvalidfileext' => 'Extensión de archivo de imagen no válida',
	'msginvalidfileext' => 'El archivo de imagen de perfil tiene una extensión no válida. Las extensiones permitidas son: gif, jpeg, jpg, png',
	'rrenabled' => 'RingRoute habilitado',
	'desc_rrenabled' => 'Especifique si la funcionalidad de RingRoute debería estar activada para este operador',
	'rrextension' => 'Extensión RingRoute',
	'desc_rrextension' => 'Introduzca el numero de extensión RingRoute para este operador.',
	'personalizeoptions' => 'Personalizar',
	'generaloptions' => 'Configuración general',
	'staffprofileimage' => 'Imagen de perfil',
	'desc_staffprofileimage' => 'Seleccione la imagen de perfil del operador. Esta imagen aparecerá bajo todos los mensajes de ticket y en la ventana de chat.',
	'ringrouteoptions' => 'Configuración de RingRoute',
	'tabprofile' => 'Perfil',
	'stafffirstname' => 'Nombre',
	'desc_stafffirstname' => '',
	'stafflastname' => 'Apellidos',
	'desc_stafflastname' => '',
	'staffdesignation' => 'Cargo',
	'desc_staffdesignation' => 'Introduzca el cargo del operador, esto será visible bajo las respuestas de ticket y en el chat. Por ejemplo: CEO, Jefe de soporte, Ejecutivo de cuentas',
	'titleemailqueuematch' => 'Conflicto de dirección de email',
	'msgemailqueuematch' => 'La dirección de email "%s" ya se está usando como dirección de cola de email.',
	'titlemobilenumberinvalid' => 'Número de teléfono móvil no válido',
	'msgmobilenumberinvalid' => 'El número de móvil introducido no es válido. Por favor, introduzca únicamente números, sin el prefijo + ni separadores o guiones.',
	'copyfrom' => 'Permisos de copia',
	'titleinsertstaff' => 'Insertado operador "%s" (%s)',
	'msginsertstaff' => 'Se ha insertado correctamente el operador "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Usuario:</b> %s<br /><b>Email:</b> %s<br /><b>Equipo:</b> %s<br /><b>Activado:</b> %s<br /><b>Móvil:</b> %s<br /><b>Usar departamentos de equipo?:</b> %s',
	'titleupdatestaff' => 'Actualizado operador "%s" (%s)',
	'msgupdatestaff' => 'Se ha actualizado correctamente el operador "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Usuario:</b> %s<br /><b>Email:</b> %s<br /><b>Equipo:</b> %s<br /><b>Activado:</b> %s<br /><b>Teléfono móvil:</b> %s<br /><b>Usar departamentos de equipo?:</b> %s',
	'titlepwnomatch' => 'Contraseña no válida',
	'msgpwnomatch' => 'La contraseña especificada para el operador no coincide.',
	'titlenodep' => 'Sin departamentos asignados',
	'msgnodep' => 'Por favor, seleccione los departamentos a los que desea asignar a este operador en la pestaña Departamentos.',
	'titleusernameexists' => 'El usuario ya existe',
	'msgusernameexists' => 'El nombre de usuario "%s" ya está asignado al operador "%s". Por favor, introduzca un nombre de usuario diferente para continuar.',
	'titlegrouperror' => 'Error de equipo. Imposible continuar.',
	'msggrouperror' => 'No puede cambiar el equipo a un equipo no administrador, ya que este operador es el único que tiene privilegios de administración.',
	'titlestaffdelsame' => 'Imposible eliminar',
	'msgstaffdelsame' => 'No se puede eliminar el operador con el que se ha iniciado la sesión. Por favor, inicie sesión con diferentes credenciales para eliminar al usuario "%s".',
	'titledelstaffmul' => 'Eliminado(s) "%d" operador(es)',
	'msgdelstaffmul' => 'Se han eliminado correctamente los siguientes operadores de la base de datos:<br />%s',
	'titledelstaff' => 'Eliminado el operador "%s" (%s)',
	'msgdelstaff' => 'Se ha eliminado el operador "%s" (%s) de la base de datos.',
	'titleinsertstaffgroup' => 'Insertado equipo "%s"',
	'msginsertstaffgroup' => 'Se ha insertado correctamente el equipo "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Es admin:</b> %s<br /><b>Asignado a departamentos:</b> %s',
	'titleupdatestaffgroup' => 'Actualizado equipo "%s"',
	'msgupdatestaffgroup' => 'Se ha actualizado correctamente el equipo "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Es admin:</b> %s<br /><b>Asignado a departamentos:</b> %s',
	'titlestaffgroupdelsame' => 'Imposible eliminar',
	'msgstaffgroupdelsame' => 'No se puede eliminar el equipo seleccionado ya que está asignado al usuario con el que ha iniciado sesión. Por favor, inicie sesión con un operador diferente para eliminar el equipo "%s".',
	'titledelstaffteammul' => 'Eliminado(s) "%d" equipo(s)',
	'msgdelstaffteammul' => 'Se han eliminado correctamente los siguientes equipos:<br />%s',
	'titledelstaffteam' => 'Eliminado equipo "%s"',
	'msgdelstaffteam' => 'Se ha eliminado correctamente el equipo "%s" (%s) de la base de datos.',
	'loginshare' => 'LoginShare',
	'tabsettings' => 'Configuración',
	'tabplugins' => 'Plugins',
	'ls_module' => 'Plugins LoginShare',
	'wineditls' => 'Editar configuración LoginShare: %s',
	'lsnotitle' => 'No hay configuración disponible',
	'lsnomsg' => 'No hay configuración disponible para el plugin LoginShare <b>"%s"</b>.',
	'tabmassmail' => 'Email masivo',
	'tabfilter' => 'Filtrar',
	'filterbyteams' => 'Filtrar por equipos',
	'filterbystaff' => 'Filtrar por operadores',
	'send' => 'Enviar',
	'isenabled' => 'Está activado?',
	'desc_isenabled' => 'Cambia el estado del operador. Los operadores desactivados no pueden iniciar sesión en el panel de control de operadores ni realizar ninguna otra acción.',
	'assigneddepartments' => 'Departamentos asignados',
	'titlenoenable' => 'No se puede desactivar a "%s"',
	'msgnoenable' => 'No puede desactivar el usuario con el que ha iniciado la sesión "%s". Por favor, inicie la sesión usando credenciales diferentes para poder desactivar al usuario.',
	'titledisablestaff' => 'Desactivados "%d" operadores',
	'msgdisablestaff' => 'Se ha desactivado correctamente a los siguientes operadores:<br />%s',
	'titleenablestaff' => 'Activados "%d" operadores',
	'msgenablestaff' => 'Se ha activado correctamente a los siguientes operadores:<br />%s',
	'titleupdatedsettings' => 'Actualizada configuración para "%s"',
	'msgupdatedsettings' => 'Se ha actualizado correctamente la configuración de la categoría "%s" bajo "%s"',
	'titleselectonerecord' => 'no se ha seleccionado operador/equipo',
	'msgselectonerecord' => 'Es necesario seleccionar al menos un operador o equipo para enviar un email masivo.',
	'titlemassmailsent' => 'Enviado mail a "%d" operadores',
	'msgmassmailsent' => 'Se ha enviado email masivo a los siguientes operadores:',
	'attachments' => 'Adjuntos',
	'tabimport' => 'Importar',
	'loginsharefile' => 'Archivo XML LoginShare',
	'desc_loginsharefile' => 'Seleccione el archivo XML LoginShare',
	'ignoreversion' => 'Ignorar versión',
	'desc_ignoreversion' => 'Si se selecciona, se ignorará la versión del archivo de importación. Se recomienda que no se active esta opción ya que puede provocar problemas en el centro de soporte de usuarios.',
	'import' => 'Importar',
	'titlenoelevatedls' => 'Imposible importar el XML LoginShare de operadores',
	'msgnoelevatedls' => SWIFT_PRODUCT.' no ha podido importar el archivo XML LoginShare de operadores LoginShare porque para ello es necesario iniciar sesión con una cuenta de operador con privilegios especiales. Puede añadir su usuario a la lista de usuarios con privilegios especiales en el archivo config/config.php.',
	'titlelsversioncheckfail' => 'Comprobación de versión errónea',
	'msglsversioncheckfail' => SWIFT_PRODUCT. ' no ha podido importar el plugin LoginShare de operadores porque ha sido creado para una versión anterior de  '.SWIFT_PRODUCT,
	'titlelsinvaliduniqueid' => 'Error de ID única duplicada',
	'msglsinvaliduniqueid' => SWIFT_PRODUCT .' no ha podido importar el Plugin LoginShare de operadores debido a un conflicto de ID única. Esto habitualmente quiere decir que el plugin ya ha sido importado a la base de datos.',
	'titlelsinvalidxml' => 'Archivo XMl no válido',
	'msglsinvalidxml' => SWIFT_PRODUCT .' no ha podido importar el plugin LoginShare de operadores porque el archivo XML está corrupto o contiene datos no válidos.',
	'titlelsimported' => 'Importado plugin LoginShare de operadores',
	'msglsimported' => SWIFT_PRODUCT .' ha importado correctamente el plugin LoginShare de operadores "%s" .',
	'titlelsdeleted' => 'Eliminado Plugin LoginShare de operadores',
	'msglsdeleted' => 'El Plugin LoginShare de operadores "%s" ha sido eliminado de la base de datos.',
	'invalidloginshareplugin' => 'Plugin LoginShare no válido, asegúrese de que el plugin existe en la base de datos.',
	'titleupdatedls' => 'Actualizada configuración LoginShare de operadores',
	'msgupdatedls' => 'Se ha actualizado correctamente la configuración para el Plugin LoginShare de operadores "%s"',
	'tabpermissionsstaff' => 'Permisos: Operadores',
	'tabpermissionsadmin' => 'Permisos: Admin',
	'iprestriction' => 'Restringir a IP',
	'desc_iprestriction' => 'Puede restringir los lugares de inicio de sesión para este operador a direcciones IP o subredes seleccionadas. Separe valores múltiples mediante una coma \',\'. Ejemplos de uso:<BR /><i> * <b>202.1.192.0-202.1.192.255</b>: un rango de IPs<BR /> * <b>200.36.161.0/24</b>: Un rango de IPs usando enmascaramiento<BR /> * <b>200.36.161/24</b>: Una sintaxis abreviada similar a la anterior.</i>',
	'tzusedefault' => '-- Usar la zona por defecto --',
	'stafftimezone' => 'Zona horaria',
	'desc_stafftimezone' => 'Seleccione la zona horaria apropiada para el operador. Si selecciona una zona horaria aquí, anulará la zona horaria por defecto para el operador.',
	'staffenabledst' => 'Activar Horario de Verano',
	'desc_staffenabledst' => 'Seleccione si desea activar el Horario de Verano.',
	// ======= END v4 LOCALES =======
	'staff' => 'Operadores',
	'desc_staff' => '',
	'managestaff' => 'Administrar operadores',

	// Staff List
	'stafflist' => 'Lista de operadores',
	'fullname' => 'Nombre',
	'staffgroup' => 'Equipo',
	'staffdeletefailedsame' => 'No es posible eliminar su propia cuenta de operador. Por favor, inicie la sesión con diferentes credenciales para eliminar "%s"',
	'staffdeleteconfirm' => 'Operador "%s" eliminado correctamente',
	'wineditstaff' => 'Editar operador',
	'tabedit' => 'Editar',
	'tabinsert' => 'Insertar',
	'tabdepartments' => 'Departamentos asignados',
	'taboptions' => 'Opciones',
	'permissions' => 'Permisos',
	'wineditteam' => 'Editar equipo',

	// Staff Group
	'staffgroups' => 'Equipos',
	'managegroups' => 'Administrar equipos',
	'isadmin' => 'Es administrador?',
	'sgroupdeletefailedsame' => 'No puede eliminar el equipo al que pertenece su cuenta de operador. Por favor, inicie la sesión con diferentes credenciales para eliminar "%s"',
	'sgroupdeleteconfirm' => 'Equipo "%s" eliminado correctamente',
	'sgroupactionconfirm' => 'IMPORTANTE: Eliminar un equipo borrará permanentemente todas las cuentas de operador asociadas al equipo! Está seguro de que desea eliminarlo?',

	// Insert Staff
	'insertstaff' => 'Insertar operador',
	'staffdetails' => 'Detalles de operador',
	'stafffullname' => 'Nombre',
	'desc_stafffullname' => 'El nombre completo del operador (p.ej.  <i>Pepe Debian</i>).',
	'staffusername' => 'Nombre de usuario',
	'desc_staffusername' => 'Un nombre de usuario para el operador. Es el que se usará al iniciar sesión en el panel de control de operadores.',
	'staffpassword' => 'Contraseña',
	'desc_staffpassword' => 'Una contraseña para la cuenta del operador.',
	'staffpasswordconfirm' => 'Confirme contraseña',
	'desc_staffpasswordconfirm' => 'Vuelva a introducir la contraseña para confirmarla.',
	'staffemail' => 'Email',
	'desc_staffemail' => 'La dirección de email del operador. Todas las alertas para el operador se enviarán a esta dirección.',
	'staffgroup' => 'Equipo',
	'desc_staffgroup' => 'Especifique el equipo al que se asignará este operador. El operador heredará todos los permisos del equipo.',
	'optionalfields' => 'Campos opcionales',
	'staffmobilenumber' => 'Teléfono móvil',
	'desc_staffmobilenumber' => 'Si este operador va a recibir alertas por SMS, introduzca su número de móvil. Nota: introduzca únicamente el número de teléfono sin espacios, guiones ni otros símbolos.<br/>p.ej: <i>\'600213456\'</i> ',
	'staffsignature' => 'Firma',
	'desc_staffsignature' => 'Introduzca la firma del operador. La firma se añadirá a todos los emails salientes enviados por este operador.',
	'staffassigneddep' => 'Departamentos asignados',
	'usegroupdep' => 'Usar departamentos del equipo',
	'desc_usegroupdep' => 'Si está activado, los permisos de departamento del equipo seleccionado serán heredados por este operador.',
	'assigneddep' => 'Departamentos asignados',
	'desc_assigneddep' => 'Especifique permisos individuales de departamentos si la opción de usar departamentos del equipo (arriba) no está activada.',
	'passworddontmatch' => 'Las contraseñas introducidas no coinciden',
	'usernameexists' => 'El nombre de usuario del operador ya existe',
	'selectdepartment' => 'Debe asignar al operador al menos un departamento',
	'redirect_staffinsert' => 'Operador insertado correctamente',
	'staffinsertconfirm' => 'Operador "%s" insertado correctamente',

	// Edit Staff
	'updatestaff' => 'Actualizar operador',
	'editstaff' => 'Editar operador',
	'invalidstaff' => 'ERROR: ID de operador no válido',
	'desc_staffpasswordedit' => 'Si desea cambiar la contraseña, introduzca una nueva aquí.',

	// Insert Staff Group
	'insertstaffgroup' => 'Insertar equipo',
	'staffgroupdetails' => 'Detalles de equipo',
	'generalfields' => 'Campos generales',
	'grouptitle' => 'Nombre',
	'desc_grouptitle' => 'Introduzca un nombre para el equipo.',
	'groupisadmin' => 'Administrador',
	'desc_groupisadmin' => 'Si está activado, este equipo será un equipo administrador, y tendra acceso a <b>ESTE</b> panel de control y por tanto sus integrantes podrán hacer cambios en la configuración general.',
	'groupassigneddep' => 'Departamentos asignados',
	'desc_groupassigneddep' => 'Seleccione los departamentos a los que los usuarios de este equipo estarán asignados.',
	'redirect_staffgroupinsert' => 'Equipo insertado correctamente',
	'staffgroupinsertconfirm' => 'Equipo "%s" insertado correctamente',

	// Edit Staff
	'staffupdateconfirm' => 'Operador "%s" actualizado correctamente',
	'grouperror' => 'No puede cambiar el tipo de equipo a "no administrador" porque es el último equipo que queda con privilegios de administración',

	// Edit Staff Group
	'editstaffgroup' => 'Editar equipo',
	'invalidstaffgroup' => 'Equipo no válido',
	'staffgroupupdateconfirm' => 'Grupo "%s" actualizado correctamente',
	'groupadminerror' => 'No puede deshabilitar los privilegios de administración de este equipo porque es el último que queda con privilegios de administración',

	// Mass Mail
	'massmail' => 'Email masivo',
	'subject' => 'Asunto',
	'desc_subject' => '',
	'send' => 'Enviar',
	'mailcontents' => 'Contenido del correo',
	'mailstaffgroup' => 'Equipo',
	'desc_mailstaffgroup' => '',
	'selectonegroup' => 'ERROR: Por favor, seleccione el menos un equipo',
	'sentmailconfirm' => 'Enviado email a %s operadores',
	'mmcontents' => 'Contenido del correo',

	// License
	'titlestafflicense' => 'Límite de licencia excedido',
	'msgstafflicense' => SWIFT_PRODUCT . ' no puede insertar un nuevo operador porque ha alcanzado el límite permitido por su licencia. Por favor, contacte con el soporte de Kayako en <a href="https://my.kayako.com" target="_blank">https://my.kayako.com</a>.',

);

?>