<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	/*
	 * ###############################################
	 * BEGIN V4 LOCALES
	 * ###############################################
	 */
	'tf_staff.staffid' => 'ID de operador',
	'tf_staff.fullname' => 'Nombre operador',
	'tf_staff.designation' => 'Cargo operador',
	'tf_staff.staffgroupid' => 'ID de equipo',
	'tf_staff.email' => 'Email operador',
	'tf_staff.lastactivity' => 'Última actividad operador',
	'tf_staff.isenabled' => 'Operador activo',
	'tf_staff.passwordupdatetimeline' => 'Actualización de contraseña de operador',
	'tf_staff.timezonephp' => 'Zona horaria de operador',
	'tf_staffgroup.staffgroupid' => 'ID de equipo',
	'tf_staffgroup.title' => 'Nombre de equipo',
	'tf_staffgroup.isadmin' => 'El equipo es admin',
	'tf_departments.slascheduleid' => 'ID de programación SLA departamento',
	'tf_departments.departmenttype' => 'Tipo departamento',
	'tf_departments.parentdepartmentid' => 'ID Departamento superior',
	'tf_departments.departmentmodule' => 'Módulo de departamento',

	'tf_departments.title' => 'Nombre departamento',
	'tf_users.userid' => 'ID usuario',
	'tf_users.usergroupid' => 'ID grupo usuarios',
	'tf_users.userorganizationid' => 'ID organización usuario',
	'tf_users.userrole' => 'Rol usuario',
	'tf_users.userdesignation' => 'Título usuario',
	'tf_users.fullname' => 'Nombre usuario',
	'tf_users.isenabled' => 'Usuario activado',
	'tf_users.languageid' => 'ID idioma usuario',
	'tf_users.useremailcount' => 'Emails usuario',
	'tf_users.slaplanid' => 'ID Plan SLA usuario',
	'tf_users.isvalidated' => 'Usuario validado',
	'tf_userorganizations.userorganizationid' => 'ID organización',
	'tf_userorganizations.organizationname' => 'Nombre de la organización',
	'tf_userorganizations.address' => 'Dirección de la organización',
	'tf_userorganizations.state' => 'Región de la organización',
	'tf_userorganizations.postalcode' => 'Código postal de la organización',
	'tf_userorganizations.country' => 'País de la organización',
	'tf_userorganizations.phone' => 'Teléfono de la organización',
	'tf_userorganizations.fax' => 'Fax de la organización',
	'tf_userorganizations.website' => 'Sitio web de la organizacion',
	'tf_userorganizations.organizationtype' => 'Tipo de organización',
	'tf_userorganizations.languageid' => 'ID de idioma de organización',
	'tf_userorganizations.slaplanid' => 'ID del Plan SLA de la organización',
	'tf_userorganizations.usergroupid' => 'ID del grupo de usuarios de la organización',
	'tf_usergroups.usergroupid' => 'ID grupo de usuarios',
	'tf_usergroups.title' => 'Nombre grupo de usuarios',
	'tf_usergroups.ismaster' => 'El grupo de usuarios es maestro',
	'tf_useremails.email' => 'Email usuario',
	'tf_tickets.ticketid' => 'ID de ticket',
	'tf_tickets.ticketmaskid' => 'ID de máscara de ticket',
	'tf_tickets.ownerstaffid' => 'ID de operador responsable',
	'tf_tickets.ticketstatusid' => 'ID de estado del ticket',
	'tf_tickets.priorityid' => 'ID de prioridad del ticket',
	'tf_tickets.emailqueueid' => 'ID de cola de email del ticket',
	'tf_tickets.fullname' => 'ID de creador del ticket',
	'tf_tickets.email' => 'Email de creador del ticket',
	'tf_tickets.lastreplier' => 'Última persona que respondió al ticket',
	'tf_tickets.replyto' => 'Respuesta para',
	'tf_tickets.subject' => 'Asunto del Ticket',
	'tf_tickets.dateline' => 'Sello de tiempo del Ticket',
	'tf_tickets.lastactivity' => 'Última actividad del ticket',
	'tf_tickets.laststaffreplytime' => 'Hora de última respuesta de operador',
	'tf_tickets.lastuserreplytime' => 'Hora de última respuesta de usuario',
	'tf_tickets.slaplanid' => 'ID de Plan SLA de ticket',
	'tf_tickets.ticketslaplanid' => 'ID de Plan SLA de ticket',
	'tf_tickets.duetime' => 'Hora de vencimiento',
	'tf_tickets.totalreplies' => 'Respuestas totales',
	'tf_tickets.ipaddress' => 'Dirección IP',
	'tf_tickets.timeworked' => 'Tiempo invertido',
	'tf_tickets.escalationruleid' => 'ID de regla de priorización',
	'tf_tickets.autoclosetimeline' => 'Hora de autocierre del ticket',
	'tf_tickets.escalatedtime' => 'Hora de priorización',
	'tf_tickets.followupcount' => 'Contador de seguimiento del ticket',
	'tf_tickets.isfirstcontactresolved' => 'El ticket es el primer contacto resuelto',
	'tf_tickets.averageresponsetime' => 'Tiempo de respuesta promedio de ticket',
	'tf_tickets.escalationlevelcount' => 'Contador de priorización de ticket',
	'tf_tickets.resolutiondateline' => 'Hora de resolución de ticket',
	'tf_tickets.wasreopened' => 'El ticket fue reabierto',
	'tf_tickets.reopenedateline' => 'Hora en que fue reabierto',
	'tf_tickets.resolutionseconds' => 'Segundos de resolución del ticket',
	'tf_tickets.resolutionduedateline' => 'Hora de vencimiento de la resolución del ticket',
	'tf_tickets.isresolved' => 'El ticket está resuelto',
	'tf_tickets.resolutionlevel' => 'Novel de resolución del ticket',
	'tf_tickets.departmentid' => 'ID de departamento',
	'tf_tickets.userid' => 'ID de usuario',
	'tf_ticketstatus.ticketstatusid' => 'ID de estado de ticket',
	'tf_ticketstatus.title' => 'Nombre de estado de ticket',
	'tf_ticketstatus.markasresolved' => 'Estado del ticket resuelto',
	'tf_ticketstatus.departmentid' => 'ID departamento estado del ticket',
	'tf_ticketstatus.type' => 'Tipo de estado de ticket',
	'tf_ticketpriorities.priorityid' => 'ID de prioridad',
	'tf_ticketpriorities.title' => 'Nombre de prioridad',
	'tf_chathits.chathitid' => 'Id impacto de chat',
	'tf_chathits.staffid' => 'ID operador impacto chat',
	'tf_chathits.fullname' => 'Nombre impacto chat',
	'tf_chathits.email' => 'Email impacto chat',
	'tf_chathits.isaccepted' => 'Impacto chat aceptado',
	'tf_chathits.dateline' => 'Hora de impacto chat',
	'tf_chatskills.chatskillid' => 'ID especialidad chat',
	'tf_chatskills.title' => 'Nombre especialidad chat',
	'tf_chatskilllinks.chatskilllinkid' => 'ID enlace especialidad chat',
	'tf_chatskilllinks.chatskillid' => 'ID especialidad de enlace de especialidad de chat',
	'tf_chatskilllinks.staffid' => 'ID operador de enlace de especialidad de chat',
	'tf_slaplans.isenabled' => 'Plan SLA activado',
	'tf_slaplans.overduehours' => 'Horas vencido el Plan SLA',
	'tf_slaplans.resolutionhours' => 'Horas resolución Plan SLA',
	'tf_slaplans.resolutionduehours' => 'Horas vencida la resolucion Plan SLA',
	'tf_slaplans.title' => 'Nombre Plan SLA',
	'tf_benchmarkresults.benchmarkresult' => 'Valoración',
	'tf_benchmarkresults.staffid' => 'ID operador resultado valoración',
	'tf_ticketposts.ticketpostid' => 'Is mensaje de ticket',
	'tf_tickettimetracks.creatorstaffname' => 'Nombre operador creador',
	'tf_tickettimetracks.timespent' => 'Tiempo invertido',
	'tf_tickettimetracks.timebillable' => 'Tiempo facturable',
	'tf_tickettimetracks.workerstaffname' => 'Nombre de trabajador',
	'tf_tickettimetracks.dateline' => 'Fecha de entrada de facturación',
	
	'tab_staff' => 'Operador',
	'tab_staffgroup' => 'Equipo de operador',
	'tab_departments' => 'Departamentos',
	'tab_users' => 'Usuarios',
	'tab_userorganizations' => 'Organizaciones de usuario',
	'tab_usergroups' => 'Grupos de usuarios',
	'tab_tickets' => 'Tickets',
	'tab_ticketstatus' => 'Estado de ticket',
	'tab_ticketpriorities' => 'Prioridades de ticket',
	'tab_chathits' => 'Impactos de char',
	'tab_chatskills' => 'especialidades de chat',
	'tab_chatskilllinks' => 'Enlaces de especialidad de chat',
	'tab_ticketposts' => 'Mensajes de ticket',
	'tab_slaplans' => 'Planes SLA',
	'tab_useremails' => 'Emails de usuario',
	'tab_tickettimetracks' => 'Facturación',
);

?>