<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titleduplicatesgroup' => 'Nombre de equipo duplicado',
	'msgduplicatesgroup' => SWIFT_PRODUCT . ' no puede insertar el equipo, ya que existe otro con el mismo nombre.',
	'depnotassigned' => '(No asignado)',
	'tabskills' => 'Habilidades',
	'noskillstodisplay' => 'No hay habilidades disponibles. Vaya a Chat &gt; Insertar habilidad para añadir habilidades.',
	'titleextinvalid' => 'Extensión no válida',
	'msgextinvalid' => 'Ha introducido una extensión no válida. Por favor, asegúrese de que la extensión especificada es numérica y de que no contiene ningún carácter especial.',
	'livechatoptions' => 'Configuración de Chat',
	'lcgreeting' => 'Saludo automático',
	'desc_lcgreeting' => 'Introduzca el saludo que recibirá automáticamente el usuario cuando un operador acepte un chat de un cliente.',
	'titleinvalidfileext' => 'Extensión de archivo de imagen no válida',
	'msginvalidfileext' => 'El archivo de imagen de perfil tiene una extensión no válida. Las extensiones permitidas son: gif, jpeg, jpg, png',
	'rrenabled' => 'RingRoute habilitado',
	'desc_rrenabled' => 'Especifique si la funcionalidad de RingRoute debería estar activada para este operador',
	'rrextension' => 'Extensión RingRoute',
	'desc_rrextension' => 'Introduzca el numero de extensión RingRoute para este operador.',
	'personalizeoptions' => 'Personalizar',
	'generaloptions' => 'Configuración general',
	'staffprofileimage' => 'Imagen de perfil',
	'desc_staffprofileimage' => 'Seleccione la imagen de perfil del operador. Esta imagen aparecerá bajo todos los mensajes de ticket y en la ventana de chat.',
	'ringrouteoptions' => 'Configuración de RingRoute',
	'tabprofile' => 'Perfil',
	'stafffirstname' => 'Nombre',
	'desc_stafffirstname' => '',
	'stafflastname' => 'Apellidos',
	'desc_stafflastname' => '',
	'staffdesignation' => 'Cargo',
	'desc_staffdesignation' => 'Introduzca el cargo del operador, esto será visible bajo las respuestas de ticket y en el chat. Por ejemplo: CEO, Jefe de soporte, Ejecutivo de cuentas',
	'titleemailqueuematch' => 'Conflicto de dirección de email',
	'msgemailqueuematch' => 'La dirección de email "%s" ya se está usando como dirección de cola de email.',
	'titlemobilenumberinvalid' => 'Número de teléfono móvil no válido',
	'msgmobilenumberinvalid' => 'El número de móvil introducido no es válido. Por favor, introduzca únicamente números, sin el prefijo + ni separadores o guiones.',
	'copyfrom' => 'Permisos de copia',
	'titleinsertstaff' => 'Insertado operador "%s" (%s)',
	'msginsertstaff' => 'Se ha insertado correctamente el operador "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Usuario:</b> %s<br /><b>Email:</b> %s<br /><b>Equipo:</b> %s<br /><b>Activado:</b> %s<br /><b>Móvil:</b> %s<br /><b>Usar departamentos de equipo?:</b> %s',
	'titleupdatestaff' => 'Actualizado operador "%s" (%s)',
	'msgupdatestaff' => 'Se ha actualizado correctamente el operador "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Usuario:</b> %s<br /><b>Email:</b> %s<br /><b>Equipo:</b> %s<br /><b>Activado:</b> %s<br /><b>Teléfono móvil:</b> %s<br /><b>Usar departamentos de equipo?:</b> %s',
	'titlepwnomatch' => 'Contraseña no válida',
	'msgpwnomatch' => 'La contraseña especificada para el operador no coincide.',
	'titlenodep' => 'Sin departamentos asignados',
	'msgnodep' => 'Por favor, seleccione los departamentos a los que desea asignar a este operador en la pestaña Departamentos.',
	'titleusernameexists' => 'El usuario ya existe',
	'msgusernameexists' => 'El nombre de usuario "%s" ya está asignado al operador "%s". Por favor, introduzca un nombre de usuario diferente para continuar.',
	'titlegrouperror' => 'Error de equipo. Imposible continuar.',
	'msggrouperror' => 'No puede cambiar el equipo a un equipo no administrador, ya que este operador es el único que tiene privilegios de administración.',
	'titlestaffdelsame' => 'Imposible eliminar',
	'msgstaffdelsame' => 'No se puede eliminar el operador con el que se ha iniciado la sesión. Por favor, inicie sesión con diferentes credenciales para eliminar al usuario "%s".',
	'titledelstaffmul' => 'Eliminado(s) "%d" operador(es)',
	'msgdelstaffmul' => 'Se han eliminado correctamente los siguientes operadores de la base de datos:<br />%s',
	'titledelstaff' => 'Eliminado el operador "%s" (%s)',
	'msgdelstaff' => 'Se ha eliminado el operador "%s" (%s) de la base de datos.',
	'titleinsertstaffgroup' => 'Insertado equipo "%s"',
	'msginsertstaffgroup' => 'Se ha insertado correctamente el equipo "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Es admin:</b> %s<br /><b>Asignado a departamentos:</b> %s',
	'titleupdatestaffgroup' => 'Actualizado equipo "%s"',
	'msgupdatestaffgroup' => 'Se ha actualizado correctamente el equipo "<b>%s</b>"<br /><b>Nombre:</b> %s<br /><b>Es admin:</b> %s<br /><b>Asignado a departamentos:</b> %s',
	'titlestaffgroupdelsame' => 'Imposible eliminar',
	'msgstaffgroupdelsame' => 'No se puede eliminar el equipo seleccionado ya que está asignado al usuario con el que ha iniciado sesión. Por favor, inicie sesión con un operador diferente para eliminar el equipo "%s".',
	'titledelstaffteammul' => 'Eliminado(s) "%d" equipo(s)',
	'msgdelstaffteammul' => 'Se han eliminado correctamente los siguientes equipos:<br />%s',
	'titledelstaffteam' => 'Eliminado equipo "%s"',
	'msgdelstaffteam' => 'Se ha eliminado correctamente el equipo "%s" (%s) de la base de datos.',
	'loginshare' => 'LoginShare',
	'tabsettings' => 'Configuración',
	'tabplugins' => 'Plugins',
	'ls_module' => 'Plugins LoginShare',
	'wineditls' => 'Editar configuración LoginShare: %s',
	'lsnotitle' => 'No hay configuración disponible',
	'lsnomsg' => 'No hay configuración disponible para el plugin LoginShare <b>"%s"</b>.',
	'tabmassmail' => 'Email masivo',
	'tabfilter' => 'Filtrar',
	'filterbyteams' => 'Filtrar por equipos',
	'filterbystaff' => 'Filtrar por operadores',
	'send' => 'Enviar',
	'isenabled' => 'Está activado?',
	'desc_isenabled' => 'Cambia el estado del operador. Los operadores desactivados no pueden iniciar sesión en el panel de control de operadores ni realizar ninguna otra acción.',
	'assigneddepartments' => 'Departamentos asignados',
	'titlenoenable' => 'No se puede desactivar a "%s"',
	'msgnoenable' => 'No puede desactivar el usuario con el que ha iniciado la sesión "%s". Por favor, inicie la sesión usando credenciales diferentes para poder desactivar al usuario.',
	'titledisablestaff' => 'Desactivados "%d" operadores',
	'msgdisablestaff' => 'Se ha desactivado correctamente a los siguientes operadores:<br />%s',
	'titleenablestaff' => 'Activados "%d" operadores',
	'msgenablestaff' => 'Se ha activado correctamente a los siguientes operadores:<br />%s',
	'titleupdatedsettings' => 'Actualizada configuración para "%s"',
	'msgupdatedsettings' => 'Se ha actualizado correctamente la configuración de la categoría "%s" bajo "%s"',
	'titleselectonerecord' => 'no se ha seleccionado operador/equipo',
	'msgselectonerecord' => 'Es necesario seleccionar al menos un operador o equipo para enviar un email masivo.',
	'titlemassmailsent' => 'Enviado mail a "%d" operadores',
	'msgmassmailsent' => 'Se ha enviado email masivo a los siguientes operadores:',
	'attachments' => 'Adjuntos',
	'tabimport' => 'Importar',
	'loginsharefile' => 'Archivo XML LoginShare',
	'desc_loginsharefile' => 'Seleccione el archivo XML LoginShare',
	'ignoreversion' => 'Ignorar versión',
	'desc_ignoreversion' => 'Si se selecciona, se ignorará la versión del archivo de importación. Se recomienda que no se active esta opción ya que puede provocar problemas en el centro de soporte de usuarios.',
	'import' => 'Importar',
	'titlenoelevatedls' => 'Imposible importar el XML LoginShare de operadores',
	'msgnoelevatedls' => SWIFT_PRODUCT.' no ha podido importar el archivo XML LoginShare de operadores LoginShare porque para ello es necesario iniciar sesión con una cuenta de operador con privilegios especiales. Puede añadir su usuario a la lista de usuarios con privilegios especiales en el archivo config/config.php.',
	'titlelsversioncheckfail' => 'Comprobación de versión errónea',
	'msglsversioncheckfail' => SWIFT_PRODUCT. ' no ha podido importar el plugin LoginShare de operadores porque ha sido creado para una versión anterior de  '.SWIFT_PRODUCT,
	'titlelsinvaliduniqueid' => 'Error de ID única duplicada',
	'msglsinvaliduniqueid' => SWIFT_PRODUCT .' no ha podido importar el Plugin LoginShare de operadores debido a un conflicto de ID única. Esto habitualmente quiere decir que el plugin ya ha sido importado a la base de datos.',
	'titlelsinvalidxml' => 'Invalid XML File',
	'msglsinvalidxml' => SWIFT_PRODUCT .' is unable to import the Staff LoginShare Plugin as the XML file corrupt or contains invalid data.',
	'titlelsimported' => 'Imported Staff LoginShare Plugin',
	'msglsimported' => SWIFT_PRODUCT .' has successfully imported the "%s" Staff LoginShare Plugin.',
	'titlelsdeleted' => 'Deleted Staff LoginShare Plugin',
	'msglsdeleted' => 'Successfully deleted the "%s" Staff LoginShare Plugin from the database.',
	'invalidloginshareplugin' => 'Invalid LoginShare Plugin, Please make sure the LoginShare plugin exists in the database.',
	'titleupdatedls' => 'Updated Staff LoginShare Settings',
	'msgupdatedls' => 'Successfully updated the settings for "%s" Staff LoginShare Plugin',
	'tabpermissionsstaff' => 'Permissions: Staff',
	'tabpermissionsadmin' => 'Permissions: Admin',
	'iprestriction' => 'Restrict to IP',
	'desc_iprestriction' => 'You may restrict login locations for this staff member to selected IP address(es) or subnet(s). Separate multiple values using a comma \',\'. Examples of usage:<BR /><i> * <b>202.1.192.0-202.1.192.255</b>: A range of IPs<BR /> * <b>200.36.161.0/24</b>: A range of IPs by using net masking<BR /> * <b>200.36.161/24</b>: A shortened syntax similar to the above.</i>',
	'tzusedefault' => '-- Use System Default --',
	'stafftimezone' => 'Time Zone',
	'desc_stafftimezone' => 'Select the appropriate time zone for the staff. If you choose a time zone here, it will override the default time zone for the staff.',
	'staffenabledst' => 'Enable Daylight Savings',
	'desc_staffenabledst' => 'Select whether or not you wish to enable Daylight Savings Time.',
	// ======= END v4 LOCALES =======
	'staff' => 'Staff',
	'desc_staff' => '',
	'managestaff' => 'Manage Staff',

	// Staff List
	'stafflist' => 'Staff List',
	'fullname' => 'Full Name',
	'staffgroup' => 'Team',
	'staffdeletefailedsame' => 'You cannot delete your own staff user account. Please log in using different staff user credentials in order to delete "%s"',
	'staffdeleteconfirm' => 'Staff user "%s" deleted successfully',
	'wineditstaff' => 'Edit Staff',
	'tabedit' => 'Edit',
	'tabinsert' => 'Insert',
	'tabdepartments' => 'Assigned Departments',
	'taboptions' => 'Options',
	'permissions' => 'Permissions',
	'wineditteam' => 'Edit Team',

	// Staff Group
	'staffgroups' => 'Teams',
	'managegroups' => 'Manage Teams',
	'isadmin' => 'Is Administrator?',
	'sgroupdeletefailedsame' => 'You cannot delete the team to which your staff user account belongs. Please log in using different staff user credentials in order to delete "%s"',
	'sgroupdeleteconfirm' => 'Team "%s" deleted successfully',
	'sgroupactionconfirm' => 'IMPORTANT: Deleting a team results in the deletion of all the staff user accounts under that team! Are you sure you wish to delete?',

	// Insert Staff
	'insertstaff' => 'Insert Staff',
	'staffdetails' => 'Staff Details',
	'stafffullname' => 'Full Name',
	'desc_stafffullname' => 'The full name of the staff user (e.g. <i>Joe Bloggs</i>).',
	'staffusername' => 'Username',
	'desc_staffusername' => 'A username for the staff user. This will be used to login to the control panel(s).',
	'staffpassword' => 'Password',
	'desc_staffpassword' => 'A password for the staff user account.',
	'staffpasswordconfirm' => 'Re-enter Password',
	'desc_staffpasswordconfirm' => 'For confirmation, re-enter the password.',
	'staffemail' => 'Email',
	'desc_staffemail' => 'The staff user\'s email address. All alerts sent to this user will be sent to this address.',
	'staffgroup' => 'Team',
	'desc_staffgroup' => 'Specify the team to which this staff user will be assigned. All permissions for the chosen team will be inherited.',
	'optionalfields' => 'Optional Fields',
	'staffmobilenumber' => 'Mobile Phone Number',
	'desc_staffmobilenumber' => 'If this staff user is to receive SMS alerts, enter their mobile phone number. Note: Enter only the telephone number without spaces, dashes or other symbols.<br/>Example: <i>\'18005551212\'</i> ',
	'staffsignature' => 'Signature',
	'desc_staffsignature' => 'Enter the staff user\'s signature. The signature will be appended to all outgoing email messages sent by this user.',
	'staffassigneddep' => 'Assigned Departments',
	'usegroupdep' => 'Use Team Departments',
	'desc_usegroupdep' => 'If enabled, the department permissions of the selected team will be inherited by this staff user.',
	'assigneddep' => 'Assigned Departments',
	'desc_assigneddep' => 'Specify individual department permissions if the team access option (above) is not enabled.',
	'passworddontmatch' => 'The passwords entered do not match',
	'usernameexists' => 'This staff username already exists',
	'selectdepartment' => 'You must assign the staff user to at least one department',
	'redirect_staffinsert' => 'Staff inserted successfully',
	'staffinsertconfirm' => 'Staff "%s" inserted successfully',

	// Edit Staff
	'updatestaff' => 'Update Staff',
	'editstaff' => 'Edit Staff',
	'invalidstaff' => 'ERROR: Invalid staff ID',
	'desc_staffpasswordedit' => 'If you wish to change the password, enter a new one here.',

	// Insert Staff Group
	'insertstaffgroup' => 'Insert Team',
	'staffgroupdetails' => 'Team Details',
	'generalfields' => 'General Fields',
	'grouptitle' => 'Title',
	'desc_grouptitle' => 'Enter a title for the team.',
	'groupisadmin' => 'Administrator',
	'desc_groupisadmin' => 'If enabled, this team will be an administrator team and will thus have access to <b>this</b> control panel and will be able to make system-wide setting changes.',
	'groupassigneddep' => 'Assigned Departments',
	'desc_groupassigneddep' => 'Select the department(s) to which the staff users under this team will be assigned.',
	'redirect_staffgroupinsert' => 'Team inserted successfully',
	'staffgroupinsertconfirm' => 'Team "%s" inserted successfully',

	// Edit Staff
	'staffupdateconfirm' => 'Staff Member "%s" updated successfully',
	'grouperror' => 'You cannot change the team to a non-administrator team as it is the only one remaining with administrator privileges',

	// Edit Staff Group
	'editstaffgroup' => 'Edit Team',
	'invalidstaffgroup' => 'Invalid team',
	'staffgroupupdateconfirm' => 'Group "%s" updated successfully',
	'groupadminerror' => 'You cannot disable administrator privileges for this team as it is the only one remaining with administrator privileges',

	// Mass Mail
	'massmail' => 'Mass Mail',
	'subject' => 'Subject',
	'desc_subject' => '',
	'send' => 'Send',
	'mailcontents' => 'Mail Contents',
	'mailstaffgroup' => 'Team',
	'desc_mailstaffgroup' => '',
	'selectonegroup' => 'ERROR: Please select at least one team',
	'sentmailconfirm' => 'Dispatched email to %s staff members',
	'mmcontents' => 'Mail Contents',

	// License
	'titlestafflicense' => 'License Limit Exceeded',
	'msgstafflicense' => SWIFT_PRODUCT . ' is unable to insert a new staff as you have reached the limit allowed by your license. Please contact Kayako Support at <a href="https://my.kayako.com" target="_blank">https://my.kayako.com</a> for further assistance.',

);

?>