<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array(
	'manage' => 'Administrar',

	'tabgeneral' => 'General',
	'tabmassaction' => 'Acción masiva',
	'tabreply' => 'Responder',
	'tabforward' => 'Reenviar',

	'manochange' => '-- Sin cambios --',
	'maticketstatus' => 'Estado de ticket',
	'maticketpriority' => 'Prioridad de ticket',
	'matickettype' => 'Tipo de ticket',
	'madepartment' => 'Departamento',
	'maowner' => 'Responsable',
	'maticketlink' => 'Enlazar',
	'maaddtags' => 'Añadir etiquetas',
	'maremovetags' => 'Eliminar etiquetas',
	'maticketflag' => 'Marca',
	'manoflag' => '-- Sin marca --',
	'mabayescategory' => 'Entrenar filtro bayesiano',
	'sactivestaff' => '-- Operador activo --',
	'tnavnextticket' => 'Siguiente ticket &raquo;',
	'tnavprevticket' => '&laquo; Ticket anterior',

	/**
	 * ---------------------------------------------
	 * Viewing a Ticket
	 * ---------------------------------------------
	 */
	'mergeoptions' => 'Opciones de fusion',
	'mergeparentticket' => 'Id de ticket principal',
	'desc_mergeparentticket' => 'si se especifica, el ticket actual se fusionará con el ticket especificado.',
	'titleeditmergefailed' => 'La fusión de los tickets ha fallado',
	'msgeditmergefailed' => SWIFT_PRODUCT . ' no ha podido fusionar los tickets porque el ticket principal no se ha podido localizar en la base de datos. Por favor, asegúrese de que el identificador (ID) que ha introducido es válido.',
	'titleeditmergesuccess' => 'Los tickets se han fusionado correctamente',
	'msgeditmergesuccess' => SWIFT_PRODUCT . ' ha fusionado correctamente el ticket.',
	'putback' => 'Retrasado',
	'tabcalls' => 'Llamadas',
	'dispatchasuser' => 'Como usuario',
	'viewticket' => 'Ver ticket',
	'viewticketext' => '[#%s]: %s',
	'proptitleticketid' => 'ID DE TICKET',
	'proptitledepartment' => 'DEPARTAMENTO',
	'proptitleowner' => 'RESPONSABLE',
	'proptitlestatus' => 'ESTADO',
	'proptitlepriority' => 'PRIORIDAD',
	'proptitletype' => 'TIPO',
	'tinforesolutiondue' => 'Vencimiento resolución: ',
	'tinfosla' => 'SLA: ',
	'tinfoticketid' => 'ID: ',
	'tinfodue' => 'Vencimiento: ',
	'tinfocreated' => 'Creado: ',
	'tinfoupdated' => 'Actualizado: ',
	'ticketlinkinfo' => 'Departamento: %s, Estado: %s',
	'tppostedon' => 'Publicado el %s',
	'tppostedonsurvey' => 'Comentario de encuesta publicado el %s',
	'tpemail' => 'Email: %s',
	'tpipaddress' => 'Dirección IP: %s',
	'participantbox' => 'Participantes',
	'badgethirdparty' => 'Tercero',
	'badgeuser' => 'Usuario',
	'badgestaff' => 'Operador',
	'badgecc' => 'CC',
	'badgebcc' => 'BCC',
	'wineditticketpost' => 'Editar mensaje ticket',
	'editpost' => 'Editar mensaje',
	'lastedited' => 'Editado por última vez por %s el %s',
	'wineditdue' => 'Editar vencimiento y línea de tiempo de vencimiento de resolución',
	'dialogduetimeline' => 'Vencimiento',
	'dialogresolutionduetimeline' => 'Vencimiento de resolución',
	'stopwatching' => 'Dejar de vigilar',
	'surrender' => 'Rendirse',
	'print' => 'Imprimir',
	'take' => 'Asignármelo a mí',
	'tabauditlog' => 'Log de auditoría',
	'aldescription' => 'Descripción',
	'aldate' => 'Fecha',
	'altimeline' => 'Línea de tiempo',
	'alentrytype' => 'Tipo de entrada',
	'alstaff' => ' (Operador)',
	'aluser' => ' (Usuario)',
	'alsystem' => ' (Sistema)',
	'alparser' => ' (Parser)',
	'editnote' => 'editar nota',
	'notetitle' => '%s el %s',
	'noteeditedtitle' => ' <i>(Editado por %s el %s)</i>',
	'ticketnotedelconfirm' => 'Está seguro  de que desea eliminar esta nota?',
	'tabaddnote' => 'Añadir nota',
	'tabeditnote' => 'Editar nota',
	'addnotes' => 'Notas',
	'notetype' => 'Tipo de nota',
	'addnote' => 'Añadir nota',
	'notes_ticket' => 'Ticket',
	'notes_user' => 'Usuario',
	'notes_userorganization' => 'Organización de usuario',
	'tabrelease' => 'Lanzamiento',
	'tabedit' => 'Editar',
	'tabhistory' => 'Historial',
	'tabchats' => 'Chats',
	'tabuser' => 'Usuarios',
	'notesvisibleall' => '-- Todos --',
	'notevisibleto' => 'Visibilidad',
	'desc_notevisibleto' => 'Puede usar esta opción para restringir la visibilidad de la nota a un operador concreto.',
	'edit_subject' => 'Asunto',
	'edit_fullname' => 'Nombre',
	'edit_email' => 'Email',
	'edit_overridesla' => 'Anular SLA',
	'desc_edit_overridesla' => 'Si está activado, este ticket seguirá usando el plan SLA seleccionado independientemente de las reglas de SLA existentes.',
	'editslausedef' => '-- Usar SLA por defecto --',
	'edittproperties' => 'Propiedades de ticket',
	'edittrecipients' => 'Destinatarios de ticket',
	'editrecipientsdesc' => 'Puede añadir un nuevo destinatario abajo introduciendo una dirección de email en el tipo de destinatario seleccionado. El destinatario seleccionado recibirá las respuestas de los operadores automáticamente, pero no tendrá acceso al ticket en el centro de soporte.<br /><br />Los destinatarios del ticket reciben todos los emails enviados por los operadores. La opción de añadir destinatarios al ticket está disponible cuando se envía un CC, BCC o se reenvía un ticket. Hay tres tipos de destinatario:<br><br><i>Tercero:</i> Un tercero al que se añade a un ticket recibe un CC de todas las respuestas enviadas por el operador. Además, un tercero puede enviar respuestas por email y éstas se añadirán al ticket, aunque el ticket no fuera creado por él.<br><br><i>Usuarios CC:</i> Un usuario CC que se añade a un ticket recibe una copia de todas las respuestas enviadas por un operador.<br><br><i>Usuarios BCC:</i> Un usuario BCC añadido a un ticket recibe una copia oculta de todas las respuestas enviadas por un operador.',
	'editthirdparty' => 'Tercero',
	'editcc' => 'CC',
	'editbcc' => 'BCC',
	'history_ticketid' => 'ID de ticket',
	'history_subject' => 'Asunto',
	'history_date' => 'Fecha',
	'history_department' => 'Departamento',
	'history_type' => 'Tipo',
	'history_status' => 'Estado',
	'history_priority' => 'Prioridad',
	'workflowbox' => 'Flujo de trabajo',
	'informationbox' => 'Información',
	'tinfobticketid' => 'ID DE TICKET',
	'tinfobuser' => 'USUARIO',
	'tinfobuserorganization' => 'ORGANIZACION',
	'tinfobusergroup' => 'GRUPO',
	'dispatchfrom' => 'De',
	'dispatchto' => 'Para',
	'dispatchcc' => 'CC',
	'dispatchbcc' => 'BCC',
	'dispatchcontents' => 'Contenido de la respuesta',
	'dispatchaddmacro' => 'Macro',
	'dispatchaddkb' => 'Biblioteca',
	'dispatchsendmail' => 'Enviar email',
	'dispatchwatch' => 'Vigilar',
	'dispatchaddfile' => 'Añadir archivo',
	'dispatchsend' => 'Enviar',
	'dispatchattachfile' => 'Adjuntar',
	'dispatchsaveasdraft' => 'Guardar como borrador',
	'dispatchto' => 'Para',
	'dispatchsubject' => 'Asunto',
	'dispatchsend' => 'Enviar',
	'dispatchsendar' => 'Enviar autorrespuesta',
	'dispatchuser' => 'Usuario',
	'dispatchnewuser' => 'Nuevo usuario',
	'dispatchisphone' => 'Ticket telefónico',
	'winuserquickinsert' => 'Nuevo usuario',
	'dispatch' => 'Despachar',
	'tabdispatch' => 'Despachar',
	'dispatchticket' => 'Despachar ticket',
	'assign' => 'Asignar',
	'newticket' => 'Nuevo ticket',
	'newticket_department' => 'Departamento',
	'desc_newticketdepartment' => 'Seleccione el departamento en el que desea crear el ticket.',
	'nt_sendmail' => 'Enviar email',
	'nt_asuser' => 'Como usuario/telefónico',
	'newticket_type' => 'Tipo',
	'desc_newticket_type' => 'Seleccione el tipo de ticket que desea crear.<br /><br /><i>Enviar email:</i> Envía un email a una dirección de email (funciona como un cliente de correo electrónico)<br /><i>Como usuario/telefónico:</i> Crear un ticket o registrar una llamada telefónica entrante en la cuenta de un usuario.',
	'nt_next' => 'Siguiente',
	'tabnewticket' => 'Nuevo ticket',
	'dispatchcreate' => 'Crear',
	'tabnewticket2' => 'Nuevo ticket: %s',
	'tpemailto' => 'Email enviado a: %s',
	'tpemailforwardedto' => 'Reenviado a: %s',
	'tlockinfo' => '%s está viendo el ticket (última actualización: %s)',
	'tpostlockinfo' => '%s está respondiendo al ticket (última actualización: %s)',
	'tabbilling' => 'Facturación',
	'tabfollowup' => 'Revisión',
	'notes' => 'Notas',
	'billworker' => 'Trabajador',
	'billdate' => 'Fecha de factura',
	'billworkdate' => 'Fecha de trabajo',
	'billtimespent' => 'Tiempo invertido (hh:mm)',
	'billworked' => 'Trabajado:',
	'billtotalworked' => 'Tiempo total trabajado:',
	'billbillable' => 'Facturable:',
	'billtotalbillable' => 'Tiempo total facturable:',
	'editbilling' => 'Editar facturación',
	'tabeditbilling' => 'Editar facturación',
	'billingtitle' => 'Facturación de: %s el %s',
	'billingtitlework' => ' (trabajado en: %s)',
	'billingeditedtitle' => ' <i>(Editado por %s el %s)</i>',
	'billingeditedtitle2' => ' <i>(editado el %s)</i>',
	'editbilling' => 'Editar registro de facturación',
	'ticketbillingdelconfirm' => 'Está seguro de que desea eliminar este registro de facturación de ticket?',
	'titleinvalidbilldate' => 'Valor de tiempo invertido no válido',
	'msginvalidbilldate' => 'Por favor, especifique un valor válido para la fecha y la hora de los campos "facturable" y "trabajable".',
	'fugeneral' => 'General',
	'fuaddnote' => 'Añadir nota',
	'fupostreply' => 'Responder',
	'fuforward' => 'Reenviar',
	'followupmins' => 'En n minutos',
	'followuphours' => 'En n horas',
	'followupdays' => 'En n días',
	'followupweeks' => 'En n semanas',
	'followupmonths' => 'En n meses',
	'followupcustom' => 'Personalizado',
	'followup' => 'Revisión',
	'currentfollowups' => 'Revisiones para este ticket:',
	'followup_willrunattime' => 'Se ejecutará la revisión a las %s creado por %s (%s)',
	'followup_willchangeownerto' => 'Cambiará el responsable del ticket a %s',
	'followup_willchangedepartmentto' => 'Cambiará el departamento a %s',
	'followup_willchangestatusto' => 'Cambiará el estado a %s',
	'followup_willchangepriorityto' => 'Cambiará la prioridad a %s',
	'followup_willchangetypeto' => 'Cambiará el tipo a %s',
	'followup_willaddstaffnotes' => 'Añadirá una nota de ticket',
	'followup_willaddusernotes' => 'Añadirá una nota de usuario',
	'followup_willaddareply' => 'Añade una respuesta pre-escrita a este ticket',
	'followup_willforwardto' => 'Reenviará este ticket a %s',
	'followup_removeowner' => 'Eliminará el responsable de este ticket',
	'flag' => 'Marcar',
	'tescalationhistory' => 'Ver historial de cambios de nivel (%d)',
	'tepdate' => 'Fecha de cambio de nivel: ',
	'tepslaplan' => 'Plan SLA: ',
	'tepescalationrule' => 'Regla de cambio de nivel: ',
	'ntchatid' => 'ID de chat: ',
	'ntchatuserfullname' => 'Usuario: ',
	'ntchatuseremail' => 'Email: ',
	'ntchatstafffullname' => 'Operador: ',
	'ntchatdepartment' => 'Departamento: ',
	'titleticketdeleted' => 'Ticket eliminado',
	'msgticketdeleted' => 'Imposible cargar ticket, el ticket ha sido eliminado',

	/**
	 * ---------------------------------------------
	 * MACRO
	 * ---------------------------------------------
	 */
	'macro' => 'Macro',
	'macros' => 'Macros',
	'insertmacro' => 'Insertar Macro',
	'editmacro' => 'Editar Macro',
	'tabcategories' => 'Categorías',
	'tabreplies' => 'Respuestas',
	'replytitle' => 'Nombre de respuesta',
	'macrotitle' => 'Nombre de macro',
	'insertcategory' => 'Insertar categoría',
	'insertreply' => 'Insertar respuesta',
	'wininsertmacrocat' => 'Insertar categoría de macros',
	'parentcategoryitem' => '- Categoría superior -',
	'macrocategorytitle' => 'Nombre de categoría',
	'desc_macrocategorytitle' => 'Introduzca el nombre de la categoría.',
	'parentcategory' => 'Categoría superior',
	'desc_parentcategory' => 'La categoría bajo la que se añadirá la nueva categoría. Puede organizar las categorías jerárquicamente sin límite.',
	'categorytype' => 'Tipo de categoría',
	'desc_categorytype' => '<i>Pública:</i> Visible para todos los operadores.<BR /><BR /><i>Privada:</i> Visible únicamente para el operador que se creó la categoría.',
	'titlemacrocategoryinsert' => 'Insertada categoría de macros "%s"',
	'msgmacrocategoryinsert' => SWIFT_PRODUCT . ' ha insertado correctamente la categoría de macros "%s".',
	'titlemacrocategoryupdate' => 'Actualizada la categoría de macros "%s"',
	'msgmacrocategoryupdate' => SWIFT_PRODUCT . ' ha actualizado correctamente la categoría de macros "%s".',
	'titleinvalidparentcat' => 'Categoría superior no válida',
	'msginvalidparentcat' => 'La categoría superior especificada no es válida. Por favor revise el árbol de categorías para segurarse de que la categoría seleccionada no es una subcategoría de la actual.',
	'titledelmacrocat' => 'Eliminadas "%d" categorías de macros',
	'msgdelmacrocat' => SWIFT_PRODUCT . ' ha eliminado correctamente las siguientes categorías de macros de la base de datos:',
	'filterreplies' => 'Filtrar respuestas',
	'rootcategory' => 'Categoría raíz',
	'macroreplytitle' => 'Nombre de macro',
	'desc_macroreplytitle' => 'Introduzca un nombre para la respuesta macro.',
	'parentcategoryreply' => 'Categoría superior',
	'desc_parentcategoryreply' => 'La categoría a la que se añadirá la nueva respuesta.',
	'reststaffgroupall' => '-- Todos los equipos de operadores --',
	'restrictstaffgroup' => 'Visible para',
	'desc_restrictstaffgroup' => 'PUede restringir la visibilidad de esta categoría a un equipo específico seleccionando una de las opciones disponibles.',
	'macroreplycontents' => 'Contenido de la respuesta',
	'tabproperties' => 'Propiedades',
	'ticketfields' => 'Propiedades de ticket',
	'macrodepartment' => 'Departamento',
	'desc_macrodepartment' => '',
	'macroticketstatus' => 'Estado de ticket',
	'desc_macroticketstatus' => '',
	'macrotickettype' => 'Tipo de ticket',
	'desc_macrotickettype' => '',
	'macroticketpriority' => 'Prioridad de ticket',
	'desc_macroticketpriority' => '',
	'desc_macroaddtags' => '',
	'macroaddtags' => 'Añadir etiquetas',
	'macroownerstaff' => 'Responsable del ticket',
	'desc_macroownerstaff' => '',
	'insertmacro' => 'Insertar macro',
	'editmacro' => 'Editar macro',
	'titlemacroreplyinsert' => 'Insertada macro "%s"',
	'msgmacroreplyinsert' => SWIFT_PRODUCT . ' ha insertado correctamente la macro "%s".',
	'titlemacroreplyupdate' => 'Actualizada macro "%s"',
	'msgmacroreplyupdate' => SWIFT_PRODUCT . ' Ha actualizado correctamente la macro "%s".',
	'titledelmacroreply' => 'Eliminadas "%d" respuestas macro',
	'msgdelmacroreply' => SWIFT_PRODUCT . ' ha eliminado correctamente las siguientes respuestas macro de la base de datos:',
	'quickinsert' => 'Inserción rápida',
	'qimacro' => 'Macro',
	'qiknowledgebase' => 'Biblioteca',
	'qidownloads' => 'Descargas',
	'replytotalhits' => 'Impactos',
	'replylastused' => 'Último uso',


	/**
	 * ---------------------------------------------
	 * SEARCH
	 * ---------------------------------------------
	 */
	'search' => 'Búsqueda',
	'tabsearch' => 'Búsqueda avanzada',
	'matchtype' => 'Opciones de criterios de búsqueda',
	'desc_matchtype' => 'Seleccione el método de agrupación para los campos de criterios de búsqueda.',
	'smatchall' => 'Coincidir todo (Y)',
	'smatchany' => 'Coincidir alguno (O)',
	'insertcriteria' => 'Insertar criterio',

	/**
	 * ---------------------------------------------
	 * NEW TICKET
	 * ---------------------------------------------
	 */
	'tabrecurrence' => 'Repeticiones',
	'recurrence_none' => 'Ninguna',
	'recurrence_daily' => 'Diaria',
	'recurrence_weekly' => 'Semanal',
	'recurrence_monthly' => 'Mensual',
	'recurrence_yearly' => 'Anual',
	'rec_every' => 'Cada',
	'rec_days' => 'día(s)',
	'rec_everyweekday' => 'Cada día laborable',
	'rec_weeks' => 'semanas(s) el',
	'rec_monday' => 'Lunes',
	'rec_tuesday' => 'Martes',
	'rec_wednesday' => 'Miércoles',
	'rec_thursday' => 'Jueves',
	'rec_friday' => 'Viernes',
	'rec_saturday' => 'Sábado',
	'rec_sunday' => 'Domingo',
	'rec_day' => 'Día',
	'rec_ofevery' => 'de cada',
	'rec_months' => 'mes(es)',
	'rec_the' => 'El',
	'rec_first' => 'Primero',
	'rec_second' => 'Segundo',
	'rec_third' => 'Tercero',
	'rec_fourth' => 'Cuarto',
	'rec_fifth' => 'Quinto',
	'rec_of' => 'de',
	'recurnotactivated' => 'Repeticiones desactivadas',
	'recurrencerange' => 'Rango de repetición',
	'recur_starts' => 'Empieza',
	'recur_ends' => 'Termina',
	'rec_noeenddate' => 'No hay fecha de finalización',
	'rec_endafter' => 'Terminar tras:',
	'rec_endby' => 'Terminar por:',
	'rec_occurrences' => 'veces',
);

?>
