<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v3 IMPORT =======
	'serrornoquery' => 'No se han encontrado resultados',
	'updatedtickets' => 'Tickets actualizados desde el último inicio de sesión',
	'unknownstaff' => 'Operador desconocido',
	'ptimebillable' => 'Facturable: ',
	'forwarderror' => 'ERROR: No se ha podido reenviar "%s." Asegúrese de rellenar el campo de contenidos y de que el email de destino es válido.',
	'followupmins' => 'En n minutos',
	'followuphours' => 'En n horas',
	'followupdays' => 'En n días',
	'followupweeks' => 'En n semanas',
	'followupmonths' => 'En n meses',
	'followupcustom' => 'Personalizado',
	'nofilterticket' => 'No´se han encontrado tickets que cumplan los criterios',
	'followup_willrunattime' => 'Ejecutará la revisión a las',
	'followup_willchangeownerto' => 'Cambiará el responsable del ticket a',
	'followup_willchangedepartmentto' => 'Cambiará el departamento a',
	'followup_willchangestatusto' => 'Cambiará el estado a',
	'followup_willchangepriorityto' => 'Cambiará la prioridad a',
	'followup_willchangeduedateto' => 'Establecerá la fecha de vencimiento a',
	'followup_willsettooverdue' => 'Marcará este ticket como vencido',
	'followup_willaddstaffnotes' => 'Añadirá una nota al ticket',
	'followup_willaddusernotes' => 'Añadirá una nota en cada ticket de este usuario',
	'followup_willaddareply' => 'Añadirá una respuesta pre-escrita a este ticket',
	'followup_willforwardto' => 'Reenviará este ticket a',
	'followup_title' => '<b>Revisiones actuales de este ticket:</b>',
	'followup_showhide' => 'Mostrar/Ocultar',
	'followup_delete_areyousure' => 'Está seguro de que desea eliminar esta revisión?  Esta acción es irreversible.',
	'followup_deleted' => 'La revisión ha sido eliminada',
	'followup_notdeleted_invalid_id' => 'La ID de revisión no es válida',
	'followup_delete_labeltext' => 'eliminar',
	'followup_nextexecution' => 'siguiente ejecución de la revisión',
	'followup_removeowner' => 'Eliminará el responsable de este ticket',
	// ======= END v3 IMPORT =======

	'tickets' => 'Tickets',
	'filtertickets' => 'Filtrar tickets',
	'manage' => 'Administrar',
	'newview' => 'Nueva vista',
	'viewoptions' => 'Opciones de vista',
	'editview' => 'Editar vista',
	'deleteview' => 'Eliminar vista',
	'views' => 'Vistas',
	'alldepartments' => 'Ver todo',
	'lookup' => 'Lookup',
	'labels' => 'Etiquetas',
	'filters' => 'Filtros',
	'editlabel' => 'Editar etiqueta',
	'newlabel' => 'Nueva etiqueta',
	'nolabel' => '-- Sin etiqueta --',

	'overdue' => 'Vencido',
	'bandelete' => 'Bloquear y eliminar',
	'markasdue' => 'Establecer vencimiento',
	'markduein24hrs' => 'Marcar como vencido en 24 horas',
	'mergetickets' => 'Fusionar tickets',
	'maprint' => 'Impresión masiva',
	'massreply' => 'Respuesta masiva',
	'massaction' => 'Acción masiva',
	'maticketstatus' => '-- Estado --',
	'maowner' => '-- Asignar a --',
	'maticketpriority' => '-- Prioridad --',
	'madepartments' => '-- Mover --',
	'maoptions' => '-- Opciones --',
	'noflag' => '-- Sin marca --',
	'go' =>'Ir',
	'rssfeed' => 'Fuente RSS',
	'qquote' => 'Citar',
	'qquoteall' => 'Citar todos los mensajes',
	'qquoteclient' => 'Citar mensajes del usuario',

	'gopenewwin' => 'Abrir tickets en nueva ventana',
	'desc_gopenewwin' => 'Si se activa, los tickets se abrirán en una nueva ventana.',
	'arnoref' => '-- Deshabilitar autoactualización --',
	'ar30sec' => 'Cada 30 segundos',
	'ar1min' => 'Cada minuto',
	'ar5min' => 'Cada 5 minutos',
	'ar15min' => 'Cada 15 minutos',
	'ar30min' => 'Cada 30 minutos',
	'ar1hr' => 'Cada hora',
	'gautorefresh' => 'Autoactualizar listado',
	'notreplied' => 'no respondido',
	'desc_gautorefresh' => 'La lista de tickets puede actualizarse automáticamente en intervalos de tiempo determinados.',
	'postreplyoptions' => 'Opciones de mensaje de respuesta',
	'rnticketlist' => 'Lista de tickets',
	'rnticket' => 'Ticket',
	'rnnextticket' => 'Siguiente ticket',
	'loading' => 'Cargando...',
	'replynav' => 'Tras responder llévame a',
	'desc_replynav' => 'Seleccione el área a la que ' . SWIFT_PRODUCT . ' le llevará tras responder a un ticket.',
	'rnticketstatus' => 'Estado por defecto del ticket al responder',
	'desc_rnticketstatus' => 'Seleccione el estado que se establecerá en los tickets tras responderlos.<br/><br/><i>Nota:</i> Esto <b>NO</b> ocurrirá con los tickets que se respondan desde el email.',
	'unspecified' => '-- No especificado --',
	'rnsetowner' => 'El usuario actual es el responsable',
	'desc_rnsetowner' => 'si está activado, el ticket se asignará automáticamente al operador que haya escrito la última respuesta.',
	'tabchats' => 'Chats%s',
	'strchats' => 'Chats',

	// Grid Titles
	'f_ticketid' => 'ID de Ticket',
	'f_ticketmaskid' => 'Máscara',
	'f_subject' => 'Asunto',
	'f_queue' => 'Cola email',
	'f_department' => 'Departamento',
	'f_ticketstatus' => 'Estado',
	'f_duedate' => 'Vencimiento',
	'f_lastactivity' => 'Última actividad',
	'f_date' => 'Fecha',
	'f_owner' => 'Responsable',
	'f_priority' => 'Prioridad',
	'f_lastreplier' => 'Última respuesta por',
	'f_fullname' => 'Nombre',
	'f_timeworked' => 'Tiempo trabajado',
	'f_email' => 'Email',
	'f_totalreplies' => 'Respuestas',
	'f_assignstatus' => 'Asignado',
	'f_flagtype' => 'Tipo de marca',
	'f_hasnotes' => 'Tiene notas',
	'f_dateicon' => 'Icono de fecha',
	'f_avgresponse' => 'prom. respuesta',
	'f_resolution' => 'Resolución',
	'f_staffworked' => 'Operadores trabajaron',
	'f_laststaffreply' => 'Ult. respuesta operador',
	'snoreply' => '- No respondido -',
	'f_slaplan' => 'Plan SLA',
	'f_rule' => 'Nombre regla',
	'f_tgroup' => 'Grupo plantillas',

	// Search stuff
	's_ticketid' => 'Id de ticket',
	's_ticketmask' => 'Máscara de ticket',
	's_fullname' => 'Nombre',
	's_lastreplier' => 'Última respuesta por',
	's_subject' => 'Asunto',
	's_messages' => 'Mensajes',
	'ticketslist' => 'Lista de tickets (%s)',
	'serrorticketid' => 'No hay resultados para "%s"',
	'serrorfullname' => 'No hay resultados para "%s"',
	'serrorlastreplier' => 'No hay resultados para "%s"',
	'serrorquery' => 'No hay resultados para  "%s"',
	'searchqresult' => '%s resultados encontrados (en %s segundos)',
	'searchkeyw' => 'Términos de búsqueda: %s',
	'rejectedwords' => 'Las siguientes palabras no han sido incluidas en la búsqueda: <span class="tabletitle">%s</span>',
	'newtickets' => 'Nuevos tickets desde el último inicio de sesión',

	'massactionconfirm' => 'Se han realizado las acciones en los tickets seleccionados.',
	'viewinsertconfirm' => 'Nueva vista de ticket "%s" insertada correctamente',
	'vieweditconfirm' => 'Vista de tickets "%s" actualizada correctamente',
	'viewdelconfirm' => 'Vista de tickets "%s" eliminada correctamente',
	'rssfeedmsg' => 'ERROR: Es necesario un nombre de usuario y contraseña para acceder a esta fuente RSS',
	'ticketrssfeed' => 'Fuente RSS de tickets',
	'rsstitleformat' => '%s: %s',
	'rssseterror' => 'ERROR: La fuente RSS de la vista de tickets se ha deshabilitado en <i>Configuración > Tickets</i> (en el panel de control de administración)',
	'invalidview' => 'Vista no válida',

	// Ticket Viewing
	'searchquery' => 'Buscar',
	'invalidticket' => 'ERROR: Ha sido imposible cargar el ticket. Es posible que no tenga <b>permiso</b> para acceder al departamento en el que se encuentra el ticket, o bien el ticket <b>no existe</b>',
	'tabgeneral' => 'General',
	'tabfollowup' => 'Revisión',
	'tabpostreply' => 'Enviar respuesta',
	'tabforward' => 'Reenviar',
	'tabaddnotes' => 'Añadir notas',
	'tabtimetracking' => 'Cronometrar',
	'tabhistory' => 'Historial',
	'tabhistorycnt' => 'Historial%s',
	'tablog' => 'Registro auditoría',
	'tabedit' => 'Editar',
	'ticketoptions' => 'Opciones de ticket',
	'flagticket' => 'Marcar ticket',
	'slalink' => 'Plan SLA',
	'markdue' => 'Marcar vencido',
	'export' => 'Exportar',
	'purpleflag' => 'Marca violeta',
	'redflag' => 'MArca roja',
	'orangeflag' => 'Marca naranja',
	'yellowflag' => 'Marca amarilla',
	'blueflag' => 'Marca azul',
	'greenflag' => 'Marca verde',
	'exportpdf' => 'Exportar PDF',
	'exportxml' => 'Exportar XML',
	'printticket' => 'Imprimir ticket',
	'mergeticket' => 'Fusionar ticket',
	'ban' => 'Bloquear',
	'delete' => 'Eliminar',
	'markasdue' => 'Marcar como vencido',
	'markduetf' => 'Marcar como vencido en 24h',
	'flagconfirm' => 'El Ticket "%s" ha sido marcado correctamente',
	'errorexport' => 'ERROR: Ha sido imposible exportar el ticket. Es posible que no tenga <b>permiso</b> para acceder al departamento en el que se encuentra el ticket, o bien el ticket <b>no existe</b>',
	'errordue' => 'ERROR: No se puede marcar el ticket como vencido. Es posible que no tenga <b>permiso</b> para acceder al departamento en el que se encuentra el ticket, o bien el ticket <b>no existe</b>',
	'erroroption' => 'ERROR: No se puede ejecutar la opción del ticket. Es posible que no tenga <b>permiso</b> para acceder al departamento en el que se encuentra el ticket, o bien el ticket <b>no existe</b>',
	'errorticketaccess' => 'ERROR: Es posible que no tenga <b>permiso</b> para acceder al departamento en el que se encuentra el ticket, o bien el ticket <b>no existe</b>',
	'delconfirm' => 'Ticket "%s" eliminado correctamente',
	'noteconfirm' => 'Se ha añadido la nota al ticket "%s"',
	'noteconfirmuser' => 'Se ha añadido la nota al usuario "%s".',
	'banconfirm' => 'Usuario "%s" bloqueado correctamente',
	'bandconfirm' => 'Usuario "%s" bloqueado y ticket eliminado correctamente',
	'dueconfirm' => 'La hora de vencimiento del ticket con ID "%s" se ha establecido correctamente',
	'clearflag' => 'Quitar marca',
	'timeline' => 'Línea de tiempo',
	'attachfilen' => 'Archivo %s',
	'entrytype' => 'Tipo de entrada',
	'alparser' => 'Parser',
	'alstaff' => 'Operador',
	'alclient' => 'Usuario',
	'alsystem' => 'Sistema',
	'alescalation' => 'Cambio de nivel',
	'notetype' => 'Tipo de nota',
	'desc_notetype' => '<i>Notas de ticket:</i> Visibles para los operadores solo en este ticket.<br><br><i>Nota de usuario:</i> Visible para los operadores en cada ticket creado por el usuario.',
	'ticket' => 'Ticket',
	'user' => 'Usuario',
	'noteoptions' => 'Opciones de nota',
	'forstaffnote' => 'Visible para',
	'desc_forstaffnote' => 'La nota de ticket puede hacerse visible solo para un operador concreto.',
	'noteallstaff' => '-- Todos los operadores --',
	'addnote' => 'Añadir nota',
	'notetitleformat' => 'Nota de %s - %s (%s)',
	'usergroup' => 'Grupo de usuarios',
	'slatconfirm' => 'Plan SLA asignado al ticket "%s"',
	'slauconfirm' => 'Plan SLA asignado al usuario "%s"',
	'notedconfirm' => 'Nota de ticket eliminada correctamente',
	'cfdelconfirm' => 'Valor de campo personalizado eliminado correctamente',
	'unassigned' => '-- No asignado --',
	'tassigned' => 'Asignado',
	'tunassigned' => 'No asignado',
	'cancel' => 'Cancelar',
	'tcconfirm' => '"%s" cambios de ticket ejecutados correctamente',
	'nextticket' => 'Siguiente ticket &raquo;',
	'previousticket' => '&laquo; Ticket anterior',
	'tremail' => 'Email: %s',
	'trtoemail' => 'Reenviado a: %s',
	'trip' => 'IP: %s',
	'trdate' => 'Publicado el: %s',
	'pdfrow' => '%s - %s',
	'staff' => 'Operador',
	'startprint' => 'Iniciar impresión',
	'delpostconfirm' => 'Mensaje de ticket "%s" eliminado correctamente',
	'delpostfail' => 'Error eliminando el mensaje de ticket. Asegúrese de que el mensaje de ticket no es el <b>primer mensaje</b> y de que tiene permisos para eliminarlo',
	'postdelmsg' => 'Está seguro de que desea eliminar este mensaje de ticket? Una vez eliminado no se podrá recuperar.',
	'viewheaders' => 'Ver cabeceras de email',
	'printpost' => 'Imprimir mensaje de ticket',
	'deletepost' => 'Eliminar mensaje de ticket',
	'editpost' => 'Editar mensaje de ticket',
	'billing' => 'Facturación',
	'tabrelease' => 'Lanzamiento',
	'quickinsert' => 'Inserción rápida',
	'qpredefinedreplies' => 'Respuestas predefinidas',
	'qknowledgebase' => 'Base de conocimiento',
	'qdownloads' => 'Descargas',
	'properties' => 'Propiedades',
	'qowner' => 'responsable: ',
	'qdepartment' => 'Departamento: ',
	'qstatus' => 'Estado: ',
	'qpriority' => 'Prioridad: ',
	'reply' => 'Contenido de la respuesta',
	'saveasdraft' => 'Guardar como borrador',
	'send' => 'Enviar',
	'addnote' => 'Añadir nota',
	'emailoptions' => 'Opciones de email',
	'eocc' => 'CC',
	'eobcc' => 'BCC',
	'addtorecp' => 'Añadir a destinatarios',
	'attachfile' => 'Adjuntar archivos',
	'file1' => 'Archivo 1',
	'file2' => 'Archivo 2',
	'file3' => 'Archivo 3',
	'optpred' => 'Predefinidas',
	'optkb' => 'Base de conocimiento',
	'optsendemail' => 'Enviar email',
	'pdue' => 'Vencimento: ',
	'inminutes' => '(en minutos)',
	'ptimeworked' => 'Tiempo trabajado: ',
	'author' => 'Autor',
	'from' => 'De',
	'attachments' => 'Adjuntos',
	'replyerror' => 'ERROR: Ha sido imposible responder a "%s." Asegúrese de que ha introducido la respuesta en el campo adecuado',
	'removefile' => 'Eliminar archivo',
	'spellcheck' => 'Ortografía',
	'to' => 'Para',
	'ticketrecipients' => 'Destinatarios del ticket',
	'dticketrecipients' => 'Los destinatarios del ticket reciben todos los emails enviados por los operadores. La opción de añadir destinatarios al ticket está disponible cuando se envía un CC, BCC o se reenvía un ticket. Hay tres tipos de destinatario:<br><br><i>Tercero:</i> Un tercero al que se añade a un ticket recibe un CC de todas las respuestas enviadas por el operador. Además, un tercero puede enviar respuestas por email y éstas se añadirán al ticket, aunque el ticket no fuera creado por él.<br><br><i>Usuarios CC:</i> Un usuario CC que se añade a un ticket recibe una copia de todas las respuestas enviadas por un operador.<br><br><i>Usuarios BCC:</i> Un usuario BCC añadido a un ticket recibe una copia oculta de todas las respuestas enviadas por un operador.',
	'arecipient' => 'Añadir destinatario',
	'desc_arecipient' => 'Puede añadir un destinatario seleccionando el tipo de destinatario y la dirección de email. El nuevo destinatario recibirá una copia de las respuestas de operadores, pero no tendrá acceso al ticket en el centro de soporte.',
	'rthirdparty' => 'Tercero',
	'rccuser' => 'Usuario CC',
	'rbccuser' => 'Usuario BCC',
	'summary' => 'Resumen',
	'worker' => 'Trabajador',
	'billdate' => 'Fecha factura',
	'timespent' => 'Tiempo invertido',
	'tworked' => 'Trabajado: ',
	'tbillable' => 'Facturable: ',
	'tdesc' => '(en minutos)',
	'billtitleformat' => 'Entrada de facturación de: %s el %s',
	'ttotalworked' => 'Tiempo total trabajado:',
	'ttotalbilled' => 'Tiempo total facturado:',
	'trphone' => 'Teléfono: %s',
	'linkcfgroup' => 'Vincular grupo de campos personalizado',
	'linkwithcfg' => 'Vincular con un grupo de campos personalizado',
	'desc_linkwithcfg' => 'Un ticket se puede vincular manualmente con un grupo de campos personalizado. Una vez vinculado, los campos personalizados se pueden editar en la pestaña <b>Editar</b>.',
	'cfnolink' => '-- No vincular --',
	'mergeticket' => 'Fusionar ticket',
	'mergewith' => 'Fusionar con el ticket con ID',
	'desc_mergewith' => 'Introduzca el identificador del ticket con el que este debería fusionarse. Todas las respuestas recibidas en este ticket se fusionarán por orden cronológico.',
	'lastedited' => 'Editado por última vez por: %s el %s',
	'editpost' => 'Editar mensaje de ticket',
	'quote' => 'Citar',
	'lockmsg' => '%s está viendo el ticket (Última actualización: %s)',
	'ticketproperties' => 'Propiedades del ticket',
	'charsetdiff' => 'El juego de caracteres de este email es diferente del juego de caracteres por defecto. El contenido podría no mostrarse correctamente. Si desea cambiar el juego de caracteres, haga click aquí.',
	'deletelabel' => 'Eliminar etiqueta',
	'ticketlabeldelconfirm' => 'Etiqueta de ticket eliminada correctamente',
	'slalabel' => 'SLA: %s',
	'tgroup' => 'Grupo de plantillas: %s',

	// New Ticket
	'newticket' => 'Nuevo ticket',
	'invaliddepartment' => 'Se ha especificado un departamento no válido',
	'foemail' => 'Email del usuario',
	'fophone' => 'Teléfono del usuario',
	'dnewticket' => 'Nuevo ticket: %s',
	'noptional' => '(Opcional)',
	'phonefieldempty' => 'ERROR: El campo teléfono está vacío',
	'emailfieldempty' => 'ERROR: El campo email está vacío',
	'newticketfailed' => 'ERROR: No se ha podido crear un nuevo ticket',
	'tdispatch' => 'Email:',
	'tnautores' => 'Autorespondedor',
	'tncontents' => 'Contenido',
	'forwardattach' => 'Adjuntos:',

	'followupsuccess' => 'Acciones de revisión añadidas a la cola',
	'followupfail' => 'No se han podido añadir las acciones de revisión. Asegúrese de que ha rellenado todos los campos',
	'followupnochange' => '-- Sin cambios --',
	'followupformerror' => 'Uno de los campos imprescindibles está vacío',

	// Ticket Post Lock
	'postlockdesc' => '%s está respondiendo al ticket (última actualización: %s)',
	'invalidemailspecified' => 'Se ha introducido una dirección de email no válida',

	// Misc
	'invaliduser' => 'Se ha especificado un usuario no válido. No se puede continuar.',
	'billingoptions' => 'Opciones de facturación',
);
?>