<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array(
	'tsticketid' => 'ID de ticket',
	'desc_tsticketid' => '',
	'tsticketmaskid' => 'Id de máscara de ticket',
	'desc_tsticketmaskid' => '',
	'tsfullname' => 'Nombre',
	'desc_tsfullname' => '',
	'tsemail' => 'Email',
	'desc_tsemail' => '',
	'tslastreplier' => 'Última respuesta por',
	'desc_tslastreplier' => '',
	'tsreplyto' => 'Responder a',
	'desc_tsreplyto' => 'El email al que llegarán las respuestas del usuario. Esta opción sólo es válida para los tickets creados por email.',
	'tssubject' => 'Asunto',
	'desc_tssubject' => '',
	'tsmessage' => 'Mensaje',
	'desc_tsmessage' => 'El cuerpo del mensaje del ticket.',
	'tsmessagelike' => 'Mensaje (SQL LIKE)',
	'desc_tsmessagelike' => 'El cuerpo del mensaje del ticket. Usa SQL LIKE para buscar en el contenido.',
	'tsuser' => 'Usuario',
	'desc_tsuser' => '',
	'tsuserorganization' => 'Organización del usuario',
	'desc_tsuserorganization' => '',
	'tsipaddress' => 'Dirección IP',
	'desc_tsipaddress' => '',
	'tscharset' => 'Juego de caracteres',
	'desc_tscharset' => 'El juego de caracteres del ticket.',
	'tsphone' => 'Teléfono',
	'desc_tsphone' => '',
	'tstimeworked' => 'Tiempo trabajado',
	'desc_tstimeworked' => 'El tiempo total trabajado (en segundos).',
	'tstimebilled' => 'Tiempo facturable',
	'desc_tstimebilled' => 'El tiempo total facturable (en segundos).',
	'tsdepartment' => 'Departamento',
	'desc_tsdepartment' => '',
	'tsowner' => 'Responsable',
	'desc_tsowner' => '',
	'tstype' => 'Tipo',
	'desc_tstype' => '',
	'tsstatus' => 'Estado',
	'desc_tsstatus' => '',
	'tspriority' => 'Prioridad',
	'desc_tspriority' => '',
	'tsemailqueue' => 'Cola de email',
	'desc_tsemailqueue' => '',
	'tsslaplan' => 'Plan SLA',
	'desc_tsslaplan' => '',
	'tsflag' => 'Marca',
	'desc_tsflag' => '',
	'tstemplategroup' => 'Grupo de plantillas',
	'desc_tstemplategroup' => '',
	'tsescalation' => 'Priorización',
	'desc_tsescalation' => '',
	'tsbayesian' => 'Filtro bayesiano',
	'desc_tsbayesian' => '',
	'tsusergroup' => 'Grupo de usuarios',
	'desc_tsusergroup' => '',
	'tscreator' => 'Creador',
	'desc_tscreator' => '',
	'tscreationmode' => 'Modo creación',
	'desc_tscreationmode' => '',
	'tsdue' => 'Vencimiento',
	'desc_tsdue' => '',
	'tsduerange' => 'Vencimiento <rango>',
	'desc_tsduerange' => '',
	'tsresolutiondue' => 'Vencimiento resolución',
	'desc_tsresolutiondue' => '',
	'tsresolutionduerange' => 'Vencimiento resolución <rango>',
	'desc_tsresolutionduerange' => '',
	'tscreationdate' => 'Fecha creación',
	'desc_tscreationdate' => '',
	'tscreationdaterange' => 'Fecha creación <rango>',
	'desc_tscreationdaterange' => '',
	'tslastactivity' => 'Última actividad',
	'desc_tslastactivity' => '',
	'tslastactivityrange' => 'Última actividad <rango>',
	'desc_tslastactivityrange' => '',
	'tslaststaffreply' => 'Última respuesta operador',
	'desc_tslaststaffreply' => '',
	'tslaststaffreplyrange' => 'Última respuesta operador <rango>',
	'desc_tslaststaffreplyrange' => '',
	'tslastuserreply' => 'Última respuesta usuario',
	'desc_tslastuserreply' => '',
	'tslastuserreplyrange' => 'Última respuesta usuario <rango>',
	'desc_tslastuserreplyrange' => '',
	'tsescalateddate' => 'Fecha priorización',
	'desc_tsescalateddate' => '',
	'tsescalateddaterange' => 'Fecha priorización <rango>',
	'desc_tsescalateddaterange' => '',
	'tsresolutiondate' => 'Fecha resolución',
	'desc_tsresolutiondate' => '',
	'tsresolutiondaterange' => 'Fecha resolución <rango>',
	'desc_tsresolutiondaterange' => '',
	'tsreopendate' => 'Fecha reapertura',
	'desc_tsreopendate' => '',
	'tsreopendaterange' => 'Fecha reapertura <rango>',
	'desc_tsreopendaterange' => '',
	'tsedited' => 'Ha sido editado?',
	'desc_tsedited' => '',
	'tseditedby' => 'Editado por',
	'desc_tseditedby' => '',
	'tsediteddate' => 'Fecha edición',
	'desc_tsediteddate' => '',
	'tsediteddaterange' => 'Fecha edición <rango>',
	'desc_tsediteddaterange' => '',
	'tstotalreplies' => 'Respuestas totales',
	'desc_tstotalreplies' => '',
	'tshasnotes' => 'Tiene notas?',
	'desc_tshasnotes' => '',
	'tshasattachments' => 'Tiene adjuntos?',
	'desc_tshasattachments' => '',
	'tsisemailed' => 'Enviado por email?',
	'desc_tsisemailed' => '',
	'tshasdraft' => 'Tiene borrador?',
	'desc_tshasdraft' => '',
	'tshasfollowup' => 'Tiene revisión?',
	'desc_tshasfollowup' => '',
	'tsislinked' => 'Está vinculado?',
	'desc_tsislinked' => '',
	'tsisfirstcontactresolved' => 'Resuelto al primer contacto?',
	'desc_tsisfirstcontactresolved' => '',
	'tsaverageresponsetime' => 'Tiempo medio respuesta',
	'desc_tsaverageresponsetime' => '',
	'tsescalationlevelcount' => 'Priorizaciones',
	'desc_tsescalationlevelcount' => '',
	'tswasreopened' => 'Fue reabierto?',
	'desc_tswasreopened' => '',
	'tsisresolved' => 'Está resuelto?',
	'desc_tsisresolved' => '',
	'tsresolutionlevel' => 'Nivel de resolución',
	'desc_tsresolutionlevel' => '',
	'tsticketnotes' => 'Notas del ticket',
	'desc_tsticketnotes' => '',

	/**
	 * ---------------------------------------------
	 * OTHER LOCALES
	 * ---------------------------------------------
	 */
	'notapplicable' => '-- No aplicable --',
	'lookup' => 'Buscar',
);
?>
