<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	/*
	 * ###############################################
	 * BEGIN V4 LOCALES
	 * ###############################################
	 */
	'titlephlookup' => 'No se ha encontrado ningún usuario con el número de teléfono %s',
	'msgphlookup' => SWIFT_PRODUCT . ' no ha podido encontrar ningún usuario con el teléfono "%s". Puede intentar buscar usuarios a través del menú de búsqueda o insertar un nuevo usuario abajo.',
	'tabgeoip' => 'Geolocalización',
	'geoiptimezone' => 'Zona horaria',
	'geoipisp' => 'ISP',
	'geoiporganization' => 'Organización',
	'geoipnetspeed' => 'Velocidad red',
	'geoipcountry' => 'País',
	'geoipcountrydesc' => 'País',
	'geoipregion' => 'Región',
	'geoipcity' => 'Localidad',
	'geoippostalcode' => 'Código postal',
	'geoiplatitude' => 'Latitud',
	'geoiplongitude' => 'Longitud',
	'geoipmetrocode' => 'Código metro',
	'geoipareacode' => 'Código área',
	'tabcalls' => 'Llamadas',
	'insertorganization' => 'Insertar organización',
	'editorganization' => 'Editar organización',
	'updateorg' => 'Actualizar organización',
	'tabmassaction' => 'Acción masiva',
	'unochange' => '-- sin cambios --',
	'merge' => 'Fusionar',
	'mergeorganization' => 'Fusionar organizaciones',
	'primaryorganization' => 'Organización principal',
	'infolastlogin' => 'ÚLTIMO INICIO SESION',
	'users' => 'Usuarios',
	'manageusers' => 'Administrar usuarios',
	'userfullname' => 'Nombre',
	'useremail' => 'Email',
	'userorganization' => 'Organización del usuario',
	'desc_userorganization' => 'Introduzca la organización del usuario. También puede seleccionar una organización existente mediante el autocompletado.',
	'usergroup' => 'Grupo de usuarios',
	'desc_usergroup' => 'Seleccione el grupo de usuarios en el que se incluirá este usuario. El usuario heredará todos los permisos del grupo de usuarios cuando inicie sesión.',
	'insertuser' => 'Insertar usuario',
	'edituser' => 'Editar usuario',
	'infobuser' => 'USUARIO',
	'infobuserorganization' => 'ORGANIZACION',
	'infobusergroup' => 'GRUPO',
	'informationbox' => 'Información',
	'userdesignation' => 'Cargo',
	'desc_userdesignation' => 'Introduzca el cargo del usuario; esto será visible en las respuestas de los tickets. Por ejemplo: CEO, Jefe de soporte, ejecutivo de cuentas',
	'generaloptions' => 'Opciones generales',
	'useremails' => 'Email(s) del usuario',
	'desc_useremails' => 'Introduzca las direcciones de correo electrónico del usuario. Puede introducir varias direcciones simplemente pulsando ENTER después de cada dirección.',
	'userrole' => 'Rol de usuario',
	'desc_userrole' => 'Seleccione el rol del usuario. Si selecciona director, este usuario tendrá acceso a todos los tickets creados por otros usuarios de la misma organización.',
	'userrolemanager' => 'Director',
	'userroleuser' => 'Usuario',
	'tabprofile' => 'Perfil',
	'taborganization' => 'Organización',
	'tabtickets' => 'Tickets',
	'tabchats' => 'Chats',
	'tabbilling' => 'Facturación',
	'salutationmr' => 'Sr.',
	'salutationmiss' => 'Srta.',
	'salutationmrs' => 'Sra.',
	'salutationdr' => 'Dr.',
	'isenabled' => 'Está activado?',
	'desc_isenabled' => 'Seleccione el estado de este usuario. Si está deshabilitado, este usuario no podrá iniciar sesión en el centro de soporte.',
	'userexpiry' => 'Caduca',
	'desc_userexpiry' => 'Seleccione la fecha de caducidad del usuario. Si se especifica, la cuenta de usuario dejará de funcionar cuando se alcance esa fecha.',
	'userphone' => 'Teléfono',
	'desc_userphone' => 'Introduzca el número de teléfono del usuario.',
	'personalizeoptions' => 'Personalización',
	'userprofileimage' => 'Imagen de perfil',
	'desc_userprofileimage' => 'Seleccione la imagen del perfil del usuario. Esta imagen aparecerá en todos los mensajes de ticket de este usuario.',
	'usertimezone' => 'Zona horaria',
	'desc_usertimezone' => 'Seleccione la zona horaria por defecto para este usuario. Si se establece una zona horaria aquí, se anulará la zona horaria por defecto del sistema para este usuario.',
	'userenabledst' => 'Activar Horario de Verano automático',
	'desc_userenabledst' => 'Seleccione si desea activar el Horario de Verano.',
	'defaultlanguage' => '-- Idioma por defecto --',
	'userlanguage' => 'Idioma',
	'desc_userlanguage' => 'Seleccione el idioma por defecto para este usuario. Si se activa, anula el idioma por defecto establecido para el grupo de plantillas.',
	'usercustomsla' => 'Opciones de Plan SLA',
	'defaultslaplan' => '-- Plan SLA por defecto --',
	'userslaplan' => 'Plan SLA',
	'desc_userslaplan' => 'Seleccione el Plan SLA por defecto para este usuario. Si se activa, anula cualquier otra regla de Plan SLA.',
	'userslaexpiry' => 'Caducidad Plan SLA',
	'desc_userslaexpiry' => 'Indique la caducidad del Plan SLA. Cuando caduque el plan seleccionado ' . SWIFT_PRODUCT . ' usará las reglas SLA por defecto para calcular el Plan SLA de los tickets enviados por este usuario.',
	'edituser' => 'Editar usuario',
	'edituserext' => 'Usuario: %s',
	'titleemailexists' => 'El email del usuario existe',
	'msgemailexists' => 'El email "%s" ya está asignado al usuario con ID "%d". Por favor, especifique una dirección de email diferente.',
	'titleuserinsert' => 'Insertado usuario "%s"',
	'msguserinsert' => SWIFT_PRODUCT . ' ha insertado correctamente el usuario "%s". Detalles:',
	'titleuserupdate' => 'Actualizado usuario "%s"',
	'msguserupdate' => SWIFT_PRODUCT . ' ha actualizado el usuario "%s". Detalles:',
	'titleinvalidfileext' => 'Extensión de archivo de imagen no válida',
	'msginvalidfileext' => 'El archivo de imagen de perfil tiene una extensión no válida. Las extensiones permitidas son: gif, jpeg, jpg, png',
	'titledisableuser' => '"%d" usuario(s) deshabilitado(s)',
	'msgdisableuser' => 'Se han deshabilitado correctamente los siguientes usuarios:<br />%s',
	'titleenableuser' => '"%d" usuario(s) activado(s)',
	'msgenableuser' => 'Se han activado correctamente los siguientes usuarios:<br />%s',
	'titledeleteduser' => '"%d" usuario(s) eliminado(s)',
	'msgdeleteduser' => SWIFT_PRODUCT . ' ha eliminado los siguientes usuarios de la base de datos:',
	'addnotes' => 'Notas',
	'notetitle' => '%s el %s',
	'addnote' => 'Añadir nota',
	'tabaddnote' => 'Añadir nota',
	'usernotedelconfirm' => 'Está seguro de que desea eliminar esta nota de usuario?',
	'editnote' => 'Editar nota',
	'tabeditnote' => 'Editar nota',
	'noteeditedtitle' => ' <i>(Editada por %s el %s)</i>',
	'manageorganizations' => 'Administrar organizaciones',
	'userorganizationshared' => 'Compartida',
	'userorganizationrestricted' => 'Restringida',
	'organizationname' => 'Nombre de organización',
	'desc_organizationname' => 'Introduzca el nombre de la organización.',
	'organizationtype' => 'Tipo',
	'organizationtype2' => 'Tipo de organización',
	'desc_organizationtype' => 'Seleccione el tipo de organización. El tipo "restringida" limita la visibilidad de los tickets a los usurios que los crearon, mientras que una organización "compartida", los tickets son visibles para todos los usuarios de la organización.',
	'titledeleteduserorganization' => '"%d" organizacion(es) eliminada(s)',
	'msgdeleteduserorganization' => SWIFT_PRODUCT . ' ha eliminado las siguientes organizaciones de la base de datos:',
	'userorganizationemails' => 'Filtros de email de organización',
	'desc_userorganizationemails' => 'Por favor, introduzca los dominios pertenecientes a esta organización. ' . SWIFT_PRODUCT . ' asignará automáticamente a los usuarios con emails dentro de esos dominios como miembros de esta organización. Por ejemplo: kayako.com google.com',
	'contactdetails' => 'Detalles de contacto',
	'userorganizationslaplan' => 'Plan SLA',
	'desc_userorganizationslaplan' => 'Seleccione el plan SLA por defecto para esta organización. Si se selecciona, anulará cualquier otra regla de plan SLA, excepto la asignación de Plan SLA de usuario, que tendrá preferencia sobre lo aquí selecionado.',
	'userorganizationslaexpiry' => 'Caducidad de Plan SLA',
	'desc_userorganizationslaexpiry' => 'Seleccione la caducidad del plan SLA. Cuando caduque el plan seleccionado ' . SWIFT_PRODUCT . ' usará las reglas  SLA por defecto para calcular el plan SLA para los tickets de los usuarios de esta organización.',
	'organizationcity' => 'Localidad',
	'desc_organizationcity' => '',
	'organizationstate' => 'Estado',
	'desc_organizationstate' => '',
	'organizationcountry' => 'País',
	'desc_organizationcountry' => '',
	'organizationpostalcode' => 'Código postal',
	'desc_organizationpostalcode' => '',
	'organizationphone' => 'Teléfono',
	'desc_organizationphone' => '',
	'organizationfax' => 'Fax',
	'desc_organizationfax' => '',
	'organizationwebsite' => 'Sitio Web',
	'desc_organizationwebsite' => '',
	'organizationaddress' => 'Dirección',
	'desc_organizationaddress' => '',
	'titleemailexistsorg' => 'El email de la organización ya existe',
	'msgemailexistsorg' => 'La dirección de email "%s"ya está asignada a la organización con ID "%d". Por favor, especifique una dirección de email diferente.',
	'editorganization' => 'Editar organización',
	'editorganizationext' => 'Organizacion: %s',
	'titleorganizationinsert' => 'Insertada organización "%s"',
	'msgorganizationinsert' => SWIFT_PRODUCT . ' ha insertado correctamente la organización "%s". Detalles:',
	'titleorganizationupdate' => 'La organización "%s" se ha actualizado',
	'msgorganizationupdate' => SWIFT_PRODUCT . ' ha actualizado la organización "%s". Detalles:',
	'titleorgnameexists' => 'Nombre de organización duplicado',
	'msgorgnameexists' => SWIFT_PRODUCT . ' ha detectado otra organización con el mismo nombre. Por favor, introduzca un nombre diferente para continuar.',
	'tabusers' => 'Usuarios',
	'search' => 'Buscar',
	'tabsearch' => 'Buscar',
	'matchtype' => 'Opciones de criterios de búsqueda',
	'desc_matchtype' => 'Seleccione el método de agrupación para los campos de criterios de búsqueda.',
	'smatchall' => 'Coincidir todo (Y)',
	'smatchany' => 'Coincidir cualquiera (O)',
	'insertcriteria' => 'Insertar criterio',
	'resetpassword' => 'Resetear contraseña',
	'changepassword' => 'Cambiar contraseña',
	'userpassword' => 'Contraseña',
	'userpasswordagain' => 'Contraseña (repetir)',
	'generateandemail' => 'Generar y enviar',
	'titlepwnomatch' => 'Contraseña no válida',
	'msgpwnomatch' => 'La contraseña especificada para el usuario no coincide.',
	'titlepwupdated' => 'Contraseña del usuario actualizada',
	'msgpwupdated' => SWIFT_PRODUCT . ' ha actualizado correctamente la contraseña para el usuario "%s".',
	'titlepwgenerated' => 'Contraseña generada y enviada por email',
	'msgpwgenerated' => SWIFT_PRODUCT . ' ha generado una contraseña aleatoria para el usuario "%s" y la ha enviado a sus direcciones de email registradas.',

	/**
	 * ---------------------------------------------
	 * SEARCH CRITERIA
	 * ---------------------------------------------
	 */
	'usfullname' => 'Nombre',
	'usemail' => 'Email',
	'usdesignation' => 'Designación',
	'usphone' => 'Teléfono',
	'ussalutation' => 'Título',
	'ususergroup' => 'Grupo de usuarios',
	'ususerrole' => 'Rol de usuario',
	'usorganization' => 'Organización',
	'usdateregistered' => 'Fecha de registro',
	'usdateregisteredrange' => 'Fecha de registro <rango>',
	'usdatelastupdate' => 'Fecha ultima actualización',
	'usdatelastupdaterange' => 'Fecha última actualización <rango>',
	'usdatelastvisit' => 'Fecha última visita',
	'usdatelastvisitrange' => 'Fecha última visita <rango>',
	'usisenabled' => 'Está activado?',
	'usslaplan' => 'Plan SLA',
	'ususerexpiry' => 'Caducidad usuario',
	'usslaexpiry' => 'Caducidad SLA',
	'notapplicable' => '-- NA --',
	'lookup' => 'Buscar',
	'usergroups' => 'Grupos de usuarios',
	'titlevalidationpen' => 'Dirección email no verificada',
	'msgvalidatationpen' => 'Este usuario no ha verificado su dirección de email. Haga click en el botón "Marcar como verificado" para verificar manualmente al usuario.',
	'markasverified' => 'Marcar como verificado',
	'titlevalidationsuccess' => 'Actualizado estado del usuario',
	'msgvalidationsuccess' => SWIFT_PRODUCT . ' ha marcado el usuario "%s" como verificado. El usuario puede ahora iniciar sesión en el centro de soporte.',



	/*
	 * ###############################################
	 * END V4 LOCALES
	 * ###############################################
	 */

	// ======= MANAGE USERS =======
	'userlist' => 'Lista de usuarios',
	'usrfullnameandemail' => 'Nombre completo & Dirección email',
	'desc_usrfullname' => 'Introduzca el nombre completo del usuario.',
	'desc_usremail' => 'Introduzca la dirección email del usuario.',
	'usrgrouptitle' => 'Grupo de usuarios',
	'usrlastvisit' => 'Última visita',
	'usrdate' => 'Fecha de alta',
	'userdelconfirm' => 'Usuario eliminado correctamente',
	'userdelconfirmmsg' => 'Está seguro de que desea eliminar el usuario especificado? Eliminar un usuario provocará el borrado permanente de todos los registros relacionados. Esta acción es irreversible!',
	'usruserid' => 'ID de usuario',
	'loginshare' => 'LoginShare',
	'usergroups2' => 'Grupos de usuarios',
	'userlanguage' => 'Idioma por defecto',
	'desc_userlanguage' => 'Por favor, seleccione el idioma a cargar cuando el usuario inicie sesión en el centro de soporte.',
	'usertimezoneoffset' => 'Zona horaria por defecto',
	'desc_usertimezoneoffset' => 'Seleccione la zona horaria del usuario. Si se establece, esta zona horaria anulará la seleccionada en el panel de control de administracion > configuración > configuración de fecha y hora.',
	'userenabled' => 'Usuario activado?',
	'desc_userenabled' => 'Si el usuario no está activado, no podrá iniciar sesión en el centro de soporte.',
	'wininsertuseremail' => 'Insertar dirección email',
	'loadingwindow' => 'Cargando ventana..',
	'winedituseremail' => 'Editar dirección email',

	// ======= INSERT USER =======
	'insertuser' => 'Insertar usuario',
	'userdetails' => 'Detalles de usuario',
	'usrpassword' => 'Contraseña',
	'desc_usrpassword' => 'Introduzca una contraseña para el usuario.',
	'usrpasswordconfirm' => 'Contraseña (confirmación)',
	'desc_usrpasswordconfirm' => 'Vuelva a introducir la contraseña.',
	'usrformgroup' => 'Grupo de usuarios',
	'desc_usrformgroup' => 'Seleccione a qué grupo pertenecerá el usuario.',
	'passworddontmatch' => 'ERROR: Las contraseñas no coinciden',
	'userinsertconfirm' => 'Usuario "%s" insertado correctamente',
	'invalidemail' => 'ERROR: Dirección de email no válida',
	'uslaplan' => 'Plan SLA',
	'desc_uslaplan' => 'El Plan SLA especificado se asignará automáticamente a todos los tickets creados por este usuario.',
	'uuser' => 'Usuario',
	'umanager' => 'Director',
	'usertype' => 'Tipo de usuario',
	'desc_usertype' => 'Seleccione el tipo de usuario. Si selecciona  <i>Director</i>, este usuario tendrá acceso a todos los tickets creados por los usuarios de su grupo.',

	// ======= EDIT USER =======
	'updateuser' => 'Actualizar usuario',
	'edituser' => 'Editar usuario',
	'invaliduser' => 'Usuario no válido',
	'usrpasswordreset' => 'Resetear contraseña',
	'useremaillist' => 'Lista de direcciones de email',
	'uemaildelconfirmsg' => 'Está seguro de que desea eliminar esta dirección de email?',
	'insertnewuseremail' => 'Insertar dirección de email',
	'cantdelprimaryemail' => 'ERROR: No se puede eliminar la única dirección de email asociada con este usuario',
	'useremaildelconfirm' => 'Dirección de email del usuario eliminada correctamente',
	'duplicateuseremail' => 'ERROR: Imposible añadir la dirección de email; está ya asociada con otro usuario',
	'useremailinsertconfirm' => 'Dirección de email "%s" insertada correctamente',
	'userupdateconfirm' => 'Usuario "%s" actualizado correctamente',
	'invaliduseremail' => 'Dirección email de usuario no válida',
	'useroptions' => 'Opciones de usuario',
	'deleteuser' => 'Eliminar usuario',
	'createticket' => 'Crear ticket',
	'tusearchticket' => 'Buscar tickets',
	'byuser' => 'Por usuario',
	'byusergroup' => 'Por grupo de usuarios',
	'validated' => 'Validado',
	'validationpending' => 'Pendiente validación',
	'markas' => 'Marcar como',
	'valconfirm' => 'Se ha cambiado correctamente el estado de validación de "%s"',
	'markasvalidated' => 'Marcar como validado',
	'markasvalidationpending' => 'Marcar como pendiente de validación',
	'resendverimail' => 'Reenviar email de verificación',
	'veriemailconfirm' => 'Email de verificación enviado a "%s"',
	'uregemailconfirm' => 'Email de registro enviado a "%s"',
	'resendregemail' => 'Reenviar email de registro',

	// ======= EDIT USER EMAIL =======
	'edituseremail' => 'Editar dirección email del usuario',
	'useremailupdateconfirm' => 'Dirección email "%s" actualizada correctamente',

	// ======= AJAX =======
	'tabnotes' => 'Notas',
	'tabbilling' => 'Facturación',
	'tabticketreports' => 'Informes de tickets',
	'tabchatreports' => 'Informes de chats',
	'tabedit' => 'Editar',
	'loading' => 'Cargando...',
);

?>