<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN NEW V4 LOCALES =======
	'tabgeneral' => 'General',
	'insertcfgrouptitle' => 'Se ha insertado el grupo de campos personalizados "%s"',
	'insertcfgroupmsg' => 'Se ha insertado correctamente el grupo de campos personalizados "<b>%s</b>" en la base de datos.<br><b>Nombre:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de visualizaci—n:</b> %s',
	'updatecfgrouptitle' => 'Se ha actualizado el grupo de campos personalizados "%s"',
	'updatecfgroupmsg' => 'Se ha actualizado correctamente el grupo de campos personalizados "<b>%s</b>".<br><b>Nombre:</b> %s<br><b>Tipo:</b> %s<br><b>Orden de visualizaci—n:</b> %s',
	'wineditcfgroup' => 'Editar grupo de campos personalizados: %s',
	'titledelcfgroup' => 'Se ha(n) eliminado "%d" grupo(s) de campos personalizados',
	'msgdelcfgroup' => 'Se han eliminado correctamente los siguientes grupos de campos personalizados de la base de datos:<br>%s',
	'buttonnext' => 'Siguiente',
	'encryptindb' => 'Cifrar el valor en la base de datos',
	'desc_encryptindb' => 'Si est‡ habilitado, el valor guardado en la base de datos ser‡ cifrado usando el hash œnico de instalaci—n. Los valores del campo contrase–a se guardan cifrados por defecto.',
	'tabdepartments' => 'Departamentos',
	'assigneddepartments' => 'Departamentos asignados',
	'titleunproc' => 'Imposible continuar',
	'msgunproc' => 'Es necesario crear al menos un grupo de campos personalizados para a–adir un campo personalizado.',
	'taboptions' => 'Opciones',
	'tablanguages' => 'Idiomas: traducci—n',
	'tabpermissions' => 'Permisos',
	'field_date' => 'Fecha',
	'desc_field_date' => 'Este tipo de campo permite crear un desplegable selector de fecha.',
	'field_linkedselect' => 'Selector enlazado',
	'desc_field_linkedselect' => 'Seleccione este tipo de campo para crear un selector enlazado.',
	'cfteampermissions' => 'Permisos: Equipo',
	'cfstaffpermissions' => 'Permisos: Operadores (Anula los permisos de equipo)',
	'notset' => 'No establecido',
	'insertcfieldtitle' => 'Se ha insertado el campo personalizado "%s"',
	'insertcfieldmsg' => 'Se ha insertado correctamente el campo personalizado "<b>%s</b>" en la base de datos.<br>',
	'updatecfieldtitle' => 'Actualizado campo personalizado "%s"',
	'updatecfieldmsg' => 'Se ha actualizado correctamente el campo personalizado "<b>%s</b>".<br>',
	'wineditcfield' => 'Editar campo personalizado: %s',
	'titledelcfields' => 'Se ha(n) eliminado "%d" campo(s) personalizado(s)',
	'msgdelcfields' => 'Se han eliminado los siguientes campos personalizados de la base de datos:<br>%s',
	// ======= END NEW V4 LOCALES =======

	'grouptitle' => 'Nombre del grupo',
	'desc_grouptitle' => '',
	'grouptype' => 'Tipo de grupo',
	'desc_grouptype' => 'Los campos personalizados deben pertenecer a un <b>grupo de campos personalizados</b>, el cual est‡ vinculado a un ‡rea del producto como creaci—n de tickets, chat, usuario, grupo de usuarios, etc.',
	'displayorder' => 'Orden de visualizaci—n',
	'desc_displayorder' => 'Si hay varios grupos en un ‡rea del producto, se ordenar‡n usando el orden de visualizaci—n (ascendente) especificado aqu’.',
	'customfields' => 'Campos personalizados',
	'managegroups' => 'Administrar grupos',
	'desc_customfieldgroups' => '',
	'grouplist' => 'Grupos de campos personalizados',
	'insertgroup' => 'Insertar grupo',
	'cfgroupdetails' => 'Detalles del grupo de campos personalizados',
	'grouptypeuser' => 'Usuario',
	'grouptypeknowledgebase' => 'Art’culos de base de conocimiento',
	'grouptypenews' => 'Art’culos de noticias',
	'grouptypetroubleshooter' => 'Pasos del solucionador',
	'grouptypedownloads' => 'Descarga de archivos',
	'grouptypeuserorganization' => 'Organizaci—n de usuario',
	'grouptypestaffticket' => 'Creaci—n de ticket por operador',
	'grouptypeuserticket' => 'Creaci—n de ticket por usuario',
	'grouptypestaffuserticket' => 'Creaci—n de ticket por usuario y operador',//Mahesh Slaria: Staff & user ticket creation
	'grouptypetimetrack' => 'Seguimiento de tiempos de ticket',
	'grouptypecontact' => 'Contacto de trabajo en equipo',
	'grouptypeevent' => 'Evento de trabajo en equipo',
	'grouptypetask' => 'Tarea de trabajo en equipo',
	'grouptypelivesupportpre' => 'Chat - Pre Chat',
	'grouptypelivesupportpost' => 'Chat - Post Chat',
	'insertgroup' => 'Insertar Grupo',
	'updategroup' => 'Actualizar grupo',
	'cfgroupinsertconfirm' => 'Se ha insertado correctamente el grupo de campos personalizados "%s"',
	'addfield' => 'A–adir campo',
	'cfgroupdelconfirm' => 'El/los grupo(s) de campos personalizados ha(n) sido eliminado(s) correctamente',
	'cfgroupactconfirm' => 'Est‡ seguro de que desea eliminar este grupo de campos personalizados? Eliminar un grupo provocar‡ el borrado permanente de todos los campos personalizados, as’ como sus respectivos valores almacenados. Esta acci—n es irreversible!',
	'editgroup' => 'Editar grupo',
	'invalidcfgroup' => 'Grupo de campos personalizados no v‡lido',
	'usergroups' => 'Grupos de usuarios',
	'desc_usergroups' => 'Seleccione los grupos de usuarios para los que el grupo de campos personalizados estar‡ disponible. Por ejemplo, puede tener dos grupos de usuarios diferentes y puede querer tener este grupo de campos personalizados disponible s—lo para uno de ellos.',
	'cfgroupupdateconfirm' => 'El grupo de campos personalizados "%s" se ha actualizado correctamente',
	'selectoneusergroup' => 'ERROR: es necesario seleccionar al menos un grupo de usuarios',
	'insertfield' => 'Insertar campo',
	'desc_customfields' => '',
	'next' => 'Siguiente &raquo;',
	'selectcftype' => 'Seleccionar tipo de campo personalizado',
	'insertfieldstep1' => 'Insertar campo: Paso 1',
	'insertfieldstep2' => 'Insertar campo: Paso 2',
	'fielddetails' => 'Detalles de campo',
	'customfieldgroup' => 'Grupo de campos personalizados',
	'desc_customfieldgroup' => '',
	'fieldtype' => 'Tipo de campo',
	'erroraddcfgroup' => 'ERROR: Necesita crear al menos un grupo de campos personalizados para a–adir un campo',
	'nogroupadded' => '-- No hay grupos de campos disponibles --',
	'fieldtitle' => 'T’tulo del campo',
	'desc_fieldtitle' => 'El t’tulo del campo se muestra junto a cada campo en los interfaces de usuario y operador para describir el prop—sito de cada campo.',
	'fieldname' => 'Nombre del campo',
	'desc_fieldname' => '',
	'isrequired' => 'Es obligatorio?',
	'desc_isrequired' => 'Si est‡ habilitado, se obligar‡ al usuario a rellenar el campo para que los datos se puedan procesar.',
	'usereditable' => 'Editable por usuarios',
	'desc_usereditable' => 'Si los usuarios pueden modificar el contenido del campo',
	'staffeditable' => 'Editable por operadores',
	'desc_staffeditable' => 'Si los operadores pueden modificar el contenido del campo',
	'regexpvalidate' => 'Validaci—n mediante expresiones regulares',
	'desc_regexpvalidate' => 'Aqu’ puede especificar una expresi—n regular para validar el contenido del campo.',
	'defaultvalue' => 'Valor por defecto',
	'desc_defaultvalue' => 'si se especifica, el valor por defecto del campo ser‡ lo que introduzca aqu’.',
	'description' => 'Descripci—n del campo',
	'desc_description' => 'Una descripci—n del campo.',
	'fielddisplayorder' => 'Orden de visualizaci—nr',
	'desc_fielddisplayorder' => 'Si hay varios campos en un grupo, se ordenan usando el orden de visualizaci—n (ascendente) especificado aqu’',
	'fieldoptions' => 'Opciones de campo',
	'optionvalues' => 'Opciones de valores',
	'optiondisplayorder' => 'Orden de visualizaci—n',
	'optionisselected' => 'Est‡ seleccionado?',
	'cfieldinsertconfirm' => 'Campo personalizado "%s" insertado correctamente',
	'cfdepartments' => 'Departamentos',
	'desc_cfdepartments' => 'Seleccione los departamentos a los que est‡ vinculado el campo personalizado. Puede usar esta caracter’stica para mostrar diferentes campos personalizados para diferentes departamentos.',
	'cfgroupd' => 'Grupo de campos personalizados',
	'desc_cfgroupd' => 'Seleccione el grupo de campos personalizados para este campo.',

	// Manage Fields
	'managefields' => 'Administrar campos',
	'desc_customfields' => '',
	'fieldlist' => 'Lista de campos',
	'cfdelconfirm' => 'Campo personalizado eliminado correctamente',
	'cfdelconfirmmsg' => 'Est‡ seguro de que desea eliminar este campo personalizado? Eliminar un campo personalizado borrar‡ permanentemente el campo y todos los valores almacenados. Esta acci—n es irreversible!',

	// Edit Custom Field
	'invalidcustomfield' => 'Campo personalizado no v‡lido',
	'editcfield' => 'Editar campo personalizado',
	'updatefield' => 'Actualizar campo',
	'cfieldupdateconfirm' => 'Campo personalizado "%s" actualizado correctamente',

	// Field List
	'field_text' => 'Texto',
	'desc_field_text' => 'Seleccione este tipo de campo para crear un campo de introducci—n de texto.',
	'field_textarea' => 'çrea de texto',
	'desc_field_textarea' => 'Seleccione este tipo de campo para crear una caja de texto multil’nea.',
	'field_password' => 'Contrase–a',
	'desc_field_password' => 'Seleccione este tipo de campo para crear un campo de introducci—n de contrase–as (sin visualizaci—n de caracteres).',
	'field_checkbox' => 'Casilla de verificaci—n',
	'desc_field_checkbox' => 'Seleccione este tipo de campo para crear una lista de casillas de verificaci—n (con posibilidad de selecci—n mœltiple).',
	'field_radio' => 'Botones Radio',
	'desc_field_radio' => 'Seleccione este tipo de campo para crear una lista de botones tipo radio (SIN posibilidad de selecci—n mœltiple).',
	'field_select' => 'Desplegable',
	'desc_field_select' => 'Seleccione este tipo de campo para crear un selector desplegable (selecci—n œnica).',
	'field_file' => 'Archivo',
	'desc_field_file' => 'Seleccione este tipo de campo para crear un campo de subida de archivos (s—lo se puede subir un archivo).',
	'field_selectmultiple' => 'Desplegable Multiple',
	'desc_field_selectmultiple' => 'Seleccione este tipo de campo para crear una lista con selecci—n mœltiple.',
	'field_custom' => 'Personalizado',
	'desc_field_custom' => 'Seleccione este tipo de campo para crear una entrada genŽrica para campos personalizados en ' . SWIFT_PRODUCT . '. Sin embargo tendr‡ que a–adir el c—digo HTML necesario en las plantillas de env’o de tickets. Este tipo de campo personalizado s—lo proporciona un encaminamiento y un ‡rea de almacenamiento para los datos. Debe escribir el c—digo HTML correspondiente para que el usuario pueda introducir los datos.',
);
?>