<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// Imported from v3
	'user' => 'Usuario',
	'tasknodue' => 'n/a',
	'dupdatedtickets' => 'Tickets actualizados desde el último acceso:',
	'ddocs' => 'Documentación del producto',

	// Staff Dashboard
	'overview' => 'Visión general (Sin resolver)',
	'dashboard' => 'Panel de control',
	'quickinsert' => 'Inserción rápida',
	'ticket' => 'Ticket',
	'contact' => 'Contacto',
	'event' => 'Evento',
	'task' => 'Tarea',
	'news' => 'Noticias',
	'file' => 'Archivo',
	'article' => 'Artículo',
	'day' => 'Día',
	'week' => 'Semana',
	'workweek' => 'Semana laborable',
	'month' => 'Mes',
	'dashtoday' => 'hoy',
	'overduetickets' => 'Tickets vencidos',
	'ticketsduetoday' => 'Tickets que vencen hoy',
	'dashtoday2' => 'Hoy',
	'dashnews' => 'Noticias (%s)',
	'dashnewstitle' => 'últimas noticias',
	'undated' => 'sin vencimiento',
	'dashduetasks' => 'Tareas vencidas/tareas sin fecha de vencimiento',
	'tasksduetoday' => 'Tareas que vencen hoy',
	'nwpostedby' => 'Publicado por ',
	'nwpostedon' => ' el ',
	'nwread' => 'Leer',
	'statistics' => 'Estadísticas',
	'dnewtickets' => 'Nuevos tickets desde el último acceso:',
	'dnewchats' => 'Nuevos chats desde el último acceso:',
	'twtoday' => 'Hoy',
	'tabrecentchats' => 'Nuevos chats',
	'tabrecentmessages' => 'Nuevos mensajes/Encuestas',
	'lcchatid' => 'ID de chat',
	'lcfullname' => 'Nombre completo',
	'lcstaff' => 'Operador',
	'lcdepartment' => 'Departamento',
	'lcmessageid' => 'ID de mensaje',
	'lcsubject' => 'Asunto',
	'dashmytickets' => 'Mis tickets',
	'dashunassigned' => 'Sin asignar',
	'dashcomments' => 'Comentarios',
	'taboverduetickets' => 'Tickets vencidos',
	'dashticketid' => 'ID de Ticket',
	'dashsubject' => 'Asunto',
	'dashowner' => 'Responsable',
	'dashdepartment' => 'Departamento',
	'dashstatus' => 'Estado',
	'dashdepartmentprogress' => 'Departamento',
	'dashstatusprogress' => 'Estado',
	'dashtypeprogress' => 'Tipo',
	'dashownerprogress' => 'Responsable',
	'dashpriorityprogress' => 'Prioridad',
	'unresolveddash' => 'Sin resolver',
	'unassigneddash' => 'Sin asignar',

	// Admin Dashboard
	'licexpirenever' => '- Nunca -',
	'licunlimited' => '- Ilimitado -',
	'licdomains' => 'Dominio(s)',
	'licstaff' => 'Operadores licenciados',
	'licexpires' => 'Expira',
	'licowner' => 'Propietario',
	'licuniqueid' => 'ID único',
	'licversion' => 'Versión',
	'licorganization' => 'Organización',
	'logfailure' => 'FALLO',
	'plogfrom' => 'De:',
	'plogto' => 'Para:',
	'plogsize' => 'Tamaño:',
	'plognosubject' => 'Sin asunto',
	'showingmsg' => ' (Mostrando %d de %d)',
	'titletemplaterevert' => 'Plantilla: Es necesaria una restauración por actualización',
	'msgtemplaterevert' => '"%d" plantilla(s) necesitan una restauración debido a una actualización reciente:',
	'titlelanguagerevert' => 'Idioma: Es necesaria una restauración por actualización',
	'msglanguagerevert' => '"%d" frase(s) de idioma necesitan una restauración debido a una actualización reciente:',
	'licensedetails' => 'Detalles de la licencia',
	'latestkayakonews' => 'Últimas noticias de Kayako',
	'tabwelcome' => 'Bienvenido',
	'tabrecentactivity' => 'Actividad reciente',
	'tabalerts' => 'Alertas',
	'tabloginfailures' => 'Fallos de acceso',
	'taberrorlog' => 'Log de errores',
	'tabparserlog' => 'Log de Parser',
	'dashipaddress' => 'Dirección IP: ',
	'dashforwardedipaddress' => 'Dirección IP alternativa: ',
	'dashuseragent' => 'User Agent: ',
	'dashinterface' => 'Interfaz: ',
	'titleloginfailuredetectedone' => 'Detectado fallo de inicio de sesión',
	'msgloginfailuredetectedone' => SWIFT_PRODUCT . ' ha detectado un fallo de inicio de sesión. Puedes revisar el log completo en Logs > Log de inicio de sesión.',
	'titleloginfailuredetected' => '%d fallos de inicio de sesión detectados',
	'msgloginfailuredetected' => SWIFT_PRODUCT . ' ha detectado %d fallos de inicio de sesión. Puedes revisar el log completo en Logs > Log de inicio de sesión.',
	'titleparserlogfailuredetected' => '%d fallos de Parser detectados',
	'msgparserlogfailuredetected' => SWIFT_PRODUCT . ' ha detectado %d errores de Parser. Puedes revisar el log completo en Logs > Log de Parser.',
	'titleerrorsdetected' => '%d Errores registrados',
	'msgerrorsdetected' => SWIFT_PRODUCT . ' ha detectado %d Errores. Para resolverlos se recomienta acudir al soporte de Kayako con los detalles completos del error.',
	'dashusername' => 'Usuario:',
	'dashemail' => 'Email:',
	'dashlastlogin' => 'Último acceso:',
	'dashversion' => 'versión',
	'dashproduct' => 'producto',
	'dashdashboard' => 'Panel de control',
	'dproduct' => 'Producto:',
	'dversion' => 'Versión: ',
	'dbuildtype' => 'Tipo de Build: ',
	'dbuilddate' => 'Fecha de Build: ',
	'kayako' => 'Kayako',
	'dhomepage' => 'Página de inicio',
	'dsupportdesk' => 'Helpdesk',
	'dmembersarea' => 'Área de miembros',
	'dforums' => 'Foros',
	'dtemplategroups' => 'Grupos de plantillas:',
	'dtemplates' => 'Plantillas:',
	'dlanguages' => 'Idiomas:',
	'dphrases' => 'Frases:',
	'dcustomfields' => 'Campos personalizados:',
	'dtasks' => 'Tareas programadas:',
	'dtables' => 'Tablas de la base de datos:',
	'ddatabasesize' => 'Tamaño de la base de datos:',
	'dstaff' => 'Operadores:',
	'ddepartments' => 'Departamentos:',
	'drecentactivity' => 'Actividad reciente',
	'drecentactivitynone' => 'No hay información disponible sobre actividad reciente',
	'accreated' => 'CREADO',
	'acupdated' => 'ACTUALIZADO',
	'acdeleted' => 'ELIMINADO',
	'acother' => 'OTRO',
);
?>