<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN V4 LOCALES =======
	'myopentickets' => 'My Open Tickets',
	'mypendingtickets' => 'My Pending Tickets',
	'defaultescalationrule' => 'Default Escalation Rule',
	'overallsatisfaction' => 'Overall Satisfaction',
	'writtencommunication' => 'Written Communication',
	'writtenexplanations' => 'Written Explanations',
	'responsespeeds' => 'Response Speeds',
	'lc_searchenginevisitors' => 'Search Engine Referrals',
	'lc_skillsales' => 'Sales',
	'lc_skillsupport' => 'Support',
	'lc_skillaccounts' => 'Accounts',
	'lc_searchenginerule' => 'Search Engine Visitors',
	'workflowcloseticket' => 'Close Ticket',
	'scconfirmcleardb' => 'Are you sure you wish to clear the database?\nContinuing with this option will cause deletion of all tables in the database.',
	'tickettypeissue' => 'Issue',
	'tickettypetask' => 'Task',
	'tickettypebug' => 'Bug',
	'tickettypelead' => 'Lead',
	'tickettypefeedback' => 'Feedback',
	'sladefaultschedule' => 'Default Schedule',
	'sladefaultplan' => 'Default 12 Hours Plan',
	'defaultrule' => 'Default Rule',
	'spam' => 'Spam',
	'nospam' => 'Not Spam',
	'setup' => 'Setup',
	'upgrade' => 'Upgrade',
	'upgautosetup' => 'Auto Upgrade',
	'modify' => 'Modify',
	'diagnostics' => 'Diagnostics',
	'setlicenseagreement' => 'License Agreement',
	'setsysreq' => 'System Requirements',
	'setcollectinfo' => 'Collect Information',
	'setautosetup' => 'Auto Setup',
	'setsettings' => 'Settings',
	'settemplates' => 'Templates',
	'setlocalization' => 'Localization',
	'setdone' => 'Done',
	'eula' => 'End User License Agreement',
	'iagree' => 'I Agree',
	'setupnext' => 'Next &raquo;',
	'setupdroptable' => 'Dropping Table %s',
	'coreadministrator' => 'Administrator',
	'corestaff' => 'Staff',
	'coregeneral' => 'General',
	'coreguest' => 'Guest',
	'coreregistered' => 'Registered',
	'coredeftgroup' => 'Default Template Group',
	'issuefixed' => 'Fixed',
	'issueimplemented' => 'Implemented',
	'issuewontfix' => 'Won\'t Fix',
	'issuewontimplement' => 'Won\'t Implement',
	'issueduplicate' => 'Duplicate',
	'issueincomplete' => 'Incomplete',
	'issuecannotrep' => 'Cannot Reproduce',
	'issuetimedout' => 'Timed Out',
	'issueobsolete' => 'Obsolete',
	'issuenotbug' => 'Not a Bug',
	'issuedeferred' => 'Deferred',
	'issueblocks' => 'Blocks',
	'issueisblockedby' => 'is blocked by',
	'issuerelatesto' => 'relates to',
	'issueisrelatedto' => 'is related to',
	'issueinc' => 'incorporates',
	'issueincby' => 'is incorporated by',
	'issueduplicates' => 'duplicates',
	'issueduplicatedby' => 'is duplicated by',
	'issueclonedas' => 'was cloned as',
	'issueisderived' => 'is derived from',
	'issuebug' => 'Bug',
	'issuefeaturerequest' => 'Feature Request',
	'issueimprovement' => 'Improvement',
	'issuetask' => 'Task',
	'issueopen' => 'Open',
	'issueinprogress' => 'In Progress',
	'issuereopened' => 'Reopened',
	'issueclosed' => 'Closed',
	'issueresolved' => 'Resolved',
	'issuecritical' => 'Critical',
	'issueurgent' => 'Urgent',
	'issuehigh' => 'High',
	'issuemedium' => 'Medium',
	'issuelow' => 'Low',
	'tcrelatesto' => 'relates to',
	'tcisrelatedto' => 'is related to',
	'tcduplicates' => 'duplicates',
	'tcisduplicatedby' => 'is duplicated by',
	'tcwasclonedas' => 'was cloned as',
	'tcisderivedfrom' => 'is derived from',
	'errorprefix' => 'Error: ',

	'sccachedir' => 'Checking to see if the cache directory is writable',
	'sccachedirerror' => 'The cache directory is not writable; please change the access permissions as described in the ' . SWIFT_PRODUCT . ' manual.',
	'scfilesdir' => 'Checking to see if the files directory is writable',
	'scfilesdirerror' => 'The files directory is not writable; please change the access permissions as described in the ' . SWIFT_PRODUCT . ' manual.',
	'scgeoipdir' => 'Checking to see if the geoip directory is writable',
	'scgeoipdirerror' => 'The geoip directory is not writable; please change the access permissions as described in the ' . SWIFT_PRODUCT . ' manual.',
	'scminphpversion' => 'Checking the version of PHP (minimum acceptable: %s)',
	'scminphpversionerror' => 'The installed PHP version is older than %s ' . SWIFT_PRODUCT .' cannot be installed until PHP is upgraded to the minimum acceptable version.',
	'scfileup' => 'Checking if file uploading is enabled',
	'scfileuperror' => 'File uploading is disabled in php.ini; Please change file_uploads to \'On\' in php.ini before installing ' . SWIFT_PRODUCT . '.',
	'scmaxupsize' => 'Checking the maximum file size for uploads',
	'scmaxupnotspec' => 'Not Specified',
	'scmaxupsizeerror' => 'Change upload_max_filesize in php.ini to increase the maximum allowed size of uploaded files if necessary.',
	'scsafemodecheck' => 'Checking the status of PHP safe mode',
	'scdisabled' => 'Disabled',
	'scenabled' => 'Enabled',
	'scenabled' => 'Enabled',
	'scstrictmode' => 'Checking for Database Strict Mode (should be disabled)',
	'scstrictmodeerror' => 'Database Strict Mode check failed. Please remove STRICT_ALL_TABLES and/or STRICT_TRANS_TABLES from your database configuration file (usually my.cnf)',
	'scmagicquotesgpc' => 'Checking if magic quotes GPC is disabled',
	'scmoduleerror' => '<span style="color: red; font-size: 11px; font-weight: bold;">The <i>%1$s</i> module is not configured to load with PHP. Please review the <u><a style="color: red; font-size: 9pt;" target="_blank" href="%2$s">instructions</a></u> for enabling %1$s in the PHP manual.</span>',
	'scmodulecheck' => 'Checking if the %s PHP module is installed',
	'scinstalled' => 'INSTALLED',
	'scmissing' => 'MISSING',
	'scdbnotempty' => 'The database is not empty. Please click "Clear Database" to delete all existing tables or click Continue to proceed with the setup. It is strongly recommended that you empty the database or the setup process might fail.',
	'sccleardb' => 'Clear Database',
	'sccontinue' => 'Continue',
	'scnext' => 'Next &raquo;',
	'scsyscheckfailed' => 'Sorry! '. SWIFT_PRODUCT .' can\'t be installed. Either an error has occurred or your web server doesn\'t meet the minimum system requirements. Please review any errors shown above and retry the setup process after those items have been resolved.',
	'scstartsetup' => 'Start Setup',
	'scpassnomatch' => 'Passwords do not match',
	'scfieldempty' => 'One of the required field(s) is empty',
	'scinvalidemail' => 'Invalid Email Address Specified',
	'scusernamelong' => 'The username specified, exceeds maximum field length',
	'scfieldlong' => 'One of the fields exceeds maximum length',
	'scsettingsbut' => 'Settings &raquo;',
	'scmodsetfailed' => 'Setup failed to execute %s. Please contact Kayako Support.',
	'setupexecsql' => 'Executing: %s',
	'setupexecinsert' => 'Inserting Data Into: %s',
	'setupexecindex' => 'Creating Index: %s for Table: %s',
	'setupexectable' => 'Creating Table: %s',
	'scinsertsettings' => 'Inserting Settings for: %s',
	'scinsertsettingsgroup' => 'Creating Settings Group: %s',
	'sctemplates' => 'Templates &raquo;',
	'sctemplatecategory' => 'Creating Template Category: %s',
	'sctemplate' => 'Creating Template: %s',
	'sclanguages' => 'Languages &raquo;',
	'scpleasewait' => 'Please Wait...',
	'sclanguage' => 'Creating Language: %s',
	'sclanguagesection' => 'Creating Language Section: %s',
	'scsetupconfirmation' => '<b>'. SWIFT_PRODUCT .' is now installed on your web server!</b> Visit the Administrator Control Panel to further configure your installation.<br/><br/><font color="red"><b>Important note:</b> You will not be able to use '. SWIFT_PRODUCT .' until you delete the \'setup\' directory in the root installation directory.</font><br/><br/><font color="darkblue"><b>Importing your data:</b></font> You can import your data from v3 of ' . SWIFT_PRODUCT . ' or other competing solutions by running the Import engine from Admin CP &gt; Import.',
	'scupgradeconfirmation' => '<div class="smalltext">Upgrade has completed successfully. Your product is now up to date.</div><br/><br/><font color="red"><b>Important note:</b> You should immediately delete the \'setup\' directory in the root installation directory. Failure to do so can result in an empty database if someone runs the setup.',
	'scadmincp' => 'Admin CP (Control Panel)',
	'scstaffcp' => 'Staff CP (Control Panel)',
	'scclientsc' => 'Client Support Center',
	'scpdaint' => 'PDA Interface',
	'scfinish' => '&raquo; Finish &laquo;',
	'diagnostics' => 'Diagnostics',
	'diagresult' => 'Diagnostics Result',
	'stproduct' => 'Product:',
	'stversion' => 'Version:',
	'stbuilddate' => 'Build Date:',
	'stbuildtype' => 'Build Type:',
	'stsourcetype' => 'Source Type:',
	'stverifyingconnection' => 'Verifying Database Connection',
	'stcurrentversion' => 'Current Version:',
	'scaction' => 'Action',
	'sccheckdbstruct' => 'Check Database Structure',
	'diagmissingtables' => 'Missing Tables',
	'diagmissingcolumns' => 'Missing Columns',
	'diagcolumnmismatch' => 'MetaType Mismatch Columns',
	'diagcolumnlengthmismatch' => 'Length Mismatch Columns',
	'diagresultok' => 'Database Structure is Up to Date',
	'diagmissingindexes' => 'Missing Indexes',
	'diagindexmismatch' => 'MetaType Mismatch Indexes',
	'sticketassigned' => 'Ticket Assigned',
	'snewuser' => 'User Registration',
	// ======= END V4 LOCALES =======

	// ======= IMPORT FROM v3 =======
	'statusonhold' => 'On Hold',
	'prlow' => 'Low',
	// ======= IMPORT FROM v3 =======

	'statusopen' => 'Open',
	'statusinprogress' => 'In Progress',
	'statusclosed' => 'Closed',
	'prnormal' => 'Normal',
	'prmedium' => 'Medium',
	'prhigh' => 'High',
	'prurgent' => 'Urgent',
	'premergency' => 'Emergency',
	'prcritical' => 'Critical',

	'defaultview' => 'Default View',
	'alltickets' => 'All Tickets',
	'impex' => 'Import',
	'setupwelcome' => 'Welcome to Kayako ' . SWIFT_PRODUCT . '\'s setup wizard. Please choose an action from the list below to begin.',
);
?>